objects/Tag_Template__c/Tag_Template__c.object-meta.xml
<CustomObject>
    <description>This object holds the template for tag object.</description>
    <label>Tag Template</label>
    <nameField>
        <label>Tag Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tag Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Tag_Template_Item__c/Tag_Template_Item__c.object-meta.xml
<CustomObject>
    <description>This object holds the tag template items.</description>
    <label>Tags Admin</label>
    <nameField>
        <label>Tag Line Item</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tags_Admin</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Tag_Template_Item__c/fields/TagTemplate__c.field-meta.xml
<CustomField>
    <fullName>TagTemplate__c</fullName>
    <description>This is master for tag line item</description>
    <label>Tag Template</label>
    <referenceTo>Tag_Template__c</referenceTo>
    <relationshipName>Tag_Template_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

classes/TestCreateTagtempLineItemsExt.cls
//@isTest
public class TestCreateTagtempLineItemsExt {
	/*static TestMethod void TestCreateTagtempLineItemsExt(){
        
        Tag_Template__c testtag=new Tag_Template__c(Name='tags');
        insert testtag;
        Tag_Template_Item__c testtagLI=new Tag_Template_Item__c(name='tagli',TagTemplate__c=testtag.id);
     //   insert testtagLI;
        
        CreateTagtempLineItemsExt controller = new CreateTagtempLineItemsExt(new ApexPages.StandardController(testtagLI));
        controller.saveme();
        controller.cancel();
	}*/
}