objects/Schedule_Task__c/Schedule_Task__c.object-meta.xml
<CustomObject>
    <description>This is Schedule Task object. It is child object of Schedule Template object.</description>
    <label>Schedule Task</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Schedule Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Schedule_Task__c/fields/Schedule_Template__c.field-meta.xml
<CustomField>
    <fullName>Schedule_Template__c</fullName>
    <label>Schedule Template</label>
    <referenceTo>Schedule_Template__c</referenceTo>
    <relationshipLabel>Schedule Tasks</relationshipLabel>
    <relationshipName>Schedule_Tasks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/Schedule_Template__c/Schedule_Template__c.object-meta.xml
<CustomObject>
    <description>This is Schedule Template object.</description>
    <label>Schedule Template</label>
    <nameField>
        <label>Schedule Template</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Schedule Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ScheduleTemplateDetailSwitchExt.cls
public with sharing class ScheduleTemplateDetailSwitchExt{

public boolean isLtng{private set; get{
                                            String theme = UserInfo.getUITheme();
                                            return (theme=='Theme4d')?true:false;
                                        }
            }  
    public string SchId{get;set;}
    public Schedule_Task__c Sct{get;set;}

    public ScheduleTemplateDetailSwitchExt(ApexPages.StandardController controller) 
    {
        SchId = controller.getRecord().id;
        
        Sct=[select id,name,Schedule_Template__c from Schedule_Task__c where id=:SchId];
    
    }


public pageReference stlistview(){
  
  String Schtaskid;
  Schtaskid =  Sct.Schedule_Template__c;
    PageReference p;
     if(isLtng)
     {
              p =  new Pagereference('/apex/ScheduleTemplateTabOverrideLightning?id='+Schtaskid);
             
     }
     else
     {
           p =  new Pagereference('/apex/ScheduleTemplateTabOverride?id='+Schtaskid);
       
     }
     p.setRedirect(true);
     return p;
  
}

}