objects/Schedule_Task__c/Schedule_Task__c.object-meta.xml
<CustomObject>
    <description>This is Schedule Task object. It is child object of Schedule Template object.</description>
    <label>Schedule Task</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Schedule Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/ScheduleTaskRole__c/ScheduleTaskRole__c.object-meta.xml
<CustomObject>
    <description>This is Schedule Task Role object. It is used to store assign roles to Schedule Task.</description>
    <label>ScheduleTask Role</label>
    <nameField>
        <label>Role</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ScheduleTaskRole</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/ScheduleTaskRole__c/fields/Schedule_Task__c.field-meta.xml
<CustomField>
    <fullName>Schedule_Task__c</fullName>
    <label>Schedule Task</label>
    <referenceTo>Schedule_Task__c</referenceTo>
    <relationshipName>ScheduleTaskRole</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

classes/AdminTabAssignRolesToTaskExtension.cls
// This class is used to assign Roles to Task on Admin Tab
public with sharing class AdminTabAssignRolesToTaskExtension
{
    // Global variables
    
                public boolean isLtng{private set; get{
                                            String theme = UserInfo.getUITheme();
                                            return (theme=='Theme4d')?true:false;
                                          }
            }  
     public String theId;
     public String strSTRID{get;set;}
     public List<ScheduleTaskRole__c> lstSTR{get;set;}
     // End of Global variables
     
    // Start Constructor
     public AdminTabAssignRolesToTaskExtension()
     {
       theId=ApexPages.CurrentPage().getParameters().get('Id');
       lstSTR=[Select Id,Name from ScheduleTaskRole__c where Schedule_Task__c=:theId];
     }
     // End Constructor
    
   // Start assignTheRole method
    public pagereference assignTheRole()
    {
           String theId=ApexPages.CurrentPage().getParameters().get('id');
           
           
             if(isLtng)
            {
                   PageReference p=Page.AssignRoleToSchduleTaskLightning;
                   p.setRedirect(true);
                   p.getParameters().put('scheduleTaskId',theId); return p;
            }
            else
            {
                    PageReference p=Page.AssignRoleToSchduleTask;
                   p.setRedirect(true);
                   p.getParameters().put('scheduleTaskId',theId);
                   return p;
            }
           
           
           
    }
    // end assignTheRole

    // Start Test Coverage
    static testMethod void Test_AdminTabAssignRolesToTaskExtension()
    {
        AdminTabAssignRolesToTaskExtension ext=new AdminTabAssignRolesToTaskExtension();
        ApexPages.Pagereference result=ext.assignTheRole();
        System.assertEquals(null,ext.theId);
    }
   // End Test Coverage 
}
// End of Class