objects/BB_Invoice_Payment__c/BB_Invoice_Payment__c.object-meta.xml
<CustomObject>
    <label>Billboard Invoice Payment</label>
    <nameField>
        <displayFormat>BBIPN-{0000000}</displayFormat>
        <label>Payment No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Billboard Invoice Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/BB_Invoice_Payment__c/fields/Billboard_Invoice__c.field-meta.xml
<CustomField>
    <fullName>Billboard_Invoice__c</fullName>
    <label>Billboard Invoice</label>
    <referenceTo>Billboard_Invoice__c</referenceTo>
    <relationshipName>Paymnets</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

objects/BB_Invoice_Payment__c/fields/Check_Amount__c.field-meta.xml
<CustomField>
    <fullName>Check_Amount__c</fullName>
    <label>Check Amount</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Currency</type>
</CustomField>

objects/BB_Invoice_Payment__c/fields/Check_New__c.field-meta.xml
<CustomField>
    <fullName>Check_New__c</fullName>
    <label>Check #</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

objects/BB_Invoice_Payment__c/fields/Vendor__c.field-meta.xml
<CustomField>
    <fullName>Vendor__c</fullName>
    <formula>Billboard_Invoice__r.Billboard_Vendor__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Vendor</label>
    <type>Text</type>
</CustomField>

objects/Billboard__c/Billboard__c.object-meta.xml
<CustomObject>
    <description>This is Billboard object.</description>
    <label>Billboard</label>
    <nameField>
        <label>BB #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billboards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Billboard__c/fields/Billboard_Type__c.field-meta.xml
<CustomField>
    <fullName>Billboard_Type__c</fullName>
    <label>Billboard Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Billboard</fullName>
            </value>
            <value>
                <fullName>DOT</fullName>
            </value>
            <value>
                <fullName>Cost Share</fullName>
            </value>
            <value>
                <fullName>Land Lease</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Billboard__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

objects/Billboard_Contract__c/Billboard_Contract__c.object-meta.xml
<CustomObject>
    <description>This is Billboard Contract object</description>
    <label>Billboard Contract</label>
    <nameField>
        <displayFormat>BBC-{00000}</displayFormat>
        <label>BBC#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Billboard Contracts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Billboard_Contract__c/fields/BB_Vendor_Name__c.field-meta.xml
<CustomField>
    <fullName>BB_Vendor_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>BB Vendor Name</label>
    <referenceTo>Vendor__c</referenceTo>
    <relationshipLabel>Billboard Contracts</relationshipLabel>
    <relationshipName>Billboard_Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Billboard_Contract__c/fields/Billboard__c.field-meta.xml
<CustomField>
    <fullName>Billboard__c</fullName>
    <label>Billboard</label>
    <referenceTo>Billboard__c</referenceTo>
    <relationshipLabel>Billboard Contracts</relationshipLabel>
    <relationshipName>Billboard_Contracts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/Billboard_Contract__c/fields/Billboard_Type__c.field-meta.xml
<CustomField>
    <fullName>Billboard_Type__c</fullName>
    <label>Billboard Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Billboard</fullName>
            </value>
            <value>
                <fullName>DOT</fullName>
            </value>
            <value>
                <fullName>Cost Share</fullName>
            </value>
            <value>
                <fullName>Land Lease</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Billboard_Contract__c/fields/Contract_Number__c.field-meta.xml
<CustomField>
    <fullName>Contract_Number__c</fullName>
    <label>Contract Number</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

objects/Billboard_Contract__c/fields/Contract_Title__c.field-meta.xml
<CustomField>
    <fullName>Contract_Title__c</fullName>
    <label>Contract Title</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

objects/Billboard_Contract__c/fields/No_of_Insertions__c.field-meta.xml
<CustomField>
    <fullName>No_of_Insertions__c</fullName>
    <label>No of Insertions</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

objects/Billboard_Contract__c/fields/Rate__c.field-meta.xml
<CustomField>
    <fullName>Rate__c</fullName>
    <label>Rate</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Currency</type>
</CustomField>

objects/Billboard_Contract__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Billboard_Invoice__c/Billboard_Invoice__c.object-meta.xml
<CustomObject>
    <description>This is Billboard invoice object. It is child object of Billboard.</description>
    <label>Billboard Invoice</label>
    <nameField>
        <label>BB Invoice #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billboard Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Billboard_Invoice__c/fields/BB_Invoice_Due_Date__c.field-meta.xml
<CustomField>
    <fullName>BB_Invoice_Due_Date__c</fullName>
    <label>BB Invoice Due Date</label>
    <type>Date</type>
</CustomField>

objects/Billboard_Invoice__c/fields/Billboard__c.field-meta.xml
<CustomField>
    <fullName>Billboard__c</fullName>
    <label>Billboard #</label>
    <referenceTo>Billboard__c</referenceTo>
    <relationshipLabel>Billboard Invoices</relationshipLabel>
    <relationshipName>Billboard_Invoices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

objects/Billboard_Invoice__c/fields/Billboard_Vendor__c.field-meta.xml
<CustomField>
    <fullName>Billboard_Vendor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Billboard Vendor</label>
    <referenceTo>Vendor__c</referenceTo>
    <relationshipLabel>Billboard Invoices</relationshipLabel>
    <relationshipName>Billboard_Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Billboard_Invoice__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <formula>Billboard__r.Location__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Location</label>
    <type>Text</type>
</CustomField>

objects/Billboard_Invoice_Line_Item__c/Billboard_Invoice_Line_Item__c.object-meta.xml
<CustomObject>
    <description>This is Billboard  Invoice Line Item object. It is child object of Billboard  Invoice.</description>
    <label>Billboard Invoice Line Item</label>
    <nameField>
        <displayFormat>BBILI{00000}</displayFormat>
        <label>BBILI</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Billboard Invoice Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Billboard_Invoice_Line_Item__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Currency</type>
</CustomField>

objects/Billboard_Invoice_Line_Item__c/fields/Billboard_Invoice__c.field-meta.xml
<CustomField>
    <fullName>Billboard_Invoice__c</fullName>
    <label>Billboard Invoice</label>
    <referenceTo>Billboard_Invoice__c</referenceTo>
    <relationshipLabel>Billboard Invoice Line Items</relationshipLabel>
    <relationshipName>Billboard_Invoice_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

objects/Billboard_Invoice_Line_Item__c/fields/GL_Code__c.field-meta.xml
<CustomField>
    <fullName>GL_Code__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GL Description</label>
    <referenceTo>GL_Code__c</referenceTo>
    <relationshipLabel>Billboard Invoice Line Items</relationshipLabel>
    <relationshipName>Billboard_Invoice_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Billboard_Invoice_Line_Item__c/fields/GL_Department__c.field-meta.xml
<CustomField>
    <fullName>GL_Department__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GL Department</label>
    <referenceTo>GL_Department__c</referenceTo>
    <relationshipLabel>Billboard Invoice Line Items</relationshipLabel>
    <relationshipName>Billboard_Invoice_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Billboard_Invoice_Line_Item__c/fields/Unit_Type__c.field-meta.xml
<CustomField>
    <fullName>Unit_Type__c</fullName>
    <formula>Text( GL_Code__r.Unit_Type__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Unit Type</label>
    <type>Text</type>
</CustomField>

objects/GL_Code__c/GL_Code__c.object-meta.xml
<CustomObject>
    <description>GL Codes are used to build line items on our Job Cost Layouts.  The Job Cost Layouts are the Quote, Estimate, Purchase Order, and Vendor Invoice.   The line items on each of these follow similar logic.</description>
    <label>GL Code</label>
    <nameField>
        <label>Description</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GL Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/GL_Code__c/fields/GL_Department__c.field-meta.xml
<CustomField>
    <fullName>GL_Department__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GL Department</label>
    <referenceTo>GL_Department__c</referenceTo>
    <relationshipLabel>GL Codes</relationshipLabel>
    <relationshipName>GL_Codes</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/GL_Code__c/fields/Unit_Type__c.field-meta.xml
<CustomField>
    <fullName>Unit_Type__c</fullName>
    <label>Unit Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Days</fullName>
                <default>true</default>
                <label>Days</label>
            </value>
            <value>
                <fullName>Each</fullName>
            </value>
            <value>
                <fullName>Hours</fullName>
            </value>
            <value>
                <fullName>Project</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/GL_Department__c/GL_Department__c.object-meta.xml
<CustomObject>
    <description>This Object is Master of GLCode Object in JobSuite Application.</description>
    <label>GL Department</label>
    <nameField>
        <label>GL Department</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GL Department</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Vendor__c/Vendor__c.object-meta.xml
<CustomObject>
    <description>This is Vendor object. Vendors in JobSuite are assigned to the line items on Quotes, Estimates, Purchase Orders and Vendor Invoices.  A printer or photographer may be a vendor.</description>
    <label>Vendor</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vendors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Vendor__c/fields/Vendor__c.field-meta.xml
<CustomField>
    <fullName>Vendor__c</fullName>
    <label>Vendor #</label>
    <length>30</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

classes/BillBoardController.cls
public with sharing class BillBoardController {
	
     @AuraEnabled
    public static string FetchObjectType(List<String> ObjNames) {
        return getDynamicLabelUtility.getDescribedObjects(ObjNames);   
    }
    
    @AuraEnabled
    public static List<String> getFieldsforObject(String sObjName) {
        
        Map<String, Schema.SObjectType> schemaMap = Schema.getGlobalDescribe();
        Map<String, Schema.FieldSet> fieldMap = schemaMap.get(sObjName).getDescribe().FieldSets.getMap();
        
        string fieldsetname;
        for (string s: fieldMap.keyset())
            fieldsetname = s;
        List<Schema.FieldSetMember> fields = fieldMap.get(fieldsetname).getFields();
        List<string> fieldsname = new List<string> ();
        
        for (Schema.FieldSetMember fieldName: fields) {
            fieldsname.add(fieldName.getFieldPath());
        }
        return fieldsname;
    }
    
    @AuraEnabled
    public static String geLabelforObject(String sObjName) {
        string objlabel = Schema.getGlobalDescribe().get(sObjName).getDescribe().getLabel();
        return objlabel;
    }
    
    // ================================================= Delete BB Records ===================================================================//
    
    @AuraEnabled
    public static string DeleteBB(String BBId){
        Billboard__c DeleteBB =[Select id,Name from Billboard__c where id =:BBId WITH SECURITY_ENFORCED];
        try{
            if(Schema.sObjectType.Billboard__c.isDeletable()){
                delete DeleteBB;
                return 'OK';
            }
            else{
                return 'Billboard has insufficient access to Delete';
            }
        } catch(Exception e){return ''+e.getMessage();
        }
    }
    
    /******************************************************* Get Latitude and Longitude Records ***************************************************************/
    @AuraEnabled
    public static Billboard__c BBLoc(Id recordId) {
        system.debug('record id' + recordId);
        Billboard__c BBLoc = [SELECT Id,Name,Latitude__c,Longitude__c FROM Billboard__c where Id = : recordId WITH SECURITY_ENFORCED];
        return BBLoc;
    }
    
     // ================================================= Display Records in Billboard Invoice table Section ==============================================================================//
    @AuraEnabled 
    public static List<Billboard_Invoice__c> getBBInvrecords(Id recordId) {
        system.debug(recordId);
        List <Billboard_Invoice__c> lstBBInv = [select id,Name,BB_Invoice_Due_Date__c,Billboard_Vendor__c,Location__c,Billboard__c,Billboard__r.Name,Billboard_Vendor__r.Name from Billboard_Invoice__c where Billboard__c =:recordId WITH SECURITY_ENFORCED];
        return lstBBInv;
    }
    /********************************************** Delete Billboard Invoice from the table **********************************************************/
    @AuraEnabled
    public static list<string> DeleteBBInv(String BBInvId){
        list<string> aa=new  list<string>();
        Billboard_Invoice__c DeleteBBInv =[Select id,Name from Billboard_Invoice__c where id =:BBInvId WITH SECURITY_ENFORCED];
        try{
            if(Schema.sObjectType.Billboard_Invoice__c.isDeletable()){
                delete DeleteBBInv;
                aa.add('OK');
                return aa;
            }
            else{
                aa.add('Billboard Invoice has insufficient access to Delete');return aa;
            }
            
        } catch(Exception e){aa.add('NO');aa.add(''+e.getMessage());return aa;}
         
    }
    
     // ================================================= Display Records in Billboard Invoice table Section ==============================================================================//
    @AuraEnabled 
    public static List<Billboard_Invoice_Line_Item__c> getBBInvLIrecords(Id recordId) {
        system.debug(recordId);
        List <Billboard_Invoice_Line_Item__c> lstBBInv = [select id,Name,Amount__c,GL_Code_No__c,Unit_Type__c,Billboard_Invoice__c,GL_Department__c,GL_Department__r.name,GL_Code__c,GL_Code__r.name,Quantity__c from Billboard_Invoice_Line_Item__c where Billboard_Invoice__c=:recordId WITH SECURITY_ENFORCED ORDER BY Name];
        return lstBBInv;
    }
    
    // ================================================= Edit BB Inv LI Records ==============================================================================//
    
    @AuraEnabled
    public static string updateBBInvLI(List <Billboard_Invoice_Line_Item__c> editedBBInvLIList){
        try{
            if(Schema.sObjectType.Billboard_Invoice_Line_Item__c.isUpdateable()){
                update editedBBInvLIList;
                return 'true';
            }
            else{
                return 'Billboard Invoice Line Item has insufficient access to update';
            }
        } catch(Exception e){return ''+e.getMessage();
        }
    }
    /********************************************** Delete Billboard Invoice from the table **********************************************************/
    @AuraEnabled
    public static list<string> DeleteBBInvLI(String BBInvLIId){
        list<string> aa=new  list<string>();
        Billboard_Invoice_Line_Item__c DeleteBBInvLI =[Select id,Name from Billboard_Invoice_Line_Item__c where id =:BBInvLIId WITH SECURITY_ENFORCED];
        try{
            if(Schema.sObjectType.Billboard_Invoice_Line_Item__c.isDeletable()){
                delete DeleteBBInvLI;
                aa.add('OK');
                return aa;
            }
            else{
                aa.add('Billboard Invoice Line Item has Insufficient access to Delete');return aa;
            }
            
        } catch(Exception e){
            aa.add('NO');   aa.add(''+e.getMessage());return aa;
        }
    }
    
     // ================================================= Display Records in Billboard Invoice  Payment table Section ==============================================================================//
    @AuraEnabled 
    public static List<BB_Invoice_Payment__c> getBBInvPayrecords(Id recordId) {
        system.debug(recordId);
        List <BB_Invoice_Payment__c> lstBBInvPay = [select id,Name,Check_New__c,Check_Amount__c,Check_Date__c ,Vendor__c,Billboard_Invoice__c from BB_Invoice_Payment__c where Billboard_Invoice__c=:recordId WITH SECURITY_ENFORCED ORDER BY Name];
        return lstBBInvPay;
    }
    
   
    /********************************************** Delete Billboard Invoice Payment from the table **********************************************************/
    @AuraEnabled
    public static list<string> DeleteBBInvPay(String BBInvPayId){
        list<string> aa=new  list<string>();
        BB_Invoice_Payment__c DeleteBBInvPay =[Select id,Name from BB_Invoice_Payment__c where id =:BBInvPayId WITH SECURITY_ENFORCED];
        try{
            
            if(Schema.sObjectType.BB_Invoice_Payment__c.isDeletable()){
                delete DeleteBBInvPay;
                aa.add('OK');
                return aa;
            }
            else{
                aa.add('BB Invoice Payment has Insufficient access to Delete');return aa;
            }
        } catch(Exception e){
            aa.add('NO');    aa.add(''+e.getMessage());return aa;
        }
    }
    
    // ================================================= Display Records in Billboard Contract table Section ==============================================================================//
    @AuraEnabled 
    public static List<Billboard_Contract__c> getBBConrecords(Id recordId) {
        system.debug(recordId);
        List <Billboard_Contract__c> lstBBCon = [select id,Name,BB_Vendor_Name__c,BB_Vendor_Name__r.Name,Billboard__c,Billboard__r.Name,Billboard_Type__c,Contract_Number__c,Contract_Title__c,End_Date__c,Expiration_Date__c,No_of_Insertions__c,Rate__c,Start_Date__c,Status__c from Billboard_Contract__c where Billboard__c =:recordId WITH SECURITY_ENFORCED ORDER BY End_Date__c];
        return lstBBCon;
    }
    
    /********************************************** Delete Billboard Contract from the table **********************************************************/
    @AuraEnabled
    public static list<string> DeleteBBCon(String BBConId){
        list<string> aa=new  list<string>();
        Billboard_Contract__c DeleteBBCon =[Select id,Name from Billboard_Contract__c where id =:BBConId WITH SECURITY_ENFORCED];
         try{
             if(Schema.sObjectType.Billboard_Contract__c.isDeletable()){
                 delete DeleteBBCon;
                 aa.add('OK');
                 return aa;
             }
             else{
                 aa.add('Billboard Contract has Insufficient access to Delete');return aa;
             }
        } catch(Exception e){
            aa.add('NO');aa.add(''+e.getMessage());return aa;
        }
    }

}