objects/BB_Invoice_Payment__c/BB_Invoice_Payment__c.object-meta.xml
<CustomObject>
    <label>Billboard Invoice Payment</label>
    <nameField>
        <displayFormat>BBIPN-{0000000}</displayFormat>
        <label>Payment No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Billboard Invoice Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/BB_Invoice_Payment__c/fields/Billboard_Invoice__c.field-meta.xml
<CustomField>
    <fullName>Billboard_Invoice__c</fullName>
    <label>Billboard Invoice</label>
    <referenceTo>Billboard_Invoice__c</referenceTo>
    <relationshipName>Paymnets</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

objects/Billboard_Invoice__c/Billboard_Invoice__c.object-meta.xml
<CustomObject>
    <description>This is Billboard invoice object. It is child object of Billboard.</description>
    <label>Billboard Invoice</label>
    <nameField>
        <label>BB Invoice #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billboard Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/CreateBillboardInvoicePaymentExt.cls
public with sharing class CreateBillboardInvoicePaymentExt {

  /*  public boolean isLtng{private set; get{
                                            String theme = UserInfo.getUITheme();
                                            return (theme=='Theme4d')?true:false;
                                          }
    }  
    private final BB_Invoice_Payment__c bbili;
    public String bbiid{get;set;}
    public String BillboardInvoicename{get;set;}
   
    // Start Constructor
    public CreateBillboardInvoicePaymentExt(ApexPages.StandardController controller) {
    
        this.bbili=(BB_Invoice_Payment__c)controller.getRecord();
        bbiid=ApexPages.CurrentPage().getParameters().get('bbiid');
        Billboard_Invoice__c objBBI=[Select id,name from Billboard_Invoice__c where id=:bbiid];
        BillboardInvoicename=objBBI.Name;
        bbili.Billboard_Invoice__c = bbiid;
        
    }
    
      
      // Save Method
        public PageReference saveme() 
        { 
                try
                {
                    insert bbili;
                }
                catch(DMLException e)
                {
                    return null;
                }
                    
                
                 PageReference p;   
                 if(isLtng)
                 {
                    p = new PageReference('/apex/BillboardInvoiceDetailpageLightning?id='+bbiid+'&section=BBLP');
                 }
                
                else
                 {
                   p = new PageReference('/apex/BillboardInvoiceDetailpage?id='+bbiid);
                 }
                
                
                // PageReference pageRef = new PageReference('/apex/BillboardInvoiceDetailpage?id='+bbiid);
                  p.setRedirect(true);
                  return p;
                 
        }
            // End of Save Method

        // Cancel Method
        Public PageReference cancelme()
        {    
                
             PageReference p;   
             if(isLtng)
             {
                p = new PageReference('/apex/BillboardInvoiceDetailpageLightning?id='+bbiid+'&section=BBLP');
             }
            
            else
             {
               p = new PageReference('/apex/BillboardInvoiceDetailpage?id='+bbiid);
             }
                
                   
            //PageReference p = new PageReference('/apex/BillboardInvoiceDetailpage?id='+bbiid);
            p.setRedirect(true);
            return p;   
            
       }
        // Cancel Method        
        
*/
}