objects/Quote__c/Quote__c.object-meta.xml
<CustomObject>
    <description>This is Quote object.</description>
    <label>Quote</label>
    <nameField>
        <label>Quote Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Quote__c/fields/Approved__c.field-meta.xml
<CustomField>
    <fullName>Approved__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Approved</label>
    <type>Checkbox</type>
</CustomField>

classes/QuoteDetailPageExtension.cls
// This class is used to display Quote Detail
public with sharing class QuoteDetailPageExtension 
{
   // Global variables
  /*  public List<Quote__c> vq{get;set;} 
    String theID;
    public String qtid{set;get;}
    // End of Global variables
    
    // Start Constructor
    public QuoteDetailPageExtension(ApexPages.StandardController controller) 
    {
         theID = ApexPages.CurrentPage().getParameters().get('id');
         vq=[select id,Name,Approved__c from Quote__c where id =: theID AND Approved__c = true];
         qtid=theID;
     }
     // End of Constructor
     
    // Test Method 
      static testMethod void Test_QuoteDetailPageExtension()
      {
           Quote__c quote = new Quote__c();
           ApexPages.StandardController con=new ApexPages.StandardController(quote);
           QuoteDetailPageExtension ext=new QuoteDetailPageExtension(con);
           System.assertEquals(quote.id,ext.theID);
       } 
     // End of test Method */
}
// End of Class