objects/Quote__c/Quote__c.object-meta.xml
<CustomObject>
    <description>This is Quote object.</description>
    <label>Quote</label>
    <nameField>
        <label>Quote Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Vendor_Quote__c/Vendor_Quote__c.object-meta.xml
<CustomObject>
    <description>This is Vendor Quote object. This object is used to assign Quote to the Vendor.</description>
    <label>Vendor Quote</label>
    <nameField>
        <displayFormat>VQ-{0000}</displayFormat>
        <label>VQ #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vendor Quotes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Vendor_Quote__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <label>Quote</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipLabel>Vendors</relationshipLabel>
    <relationshipName>Vendor_Quotes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

classes/QuoteVendorViewSwitchExt.cls
public with sharing class QuoteVendorViewSwitchExt{
    
    public boolean isLtng{private set; get{
                                            String theme = UserInfo.getUITheme();
                                            return (theme=='Theme4d')?true:false;
                                          }
            }  
   
   
    public string QuoteVenId{get;set;}
    public Vendor_Quote__c Qus{get;set;}
    
    public QuoteVendorViewSwitchExt(ApexPages.StandardController controller) 
    {
        QuoteVenId= controller.getRecord().id;
        
        Qus=[select id,name,Quote__c from Vendor_Quote__c where id=:QuoteVenId];
        
    }
    
    Public PageReference pagedir()
    {
         String Quoteid;
         Quoteid =  Qus.Quote__c;
         if(isLtng)
        {
             PageReference p =  new Pagereference('/apex/QuoteDetailPageLightning?id='+Quoteid);
             p.setRedirect(true);
             return p; 
        }
        else
        {
                PageReference p =  new Pagereference('/apex/QuoteDetailPage?id='+Quoteid);
                p.setRedirect(true);
                return p;
        } 
    }
    

}