objects/Job_Task_Role__c/Job_Task_Role__c.object-meta.xml
<CustomObject>
    <description>Staff assigned to the Job Tasks.</description>
    <label>Task Staff Assigned</label>
    <nameField>
        <label>Role</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Task Staff Assigned</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Job_Team__c/Job_Team__c.object-meta.xml
<CustomObject>
    <description>This is Job Team object. It is used to store role and assigned staff to that role for a Job record.</description>
    <label>Job Team</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>JobTeam Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Team</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Job_Team__c/fields/Staff__c.field-meta.xml
<CustomField>
    <fullName>Staff__c</fullName>
    <label>Staff</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

objects/Staff__c/Staff__c.object-meta.xml
<CustomObject>
    <description>This is Staff object.</description>
    <label>Staff</label>
    <nameField>
        <label>Staff Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Staff</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/StaffNameUpdateforJobTeamTask.cls
public with sharing class StaffNameUpdateforJobTeamTask{
      
      public static void updateStaffname(string OldStaffname,string NewStaffname){
      
          list<Job_Team__c> JobTeamlist=new list<Job_Team__c>();
          list<Job_Task_Role__c> JobTaskRolelist=new list<Job_Task_Role__c>();
     
          system.debug('<!----  OldStaffName ----------!> '+OldStaffname);
          system.debug('<!----  NewStaffName -----------!> '+NewStaffname);
        
          if((OldStaffname!= null || OldStaffname!= '') ){   
                
          List<Job_Team__c> Jteam = [SELECT id,Staff__c FROM Job_Team__c WHERE Staff__c =:OldStaffname WITH SECURITY_ENFORCED];
              
           system.debug('<!----  Teamlist ----------!> '+Jteam);  
             
           List<Job_Task_Role__c> Jtaskrole = [SELECT id,User__c FROM Job_Task_Role__c WHERE User__c=:OldStaffname WITH SECURITY_ENFORCED];
              
           system.debug('<!----  Jtaskrolelist ----------!> '+Jtaskrole );    
            
              for(Job_Team__c jt:Jteam){
                  if(schema.SobjectType.Job_Team__c.Fields.Staff__c.isUpdateable()){ 
                      jt.Staff__c=NewStaffname;
                  }
                      JobTeamlist.add(jt);
                  
              }
            
           for(Job_Task_Role__c Jtrole:Jtaskrole){
               if(schema.SobjectType.Job_Task_Role__c.Fields.User__c.isUpdateable()){ 
                   Jtrole.User__c =NewStaffname;}
               JobTaskRolelist.add(Jtrole);
           }
              try{
                  
                  if(!JobTeamlist.IsEmpty()) 
                  { 
                      if(Schema.sObjectType.Job_Team__c.isUpdateable()){
                          Update JobTeamlist;
                      }
                  }
                  if(!JobTaskRolelist.IsEmpty()){
                      if(Schema.sObjectType.Job_Task_Role__c.isUpdateable()){
                          Update JobTaskRolelist;}
                  }
                 
                 
              }
              catch(exception e){}
          }
          
          
          
          
          
          
      }
}