objects/Estimate_Line_Items__c/Estimate_Line_Items__c.object-meta.xml
<CustomObject>
    <description>This is Estimate Line Item object.</description>
    <label>Estimate Line Item</label>
    <nameField>
        <label>Line Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Estimate Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Estimate_Line_Items__c/fields/GL_Code__c.field-meta.xml
<CustomField>
    <fullName>GL_Code__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GL Description</label>
    <referenceTo>GL_Code__c</referenceTo>
    <relationshipLabel>Line Items</relationshipLabel>
    <relationshipName>Estimate</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Estimate_Line_Items__c/fields/GL_Department__c.field-meta.xml
<CustomField>
    <fullName>GL_Department__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GL Department</label>
    <referenceTo>GL_Department__c</referenceTo>
    <relationshipLabel>Line Items</relationshipLabel>
    <relationshipName>Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Estimate_Line_Items__c/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <label>Job Name</label>
    <referenceTo>Job__c</referenceTo>
    <relationshipLabel>Line Items</relationshipLabel>
    <relationshipName>Estimate</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/Estimate_Line_Items__c/fields/Unit_Type__c.field-meta.xml
<CustomField>
    <fullName>Unit_Type__c</fullName>
    <formula>Text( GL_Code__r.Unit_Type__c )</formula>
    <label>Unit Type</label>
    <type>Text</type>
</CustomField>

objects/Estimate_Line_Items__c/fields/Vendor__c.field-meta.xml
<CustomField>
    <fullName>Vendor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vendor</label>
    <referenceTo>Vendor__c</referenceTo>
    <relationshipLabel>Estimate Line Items</relationshipLabel>
    <relationshipName>Estimate</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/GL_Code__c/GL_Code__c.object-meta.xml
<CustomObject>
    <description>GL Codes are used to build line items on our Job Cost Layouts.  The Job Cost Layouts are the Quote, Estimate, Purchase Order, and Vendor Invoice.   The line items on each of these follow similar logic.</description>
    <label>GL Code</label>
    <nameField>
        <label>Description</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GL Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/GL_Code__c/fields/GL_Department__c.field-meta.xml
<CustomField>
    <fullName>GL_Department__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GL Department</label>
    <referenceTo>GL_Department__c</referenceTo>
    <relationshipLabel>GL Codes</relationshipLabel>
    <relationshipName>GL_Codes</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/GL_Code__c/fields/GL_ID__c.field-meta.xml
<CustomField>
    <fullName>GL_ID__c</fullName>
    <description>This is GL ID field. These id&apos;s are auto generated.</description>
    <label>GL Code</label>
    <length>15</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

objects/GL_Code__c/fields/Unit_Cost__c.field-meta.xml
<CustomField>
    <fullName>Unit_Cost__c</fullName>
    <label>Unit Cost (In $)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

objects/GL_Code__c/fields/Unit_Type__c.field-meta.xml
<CustomField>
    <fullName>Unit_Type__c</fullName>
    <label>Unit Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Days</fullName>
                <default>true</default>
                <label>Days</label>
            </value>
            <value>
                <fullName>Each</fullName>
            </value>
            <value>
                <fullName>Hours</fullName>
            </value>
            <value>
                <fullName>Project</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <description>This is Invoice object.</description>
    <label>Invoice</label>
    <nameField>
        <label>Invoice Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Invoice__c/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <label>Job Name</label>
    <referenceTo>Job__c</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/Invoice__c/fields/Vendor__c.field-meta.xml
<CustomField>
    <fullName>Vendor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vendor</label>
    <referenceTo>Vendor__c</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Job__c/Job__c.object-meta.xml
<CustomObject>
    <description>This is Job object.</description>
    <label>Job</label>
    <nameField>
        <label>Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Job__c/fields/Media_Types__c.field-meta.xml
<CustomField>
    <fullName>Media_Types__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Media Type</label>
    <referenceTo>Media_Type__c</referenceTo>
    <relationshipName>Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Job__c/fields/Schedule_Template__c.field-meta.xml
<CustomField>
    <fullName>Schedule_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Schedule Template</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Schedule_Template__c.Media_Types__c</field>
            <operation>equals</operation>
            <valueField>$Source.Media_Types__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Schedule_Template__c</referenceTo>
    <relationshipName>Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Job__c/fields/Specification_Template__c.field-meta.xml
<CustomField>
    <fullName>Specification_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Creative Brief Template</label>
    <referenceTo>Specification_Template__c</referenceTo>
    <relationshipName>Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/PO_Line_Item__c/PO_Line_Item__c.object-meta.xml
<CustomObject>
    <description>This is Purchase Order Line Item object. It is child object of Purchase Order.</description>
    <label>PO Line Item</label>
    <nameField>
        <displayFormat>POLI-{0000}</displayFormat>
        <label>POLI #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PO Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/PO_Line_Item__c/fields/GL_Code__c.field-meta.xml
<CustomField>
    <fullName>GL_Code__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GL Description</label>
    <referenceTo>GL_Code__c</referenceTo>
    <relationshipLabel>PO Line Items</relationshipLabel>
    <relationshipName>PO_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/PO_Line_Item__c/fields/Unit_Type__c.field-meta.xml
<CustomField>
    <fullName>Unit_Type__c</fullName>
    <formula>Text(GL_Code__r.Unit_Type__c)</formula>
    <label>Unit Type</label>
    <type>Text</type>
</CustomField>

objects/Production_Estimate__c/Production_Estimate__c.object-meta.xml
<CustomObject>
    <description>This is Production Estimate object.</description>
    <label>Production Estimate</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Production Estimates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Production_Estimate__c/fields/GL_Code__c.field-meta.xml
<CustomField>
    <fullName>GL_Code__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GL Description</label>
    <referenceTo>GL_Code__c</referenceTo>
    <relationshipLabel>Production Estimates</relationshipLabel>
    <relationshipName>Production_Estimates</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Production_Estimate__c/fields/GL_Department__c.field-meta.xml
<CustomField>
    <fullName>GL_Department__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GL Department</label>
    <referenceTo>GL_Department__c</referenceTo>
    <relationshipLabel>Production Estimates</relationshipLabel>
    <relationshipName>Production_Estimates</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Production_Estimate__c/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <label>Job Name</label>
    <referenceTo>Job__c</referenceTo>
    <relationshipLabel>Production Estimates</relationshipLabel>
    <relationshipName>Production_Estimates</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/Production_Estimate__c/fields/Vendor__c.field-meta.xml
<CustomField>
    <fullName>Vendor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vendor</label>
    <referenceTo>Vendor__c</referenceTo>
    <relationshipLabel>Production Estimates</relationshipLabel>
    <relationshipName>Production_Estimates</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Purchase_Order__c/Purchase_Order__c.object-meta.xml
<CustomObject>
    <description>This is Purchase Order object.</description>
    <label>Purchase Order</label>
    <nameField>
        <label>PO #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Purchase Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Purchase_Order__c/fields/GL_Code__c.field-meta.xml
<CustomField>
    <fullName>GL_Code__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GL Code</label>
    <lookupFilter>
        <active>false</active>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>GL_Code__c</referenceTo>
    <relationshipLabel>Purchase Orders</relationshipLabel>
    <relationshipName>Purchase_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Purchase_Order__c/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <label>Job Name</label>
    <referenceTo>Job__c</referenceTo>
    <relationshipLabel>Purchase Orders</relationshipLabel>
    <relationshipName>Purchase_Orders</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/Purchase_Order__c/fields/Vendor__c.field-meta.xml
<CustomField>
    <fullName>Vendor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vendor</label>
    <referenceTo>Vendor__c</referenceTo>
    <relationshipLabel>Purchase Orders</relationshipLabel>
    <relationshipName>Purchase_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Schedule_Template__c/Schedule_Template__c.object-meta.xml
<CustomObject>
    <description>This is Schedule Template object.</description>
    <label>Schedule Template</label>
    <nameField>
        <label>Schedule Template</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Schedule Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Schedule_Template__c/fields/Media_Types__c.field-meta.xml
<CustomField>
    <fullName>Media_Types__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Media Type</label>
    <referenceTo>Media_Type__c</referenceTo>
    <relationshipLabel>Schedule Templates</relationshipLabel>
    <relationshipName>Schedule_Templates</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Vendor__c/Vendor__c.object-meta.xml
<CustomObject>
    <description>This is Vendor object. Vendors in JobSuite are assigned to the line items on Quotes, Estimates, Purchase Orders and Vendor Invoices.  A printer or photographer may be a vendor.</description>
    <label>Vendor</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vendors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Vendor__c/fields/Vendor__c.field-meta.xml
<CustomField>
    <fullName>Vendor__c</fullName>
    <label>Vendor #</label>
    <length>30</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

classes/TestaddPOLineItem.cls
//@isTest
Public class TestaddPOLineItem {
 // Start Test Method
   /*static testMethod void TestAddPOLineItem()
     {
     test.starttest();
        Job_Number_Setting__c cs1999 = new  Job_Number_Setting__c(Name= 'yy');
        insert cs1999;
        
        Media_Type__c testMedia=new Media_Type__c(Name='TM 2999');
        try
         {
          insert testMedia;
         }
        catch(System.DMLException e)
         {
          System.assertEquals('FIELD_CUSTOM_VALIDATION',e.getDmlStatusCode(0));
         }
           
        Schedule_Template__c testST=new Schedule_Template__c(Name='TST2999',Media_Types__c=testMedia.Id);
        insert testST;
                 
        Specification_Template__c testSpec=new Specification_Template__c(Name='TST2999');
        insert testSpec;
                
        Job__c testJob1=new Job__c(Name='TJ2999',Start_Date__c=System.Today(),Media_Types__c=testMedia.Id,Schedule_Template__c=testST.Id,Specification_Template__c=testSpec.Id);
        try
         {
          insert testJob1;
         }
        catch(System.DMLException e)
         {
          System.assertEquals('FIELD_CUSTOM_VALIDATION',e.getDmlStatusCode(0));
         }
        System.assertEquals('TJ2999',testJob1.Name);
           
        GL_Department__c testGLD = new GL_Department__c(Name='TGLD2999');
         try
          {
           insert testGLD;
          }
         catch(System.DMLException e)
          {
           System.assertEquals('FIELD_CUSTOM_VALIDATION_EXCEPTION',e.getDmlStatusCode(0));
          }   
                    
        Vendor__c testVendor=new Vendor__c(Name='TV2999');
        insert testVendor;
             
        GL_Code__c testGL1=new GL_Code__c();
          testGL1.Name='TGLC2999';
          testGL1.GL_Id__c='GL 2999';
          testGL1.GL_Department__c=testGLD.id;
          testGL1.Unit_Cost__c=2500;
          testGL1.Unit_Type__c='Days';
             
        try
         {
          insert testGL1;
         }
        catch(System.DMLException e)
         {
          System.assert(e.getMessage().contains('Record already exist with same GLCode'));
         }
             
        Estimate_Line_Items__c testELI=new Estimate_Line_Items__c(Name='ELI 2999',Job__c=testjob1.Id,GL_Department__c=testGLD.id,Vendor__c=testVendor.Id,Amount__c=500,Quantity__c=120,GL_Code__c =testGL1.Id);   
        insert testELI;
          
        Purchase_Order__c testPO=new Purchase_Order__c(Job__c=testjob1.Id,Issue_Date__c=System.Today(),Due_Date__c=System.Today(),Invoice_Created__c='No',Status__c='Sent',Vendor__c=testVendor.Id,GL_Code__c=testGL1.Id);
        insert testPO;
          
        PO_Line_Item__c POLI = new PO_Line_Item__c(Invoice_Created__c=False,Amount__c=5000,Purchase_Order__c=testPO.Id,Estimate_Line_Item__c=testELI.Id);
        insert POLI;
           
        PO_Line_Item__c POLI1 = new PO_Line_Item__c(Invoice_Created__c=True,Amount__c=5000,Purchase_Order__c=testPO.Id,Estimate_Line_Item__c=testELI.Id);
        insert POLI1;
              
        Invoice__c testI=new Invoice__c(Job__c=testjob1.Id,Date_Received__c=System.Today(),Vendor__c=testVendor.Id,Purchase_Order__c=testPO.id);  
        insert testI;
            
        ApexPages.currentPage().getParameters().put('Invid', testI.Id);    
      
       // Invoke the primary method on the extension 
       addPOLineItem ext=new addPOLineItem();
       ApexPages.PageReference result1=ext.save();
             ext.roleWraps[0].checked=False;
         
             result1=ext.save();
        
             ext.roleWraps[0].checked=True;
       
            result1=ext.save();
            ApexPages.PageReference result2=ext.Back();
	  test.stoptest(); 
     }
   // End Test Coverage
   
   static testMethod void TestAddPOLineItem1()
     {
     
     test.starttest();
        ProductionEstimate__c cs11etting=new ProductionEstimate__c(Active__c=true);
           insert cs11etting;
        Job_Number_Setting__c cs1999 = new  Job_Number_Setting__c(Name= 'yy');
        insert cs1999;
        
        Media_Type__c testMedia=new Media_Type__c(Name='TM 2999');
        try
         {
          insert testMedia;
         }
        catch(System.DMLException e)
         {
          System.assertEquals('FIELD_CUSTOM_VALIDATION',e.getDmlStatusCode(0));
         }
           
        Schedule_Template__c testST=new Schedule_Template__c(Name='TST2999',Media_Types__c=testMedia.Id);
        insert testST;
                 
        Specification_Template__c testSpec=new Specification_Template__c(Name='TST2999');
        insert testSpec;
                
        Job__c testJob1=new Job__c(Name='TJ2999',Start_Date__c=System.Today(),Media_Types__c=testMedia.Id,Schedule_Template__c=testST.Id,Specification_Template__c=testSpec.Id);
        try
         {
          insert testJob1;
         }
        catch(System.DMLException e)
         {
          System.assertEquals('FIELD_CUSTOM_VALIDATION',e.getDmlStatusCode(0));
         }
        System.assertEquals('TJ2999',testJob1.Name);
           
        GL_Department__c testGLD = new GL_Department__c(Name='TGLD2999');
         try
          {
           insert testGLD;
          }
         catch(System.DMLException e)
          {
           System.assertEquals('FIELD_CUSTOM_VALIDATION_EXCEPTION',e.getDmlStatusCode(0));
          }   
                    
        Vendor__c testVendor=new Vendor__c(Name='TV2999');
        insert testVendor;
             
        GL_Code__c testGL1=new GL_Code__c();
          testGL1.Name='TGLC2999';
          testGL1.GL_Id__c='GL 2999';
          testGL1.GL_Department__c=testGLD.id;
          testGL1.Unit_Cost__c=2500;
          testGL1.Unit_Type__c='Days';
             
        try
         {
          insert testGL1;
         }
        catch(System.DMLException e)
         {
          System.assert(e.getMessage().contains('Record already exist with same GLCode'));
         }
             
        Production_Estimate__c  testELI=new Production_Estimate__c (Name='ELI 2999',Job__c=testjob1.Id,GL_Department__c=testGLD.id,Vendor__c=testVendor.Id,Amount__c=500,Quantity__c=120,GL_Code__c =testGL1.Id);   
        insert testELI;
          
        Purchase_Order__c testPO=new Purchase_Order__c(Job__c=testjob1.Id,Issue_Date__c=System.Today(),Due_Date__c=System.Today(),Invoice_Created__c='No',Status__c='Sent',Vendor__c=testVendor.Id,GL_Code__c=testGL1.Id);
        insert testPO;
          
        PO_Line_Item__c POLI = new PO_Line_Item__c(Invoice_Created__c=False,Amount__c=5000,Purchase_Order__c=testPO.Id,Production_Estimate__c =testELI.Id);
        insert POLI;
           
        PO_Line_Item__c POLI1 = new PO_Line_Item__c(Invoice_Created__c=True,Amount__c=5000,Purchase_Order__c=testPO.Id,Production_Estimate__c =testELI.Id);
        insert POLI1;
              
        Invoice__c testI=new Invoice__c(Job__c=testjob1.Id,Date_Received__c=System.Today(),Vendor__c=testVendor.Id,Purchase_Order__c=testPO.id);  
        insert testI;
              test.stoptest();
        ApexPages.currentPage().getParameters().put('Invid', testI.Id);    
      
       // Invoke the primary method on the extension 
       addPOLineItem ext=new addPOLineItem();
       ApexPages.PageReference result1=ext.save();
             ext.roleWraps[0].checked=False;
         
             result1=ext.save();
        
             ext.roleWraps[0].checked=True;
       
            result1=ext.save();
            ApexPages.PageReference result2=ext.Back();

     }
   // End Test Coverage
	static testMethod void TestAddPOLineItem2()
     {
     
     test.starttest();
        ProductionEstimate__c cs11etting=new ProductionEstimate__c(Active__c=false);
           insert cs11etting;
        Job_Number_Setting__c cs1999 = new  Job_Number_Setting__c(Name= 'yy');
        insert cs1999;
        
        Media_Type__c testMedia=new Media_Type__c(Name='TM 2999');
        try
         {
          insert testMedia;
         }
        catch(System.DMLException e)
         {
          System.assertEquals('FIELD_CUSTOM_VALIDATION',e.getDmlStatusCode(0));
         }
           
        Schedule_Template__c testST=new Schedule_Template__c(Name='TST2999',Media_Types__c=testMedia.Id);
        insert testST;
                 
        Specification_Template__c testSpec=new Specification_Template__c(Name='TST2999');
        insert testSpec;
                
        Job__c testJob1=new Job__c(Name='TJ2999',Start_Date__c=System.Today(),Media_Types__c=testMedia.Id,Schedule_Template__c=testST.Id,Specification_Template__c=testSpec.Id);
        try
         {
          insert testJob1;
         }
        catch(System.DMLException e)
         {
          System.assertEquals('FIELD_CUSTOM_VALIDATION',e.getDmlStatusCode(0));
         }
        System.assertEquals('TJ2999',testJob1.Name);
           
        GL_Department__c testGLD = new GL_Department__c(Name='TGLD2999');
         try
          {
           insert testGLD;
          }
         catch(System.DMLException e)
          {
           System.assertEquals('FIELD_CUSTOM_VALIDATION_EXCEPTION',e.getDmlStatusCode(0));
          }   
                    
        Vendor__c testVendor=new Vendor__c(Name='TV2999');
        insert testVendor;
             
        GL_Code__c testGL1=new GL_Code__c();
          testGL1.Name='TGLC2999';
          testGL1.GL_Id__c='GL 2999';
          testGL1.GL_Department__c=testGLD.id;
          testGL1.Unit_Cost__c=2500;
          testGL1.Unit_Type__c='Days';
             
        try
         {
          insert testGL1;
         }
        catch(System.DMLException e)
         {
          System.assert(e.getMessage().contains('Record already exist with same GLCode'));
         }
             
        Production_Estimate__c  testELI=new Production_Estimate__c (Name='ELI 2999',Job__c=testjob1.Id,GL_Department__c=testGLD.id,Vendor__c=testVendor.Id,Amount__c=500,Quantity__c=120,GL_Code__c =testGL1.Id);   
        insert testELI;
          
        Purchase_Order__c testPO=new Purchase_Order__c(Job__c=testjob1.Id,Issue_Date__c=System.Today(),Due_Date__c=System.Today(),Invoice_Created__c='No',Status__c='Sent',Vendor__c=testVendor.Id,GL_Code__c=testGL1.Id);
        insert testPO;
          
        PO_Line_Item__c POLI = new PO_Line_Item__c(Invoice_Created__c=False,Amount__c=5000,Purchase_Order__c=testPO.Id,Production_Estimate__c =testELI.Id);
        insert POLI;
           
        PO_Line_Item__c POLI1 = new PO_Line_Item__c(Invoice_Created__c=True,Amount__c=5000,Purchase_Order__c=testPO.Id,Production_Estimate__c =testELI.Id);
        insert POLI1;
              
        Invoice__c testI=new Invoice__c(Job__c=testjob1.Id,Date_Received__c=System.Today(),Vendor__c=testVendor.Id,Purchase_Order__c=testPO.id);  
        insert testI;
              test.stoptest();
        ApexPages.currentPage().getParameters().put('Invid', testI.Id);    
      
       // Invoke the primary method on the extension 
       addPOLineItem ext=new addPOLineItem();
       ApexPages.PageReference result1=ext.save();
             ext.roleWraps[0].checked=False;
         
             result1=ext.save();
        
             ext.roleWraps[0].checked=True;
       		 ext.roleWraps[0].Calc_amnt = 0;
            result1=ext.save();
            ApexPages.PageReference result2=ext.Back();

     }*/


}