objects/Estimate_Line_Items__c/Estimate_Line_Items__c.object-meta.xml
<CustomObject>
    <description>This is Estimate Line Item object.</description>
    <label>Estimate Line Item</label>
    <nameField>
        <label>Line Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Estimate Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Estimate_Line_Items__c/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <label>Job Name</label>
    <referenceTo>Job__c</referenceTo>
    <relationshipLabel>Line Items</relationshipLabel>
    <relationshipName>Estimate</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/Job__c/Job__c.object-meta.xml
<CustomObject>
    <description>This is Job object.</description>
    <label>Job</label>
    <nameField>
        <label>Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/TestEstimateSwitchExt.cls
@isTest
public class TestEstimateSwitchExt {
	/* static TestMethod void TestEstimateSwitchExt(){
        Job__c testJob1=new Job__c(Name='Job858',Start_Date__c=System.Today());
        insert testJob1;
        Estimate_Line_Items__c testEst=new Estimate_Line_Items__c(Name='Camp',Job__c=testJob1.id);
        insert testEst;
        EstimateSwitchExt controller = new EstimateSwitchExt(new ApexPages.StandardController(testEst));
      //  boolean x = controller.isMobile;
}*/
}