objects/Estimate_Line_Items__c/Estimate_Line_Items__c.object-meta.xml
<CustomObject>
    <description>This is Estimate Line Item object.</description>
    <label>Estimate Line Item</label>
    <nameField>
        <label>Line Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Estimate Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Estimate_Line_Items__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Unit Cost</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

objects/Estimate_Line_Items__c/fields/GL_Code__c.field-meta.xml
<CustomField>
    <fullName>GL_Code__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GL Description</label>
    <referenceTo>GL_Code__c</referenceTo>
    <relationshipLabel>Line Items</relationshipLabel>
    <relationshipName>Estimate</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Estimate_Line_Items__c/fields/GL_Department__c.field-meta.xml
<CustomField>
    <fullName>GL_Department__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GL Department</label>
    <referenceTo>GL_Department__c</referenceTo>
    <relationshipLabel>Line Items</relationshipLabel>
    <relationshipName>Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Estimate_Line_Items__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <label>Quantity</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

objects/Estimate_Line_Items__c/fields/Unit_Type__c.field-meta.xml
<CustomField>
    <fullName>Unit_Type__c</fullName>
    <formula>Text( GL_Code__r.Unit_Type__c )</formula>
    <label>Unit Type</label>
    <type>Text</type>
</CustomField>

objects/Estimate_Spec_Item__c/Estimate_Spec_Item__c.object-meta.xml
<CustomObject>
    <description>This is Estimate Spec Item object. It act as line items of Estimate Line Item Object.</description>
    <label>Spec  Item</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Estimate Spec Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Estimate_Spec_Item__c/fields/Estimates__c.field-meta.xml
<CustomField>
    <fullName>Estimates__c</fullName>
    <label>Estimates</label>
    <referenceTo>Estimate_Line_Items__c</referenceTo>
    <relationshipName>Estimate_Line_Item</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/GL_Code__c/GL_Code__c.object-meta.xml
<CustomObject>
    <description>GL Codes are used to build line items on our Job Cost Layouts.  The Job Cost Layouts are the Quote, Estimate, Purchase Order, and Vendor Invoice.   The line items on each of these follow similar logic.</description>
    <label>GL Code</label>
    <nameField>
        <label>Description</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GL Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/GL_Code__c/fields/GL_Department__c.field-meta.xml
<CustomField>
    <fullName>GL_Department__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GL Department</label>
    <referenceTo>GL_Department__c</referenceTo>
    <relationshipLabel>GL Codes</relationshipLabel>
    <relationshipName>GL_Codes</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/GL_Code__c/fields/Unit_Type__c.field-meta.xml
<CustomField>
    <fullName>Unit_Type__c</fullName>
    <label>Unit Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Days</fullName>
                <default>true</default>
                <label>Days</label>
            </value>
            <value>
                <fullName>Each</fullName>
            </value>
            <value>
                <fullName>Hours</fullName>
            </value>
            <value>
                <fullName>Project</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/GL_Department__c/GL_Department__c.object-meta.xml
<CustomObject>
    <description>This Object is Master of GLCode Object in JobSuite Application.</description>
    <label>GL Department</label>
    <nameField>
        <label>GL Department</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GL Department</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <description>This is Invoice object.</description>
    <label>Invoice</label>
    <nameField>
        <label>Invoice Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Invoice__c/fields/Invoice_Status__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Status__c</fullName>
    <description>This is Invoice Status field.</description>
    <label>Invoice Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>Sent to AP</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Invoice__c/fields/Purchase_Order__c.field-meta.xml
<CustomField>
    <fullName>Purchase_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>PO #</label>
    <referenceTo>Purchase_Order__c</referenceTo>
    <relationshipLabel>Invoice</relationshipLabel>
    <relationshipName>Invoice</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Invoice_Line_Item__c/Invoice_Line_Item__c.object-meta.xml
<CustomObject>
    <description>This is Invoice Line Item object. It is child object Invoice object.</description>
    <label>Invoice Line Item</label>
    <nameField>
        <displayFormat>ILI-{0000}</displayFormat>
        <label>ILI #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Invoice_Line_Item__c/fields/Estimate_Line_Item__c.field-meta.xml
<CustomField>
    <fullName>Estimate_Line_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Line Item Name</label>
    <referenceTo>Estimate_Line_Items__c</referenceTo>
    <relationshipLabel>Invoice Line Items</relationshipLabel>
    <relationshipName>Invoice_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Invoice_Line_Item__c/fields/GL_Code__c.field-meta.xml
<CustomField>
    <fullName>GL_Code__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GL Description</label>
    <referenceTo>GL_Code__c</referenceTo>
    <relationshipLabel>Invoice Line Items</relationshipLabel>
    <relationshipName>Invoice_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Invoice_Line_Item__c/fields/GL_Code_No__c.field-meta.xml
<CustomField>
    <fullName>GL_Code_No__c</fullName>
    <formula>GL_Code__r.GL_ID__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>GL Code</label>
    <type>Text</type>
</CustomField>

objects/Invoice_Line_Item__c/fields/GL_Department__c.field-meta.xml
<CustomField>
    <fullName>GL_Department__c</fullName>
    <formula>GL_Code__r.GL_Department__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>GL Department</label>
    <type>Text</type>
</CustomField>

objects/Invoice_Line_Item__c/fields/Production_Estimate__c.field-meta.xml
<CustomField>
    <fullName>Production_Estimate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Production Estimate</label>
    <referenceTo>Production_Estimate__c</referenceTo>
    <relationshipLabel>Invoice Line Items</relationshipLabel>
    <relationshipName>Invoice_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Invoice_Line_Item__c/fields/Unit_Type__c.field-meta.xml
<CustomField>
    <fullName>Unit_Type__c</fullName>
    <formula>Text( GL_Code__r.Unit_Type__c)</formula>
    <label>Unit Type</label>
    <type>Text</type>
</CustomField>

objects/Production_Estimate__c/Production_Estimate__c.object-meta.xml
<CustomObject>
    <description>This is Production Estimate object.</description>
    <label>Production Estimate</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Production Estimates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Production_Estimate__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Cost</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Currency</type>
</CustomField>

objects/Production_Estimate__c/fields/GL_Code__c.field-meta.xml
<CustomField>
    <fullName>GL_Code__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GL Description</label>
    <referenceTo>GL_Code__c</referenceTo>
    <relationshipLabel>Production Estimates</relationshipLabel>
    <relationshipName>Production_Estimates</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Production_Estimate__c/fields/GL_Department__c.field-meta.xml
<CustomField>
    <fullName>GL_Department__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GL Department</label>
    <referenceTo>GL_Department__c</referenceTo>
    <relationshipLabel>Production Estimates</relationshipLabel>
    <relationshipName>Production_Estimates</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/ProductionEstimate__c/ProductionEstimate__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>This is to use Production Estimate in place of Standard Estimate &amp; New Copy Schedule Button.</description>
    <label>Job Suite Controls</label>
</CustomObject>

objects/ProductionEstimate__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This One Is for to Activate Production Estimate in place of Standard Estimate</description>
    <inlineHelpText>This One Is for to Activate Production Estimate in place of Standard Estimate</inlineHelpText>
    <label>Production Estimate Active</label>
    <type>Checkbox</type>
</CustomField>

objects/Purchase_Order__c/Purchase_Order__c.object-meta.xml
<CustomObject>
    <description>This is Purchase Order object.</description>
    <label>Purchase Order</label>
    <nameField>
        <label>PO #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Purchase Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Purchase_Order__c/fields/GL_Code__c.field-meta.xml
<CustomField>
    <fullName>GL_Code__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GL Code</label>
    <lookupFilter>
        <active>false</active>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>GL_Code__c</referenceTo>
    <relationshipLabel>Purchase Orders</relationshipLabel>
    <relationshipName>Purchase_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

classes/DisplayInvoiceNewExtension.cls
// This method is used to display Invoices under Job Tab
public with sharing class DisplayInvoiceNewExtension     
{

    public boolean isLtng{ set; get{
                                            String theme = UserInfo.getUITheme();
                                            return (theme=='Theme4d')?true:false;
                                          }
            }  
            

//Added by Rahul starts--
    public string myClient {get; set;}
    public Invoice_Line_Item__c inv {get; set;}
    Public Boolean ShowProductionEstimate{get;set;}
//--ends

    public String getPoId() { 
        return poId;
    }

    // Global variables
   // Public String theID;
   Public ID theID;
    public List<Invoice_Line_Item__c> ILI{get;set;} 
    Invoice__c objInv{get;set;}
   // String poId{get;set;}
   ID poId{get;set;}
//Added by Rahul
    public String inSt{get; set;}
    // End of Global variables

//by rahul added code starts--
    //Delete Line Item 
    public void deleteRec(){
        string pgId = ApexPages.currentPage().getParameters().get('id');
        string ss1 = ApexPages.currentPage().getParameters().get('di1');
        system.debug('@@@@@@@@@@@@@ '+myClient);
        system.debug('************* '+pgId );
         system.debug('========================================================================================== '+ss1);


        inv = [SELECT id, Name, Invoice__c, Invoice__r.Invoice_Status__c FROM Invoice_Line_Item__c WHERE Id =: myClient];
        delete inv;
        ILI=[select id,Name,Invoice__c,Estimate_Line_Item__c,Estimate_Line_Item__r.Name,Production_Estimate__r.name,Production_Estimate__c,Amount__c,GL_Code__c,Unit_Type__c,GL_Department__c,GL_Code_No__c,Quantity__c from Invoice_Line_Item__c where Invoice__c =: theID ORDER BY Name];

        /*
       PageReference newpg = new PageReference('/apex/InvoiceDetailPageLightning?id='+pgId);
        return newpg;
       */
    }

    //Edit record
    public pageReference editRec(){
        string pgId = ApexPages.currentPage().getParameters().get('id');
        string ss2 = ApexPages.currentPage().getParameters().get('di2');
        system.debug('@@@@@@@@@@@@@ '+myClient);
        system.debug('************* '+pgId );
         system.debug('==================================================================================================== '+ss2);
        inv = [SELECT id, Name, Invoice__c, Invoice__r.Purchase_Order__c, Invoice__r.Invoice_Status__c, Amount__c, GL_Code__c, Estimate_Line_Item__c FROM Invoice_Line_Item__c WHERE Id =: myClient];
       
        PageReference newpg;
        if(isLtng)
            newpg = new PageReference('/apex/EditLineItemLightning?id='+myClient);
        else
            newpg = new PageReference('/apex/EditLineItem?id='+myClient);
            newpg.setRedirect(true);
            return newpg;
        
//created this following new page.
        
    }
//added code ends here
    
    // Start Constructor
    public DisplayInvoiceNewExtension()
    {
         ProductionEstimate__c  activeSettings = ProductionEstimate__c.getOrgDefaults();
         ShowProductionEstimate =activeSettings.Active__c;
        
         theID = ESAPI.encoder().SFDC_HTMLENCODE(ApexPages.CurrentPage().getParameters().get('id'));
         objInv=[Select Id, Name, Purchase_Order__c, Invoice_Status__c from Invoice__c where Id=: theId LIMIT 1];
         poId=ESAPI.encoder().SFDC_HTMLENCODE(objInv.Purchase_Order__c);
         ILI=[select id,Name,Invoice__c,Estimate_Line_Item__c,Estimate_Line_Item__r.Name,Production_Estimate__r.name,Production_Estimate__c,Amount__c,GL_Code__c,Unit_Type__c,GL_Department__c,GL_Code_No__c,Quantity__c from Invoice_Line_Item__c where Invoice__c =: theID ORDER BY Name];
         
//added by Rahul
         inSt = objInv.Invoice_Status__c;
    }
    // End of Constructor
 
    // This method is called on to add Invoice LIne Item for selected Invoice
     public PageReference add_ILI()
    {
        
        PageReference p;
        if(isLtng)
             p =  Page.AddInvoicelineItemNewLightning;
            
        else
            p =  Page.AddInvoicelineItemNew;
            p.setRedirect(true);
            p.getParameters().put('Invid',theID);
            return p;
    } 
    // End of method
    
     // This method is called on to add PO LIne Item for selected Invoice
    public PageReference add_ILI_from_poli()
    {
       
     //   PageReference p =  Page.AddPOLineItem;
     PageReference p;
       if(isLtng)
             p =  Page.addPOLineItemLightning;
        else
            p=Page.addPOLineItem;
            p.setRedirect(true);
            p.getParameters().put('Invid',theID);
            return p;
        
    } 
    // End of method
    
    
    public PageReference save()
    {
     try
      {
           update ILI;
      }
     catch(System.DMLException e){return null;}
     
     PageReference p;
    if(isLtng)
           p = new Pagereference('/apex/InvoiceDetailPageLightning?id='+theID);
    else
         p =  new Pagereference('/apex/InvoiceDetailPage?id='+theID);
          p.setRedirect(true);
          return p; 
   
      // After updating PO, navigate to Purchase Order Tab
     
    }
    //End Of Save Method  
    
    //Method For Cancel button    
     public PageReference cancelme()
     {
       PageReference p;
       if(isLtng)
           p=new Pagereference('/apex/InvoiceDetailPageLightning?id='+theID);
        else
          p=new Pagereference('/apex/InvoiceDetailPage?id='+theID);
          p.setRedirect(true);
          return p;    
        
     }
    //End Of Cancel Buttons method  
     
    
}// End of Class