objects/Estimate_Line_Items__c/Estimate_Line_Items__c.object-meta.xml
<CustomObject>
    <description>This is Estimate Line Item object.</description>
    <label>Estimate Line Item</label>
    <nameField>
        <label>Line Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Estimate Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Estimate_Line_Items__c/fields/GL_Department__c.field-meta.xml
<CustomField>
    <fullName>GL_Department__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GL Department</label>
    <referenceTo>GL_Department__c</referenceTo>
    <relationshipLabel>Line Items</relationshipLabel>
    <relationshipName>Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Estimate_Line_Items__c/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <label>Job Name</label>
    <referenceTo>Job__c</referenceTo>
    <relationshipLabel>Line Items</relationshipLabel>
    <relationshipName>Estimate</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/Estimate_Spec_Item__c/Estimate_Spec_Item__c.object-meta.xml
<CustomObject>
    <description>This is Estimate Spec Item object. It act as line items of Estimate Line Item Object.</description>
    <label>Spec  Item</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Estimate Spec Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Estimate_Spec_Item__c/fields/Estimates__c.field-meta.xml
<CustomField>
    <fullName>Estimates__c</fullName>
    <label>Estimates</label>
    <referenceTo>Estimate_Line_Items__c</referenceTo>
    <relationshipName>Estimate_Line_Item</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/GL_Department__c/GL_Department__c.object-meta.xml
<CustomObject>
    <description>This Object is Master of GLCode Object in JobSuite Application.</description>
    <label>GL Department</label>
    <nameField>
        <label>GL Department</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GL Department</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Job__c/Job__c.object-meta.xml
<CustomObject>
    <description>This is Job object.</description>
    <label>Job</label>
    <nameField>
        <label>Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Job__c/fields/Media_Types__c.field-meta.xml
<CustomField>
    <fullName>Media_Types__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Media Type</label>
    <referenceTo>Media_Type__c</referenceTo>
    <relationshipName>Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Job__c/fields/Schedule_Template__c.field-meta.xml
<CustomField>
    <fullName>Schedule_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Schedule Template</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Schedule_Template__c.Media_Types__c</field>
            <operation>equals</operation>
            <valueField>$Source.Media_Types__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Schedule_Template__c</referenceTo>
    <relationshipName>Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Job__c/fields/Specification_Template__c.field-meta.xml
<CustomField>
    <fullName>Specification_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Creative Brief Template</label>
    <referenceTo>Specification_Template__c</referenceTo>
    <relationshipName>Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Media_Type__c/Media_Type__c.object-meta.xml
<CustomObject>
    <description>This is Media Type object.</description>
    <label>Media Type</label>
    <nameField>
        <label>Media Type</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Media Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Production_Spec_Item__c/Production_Spec_Item__c.object-meta.xml
<CustomObject>
    <description>This Object is used as child object of Production Spec Template in Master detail relationship.</description>
    <label>Production Spec Item</label>
    <nameField>
        <label>Spec Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Production Spec Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Production_Spec_Item__c/fields/Production_Spec_Template__c.field-meta.xml
<CustomField>
    <fullName>Production_Spec_Template__c</fullName>
    <label>Production Spec Template</label>
    <referenceTo>Production_Spec_Template__c</referenceTo>
    <relationshipLabel>Production Spec Items</relationshipLabel>
    <relationshipName>Production_Spec_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/Production_Spec_Template__c/Production_Spec_Template__c.object-meta.xml
<CustomObject>
    <description>This object is used to import spec for Quote object.</description>
    <label>Production Spec Template</label>
    <nameField>
        <label>Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Production Spec Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Schedule_Template__c/Schedule_Template__c.object-meta.xml
<CustomObject>
    <description>This is Schedule Template object.</description>
    <label>Schedule Template</label>
    <nameField>
        <label>Schedule Template</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Schedule Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Schedule_Template__c/fields/Media_Types__c.field-meta.xml
<CustomField>
    <fullName>Media_Types__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Media Type</label>
    <referenceTo>Media_Type__c</referenceTo>
    <relationshipLabel>Schedule Templates</relationshipLabel>
    <relationshipName>Schedule_Templates</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Specification_Template__c/Specification_Template__c.object-meta.xml
<CustomObject>
    <description>This is Creative Brief Template object. Also known as Specification Template.</description>
    <label>Creative Brief Template</label>
    <nameField>
        <label>Creative Brief Template</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Creative Brief Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/Test_DisplayProdEstSpecInEstTab.cls
@istest
public Class Test_DisplayProdEstSpecInEstTab
{

    static testMethod void Test_DisplayProdEstSpecInEstTab()
    {
       /*  Media_Type__c testMedia=new Media_Type__c(Name='Test Media 361');
             
                insert testMedia;
             
              Schedule_Template__c testST=new Schedule_Template__c(Name='Test Schedule Template 361',Media_Types__c=testMedia.Id);
             
                 insert testST;
     
              Specification_Template__c testSpec=new Specification_Template__c(Name='Testing Spcification Template 361');
              
                insert testSpec;
                
              Production_Spec_Template__c testProdSpectemp= new Production_Spec_Template__c (Name='Testing Production Spcification Temp');
              insert testProdSpectemp;
                
             Production_Spec_Item__c testProdSpec= new Production_Spec_Item__c(Name='Testing Production Spcification item',Production_Spec_Template__c=testProdSpectemp.Id );
              insert testProdSpec;
        
             Job__c testJob1=new Job__c(Name='Test Job 361',Start_Date__c=System.Today(),Media_Types__c=testMedia.Id,Schedule_Template__c=testST.Id,Specification_Template__c=testSpec.Id);
              try
               {
                   insert testJob1;
               }
              catch(System.DMLException e)
               {
                   System.assert(e.getMessage().contains('Job with same name Exists'));
               }
              System.assertEquals('Test Job 361',testJob1.Name); 
               
             GL_Department__c testGLD = new GL_Department__c(Name='TestGLD3');
              try
               {
                   insert testGLD;
               }
              catch(System.DMLException e)
               {
                   System.assertEquals('FIELD_CUSTOM_VALIDATION_EXCEPTION',e.getDmlStatusCode(0));
               }      
       
             Estimate_Line_Items__c testELI=new Estimate_Line_Items__c(Name='Quote 361',Job__c=testjob1.Id,GL_Department__c=testGLD.id);
              try
               {
                   insert testELI;
               }
              catch(System.DMLException e)
               {
                   System.assert(e.getMessage().contains('Job with same name Exists'));
               }
               
             Estimate_Spec_Item__c testESI = new Estimate_Spec_Item__c(Name='Spec Item 361',Estimates__c=testELI.Id);
             try
               {
                   insert testESI;
               }
              catch(System.DMLException e)
               {
                   System.assert(e.getMessage().contains('Job with same name Exists'));
               }
             
             
             
              System.assertEquals('Spec Item 361',testESI.Name);
                 
        ApexPages.currentPage().getParameters().put('id',testELI.Id); 
       
       // Instantiate the standard controller with the Job
        ApexPages.StandardController con=new ApexPages.StandardController(testELI);
       
        // Instantiate the extention instance with the standard controller 
        
        DisplayProductionEstSpecInEstimateTabExt  ext1=new DisplayProductionEstSpecInEstimateTabExt(con);
       
        ext1.specId=testESI.id;
       
        // Invoke the primary method on the extension
        
        ApexPages.Pagereference result=ext1.editspec();
       
        ext1.save();
        ext1.importSpecs();
        
        ext1.ProductionSpecTempName=testProdSpectemp.Id;
        ext1.importSpecs();
    	ext1.addNewSpecs();
        
        List<SelectOption> lst=ext1.getProductionSpecTemplate();
       
        ext1.cancelme();
       
        ext1.DelSpec();
        
      
        ext1.importSpecs();*/
    }
    // End Test Coverage
}