objects/Estimate_Line_Items__c/Estimate_Line_Items__c.object-meta.xml
<CustomObject>
    <description>This is Estimate Line Item object.</description>
    <label>Estimate Line Item</label>
    <nameField>
        <label>Line Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Estimate Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Estimate_Line_Items__c/fields/GL_Code__c.field-meta.xml
<CustomField>
    <fullName>GL_Code__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GL Description</label>
    <referenceTo>GL_Code__c</referenceTo>
    <relationshipLabel>Line Items</relationshipLabel>
    <relationshipName>Estimate</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Estimate_Line_Items__c/fields/GL_Department__c.field-meta.xml
<CustomField>
    <fullName>GL_Department__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GL Department</label>
    <referenceTo>GL_Department__c</referenceTo>
    <relationshipLabel>Line Items</relationshipLabel>
    <relationshipName>Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Estimate_Line_Items__c/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <label>Job Name</label>
    <referenceTo>Job__c</referenceTo>
    <relationshipLabel>Line Items</relationshipLabel>
    <relationshipName>Estimate</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/Estimate_Line_Items__c/fields/Unit_Type__c.field-meta.xml
<CustomField>
    <fullName>Unit_Type__c</fullName>
    <formula>Text( GL_Code__r.Unit_Type__c )</formula>
    <label>Unit Type</label>
    <type>Text</type>
</CustomField>

objects/GL_Code__c/GL_Code__c.object-meta.xml
<CustomObject>
    <description>GL Codes are used to build line items on our Job Cost Layouts.  The Job Cost Layouts are the Quote, Estimate, Purchase Order, and Vendor Invoice.   The line items on each of these follow similar logic.</description>
    <label>GL Code</label>
    <nameField>
        <label>Description</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GL Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/GL_Code__c/fields/GL_Department__c.field-meta.xml
<CustomField>
    <fullName>GL_Department__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GL Department</label>
    <referenceTo>GL_Department__c</referenceTo>
    <relationshipLabel>GL Codes</relationshipLabel>
    <relationshipName>GL_Codes</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/GL_Code__c/fields/GL_ID__c.field-meta.xml
<CustomField>
    <fullName>GL_ID__c</fullName>
    <description>This is GL ID field. These id&apos;s are auto generated.</description>
    <label>GL Code</label>
    <length>15</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

objects/GL_Code__c/fields/Unit_Cost__c.field-meta.xml
<CustomField>
    <fullName>Unit_Cost__c</fullName>
    <label>Unit Cost (In $)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

objects/GL_Code__c/fields/Unit_Type__c.field-meta.xml
<CustomField>
    <fullName>Unit_Type__c</fullName>
    <label>Unit Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Days</fullName>
                <default>true</default>
                <label>Days</label>
            </value>
            <value>
                <fullName>Each</fullName>
            </value>
            <value>
                <fullName>Hours</fullName>
            </value>
            <value>
                <fullName>Project</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Job__c/Job__c.object-meta.xml
<CustomObject>
    <description>This is Job object.</description>
    <label>Job</label>
    <nameField>
        <label>Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Job__c/fields/Media_Types__c.field-meta.xml
<CustomField>
    <fullName>Media_Types__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Media Type</label>
    <referenceTo>Media_Type__c</referenceTo>
    <relationshipName>Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Job__c/fields/Schedule_Template__c.field-meta.xml
<CustomField>
    <fullName>Schedule_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Schedule Template</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Schedule_Template__c.Media_Types__c</field>
            <operation>equals</operation>
            <valueField>$Source.Media_Types__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Schedule_Template__c</referenceTo>
    <relationshipName>Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Job__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Requested</fullName>
                <default>true</default>
                <label>Requested</label>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Job_Task__c/Job_Task__c.object-meta.xml
<CustomObject>
    <description>This is Job Task object. Also known as Schedule.</description>
    <label>Job Task</label>
    <nameField>
        <label>Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Job_Task__c/fields/Days__c.field-meta.xml
<CustomField>
    <fullName>Days__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Days</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

objects/Job_Task__c/fields/GL_Code__c.field-meta.xml
<CustomField>
    <fullName>GL_Code__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GL Code</label>
    <referenceTo>GL_Code__c</referenceTo>
    <relationshipName>Job_Task</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Job_Task__c/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <label>Job Name</label>
    <referenceTo>Job__c</referenceTo>
    <relationshipName>Job_Task</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/Job_Task__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Requested</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Production_Estimate__c/Production_Estimate__c.object-meta.xml
<CustomObject>
    <description>This is Production Estimate object.</description>
    <label>Production Estimate</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Production Estimates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Production_Estimate__c/fields/GL_Code__c.field-meta.xml
<CustomField>
    <fullName>GL_Code__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GL Description</label>
    <referenceTo>GL_Code__c</referenceTo>
    <relationshipLabel>Production Estimates</relationshipLabel>
    <relationshipName>Production_Estimates</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Production_Estimate__c/fields/GL_Department__c.field-meta.xml
<CustomField>
    <fullName>GL_Department__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GL Department</label>
    <referenceTo>GL_Department__c</referenceTo>
    <relationshipLabel>Production Estimates</relationshipLabel>
    <relationshipName>Production_Estimates</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Production_Estimate__c/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <label>Job Name</label>
    <referenceTo>Job__c</referenceTo>
    <relationshipLabel>Production Estimates</relationshipLabel>
    <relationshipName>Production_Estimates</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/Schedule_Task__c/Schedule_Task__c.object-meta.xml
<CustomObject>
    <description>This is Schedule Task object. It is child object of Schedule Template object.</description>
    <label>Schedule Task</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Schedule Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Schedule_Task__c/fields/Days__c.field-meta.xml
<CustomField>
    <fullName>Days__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Days</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

objects/Schedule_Task__c/fields/GL_Code__c.field-meta.xml
<CustomField>
    <fullName>GL_Code__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GL Code</label>
    <referenceTo>GL_Code__c</referenceTo>
    <relationshipLabel>Schedule Tasks</relationshipLabel>
    <relationshipName>Schedule_Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Schedule_Task__c/fields/Schedule_Template__c.field-meta.xml
<CustomField>
    <fullName>Schedule_Template__c</fullName>
    <label>Schedule Template</label>
    <referenceTo>Schedule_Template__c</referenceTo>
    <relationshipLabel>Schedule Tasks</relationshipLabel>
    <relationshipName>Schedule_Tasks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/Schedule_Template__c/Schedule_Template__c.object-meta.xml
<CustomObject>
    <description>This is Schedule Template object.</description>
    <label>Schedule Template</label>
    <nameField>
        <label>Schedule Template</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Schedule Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Schedule_Template__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

objects/Schedule_Template__c/fields/Media_Types__c.field-meta.xml
<CustomField>
    <fullName>Media_Types__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Media Type</label>
    <referenceTo>Media_Type__c</referenceTo>
    <relationshipLabel>Schedule Templates</relationshipLabel>
    <relationshipName>Schedule_Templates</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Timesheet_Entries__c/Timesheet_Entries__c.object-meta.xml
<CustomObject>
    <label>Timesheet Entry</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Timesheet Entry No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Timesheet Entries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Timesheet_Entries__c/fields/GL_Code__c.field-meta.xml
<CustomField>
    <fullName>GL_Code__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GL Code</label>
    <referenceTo>GL_Code__c</referenceTo>
    <relationshipName>Timesheet_Entries</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Timesheet_Entries__c/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <label>Job</label>
    <referenceTo>Job__c</referenceTo>
    <relationshipName>Job_Timesheets</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

objects/Vendor_GL_Code__c/Vendor_GL_Code__c.object-meta.xml
<CustomObject>
    <description>This is Vendor GL Code object.</description>
    <label>Vendor GL Code</label>
    <nameField>
        <displayFormat>VGC - {0000}</displayFormat>
        <label>Vendor GL Code #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vendor GL Codes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Vendor_GL_Code__c/fields/GL_Code__c.field-meta.xml
<CustomField>
    <fullName>GL_Code__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GL Code</label>
    <referenceTo>GL_Code__c</referenceTo>
    <relationshipName>Vendor_GL_Codes</relationshipName>
    <type>Lookup</type>
</CustomField>

classes/TestNewTsEntrieshometasksExt.cls
@IsTest
public class TestNewTsEntrieshometasksExt{
    public static testMethod void TestNewTsEntrieshometasksExt(){                
      /*  GL_Department__c objGLD = new GL_Department__c(Name='Test GL Dept');
        insert objGLD;
        
        GL_Code__c objGLC = new GL_Code__c(Name='Test GL Code', GL_ID__c='Test Id1', GL_Department__c=objGLD.Id,Unit_Type__c='Days',Unit_Cost__c=100);
        insert objGLC;
        
        Media_Type__c objMType = new Media_Type__c(Name='Test Media Type');
        insert objMType;
        
        Schedule_Template__c objST = new Schedule_Template__c(Name='Test Schedule Temp', Active__c=true, Media_Types__c=objMType.Id);
        insert objST;
        
        Schedule_Task__c objSchTask1 = new Schedule_Task__c(Name='Task 1', GL_Code__c=objGLC.Id, Schedule_Template__c=objST.Id, Days__c=10);
        insert objSchTask1;
        
        Schedule_Task__c objSchTask2 = new Schedule_Task__c(Name='Task 2', GL_Code__c=objGLC.Id, Schedule_Template__c=objST.Id, Days__c=10);
        insert objSchTask2;
        
        Job__c objJob = new Job__c();
        objJob.Name = 'Test Job 1';
        objJob.Status__c = 'Active';
        objJob.Media_Types__c = objMType.Id;
        objJob.Schedule_Template__c = objST.Id;
        objJob.Schedule_Calc__c = 'Start Date';
        objJob.Start_Date__c = Date.Today();
        insert objJob;
        
        Job_Task__c objJobTask1 = new Job_Task__c();
        objJobTask1.Name = objSchTask1.Name;
        objJobTask1.GL_Code__c = objSchTask1.GL_Code__c;
        objJobTask1.Job__c = objJob.Id;
        objJobTask1.Days__c = objSchTask1.Days__c;
        objJobTask1.Start_Date__c = Date.Today();
        objJobTask1.Task_Order__c = 1;
        insert objJobTask1;

        Job_Task__c objJobTask2 = new Job_Task__c();
        objJobTask2.Name = objSchTask2.Name;
        objJobTask2.GL_Code__c = objSchTask2.GL_Code__c;
        objJobTask2.Job__c = objJob.Id;
        objJobTask2.Days__c = objSchTask2.Days__c;
        objJobTask2.Start_Date__c = Date.Today();
        objJobTask2.Task_Order__c = 2;
        insert objJobTask2;
        
        Vendor__c objV = new Vendor__c();
        objV.Name = 'Test Vendor';
        insert objV;
        
        Vendor_GL_Code__c objVGL = new Vendor_GL_Code__c();
        objVGL.GL_Code__c = objGLC.Id;
        objVGL.Vendor__c = objV.Id;
        insert objVGL;
        
        Estimate_Line_Items__c objESLT = new Estimate_Line_Items__c();
        objESLT.Name = 'Test Line Item 1';
        objESLT.GL_Department__c = objGLD.Id;
        objESLT.GL_Code__c = objGLC.Id;
        objESLT.Job__c = objJob.Id;
        objESLT.Quantity__c = 200;
        objESLT.Vendor__c = objV.Id;      
        insert objESLT;
        
        
        
        
        Timesheet_Entries__c objJSTS = new Timesheet_Entries__c();
        ApexPages.currentPage().getParameters().put('jobId',objJob.id);
        ApexPages.currentPage().getParameters().put('tid',objJobTask1.id);
       // ApexPages.currentPage().getParameters().put('TaskId',objJobTask1.id);
        ApexPages.StandardController sc = new ApexPages.StandardController(objJSTS);
        
        NewTsEntrieshometasksExt objJTExt = new NewTsEntrieshometasksExt(sc);
        objJTExt.JobNameStr = objJob.Id;
        objJTExt.JobTaskNameStr = objJobTask1.Id; 
               
        objJTExt.getJobName();
        objJTExt.getTaskName();        
       // objJTExt.getGLCodeOfTask();
        objJTExt.getTotalHours();
        objJTExt.getRemainHours();
        objJTExt.objTSDetail.Date__c = Date.Today();
        objJTExt.objTSDetail.Notes__c = 'Test-Worked on task 1 today';
        objJTExt.objTSDetail.Hours_Worked__c = 10;
        objJTExt.objTSDetail.User__c = UserInfo.getUserId();        
        //objJTExt.Save();
      //   objJTExt.cancel();
        objJTExt.JobNameStr = '';
        objJTExt.JobTaskNameStr = '';
        objJTExt.getJobName();
        objJTExt.getTaskName();        
       // objJTExt.getGLCodeOfTask();
        objJTExt.getTotalHours();
        objJTExt.getRemainHours();
        objJTExt.objTSDetail.Date__c = Null;
        objJTExt.objTSDetail.Notes__c = '';
        objJTExt.objTSDetail.Hours_Worked__c = 0.00;
        objJTExt.objTSDetail.User__c = Null; 
        objJTExt.end();
        objJTExt.start();       
        objJTExt.Save();
        
        objJTExt.JobNameStr = objJob.Id;
        objJTExt.JobTaskNameStr = '';
        objJTExt.getJobName();
        objJTExt.getTaskName();        
      //  objJTExt.getGLCodeOfTask();
        objJTExt.getTotalHours();
        objJTExt.getRemainHours();
        objJTExt.objTSDetail.Date__c = Null;
        objJTExt.objTSDetail.Notes__c = '';
        objJTExt.objTSDetail.Hours_Worked__c = 0.00;
        objJTExt.objTSDetail.User__c = Null;        
        objJTExt.Save();
        
        objJTExt.JobNameStr = objJob.Id;
        objJTExt.JobTaskNameStr = objJobTask1.Id;
        objJTExt.getJobName();
        objJTExt.getTaskName();        
       // objJTExt.getGLCodeOfTask();
        objJTExt.getTotalHours();
        objJTExt.getRemainHours();
        objJTExt.objTSDetail.Date__c = Null;
        objJTExt.objTSDetail.Notes__c = '';
        objJTExt.objTSDetail.Hours_Worked__c = 0.00;
        objJTExt.objTSDetail.User__c = Null;        
        objJTExt.Save();
        
     /*    objJTExt.JobNameStr = objJob.Id;
        objJTExt.JobTaskNameStr = objJobTask1.Id;
        objJTExt.getJobName();
        objJTExt.getTaskName();        
        objJTExt.getGLCodeOfTask();
        objJTExt.getTotalHours();
        objJTExt.getRemainHours();
        objJTExt.objTSDetail.Date__c = Date.Today();
        objJTExt.objTSDetail.Notes__c = '';
        objJTExt.objTSDetail.Hours_Worked__c = 0.00;
        objJTExt.objTSDetail.User__c = Null;        
        objJTExt.Save();
        
       objJTExt.JobNameStr = objJob.Id;
        objJTExt.JobTaskNameStr = objJobTask1.Id;
        objJTExt.getJobName();
        objJTExt.getTaskName();        
        objJTExt.getGLCodeOfTask();
        objJTExt.getTotalHours();
        objJTExt.getRemainHours();
        objJTExt.objTSDetail.Date__c = Date.Today();
        objJTExt.objTSDetail.Notes__c = '';
        objJTExt.objTSDetail.Hours_Worked__c = 10;
        objJTExt.objTSDetail.User__c = Null;        
        objJTExt.Save();
        
        objJTExt.Cancel();
        
        ApexPages.currentPage().getParameters().put('jobId',objJob.id);
        ApexPages.StandardController sc1 = new ApexPages.StandardController(objJSTS);
        TimesheetEntriesExt objJTExt1 = new TimesheetEntriesExt(sc1);
        objJTExt1.JobNameStr = objJob.Id;
        objJTExt1.JobTaskNameStr = objJobTask1.Id;        
        objJTExt1.getJobName();
        objJTExt1.getTaskName();        
        objJTExt1.getGLCodeOfTask();
        objJTExt1.getTotalHours();
        objJTExt1.getRemainHours();
        objJTExt1.objTSDetail.Date__c = Date.Today();
        objJTExt1.objTSDetail.Notes__c = 'Test-Worked on task 1 today';
        objJTExt1.objTSDetail.Hours_Worked__c = 10;
        objJTExt1.objTSDetail.User__c = UserInfo.getUserId();        
        objJTExt1.Save();
    }
    
    /* public static testMethod void TestTimesheetEntriesExt1(){                
        GL_Department__c objGLD = new GL_Department__c(Name='Test GL Dept');
        insert objGLD;
        
        GL_Code__c objGLC = new GL_Code__c(Name='Test GL Code', GL_ID__c='Test Id1', GL_Department__c=objGLD.Id,Unit_Type__c='Days',Unit_Cost__c=100);
        insert objGLC;
        
        Media_Type__c objMType = new Media_Type__c(Name='Test Media Type');
        insert objMType;
        
        Schedule_Template__c objST = new Schedule_Template__c(Name='Test Schedule Temp', Active__c=true, Media_Types__c=objMType.Id);
        insert objST;
        
        Schedule_Task__c objSchTask1 = new Schedule_Task__c(Name='Task 1', GL_Code__c=objGLC.Id, Schedule_Template__c=objST.Id, Days__c=10);
        insert objSchTask1;
        
        Schedule_Task__c objSchTask2 = new Schedule_Task__c(Name='Task 2', GL_Code__c=objGLC.Id, Schedule_Template__c=objST.Id, Days__c=10);
        insert objSchTask2;
        
        Job__c objJob = new Job__c();
        objJob.Name = 'Test Job 1';
        objJob.Status__c = 'Active';
        objJob.Media_Types__c = objMType.Id;
        objJob.Schedule_Template__c = objST.Id;
        objJob.Schedule_Calc__c = 'Start Date';
        objJob.Start_Date__c = Date.Today();
        insert objJob;
        
        Job_Task__c objJobTask1 = new Job_Task__c();
        objJobTask1.Name = objSchTask1.Name;
        objJobTask1.GL_Code__c = objSchTask1.GL_Code__c;
        objJobTask1.Job__c = objJob.Id;
        objJobTask1.Days__c = objSchTask1.Days__c;
        objJobTask1.Start_Date__c = Date.Today();
        objJobTask1.Task_Order__c = 1;
        insert objJobTask1;

        Job_Task__c objJobTask2 = new Job_Task__c();
        objJobTask2.Name = objSchTask2.Name;
        objJobTask2.GL_Code__c = objSchTask2.GL_Code__c;
        objJobTask2.Job__c = objJob.Id;
        objJobTask2.Days__c = objSchTask2.Days__c;
        objJobTask2.Start_Date__c = Date.Today();
        objJobTask2.Task_Order__c = 2;
        insert objJobTask2;
        
        Vendor__c objV = new Vendor__c();
        objV.Name = 'Test Vendor';
        insert objV;
        
        Vendor_GL_Code__c objVGL = new Vendor_GL_Code__c();
        objVGL.GL_Code__c = objGLC.Id;
        objVGL.Vendor__c = objV.Id;
        insert objVGL;
        
        
        
        
        
        Production_Estimate__c   objpESLT = new Production_Estimate__c  ();
         objpESLT.Name = 'Test Line Item 1';
         objpESLT.GL_Department__c = objGLD.Id;
         objpESLT.GL_Code__c = objGLC.Id;
         objpESLT.Job__c = objJob.Id;
         objpESLT.Quantity__c = 200;
         objpESLT.Vendor__c = objV.Id;      
        insert  objpESLT;
        
        Timesheet_Entries__c objJSTS = new Timesheet_Entries__c();
        objJSTS.Start_Watch__c =system.now();
        objJSTS.End_Watch__c=system.now()+1;
        ApexPages.StandardController sc = new ApexPages.StandardController(objJSTS);
        
        TimesheetEntriesExt objJTExt = new TimesheetEntriesExt(sc);
        objJTExt.JobNameStr = objJob.Id;
        objJTExt.JobTaskNameStr = objJobTask1.Id; 
           
        boolean t=True;
        objJTExt.ShowProductionEstimate=t;
        boolean s=objJTExt.error;
        string t1=objJTExt.calcTimeDiff;
        objJTExt.getJobName();
        objJTExt.getTaskName();        
        objJTExt.getGLCodeOfTask();
        objJTExt.getTotalHours();
        objJTExt.getRemainHours();
        objJTExt.objTSDetail.Date__c = Date.Today();
        objJTExt.objTSDetail.Notes__c = 'Test-Worked on task 1 today';
        objJTExt.objTSDetail.Hours_Worked__c = 10;
        objJTExt.objTSDetail.User__c = UserInfo.getUserId();        
        objJTExt.Save();
        
        objJTExt.JobNameStr = '';
        objJTExt.JobTaskNameStr = '';
        objJTExt.getJobName();
        objJTExt.getTaskName();        
        objJTExt.getGLCodeOfTask();
        objJTExt.getTotalHours();
        objJTExt.getRemainHours();
        objJTExt.objTSDetail.Date__c = Null;
        objJTExt.objTSDetail.Notes__c = '';
        objJTExt.objTSDetail.Hours_Worked__c = 0.00;
        objJTExt.objTSDetail.User__c = Null; 
        objJTExt.end();
        objJTExt.start();       
        objJTExt.Save();
        
        objJTExt.JobNameStr = objJob.Id;
        objJTExt.JobTaskNameStr = '';
        objJTExt.getJobName();
        objJTExt.getTaskName();        
        objJTExt.getGLCodeOfTask();
        objJTExt.getTotalHours();
        objJTExt.getRemainHours();
        objJTExt.objTSDetail.Date__c = Null;
        objJTExt.objTSDetail.Notes__c = '';
        objJTExt.objTSDetail.Hours_Worked__c = 0.00;
        objJTExt.objTSDetail.User__c = Null;        
        objJTExt.Save();
        
        objJTExt.JobNameStr = objJob.Id;
        objJTExt.JobTaskNameStr = objJobTask1.Id;
        objJTExt.getJobName();
        objJTExt.getTaskName();        
        objJTExt.getGLCodeOfTask();
        objJTExt.getTotalHours();
        objJTExt.getRemainHours();
        objJTExt.objTSDetail.Date__c = Null;
        objJTExt.objTSDetail.Notes__c = '';
        objJTExt.objTSDetail.Hours_Worked__c = 0.00;
        objJTExt.objTSDetail.User__c = Null;        
        objJTExt.Save();
        */
        }
    
    
    
    
    
    
}