objects/Estimate_Line_Items__c/Estimate_Line_Items__c.object-meta.xml
<CustomObject>
    <description>This is Estimate Line Item object.</description>
    <label>Estimate Line Item</label>
    <nameField>
        <label>Line Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Estimate Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Estimate_Line_Items__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Unit Cost</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

objects/Estimate_Line_Items__c/fields/GL_Code__c.field-meta.xml
<CustomField>
    <fullName>GL_Code__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GL Description</label>
    <referenceTo>GL_Code__c</referenceTo>
    <relationshipLabel>Line Items</relationshipLabel>
    <relationshipName>Estimate</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Estimate_Line_Items__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <label>Quantity</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

objects/Estimate_Line_Items__c/fields/Unit_Type__c.field-meta.xml
<CustomField>
    <fullName>Unit_Type__c</fullName>
    <formula>Text( GL_Code__r.Unit_Type__c )</formula>
    <label>Unit Type</label>
    <type>Text</type>
</CustomField>

objects/Estimate_Spec_Item__c/Estimate_Spec_Item__c.object-meta.xml
<CustomObject>
    <description>This is Estimate Spec Item object. It act as line items of Estimate Line Item Object.</description>
    <label>Spec  Item</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Estimate Spec Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Estimate_Spec_Item__c/fields/Estimates__c.field-meta.xml
<CustomField>
    <fullName>Estimates__c</fullName>
    <label>Estimates</label>
    <referenceTo>Estimate_Line_Items__c</referenceTo>
    <relationshipName>Estimate_Line_Item</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/GL_Code__c/GL_Code__c.object-meta.xml
<CustomObject>
    <description>GL Codes are used to build line items on our Job Cost Layouts.  The Job Cost Layouts are the Quote, Estimate, Purchase Order, and Vendor Invoice.   The line items on each of these follow similar logic.</description>
    <label>GL Code</label>
    <nameField>
        <label>Description</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GL Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/GL_Code__c/fields/Unit_Type__c.field-meta.xml
<CustomField>
    <fullName>Unit_Type__c</fullName>
    <label>Unit Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Days</fullName>
                <default>true</default>
                <label>Days</label>
            </value>
            <value>
                <fullName>Each</fullName>
            </value>
            <value>
                <fullName>Hours</fullName>
            </value>
            <value>
                <fullName>Project</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/PO_Line_Item__c/PO_Line_Item__c.object-meta.xml
<CustomObject>
    <description>This is Purchase Order Line Item object. It is child object of Purchase Order.</description>
    <label>PO Line Item</label>
    <nameField>
        <displayFormat>POLI-{0000}</displayFormat>
        <label>POLI #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PO Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/PO_Line_Item__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Amount</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

objects/PO_Line_Item__c/fields/Estimate_Line_Item__c.field-meta.xml
<CustomField>
    <fullName>Estimate_Line_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Line Item</label>
    <referenceTo>Estimate_Line_Items__c</referenceTo>
    <relationshipLabel>PO Line Items</relationshipLabel>
    <relationshipName>PO_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/PO_Line_Item__c/fields/GL_Code__c.field-meta.xml
<CustomField>
    <fullName>GL_Code__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GL Description</label>
    <referenceTo>GL_Code__c</referenceTo>
    <relationshipLabel>PO Line Items</relationshipLabel>
    <relationshipName>PO_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/PO_Line_Item__c/fields/Invoice_Created__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Created__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Invoice Created</label>
    <type>Checkbox</type>
</CustomField>

objects/PO_Line_Item__c/fields/Production_Estimate__c.field-meta.xml
<CustomField>
    <fullName>Production_Estimate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Production Estimate</label>
    <referenceTo>Production_Estimate__c</referenceTo>
    <relationshipLabel>PO Line Items</relationshipLabel>
    <relationshipName>PO_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/PO_Line_Item__c/fields/Purchase_Order__c.field-meta.xml
<CustomField>
    <fullName>Purchase_Order__c</fullName>
    <label>Purchase Order</label>
    <referenceTo>Purchase_Order__c</referenceTo>
    <relationshipLabel>PO Line Items</relationshipLabel>
    <relationshipName>PO_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/PO_Line_Item__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <description>POLI&apos; s Quantity will be same as its ELI&apos;s Quantity field value.</description>
    <formula>Estimate_Line_Item__r.Quantity__c</formula>
    <label>Quantity</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

objects/PO_Line_Item__c/fields/Quantity_production__c.field-meta.xml
<CustomField>
    <fullName>Quantity_production__c</fullName>
    <formula>Production_Estimate__r.Quantity__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Quantity</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

objects/PO_Line_Item__c/fields/Unit_Type__c.field-meta.xml
<CustomField>
    <fullName>Unit_Type__c</fullName>
    <formula>Text(GL_Code__r.Unit_Type__c)</formula>
    <label>Unit Type</label>
    <type>Text</type>
</CustomField>

objects/Production_Estimate__c/Production_Estimate__c.object-meta.xml
<CustomObject>
    <description>This is Production Estimate object.</description>
    <label>Production Estimate</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Production Estimates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Production_Estimate__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Cost</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Currency</type>
</CustomField>

objects/Production_Estimate__c/fields/GL_Code__c.field-meta.xml
<CustomField>
    <fullName>GL_Code__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GL Description</label>
    <referenceTo>GL_Code__c</referenceTo>
    <relationshipLabel>Production Estimates</relationshipLabel>
    <relationshipName>Production_Estimates</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/ProductionEstimate__c/ProductionEstimate__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>This is to use Production Estimate in place of Standard Estimate &amp; New Copy Schedule Button.</description>
    <label>Job Suite Controls</label>
</CustomObject>

objects/ProductionEstimate__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This One Is for to Activate Production Estimate in place of Standard Estimate</description>
    <inlineHelpText>This One Is for to Activate Production Estimate in place of Standard Estimate</inlineHelpText>
    <label>Production Estimate Active</label>
    <type>Checkbox</type>
</CustomField>

objects/Purchase_Order__c/Purchase_Order__c.object-meta.xml
<CustomObject>
    <description>This is Purchase Order object.</description>
    <label>Purchase Order</label>
    <nameField>
        <label>PO #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Purchase Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Purchase_Order__c/fields/GL_Code__c.field-meta.xml
<CustomField>
    <fullName>GL_Code__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GL Code</label>
    <lookupFilter>
        <active>false</active>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>GL_Code__c</referenceTo>
    <relationshipLabel>Purchase Orders</relationshipLabel>
    <relationshipName>Purchase_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Purchase_Order__c/fields/Invoice_Created__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Created__c</fullName>
    <label>Invoice Created</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>No</fullName>
                <default>true</default>
                <label>No</label>
            </value>
            <value>
                <fullName>Created</fullName>
            </value>
            <value>
                <fullName>Partially</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

classes/DisplayPOLIWhenPOStatusIsSent.cls
// This class is used to Display POLI When PO Status Is Sent
public with sharing class DisplayPOLIWhenPOStatusIsSent 
{
    // Global variables
    Public String theID;
    public List<PO_Line_Item__c> poli{get;set;} 
    Public Boolean ShowProductionEstimate{get;set;}
    // End of Global variables
    
    // Start Constructor
    public DisplayPOLIWhenPOStatusIsSent(ApexPages.StandardController controller) 
    {
        theID = ApexPages.CurrentPage().getParameters().get('id');
        poli=[select id,Name,Estimate_Line_Item__c,Production_Estimate__c,Estimate_Line_Item__r.name,Invoice_Created__c,Purchase_Order__c,Amount__c,GL_Code__c, Unit_Type__c, Quantity_production__c,Quantity__c from PO_Line_Item__c where Purchase_Order__c =: [Select id from  Purchase_Order__c where id =: theID] Order By Name];
       
        ProductionEstimate__c  activeSettings = ProductionEstimate__c.getOrgDefaults();
        ShowProductionEstimate =activeSettings.Active__c;
    
    }
    // End of Constructor

    
} // End of Class