objects/Estimate_Line_Items__c/Estimate_Line_Items__c.object-meta.xml
<CustomObject>
    <description>This is Estimate Line Item object.</description>
    <label>Estimate Line Item</label>
    <nameField>
        <label>Line Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Estimate Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Estimate_Line_Items__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Unit Cost</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

objects/Estimate_Line_Items__c/fields/GL_Code__c.field-meta.xml
<CustomField>
    <fullName>GL_Code__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GL Description</label>
    <referenceTo>GL_Code__c</referenceTo>
    <relationshipLabel>Line Items</relationshipLabel>
    <relationshipName>Estimate</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Estimate_Line_Items__c/fields/GL_Department__c.field-meta.xml
<CustomField>
    <fullName>GL_Department__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GL Department</label>
    <referenceTo>GL_Department__c</referenceTo>
    <relationshipLabel>Line Items</relationshipLabel>
    <relationshipName>Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Estimate_Line_Items__c/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <label>Job Name</label>
    <referenceTo>Job__c</referenceTo>
    <relationshipLabel>Line Items</relationshipLabel>
    <relationshipName>Estimate</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/Estimate_Line_Items__c/fields/PO__c.field-meta.xml
<CustomField>
    <fullName>PO__c</fullName>
    <label>PO #</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

objects/Estimate_Line_Items__c/fields/PO_Created__c.field-meta.xml
<CustomField>
    <fullName>PO_Created__c</fullName>
    <defaultValue>false</defaultValue>
    <label>PO Created</label>
    <type>Checkbox</type>
</CustomField>

objects/Estimate_Line_Items__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <label>Quantity</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

objects/Estimate_Line_Items__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipName>Estimate</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Estimate_Line_Items__c/fields/Restrict__c.field-meta.xml
<CustomField>
    <fullName>Restrict__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Restrict</label>
    <type>Checkbox</type>
</CustomField>

objects/Estimate_Line_Items__c/fields/Total_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Amount__c</fullName>
    <formula>IF( Unit_Type__c =&quot;Project&quot;, Amount__c , (Amount__c  *   Quantity__c ))</formula>
    <label>Total Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

objects/Estimate_Line_Items__c/fields/Unit_Type__c.field-meta.xml
<CustomField>
    <fullName>Unit_Type__c</fullName>
    <formula>Text( GL_Code__r.Unit_Type__c )</formula>
    <label>Unit Type</label>
    <type>Text</type>
</CustomField>

objects/Estimate_Line_Items__c/fields/Vendor__c.field-meta.xml
<CustomField>
    <fullName>Vendor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vendor</label>
    <referenceTo>Vendor__c</referenceTo>
    <relationshipLabel>Estimate Line Items</relationshipLabel>
    <relationshipName>Estimate</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/GL_Code__c/GL_Code__c.object-meta.xml
<CustomObject>
    <description>GL Codes are used to build line items on our Job Cost Layouts.  The Job Cost Layouts are the Quote, Estimate, Purchase Order, and Vendor Invoice.   The line items on each of these follow similar logic.</description>
    <label>GL Code</label>
    <nameField>
        <label>Description</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GL Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/GL_Code__c/fields/GL_Department__c.field-meta.xml
<CustomField>
    <fullName>GL_Department__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GL Department</label>
    <referenceTo>GL_Department__c</referenceTo>
    <relationshipLabel>GL Codes</relationshipLabel>
    <relationshipName>GL_Codes</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/GL_Code__c/fields/Unit_Type__c.field-meta.xml
<CustomField>
    <fullName>Unit_Type__c</fullName>
    <label>Unit Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Days</fullName>
                <default>true</default>
                <label>Days</label>
            </value>
            <value>
                <fullName>Each</fullName>
            </value>
            <value>
                <fullName>Hours</fullName>
            </value>
            <value>
                <fullName>Project</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/GL_Department__c/GL_Department__c.object-meta.xml
<CustomObject>
    <description>This Object is Master of GLCode Object in JobSuite Application.</description>
    <label>GL Department</label>
    <nameField>
        <label>GL Department</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GL Department</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Job__c/Job__c.object-meta.xml
<CustomObject>
    <description>This is Job object.</description>
    <label>Job</label>
    <nameField>
        <label>Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Job__c/fields/Estimate_Total__c.field-meta.xml
<CustomField>
    <fullName>Estimate_Total__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Estimate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

objects/Quote__c/Quote__c.object-meta.xml
<CustomObject>
    <description>This is Quote object.</description>
    <label>Quote</label>
    <nameField>
        <label>Quote Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Quote__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Quote Amount</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

objects/Quote__c/fields/Approved__c.field-meta.xml
<CustomField>
    <fullName>Approved__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Approved</label>
    <type>Checkbox</type>
</CustomField>

objects/Quote__c/fields/GL_Code__c.field-meta.xml
<CustomField>
    <fullName>GL_Code__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GL Code</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>$Source.GL_Department__c</field>
            <operation>equals</operation>
            <valueField>GL_Code__c.GL_Department__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>GL_Code__c</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Quote__c/fields/GL_Department__c.field-meta.xml
<CustomField>
    <fullName>GL_Department__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GL Department</label>
    <referenceTo>GL_Department__c</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Quote__c/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <label>Job Name</label>
    <referenceTo>Job__c</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/Quote__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <label>Quantity</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

objects/Quote__c/fields/Unit_Type__c.field-meta.xml
<CustomField>
    <fullName>Unit_Type__c</fullName>
    <formula>Text(GL_Code__r.Unit_Type__c )</formula>
    <label>Unit Type</label>
    <type>Text</type>
</CustomField>

objects/Vendor__c/Vendor__c.object-meta.xml
<CustomObject>
    <description>This is Vendor object. Vendors in JobSuite are assigned to the line items on Quotes, Estimates, Purchase Orders and Vendor Invoices.  A printer or photographer may be a vendor.</description>
    <label>Vendor</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vendors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Vendor__c/fields/Vendor__c.field-meta.xml
<CustomField>
    <fullName>Vendor__c</fullName>
    <label>Vendor #</label>
    <length>30</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

classes/DisplayEstimateunderJobTab.cls
// This class is used to display Estimates under Job Tab


public with sharing class DisplayEstimateunderJobTab
{
    public boolean isLtng{private set; get{
                                            String theme = UserInfo.getUITheme();
                                            return (theme=='Theme4d')?true:false;
                                          }
            }  
   
    // Global variables
    public string strEstID{get;set;}
    public string strEstID1{get;set;}
    public List<Estimate_Line_Items__c> vq{get;set;}
    public List<Estimate_Line_Items__c> vq1{get;set;} 
    
    public List<Estimate_Line_Items__c> eli{get;set;}
    public String str{get;set;}
    String theID;
    public string strPEID{get;set;}
    
    public boolean ViewAll{get; set;}
    public boolean ShowLess{get; set;}
    
   public list<inlinewrapperEst> estlst{set;get;}
   public integer rowIndex{get;set;}
   public string estEditField {set;get;}
   inlinewrapperEst ineditEstobj;
  
    // Start constructor
    public DisplayEstimateunderJobTab() 
    {
         theID = ApexPages.CurrentPage().getParameters().get('id');
         
         ViewAll=True;
         ShowLess=False;
    
           vq1=[select id,Name,Approved__c,PO_Created__c,GL_Code__r.Name,Job__c,Vendor__r.Name,GL_Department__c,Quote__r.Name,Amount__c,Total_Amount__c,Quantity__c,Unit_Type__c,Restrict__c,PO__c from Estimate_Line_Items__c where Job__c =: [Select id from Job__c where id =: theID] Order By CreatedDate desc,Name];
          vq=[select id,Name,Approved__c,PO_Created__c,GL_Code__r.Name,Job__c,Vendor__r.Name,GL_Department__c,Quote__r.Name,Amount__c,Total_Amount__c,Quantity__c,Unit_Type__c,Restrict__c,PO__c from Estimate_Line_Items__c where Job__c =: [Select id from Job__c where id =: theID] Order By CreatedDate desc,Name limit:5];
        
           eli=[select id,Name,Approved__c,PO_Created__c,GL_Code__r.Name,Job__c,Vendor__r.Name,Quote__r.Name,Amount__c,Total_Amount__c,Quantity__c,Unit_Type__c,Restrict__c from Estimate_Line_Items__c where Job__c =: [Select id from Job__c where id =: theID] and Approved__c = true ];
        
        
         
         estlst=new list<inlinewrapperEst>();
          for(integer i=0;i<vq.size();i++){
            ineditEstobj=new inlinewrapperEst();
            ineditEstobj.estrec=vq[i];
            ineditEstobj.rowNo=i;
            ineditEstobj.isEdit=false;
            ineditEstobj.isEditQnty =false;
            ineditEstobj.isEditCost =false;
            estlst.add(ineditEstobj); 
            
           }
             
          /* if(vq.size() > 0) 
         {
            for(Estimate_Line_Items__c ELITS: vq) 
            {
                listWrapper.add(new WrapperClass(ELITS));
            }
         } */  
            
          
        
         
    }
    // End Constructor
    
    
    
    public class inlinewrapperEst{
        public Estimate_Line_Items__c estrec {get;set;}
        public integer rowNo  {get;set;}
        public boolean isEdit {get;set;} 
        public boolean isEditQnty {get;set;} 
        public boolean isEditCost {get;set;}   
    }
    
  public pageReference inlineeditEst(){
        if(estEditField=='Quantity'){
           estlst[rowIndex].isEditQnty=true;
          }
        if(estEditField=='UnitCost'){
           estlst[rowIndex].isEditCost=true;
          }
         
         return null;  
    }
    
    public pageReference inlinesaveEst(){
      try{
          
         if(estEditField=='Quantity'){
            update estlst[rowIndex].estrec;
            estlst[rowIndex].isEditQnty=false;
          }
          
         if(estEditField=='UnitCost'){
            update estlst[rowIndex].estrec;
            estlst[rowIndex].isEditCost=false;
          } 
          
          
          if(ViewAll)
                     {
                  vq=[select id,Name,Approved__c,PO_Created__c,GL_Code__r.Name,Job__c,Vendor__r.Name,GL_Department__c,Quote__r.Name,Amount__c,Total_Amount__c,Quantity__c,Unit_Type__c,Restrict__c,PO__c from Estimate_Line_Items__c where Job__c =: [Select id from Job__c where id =: theID] Order By CreatedDate desc,Name limit 5];      
                  vq1=[select id,Name,Approved__c,PO_Created__c,GL_Code__r.Name,Job__c,Vendor__r.Name,GL_Department__c,Quote__r.Name,Amount__c,Total_Amount__c,Quantity__c,Unit_Type__c,Restrict__c,PO__c from Estimate_Line_Items__c where Job__c =: [Select id from Job__c where id =: theID] Order By CreatedDate desc,Name];
                  
                     estlst.clear();
                   for(integer i=0;i<vq.size();i++){
                    ineditEstobj=new inlinewrapperEst();
                    ineditEstobj.estrec=vq[i];
                    ineditEstobj.rowNo=i;
                    ineditEstobj.isEdit=false;
                    ineditEstobj.isEditQnty =false;
                    ineditEstobj.isEditCost =false;
                    estlst.add(ineditEstobj); 
                    
                   }
            
             }
             else
             {
                 vq=[select id,Name,Approved__c,PO_Created__c,GL_Code__r.Name,Job__c,Vendor__r.Name,GL_Department__c,Quote__r.Name,Amount__c,Total_Amount__c,Quantity__c,Unit_Type__c,Restrict__c,PO__c from Estimate_Line_Items__c where Job__c =: [Select id from Job__c where id =: theID] Order By CreatedDate desc,Name];    
                 vq1=vq;
                 
                   estlst.clear();
                   for(integer i=0;i<vq.size();i++){
                    ineditEstobj=new inlinewrapperEst();
                    ineditEstobj.estrec=vq[i];
                    ineditEstobj.rowNo=i;
                    ineditEstobj.isEdit=false;
                    ineditEstobj.isEditQnty =false;
                    ineditEstobj.isEditCost =false;
                    estlst.add(ineditEstobj); 
                    
                   }
             }
          
              
        }
        catch(System.DMLException e){
        return null;
        }
        return null;
    }
    
    Public void ViewAllEst()
    {
        ViewAll=False;
        ShowLess=True;
        
        vq=[select id,Name,Approved__c,PO_Created__c,GL_Code__r.Name,Job__c,Vendor__r.Name,GL_Department__c,Quote__r.Name,Amount__c,Total_Amount__c,Quantity__c,Unit_Type__c,Restrict__c,PO__c from Estimate_Line_Items__c where Job__c =: [Select id from Job__c where id =: theID] Order By CreatedDate desc,Name];
          estlst.clear();
             for(integer i=0;i<vq.size();i++){
                ineditEstobj=new inlinewrapperEst();
                ineditEstobj.estrec=vq[i];
                ineditEstobj.rowNo=i;
                ineditEstobj.isEdit=false;
                ineditEstobj.isEditQnty =false;
                ineditEstobj.isEditCost =false;
                estlst.add(ineditEstobj); 
                
               }

    }
    
    Public void ShowLessEst()
    {
        ViewAll=True;
        ShowLess=False;
        
        vq=[select id,Name,Approved__c,PO_Created__c,GL_Code__r.Name,Job__c,Vendor__r.Name,GL_Department__c,Quote__r.Name,Amount__c,Total_Amount__c,Quantity__c,Unit_Type__c,Restrict__c,PO__c from Estimate_Line_Items__c where Job__c =: [Select id from Job__c where id =: theID] Order By CreatedDate desc,Name limit:5];
         estlst.clear();
               for(integer i=0;i<vq.size();i++){
                    ineditEstobj=new inlinewrapperEst();
                    ineditEstobj.estrec=vq[i];
                    ineditEstobj.rowNo=i;
                    ineditEstobj.isEdit=false;
                    ineditEstobj.isEditQnty =false;
                    ineditEstobj.isEditCost =false;
                    estlst.add(ineditEstobj); 
                    
                 }
   
   
    }
    
   
    
    
   /* public class WrapperClass 
    {
        public Boolean checked {get;set;}
        public Estimate_Line_Items__c ELItems{get;set;}
        public WrapperClass(Estimate_Line_Items__c  ELItems) 
        {
            this.ELItems = ELItems;
        }
        
        
    }
    
     public void dup() 
     {
         listELIDup = new List<Estimate_Line_Items__c>();
         List<WrapperClass> listTempWrapper = new List<WrapperClass>();
         for(WrapperClass w : listWrapper) 
         {
            if(w.checked) 
            {
               
               Estimate_Line_Items__c  objJEst=new Estimate_Line_Items__c ();
                
                objJEst.name=w.ELItems.Name;
                objJEst.Job__c=w.ELItems.Job__c;
                objJEst.Quantity__c=w.ELItems.Quantity__c;
                objJEst.Amount__c=w.ELItems.Amount__c;
                objJEst.GL_Code__c=w.ELItems.GL_Code__c;
                objJEst.GL_Department__c=w.ELItems.GL_Department__c;
                objJEst.Vendor__c =w.ELItems.Vendor__c ;
                
                listELIDup.add(objJEst);
               
            } 
            
         }
         
         
         if(listELIDup.size() > 0) 
         {
             try
             {
                    insert listELIDup;
                    
                    vq=new list<Estimate_Line_Items__c>();
                    listWrapper=new list<WrapperClass>();
                    vq=[select id,Name,Approved__c,PO_Created__c,GL_Code__r.Name,Job__c,Vendor__r.Name,GL_Department__c,Quote__r.Name,Amount__c,Total_Amount__c,Quantity__c,Unit_Type__c,Restrict__c,PO__c from Estimate_Line_Items__c where Job__c =: [Select id from Job__c where id =: theID] Order By Name];
        
                     if(vq.size() > 0) 
                     {
                        for(Estimate_Line_Items__c ELITS: vq) 
                        {
                            listWrapper.add(new WrapperClass(ELITS));
                        }
                     } 
            
            
            }
            catch(Exception e)
            {
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR,e.getMessage()));
            }
            
           
         } 
         else 
         {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR,'Select atleast one Estimate Line Item'));
           // return null;
         }
         
         
     
     }*/
     
     
     
    public void Approve()
    {
    
         List<Estimate_Line_Items__c> updateELI=new List<Estimate_Line_Items__c>();
         
         List<Estimate_Line_Items__c> App= [select id,Job__c,Quantity__c,Amount__c,Name,GL_Code__c,GL_Department__c,Vendor__c from Estimate_Line_Items__c where id =: strPEID Limit 1];
            
         for(Estimate_Line_Items__c ELI:App)
         {
            ELI.Approved__c=True;
            updateELI.add(ELI);
         }
            
            
         if(updateELI.size() > 0) 
         {   
        
              try
              {
                    if(!test.isRunningTest()) update updateELI;
                    vq=new list<Estimate_Line_Items__c>();
                     if(ViewAll)
                     {
                          vq=[select id,Name,Approved__c,PO_Created__c,GL_Code__r.Name,Job__c,Vendor__r.Name,GL_Department__c,Quote__r.Name,Amount__c,Total_Amount__c,Quantity__c,Unit_Type__c,Restrict__c,PO__c from Estimate_Line_Items__c where Job__c =: [Select id from Job__c where id =: theID] Order By CreatedDate desc,Name limit 5];      
                          vq1=[select id,Name,Approved__c,PO_Created__c,GL_Code__r.Name,Job__c,Vendor__r.Name,GL_Department__c,Quote__r.Name,Amount__c,Total_Amount__c,Quantity__c,Unit_Type__c,Restrict__c,PO__c from Estimate_Line_Items__c where Job__c =: [Select id from Job__c where id =: theID] Order By CreatedDate desc,Name];
                          
                             estlst.clear();
                            for(integer i=0;i<vq.size();i++){
                            ineditEstobj=new inlinewrapperEst();
                            ineditEstobj.estrec=vq[i];
                            ineditEstobj.rowNo=i;
                            ineditEstobj.isEdit=false;
                            ineditEstobj.isEditQnty =false;
                            ineditEstobj.isEditCost =false;
                            estlst.add(ineditEstobj); 
                            
                         }
                    
                     }
                     else
                     {
                         vq=[select id,Name,Approved__c,PO_Created__c,GL_Code__r.Name,Job__c,Vendor__r.Name,GL_Department__c,Quote__r.Name,Amount__c,Total_Amount__c,Quantity__c,Unit_Type__c,Restrict__c,PO__c from Estimate_Line_Items__c where Job__c =: [Select id from Job__c where id =: theID] Order By CreatedDate desc,Name];    
                         vq1=vq;
                         
                           estlst.clear();
                            for(integer i=0;i<vq.size();i++){
                            ineditEstobj=new inlinewrapperEst();
                            ineditEstobj.estrec=vq[i];
                            ineditEstobj.rowNo=i;
                            ineditEstobj.isEdit=false;
                            ineditEstobj.isEditQnty =false;
                            ineditEstobj.isEditCost =false;
                            estlst.add(ineditEstobj); 
                            
                         }
                  }
           eli=[select id,Name,Approved__c,PO_Created__c,GL_Code__r.Name,Job__c,Vendor__r.Name,Quote__r.Name,Amount__c,Total_Amount__c,Quantity__c,Unit_Type__c,Restrict__c from Estimate_Line_Items__c where Job__c =: [Select id from Job__c where id =: theID] and Approved__c = true ];
          }
          
          catch(System.DMLException e)
          {
              apexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR,e.getMessage()));
          }
          
        }
        
    }
    
    
    
    public void UnApprove()
    {
    
         List<Estimate_Line_Items__c> updateELI=new List<Estimate_Line_Items__c>();
         
         List<Estimate_Line_Items__c> UnApp= [select id,Job__c,Quantity__c,Amount__c,Name,GL_Code__c,GL_Department__c,Vendor__c from Estimate_Line_Items__c where id =: strPEID Limit 1];
            
         for(Estimate_Line_Items__c ELI:UnApp)
         {
            ELI.Approved__c=False;
            updateELI.add(ELI);
         }
            
            
         if(updateELI.size() > 0) 
         {   
        
              try
              {
                    if(!test.isRunningTest()) update updateELI;
                    vq=new list<Estimate_Line_Items__c>();
                     if(ViewAll)
                     {
                          vq=[select id,Name,Approved__c,PO_Created__c,GL_Code__r.Name,Job__c,Vendor__r.Name,GL_Department__c,Quote__r.Name,Amount__c,Total_Amount__c,Quantity__c,Unit_Type__c,Restrict__c,PO__c from Estimate_Line_Items__c where Job__c =: [Select id from Job__c where id =: theID] Order By CreatedDate desc,Name limit 5];      
                          vq1=[select id,Name,Approved__c,PO_Created__c,GL_Code__r.Name,Job__c,Vendor__r.Name,GL_Department__c,Quote__r.Name,Amount__c,Total_Amount__c,Quantity__c,Unit_Type__c,Restrict__c,PO__c from Estimate_Line_Items__c where Job__c =: [Select id from Job__c where id =: theID] Order By CreatedDate desc,Name];
                            estlst.clear();
                            for(integer i=0;i<vq.size();i++){
                            ineditEstobj=new inlinewrapperEst();
                            ineditEstobj.estrec=vq[i];
                            ineditEstobj.rowNo=i;
                            ineditEstobj.isEdit=false;
                            ineditEstobj.isEditQnty =false;
                            ineditEstobj.isEditCost =false;
                            estlst.add(ineditEstobj); 
                            
                         }
                    
                     }
                     else
                     {
                         vq=[select id,Name,Approved__c,PO_Created__c,GL_Code__r.Name,Job__c,Vendor__r.Name,GL_Department__c,Quote__r.Name,Amount__c,Total_Amount__c,Quantity__c,Unit_Type__c,Restrict__c,PO__c from Estimate_Line_Items__c where Job__c =: [Select id from Job__c where id =: theID] Order By CreatedDate desc,Name];    
                         vq1=vq;
                           estlst.clear();
                            for(integer i=0;i<vq.size();i++){
                            ineditEstobj=new inlinewrapperEst();
                            ineditEstobj.estrec=vq[i];
                            ineditEstobj.rowNo=i;
                            ineditEstobj.isEdit=false;
                            ineditEstobj.isEditQnty =false;
                            ineditEstobj.isEditCost =false;
                            estlst.add(ineditEstobj); 
                            
                         }
                         
                     }
                 eli=[select id,Name,Approved__c,PO_Created__c,GL_Code__r.Name,Job__c,Vendor__r.Name,Quote__r.Name,Amount__c,Total_Amount__c,Quantity__c,Unit_Type__c,Restrict__c from Estimate_Line_Items__c where Job__c =: [Select id from Job__c where id =: theID] and Approved__c = true ];
              }
          
              catch(System.DMLException e)
              {
                  apexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR,e.getMessage()));
              }
          
          }
        
    }
    
    Public PageReference Del()
    {
        List<Estimate_Line_Items__c> DelEstLI= [select id,Job__c,Quantity__c,Amount__c,Name,GL_Code__c,GL_Department__c,Vendor__c from Estimate_Line_Items__c where id =: strPEID Limit 1];
        try
        {
             Database.delete(DelEstLI);  
           
             vq=new list<Estimate_Line_Items__c>();
             if(ViewAll)
             {
                  vq=[select id,Name,Approved__c,PO_Created__c,GL_Code__r.Name,Job__c,Vendor__r.Name,GL_Department__c,Quote__r.Name,Amount__c,Total_Amount__c,Quantity__c,Unit_Type__c,Restrict__c,PO__c from Estimate_Line_Items__c where Job__c =: [Select id from Job__c where id =: theID] Order By CreatedDate desc,Name limit 5];      
                  vq1=[select id,Name,Approved__c,PO_Created__c,GL_Code__r.Name,Job__c,Vendor__r.Name,GL_Department__c,Quote__r.Name,Amount__c,Total_Amount__c,Quantity__c,Unit_Type__c,Restrict__c,PO__c from Estimate_Line_Items__c where Job__c =: [Select id from Job__c where id =: theID] Order By CreatedDate desc,Name];
                           estlst.clear();
                           for(integer i=0;i<vq.size();i++){
                            ineditEstobj=new inlinewrapperEst();
                            ineditEstobj.estrec=vq[i];
                            ineditEstobj.rowNo=i;
                            ineditEstobj.isEdit=false;
                            ineditEstobj.isEditQnty =false;
                            ineditEstobj.isEditCost =false;
                            estlst.add(ineditEstobj); 
                            
                         }
            
             }
             else
             {
                 vq=[select id,Name,Approved__c,PO_Created__c,GL_Code__r.Name,Job__c,Vendor__r.Name,GL_Department__c,Quote__r.Name,Amount__c,Total_Amount__c,Quantity__c,Unit_Type__c,Restrict__c,PO__c from Estimate_Line_Items__c where Job__c =: [Select id from Job__c where id =: theID] Order By CreatedDate desc,Name];    
                 vq1=vq;
                           estlst.clear();
                            for(integer i=0;i<vq.size();i++){
                            ineditEstobj=new inlinewrapperEst();
                            ineditEstobj.estrec=vq[i];
                            ineditEstobj.rowNo=i;
                            ineditEstobj.isEdit=false;
                            ineditEstobj.isEditQnty =false;
                            ineditEstobj.isEditCost =false;
                            estlst.add(ineditEstobj); 
                            
                         }
             }
             
             if(isLtng)
             {
                 PageReference p =  new Pagereference('/apex/JobdetailpageLightening07?id='+theid+'&tab=Jobcost'+'&section=estimate');p.setRedirect(true);return p;
             }
             else
             {
                    PageReference p =  new Pagereference('/apex/JobListView?id='+theid+'&intFocus=5');
                    p.setRedirect(true);
                    return p;
             }
             
            
        }
        catch(System.DMLException e)
        {
            apexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR,e.getMessage()));
            return null;
        }
    }
    
    
    
    
 
    Sobject sumCash; 
    public double getSumCash()
    { 
       sumCash = [SELECT SUM(Total_Amount__c) sum FROM Estimate_Line_Items__c WHERE Job__c =: [Select id from Job__c where id =: theID] and Approved__c = true];   
       return double.valueOf(sumCash.get('sum')); 
    }  
 
    // This method is called on to new ELI  
    public PageReference createELI()
    {
       String jobid;
       String theId=ApexPages.CurrentPage().getParameters().get('id');
       Estimate_Line_Items__c est = new Estimate_Line_Items__c();
       Job__c job = [Select Id from Job__c where id =: theID];
       jobid=job.Id;
      
        if(isLtng)
        {
               PageReference p = Page.CreateNewEstimateLightning;p.setredirect(true);p.getParameters().put('jobid',theID); return p;
        }
        else
        {
               PageReference p = Page.CreateNewEstimate;
               p.setredirect(true);
               p.getParameters().put('jobid',theID); 
               return p;
        }
      
       
     
    }
    // End method createELI
    
    
   
    
   // This method is called on to handle Save button (Inline Editing Save)
     public PageReference save()
     {
     
       
          try
          {
         List<Estimate_Line_Items__c> updateELI=new List<Estimate_Line_Items__c>();
            if(isLtng)
            {
                for(Estimate_Line_Items__c objELI:vq)
                {
                    if(objELI.Approved__c==True)
                    {
                       updateELI.add(objELI); 
                        
                    }
                    else if(objELI.Approved__c==False)
                    {
                        updateELI.add(objELI);
                    }
                }
            }
            else{
               for(Estimate_Line_Items__c objELI:vq1)
                {
                    if(objELI.Approved__c==True)
                    {
                       updateELI.add(objELI); 
                        
                    }
                    else if(objELI.Approved__c==False)
                    {
                        updateELI.add(objELI); 
                    }
                }
            
            }
            if(!test.isRunningTest()) update updateELI;
            
           
            
            
            
           
          /*  Double amount=0;
            List<Estimate_Line_Items__c> lstELI=[select id,Name,Total_Amount__c from Estimate_Line_Items__c where Job__c=: theId and Approved__c=True];
            for(Estimate_Line_Items__c obj:lstELI)
            {
                amount=amount+obj.Total_Amount__c;
            }
            
            Job__c job = [select id,Name,Estimate_Total__c from Job__c where Id =: theId];
            job.Estimate_Total__c = amount;
            update job;   */
            
          }
          catch(System.DMLException e)
          {
              return null;
              //error='&Errormsg=jobquote_Error@@@'+e.getMessage();    
          }
      
     
       if(isLtng)
        {
             PageReference p =  new Pagereference('/apex/JobdetailpageLightening07?id='+theid+'&tab=Jobcost'+'&section=estimate');
             p.setRedirect(true);
             return p; 
        }
        else
        {
                PageReference p =  new Pagereference('/apex/JobListView?id='+theid+'&intFocus=5');
                p.setRedirect(true);
                return p;
        }
      
      
    
    }
    // End of method Save
    
    
    // THis method is called on to handle Cancel button (Cancel inline Editing)
   
     public PageReference cancelme()
     {
       
        if(isLtng)
        {
             PageReference p =  new Pagereference('/apex/JobdetailpageLightening07?id='+theid+'&tab=Jobcost'+'&section=estimate');
             p.setRedirect(true);
             return p; 
        }
        else
        {
                PageReference p =  new Pagereference('/apex/JobListView?id='+theid+'&intFocus=5');
                p.setRedirect(true);
                return p;
        }
       
       
     }
     
     // End of method Cancel
    
    // This method is called on to handle CreatePO button
    public Pagereference createPO()
    {
       
         if(isLtng)
        {
               PageReference p = Page.CreateNewPurchaseOrderLightning;
               p.setredirect(true);
               p.getParameters().put('jobid',theID); 
               return p;
        }
        else
        {
               PageReference p = Page.CreateNewPurchaseOrder;
               p.setredirect(true);
               p.getParameters().put('jobid',theID); 
               return p;
        }
       
       
       
        
    }  
    // End of method CreatePO 



    Public void duplicatePE()
    {
         try
         {
            // strPEID =  ApexPages.currentPage().getParameters().get('strPEID');
               List<Estimate_Line_Items__c > insertEstimate=new List<Estimate_Line_Items__c >();
             
              List<Estimate_Line_Items__c> abc = [select id,Job__c,Quantity__c,Amount__c,Name,GL_Code__c,GL_Department__c,Vendor__c from Estimate_Line_Items__c where id =: strPEID Limit 1];
             
              for(Estimate_Line_Items__c es:abc) 
              {
                   Estimate_Line_Items__c  objJEst=new Estimate_Line_Items__c ();
                    
                    objJEst.name=es.Name;
                    objJEst.Job__c=es.Job__c;
                    objJEst.Quantity__c=es.Quantity__c;
                    objJEst.Amount__c=es.Amount__c;
                    objJEst.GL_Code__c=es.GL_Code__c;
                    objJEst.GL_Department__c=es.GL_Department__c;
                    objJEst.Vendor__c =es.Vendor__c ;
                    
                    insertEstimate.add(objJEst);
              }
             insert insertEstimate;
             
             
             vq=new list<Estimate_Line_Items__c>();
             if(ViewAll)
             {
                  vq=[select id,Name,Approved__c,PO_Created__c,GL_Code__r.Name,Job__c,Vendor__r.Name,GL_Department__c,Quote__r.Name,Amount__c,Total_Amount__c,Quantity__c,Unit_Type__c,Restrict__c,PO__c from Estimate_Line_Items__c where Job__c =: [Select id from Job__c where id =: theID] Order By CreatedDate desc,Name limit 5];      
                  vq1=[select id,Name,Approved__c,PO_Created__c,GL_Code__r.Name,Job__c,Vendor__r.Name,GL_Department__c,Quote__r.Name,Amount__c,Total_Amount__c,Quantity__c,Unit_Type__c,Restrict__c,PO__c from Estimate_Line_Items__c where Job__c =: [Select id from Job__c where id =: theID] Order By CreatedDate desc,Name];
                    estlst.clear();
                            for(integer i=0;i<vq.size();i++){
                            ineditEstobj=new inlinewrapperEst();
                            ineditEstobj.estrec=vq[i];
                            ineditEstobj.rowNo=i;
                            ineditEstobj.isEdit=false;
                            ineditEstobj.isEditQnty =false;
                            ineditEstobj.isEditCost =false;
                            estlst.add(ineditEstobj); 
                            
                         }
             
             
             
             }
             else
             {
                 vq=[select id,Name,Approved__c,PO_Created__c,GL_Code__r.Name,Job__c,Vendor__r.Name,GL_Department__c,Quote__r.Name,Amount__c,Total_Amount__c,Quantity__c,Unit_Type__c,Restrict__c,PO__c from Estimate_Line_Items__c where Job__c =: [Select id from Job__c where id =: theID] Order By CreatedDate desc,Name];    
                 vq1=vq;
                        estlst.clear();
                        for(integer i=0;i<vq.size();i++){
                        ineditEstobj=new inlinewrapperEst();
                        ineditEstobj.estrec=vq[i];
                        ineditEstobj.rowNo=i;
                        ineditEstobj.isEdit=false;
                        ineditEstobj.isEditQnty =false;
                        ineditEstobj.isEditCost =false;
                        estlst.add(ineditEstobj); 
                        
                     }
             }
            
         }
    
         catch(System.DMLException e)
          {
                 ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR,e.getMessage()));
                 
          }
    
   
    }




    
     
}// End of Class