objects/Estimate_Line_Items__c/Estimate_Line_Items__c.object-meta.xml
<CustomObject>
    <description>This is Estimate Line Item object.</description>
    <label>Estimate Line Item</label>
    <nameField>
        <label>Line Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Estimate Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Estimate_Line_Items__c/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <label>Job Name</label>
    <referenceTo>Job__c</referenceTo>
    <relationshipLabel>Line Items</relationshipLabel>
    <relationshipName>Estimate</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/Estimate_Spec_Item__c/Estimate_Spec_Item__c.object-meta.xml
<CustomObject>
    <description>This is Estimate Spec Item object. It act as line items of Estimate Line Item Object.</description>
    <label>Spec  Item</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Estimate Spec Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Estimate_Spec_Item__c/fields/Estimates__c.field-meta.xml
<CustomField>
    <fullName>Estimates__c</fullName>
    <label>Estimates</label>
    <referenceTo>Estimate_Line_Items__c</referenceTo>
    <relationshipName>Estimate_Line_Item</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/Job__c/Job__c.object-meta.xml
<CustomObject>
    <description>This is Job object.</description>
    <label>Job</label>
    <nameField>
        <label>Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Production_Estimate__c/Production_Estimate__c.object-meta.xml
<CustomObject>
    <description>This is Production Estimate object.</description>
    <label>Production Estimate</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Production Estimates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Production_Estimate__c/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <label>Job Name</label>
    <referenceTo>Job__c</referenceTo>
    <relationshipLabel>Production Estimates</relationshipLabel>
    <relationshipName>Production_Estimates</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/Production_Estimate_Spec_Item__c/Production_Estimate_Spec_Item__c.object-meta.xml
<CustomObject>
    <description>This is Production Estimate Spec Item object. It act as line items of Production Estimate Object.</description>
    <label>Production Estimate Spec Item</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Production Estimate Spec Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Production_Estimate_Spec_Item__c/fields/Production_Estimate__c.field-meta.xml
<CustomField>
    <fullName>Production_Estimate__c</fullName>
    <label>Production Estimate</label>
    <referenceTo>Production_Estimate__c</referenceTo>
    <relationshipLabel>Production Estimate Spec Items</relationshipLabel>
    <relationshipName>Production_Estimate_Spec_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/ProductionEstimate__c/ProductionEstimate__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>This is to use Production Estimate in place of Standard Estimate &amp; New Copy Schedule Button.</description>
    <label>Job Suite Controls</label>
</CustomObject>

objects/ProductionEstimate__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This One Is for to Activate Production Estimate in place of Standard Estimate</description>
    <inlineHelpText>This One Is for to Activate Production Estimate in place of Standard Estimate</inlineHelpText>
    <label>Production Estimate Active</label>
    <type>Checkbox</type>
</CustomField>

objects/Shipment__c/Shipment__c.object-meta.xml
<CustomObject>
    <description>This is shipment object used for production estimate process</description>
    <label>Shipment</label>
    <nameField>
        <displayFormat>Ship-{000000}</displayFormat>
        <label>Shipment #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shipments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Shipment__c/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Job</label>
    <referenceTo>Job__c</referenceTo>
    <relationshipLabel>Shipments</relationshipLabel>
    <relationshipName>Shipments</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

objects/Shipment_Line_Item__c/Shipment_Line_Item__c.object-meta.xml
<CustomObject>
    <description>This Shipment Line Item object is child object of Shipment  object</description>
    <label>Shipment Line Item</label>
    <nameField>
        <displayFormat>SLI-{00000}</displayFormat>
        <label>Shipment Line Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shipment Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Shipment_Line_Item__c/fields/Estimate_Line_Item__c.field-meta.xml
<CustomField>
    <fullName>Estimate_Line_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Estimate Line Item</label>
    <referenceTo>Estimate_Line_Items__c</referenceTo>
    <relationshipLabel>Shipment Line Items</relationshipLabel>
    <relationshipName>Shipment_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Shipment_Line_Item__c/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <formula>IF(($Setup.ProductionEstimate__c.Active__c==True), Production_Estimate__r.Job__r.Job_Auto_Number__c,  Estimate_Line_Item__r.Job__r.Job_Auto_Number__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Job #</label>
    <type>Text</type>
</CustomField>

objects/Shipment_Line_Item__c/fields/Job_Name__c.field-meta.xml
<CustomField>
    <fullName>Job_Name__c</fullName>
    <formula>IF(($Setup.ProductionEstimate__c.Active__c == True), Production_Estimate__r.Job__r.Name ,  Estimate_Line_Item__r.Job__r.Name)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Job Name</label>
    <type>Text</type>
</CustomField>

objects/Shipment_Line_Item__c/fields/Production_Estimate__c.field-meta.xml
<CustomField>
    <fullName>Production_Estimate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Item Name</label>
    <referenceTo>Production_Estimate__c</referenceTo>
    <relationshipLabel>Shipment Line Items</relationshipLabel>
    <relationshipName>Shipment_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Shipment_Line_Item__c/fields/Qty_Shipped__c.field-meta.xml
<CustomField>
    <fullName>Qty_Shipped__c</fullName>
    <label>Qty Shipped</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

objects/Shipment_Line_Item__c/fields/Shipment__c.field-meta.xml
<CustomField>
    <fullName>Shipment__c</fullName>
    <label>Shipment</label>
    <referenceTo>Shipment__c</referenceTo>
    <relationshipLabel>Shipment Line Items</relationshipLabel>
    <relationshipName>Shipment_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

classes/ShipmentPrintExtension.cls
public with sharing class ShipmentPrintExtension {
    
    String theID;
    public List<Shipment_Line_Item__c> tempSLI{get;set;} // 
    
    
    public Map<ID,List<Production_Estimate_Spec_Item__c>> PELI_ESI_Map = new Map<ID,List<Production_Estimate_Spec_Item__c>>(); 
    public Set<ID> PELIIds = new Set<ID>();
    
    public list<wrapper> wrapout{get;set;}
    public DateTime today{get;set;}
    public List<Document> lstDoc;
    public String imageBody{get;set;}
    public String imageURL{get;set;}
    public boolean imageNotFound{get;set;}
    public boolean ShowProductionEstimate{get;set;}

    // End of Global variables

    // Start constructor
    public ShipmentPrintExtension (ApexPages.StandardController controller)
    {
           ProductionEstimate__c  activeSettings = ProductionEstimate__c.getOrgDefaults();
        ShowProductionEstimate =activeSettings.Active__c;
         
          // Code to display Subsriber Organization Logo
          
          // If subscriber deletes the Document : JobSuite_OrganizationLogo from their Org then JobSuite App logo will be displayed
         
        imageURL = '/servlet/servlet.FileDownload?file='; 
        lstDoc = [Select Id, Name, Body from Document where Name =: 'JobSuite_OrganizationLogo' WITH SECURITY_ENFORCED LIMIT 1];
        if(!lstDoc.isEmpty())
        {
           String imageId =  lstDoc[0].Id;
           imageBody = imageURL+imageId; 
           imageNotFound = False;
        }    
        else
        {
           imageNotFound = True;
        }

        // End of code to display Subscriber Organization Logo
        
          wrapout = new List<Wrapper>();
          theID = ApexPages.CurrentPage().getParameters().get('id');
          tempSLI= [select id,Name,Production_Estimate__c,Estimate_Line_Item__r.name,Qty_Shipped__c ,Job_Name__c ,Job__c, Production_Estimate__r.name from Shipment_Line_Item__c where Shipment__c  =: [Select id from Shipment__c  where id =: theID] WITH SECURITY_ENFORCED Order By Name];
          setupGrouping();
          today=System.NOW();
          
         
     }
     
     Public class wrapper
    {
         public Shipment_Line_Item__c sili{get;set;}
         
         public list<Wrapper3> pesis{get;set;}
         public wrapper()
        {
           if(sili == null)
            {
                sili = new Shipment_Line_Item__c();
            }
           
           if(pesis == null)
           {
                 pesis = new List<Wrapper3>();
           }   
        }
     }
 
  
    
    Public class wrapper3
   {
         public Production_Estimate_Spec_Item__c pesi{get;set;}
         public wrapper3()
        {
           if(pesi == null)
           {
                pesi = new Production_Estimate_Spec_Item__c ();
           }
       }
    }  
     
     
     
     Public void setupGrouping()
    {
         for(Shipment_Line_Item__c SILIRecord : tempSLI)
         {  
         
                PELIIds.add(SILIRecord.Production_Estimate__c);
              
         
               
         }
         
         
         
         for(Production_Estimate_Spec_Item__c pesiRecord : [select id,Name,Production_Estimate__c,Description__c from Production_Estimate_Spec_Item__c where Production_Estimate__c=: PELIIds WITH SECURITY_ENFORCED order by CreatedDate])
         {
           if(PELI_ESI_Map.containskey(PesiRecord.Production_Estimate__c))
            {
                 PELI_ESI_Map.get(PesiRecord.Production_Estimate__c).add(PesiRecord);
            }
            else
            {
                PELI_ESI_Map.put(PesiRecord.Production_Estimate__c,new List<Production_Estimate_Spec_Item__c>{PesiRecord});
            } 
         }
         
         
         
  
         for(Shipment_Line_Item__c  SILIRecord1 : tempSLI)
         {
              wrapper tmpWrapper = new wrapper();
              tmpWrapper.sili = SILIRecord1 ;
              
              List<Wrapper3> t3 = new List<Wrapper3>();
              
              
              if(PELI_ESI_Map.containskey(SILIRecord1.Production_Estimate__c))
              {
                   for(Production_Estimate_Spec_Item__c esi3:PELI_ESI_Map.get(SILIRecord1.Production_Estimate__c))
                    { 
                         wrapper3 twrap3 = new Wrapper3();
                         twrap3.pesi = esi3;
                         t3.add(twrap3);
                    }
              }
              tmpWrapper.pesis=t3;
              wrapout.add(tmpWrapper); 
              
             
                
         } 
    } 
    
    
   }