objects/Estimate_Line_Items__c/Estimate_Line_Items__c.object-meta.xml
<CustomObject>
    <description>This is Estimate Line Item object.</description>
    <label>Estimate Line Item</label>
    <nameField>
        <label>Line Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Estimate Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Estimate_Spec_Item__c/Estimate_Spec_Item__c.object-meta.xml
<CustomObject>
    <description>This is Estimate Spec Item object. It act as line items of Estimate Line Item Object.</description>
    <label>Spec  Item</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Estimate Spec Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Estimate_Spec_Item__c/fields/Estimates__c.field-meta.xml
<CustomField>
    <fullName>Estimates__c</fullName>
    <label>Estimates</label>
    <referenceTo>Estimate_Line_Items__c</referenceTo>
    <relationshipName>Estimate_Line_Item</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/Production_Spec_Item__c/Production_Spec_Item__c.object-meta.xml
<CustomObject>
    <description>This Object is used as child object of Production Spec Template in Master detail relationship.</description>
    <label>Production Spec Item</label>
    <nameField>
        <label>Spec Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Production Spec Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Production_Spec_Item__c/fields/Production_Spec_Template__c.field-meta.xml
<CustomField>
    <fullName>Production_Spec_Template__c</fullName>
    <label>Production Spec Template</label>
    <referenceTo>Production_Spec_Template__c</referenceTo>
    <relationshipLabel>Production Spec Items</relationshipLabel>
    <relationshipName>Production_Spec_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/Production_Spec_Template__c/Production_Spec_Template__c.object-meta.xml
<CustomObject>
    <description>This object is used to import spec for Quote object.</description>
    <label>Production Spec Template</label>
    <nameField>
        <label>Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Production Spec Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/DisplayProductionEstSpecInEstimateTabExt.cls
public with sharing class DisplayProductionEstSpecInEstimateTabExt {

  /*   public boolean isLtng{private set; get{
                                            String theme = UserInfo.getUITheme();
                                            return (theme=='Theme4d')?true:false;
                                          }
            }  
    
    public Id EstLIId{get;set;}
    public List<Production_Spec_Item__c> lstProdSpec{get;set;}
    public List<Estimate_Spec_Item__c> lstEstli{get;set;}
    public Estimate_Line_Items__c EstLI{get;set;}
    public String ProductionSpecTempName{get;set;}
    public String SpecId{get;set;}
    public boolean errorMsg {set;get;}
    
    
    public List<selectOption> getProductionSpecTemplate() 
    {
        List<selectOption> optionList = new List<selectOption>();
        optionList.add(new SelectOption('','-None-'));
        for (Production_Spec_Template__c a : [SELECT Id, name FROM Production_Spec_Template__c ORDER BY Name]) 
        {  
            optionList.add(new selectOption(a.Id, a.Name));  
        }
       return optionList;  
    }
    
    public DisplayProductionEstSpecInEstimateTabExt(ApexPages.StandardController SC) 
    {
       errorMsg=false;
        EstLI = (Estimate_Line_Items__c)SC.getRecord();
        EstLIId = ApexPages.currentPage().getParameters().get('id');  
        LoadEstSpecItemss();
    }
    
    private void LoadEstSpecItemss()
    {
         EstLIId = ApexPages.currentPage().getParameters().get('id');       
         lstEstli=[Select id,Name,Description__c from Estimate_Spec_Item__c where Estimates__c=: EstLIId  ORDER BY CreatedDate];   
    }
    
    public Pagereference editSpec()
    {
           Pagereference p=new Pagereference('/apex/EditestimatelineitemunderJob?id='+SpecId);
           p.setRedirect(true);
           return p;
    }
    
    
    public Pagereference DelSpec()
    {
           Pagereference p=new Pagereference('/apex/DeleteSpecItemUndertheEstLI?id='+SpecId);
           p.setRedirect(true);
           return p;
    }
    
     // This method is called on to handle Save button
    public PageReference save()
    {
          try
          {   
              update lstEstli;
          }
          catch(System.DMLException e)
          {
              return null;
          }
          
          if(isLtng)
          {
                 PageReference p = new Pagereference('/apex/EstimatedetailpageLightning?id='+EstLIId);
                 p.setRedirect(true);
                 return p; 
          }
          else
          {
                PageReference p =  new Pagereference('/apex/Estimatedetailpage?id='+EstLIId);
                p.setRedirect(true);
                return p;
          }
          
         
    }
    // End of method Save
    
    // This method is called on to handle Cancel button
     Public PageReference cancelme()
     {
         if(isLtng)
          {
                 PageReference p = new Pagereference('/apex/EstimatedetailpageLightning?id='+EstLIId);
                 p.setRedirect(true);
                 return p; 
          }
          else
          {
                PageReference p =  new Pagereference('/apex/Estimatedetailpage?id='+EstLIId);
                p.setRedirect(true);
                return p;
          }    
     }
    // End Cancel method
    
   
    // This method is called on to add New Spec
    public pagereference addNewSpecs()
    {
         EstLIId = ApexPages.currentPage().getParameters().get('id');       
         
         
          if(isLtng)
          {
                 Pagereference p=Page.createnewestimatelineitemLightning;
                 p.setRedirect(true);
                 p.getParameters().put('EstLIId',EstLIId);
                 return p; 
          }
          else
          {
                 Pagereference p=Page.createnewestimatelineitem;
                 p.setRedirect(true);
                 p.getParameters().put('EstLIId',EstLIId);
                 return p;
          }
         
         
         
         
    }
    // End of method addNewJobSpec
    
    
    
    // This method is called on to Import Specs
    public void importSpecs()
    {
        List<Estimate_Spec_Item__c > insertEstSpecItems=new List<Estimate_Spec_Item__c >();    
        
        if(ProductionSpecTempName==NULL || ProductionSpecTempName=='-None-')
        {
           errorMsg=true;
           ApexPages.Message msg1 = new ApexPages.Message(ApexPages.Severity.ERROR,'Production Spec Temp : You must select a Template.');
           ApexPages.addMessage(msg1);
          // return null;
          
        }
        else
        {
          errorMsg=false;
            try
            {
                List<Production_Spec_Item__c> lstSpecs=[Select id,Name,Description__c from Production_Spec_Item__c where Production_Spec_Template__c=:ProductionSpecTempName];
                for(Production_Spec_Item__c sp:lstSpecs)
                {
                  Estimate_Spec_Item__c js=new Estimate_Spec_Item__c ();
                    if(schema.SobjectType.Estimate_Spec_Item__c.Fields.Name.isCreateable()){ 
                        js.Name=sp.Name;
                    }
                    if(schema.SobjectType.Estimate_Spec_Item__c.Fields.Description__c.isCreateable()){ 
                        js.Description__c=sp.Description__c;
                    }
                    if(schema.SobjectType.Estimate_Spec_Item__c.Fields.Estimates__c.isCreateable()){ 
                        js.Estimates__c= EstLIId ;
                    }
                  insertEstSpecItems.add(js);
                }
                if(Schema.sObjectType.Estimate_Spec_Item__c.isCreateable()){
                    insert insertEstSpecItems;
                }
             }
             catch(System.DMLException e)
             {
               //return NULL;
             }
             
          // lstEstli=[Select id,Name,Description__c from Estimate_Spec_Item__c where Estimates__c=: EstLIId  ORDER BY CreatedDate]; 
          
          
        }   
        
          
          
    }*/
    // End of method Import Specs
    
}