objects/Estimate_Line_Items__c/Estimate_Line_Items__c.object-meta.xml
<CustomObject>
    <description>This is Estimate Line Item object.</description>
    <label>Estimate Line Item</label>
    <nameField>
        <label>Line Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Estimate Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Estimate_Line_Items__c/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <label>Job Name</label>
    <referenceTo>Job__c</referenceTo>
    <relationshipLabel>Line Items</relationshipLabel>
    <relationshipName>Estimate</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/Job__c/Job__c.object-meta.xml
<CustomObject>
    <description>This is Job object.</description>
    <label>Job</label>
    <nameField>
        <label>Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/TestEstimateViewSwitchExt.cls
@isTest
public class TestEstimateViewSwitchExt {
	static TestMethod void TestEstimateViewSwitchExt(){
     /*   job__c job=new job__c(Name='testjob');
        insert job;
        Estimate_Line_Items__c Est=new Estimate_Line_Items__c(Name='Est',job__c=job.id);
        insert Est;
       
        EstimateViewSwitchExt controller = new EstimateViewSwitchExt(new ApexPages.StandardController(Est));
       // boolean x = controller.isMobile;
       controller.pagedir();*/
    }
}