objects/Estimate_Line_Items__c/Estimate_Line_Items__c.object-meta.xml
<CustomObject>
    <description>This is Estimate Line Item object.</description>
    <label>Estimate Line Item</label>
    <nameField>
        <label>Line Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Estimate Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Estimate_Line_Items__c/fields/GL_Code__c.field-meta.xml
<CustomField>
    <fullName>GL_Code__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GL Description</label>
    <referenceTo>GL_Code__c</referenceTo>
    <relationshipLabel>Line Items</relationshipLabel>
    <relationshipName>Estimate</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Estimate_Line_Items__c/fields/GL_Department__c.field-meta.xml
<CustomField>
    <fullName>GL_Department__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GL Department</label>
    <referenceTo>GL_Department__c</referenceTo>
    <relationshipLabel>Line Items</relationshipLabel>
    <relationshipName>Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Estimate_Line_Items__c/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <label>Job Name</label>
    <referenceTo>Job__c</referenceTo>
    <relationshipLabel>Line Items</relationshipLabel>
    <relationshipName>Estimate</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/Estimate_Line_Items__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <label>Quantity</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

objects/Estimate_Line_Items__c/fields/Unit_Type__c.field-meta.xml
<CustomField>
    <fullName>Unit_Type__c</fullName>
    <formula>Text( GL_Code__r.Unit_Type__c )</formula>
    <label>Unit Type</label>
    <type>Text</type>
</CustomField>

objects/GL_Code__c/GL_Code__c.object-meta.xml
<CustomObject>
    <description>GL Codes are used to build line items on our Job Cost Layouts.  The Job Cost Layouts are the Quote, Estimate, Purchase Order, and Vendor Invoice.   The line items on each of these follow similar logic.</description>
    <label>GL Code</label>
    <nameField>
        <label>Description</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GL Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/GL_Code__c/fields/GL_Department__c.field-meta.xml
<CustomField>
    <fullName>GL_Department__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GL Department</label>
    <referenceTo>GL_Department__c</referenceTo>
    <relationshipLabel>GL Codes</relationshipLabel>
    <relationshipName>GL_Codes</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/GL_Code__c/fields/GL_ID__c.field-meta.xml
<CustomField>
    <fullName>GL_ID__c</fullName>
    <description>This is GL ID field. These id&apos;s are auto generated.</description>
    <label>GL Code</label>
    <length>15</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

objects/GL_Code__c/fields/Unit_Cost__c.field-meta.xml
<CustomField>
    <fullName>Unit_Cost__c</fullName>
    <label>Unit Cost (In $)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

objects/GL_Code__c/fields/Unit_Type__c.field-meta.xml
<CustomField>
    <fullName>Unit_Type__c</fullName>
    <label>Unit Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Days</fullName>
                <default>true</default>
                <label>Days</label>
            </value>
            <value>
                <fullName>Each</fullName>
            </value>
            <value>
                <fullName>Hours</fullName>
            </value>
            <value>
                <fullName>Project</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/GL_Department__c/GL_Department__c.object-meta.xml
<CustomObject>
    <description>This Object is Master of GLCode Object in JobSuite Application.</description>
    <label>GL Department</label>
    <nameField>
        <label>GL Department</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GL Department</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Job__c/Job__c.object-meta.xml
<CustomObject>
    <description>This is Job object.</description>
    <label>Job</label>
    <nameField>
        <label>Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Job__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Requested</fullName>
                <default>true</default>
                <label>Requested</label>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Job_Task__c/Job_Task__c.object-meta.xml
<CustomObject>
    <description>This is Job Task object. Also known as Schedule.</description>
    <label>Job Task</label>
    <nameField>
        <label>Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Job_Task__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <label>Staff Email</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

objects/Job_Task__c/fields/GL_Code__c.field-meta.xml
<CustomField>
    <fullName>GL_Code__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GL Code</label>
    <referenceTo>GL_Code__c</referenceTo>
    <relationshipName>Job_Task</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Job_Task__c/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <label>Job Name</label>
    <referenceTo>Job__c</referenceTo>
    <relationshipName>Job_Task</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/Job_Task__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Requested</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Job_Team__c/Job_Team__c.object-meta.xml
<CustomObject>
    <description>This is Job Team object. It is used to store role and assigned staff to that role for a Job record.</description>
    <label>Job Team</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>JobTeam Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Team</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Job_Team__c/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <label>Job Name</label>
    <referenceTo>Job__c</referenceTo>
    <relationshipLabel>Job Team</relationshipLabel>
    <relationshipName>Job_Team</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/Job_Team__c/fields/Staff__c.field-meta.xml
<CustomField>
    <fullName>Staff__c</fullName>
    <label>Staff</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

objects/Production_Estimate__c/Production_Estimate__c.object-meta.xml
<CustomObject>
    <description>This is Production Estimate object.</description>
    <label>Production Estimate</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Production Estimates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Production_Estimate__c/fields/GL_Code__c.field-meta.xml
<CustomField>
    <fullName>GL_Code__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GL Description</label>
    <referenceTo>GL_Code__c</referenceTo>
    <relationshipLabel>Production Estimates</relationshipLabel>
    <relationshipName>Production_Estimates</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Production_Estimate__c/fields/GL_Department__c.field-meta.xml
<CustomField>
    <fullName>GL_Department__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GL Department</label>
    <referenceTo>GL_Department__c</referenceTo>
    <relationshipLabel>Production Estimates</relationshipLabel>
    <relationshipName>Production_Estimates</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Production_Estimate__c/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <label>Job Name</label>
    <referenceTo>Job__c</referenceTo>
    <relationshipLabel>Production Estimates</relationshipLabel>
    <relationshipName>Production_Estimates</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/Staff__c/Staff__c.object-meta.xml
<CustomObject>
    <description>This is Staff object.</description>
    <label>Staff</label>
    <nameField>
        <label>Staff Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Staff</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Staff__c/fields/Alias__c.field-meta.xml
<CustomField>
    <fullName>Alias__c</fullName>
    <label>Alias</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

objects/Staff__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <label>Email</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

objects/Staff__c/fields/Email_Encoding__c.field-meta.xml
<CustomField>
    <fullName>Email_Encoding__c</fullName>
    <label>Email Encoding</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

objects/Staff__c/fields/Phone_1__c.field-meta.xml
<CustomField>
    <fullName>Phone_1__c</fullName>
    <label>Phone</label>
    <type>Phone</type>
</CustomField>

objects/Staff__c/fields/User_Type__c.field-meta.xml
<CustomField>
    <fullName>User_Type__c</fullName>
    <label>User Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Licensed User</fullName>
            </value>
            <value>
                <fullName>Unlicensed Staff</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Staff__c/fields/Username__c.field-meta.xml
<CustomField>
    <fullName>Username__c</fullName>
    <label>Username</label>
    <type>Email</type>
</CustomField>

objects/Timesheet_Entries__c/Timesheet_Entries__c.object-meta.xml
<CustomObject>
    <label>Timesheet Entry</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Timesheet Entry No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Timesheet Entries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Timesheet_Entries__c/fields/GL_Code__c.field-meta.xml
<CustomField>
    <fullName>GL_Code__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GL Code</label>
    <referenceTo>GL_Code__c</referenceTo>
    <relationshipName>Timesheet_Entries</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Timesheet_Entries__c/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <label>Job</label>
    <referenceTo>Job__c</referenceTo>
    <relationshipName>Job_Timesheets</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

classes/TestTimeSheetEntrySiteFormExt.cls
@isTest
public class TestTimeSheetEntrySiteFormExt {
    
    static TestMethod void TestTimeSheetEntrySiteFormExt(){
      /*
         GL_Department__c testGLD = new GL_Department__c(Name='Test GLD 9980');
        insert testGLD;
        
        GL_Code__c testGL=new GL_Code__c(Name='GL Code 9980',GL_ID__c='TestGL9980',GL_Department__c = testGLD.id,Unit_Type__c='Project',Unit_Cost__c=120);
        insert testGL;
        
        Job__c testJob1=new Job__c(Name='Job858',Start_Date__c=System.Today(),status__c='Active');
        insert testJob1;
        
        Staff__c testST=new Staff__c(User_Type__c='Unlicensed Staff',First_Name__c='Test',Last_Name__c='Staff',Username__c='testStaff1021@jobsuite.com',Email__c='testStaff1021@jobsuite.com',Alias__c='TEST',Profile__c='System Administrator',IsDeleted__c=false,Active__c=True,Fax__c='12345',Phone_1__c='9870123456',Email_Encoding__c='ISO 8859-1');
        insert testST;
          
        
        job_Task__c jTask = new Job_Task__c(Job__c = testJob1.id,GL_Code__c=testGL.id);
        insert jTask;
        
        Estimate_Line_Items__c testELI=new Estimate_Line_Items__c(Name='Quote 8901',Job__c=testjob1.Id,Quantity__c=10,GL_Department__c=testGLD.id,GL_Code__c=testGL.id);
                insert testELI;
        
        Production_Estimate__c testpELI=new Production_Estimate__c(Name='Quote 8901',Job__c=testjob1.Id,Quantity__c=10,GL_Department__c=testGLD.id,GL_Code__c=testGL.id);
                insert testpELI;
        
        Job_Team__c objTeam2 = new  Job_Team__c(Role__c= 'Project Manager',Job__c= testjob1.Id,Staff__c='Test Staff');
       insert objTeam2 ;     
        
       
        
        Document document;

        document = new Document();
        document.Body = Blob.valueOf('Some Text');
        document.ContentType = 'application/pdf';
        document.DeveloperName = 'my_document';
        document.IsPublic = true;
        document.Name = 'JobSuite_OrganizationLogo2';
        document.FolderId = [select id from folder where name ='JobSuiteFolder'].id;
        insert document;
        

       
        Timesheet_Entries__c t = new Timesheet_Entries__c(Date__c = date.valueOf('2016-10-01 09:09:09') ,Job__c=testJob1.id,Start_Watch__c=datetime.valueOf('2016-11-11 11:11:11'), End_Watch__c=datetime.valueOf('2016-11-11 12:11:11'),GL_Code__c=testGL.id);
      //  insert t;
        TimeSheetEntrySiteFormExt controller = new TimeSheetEntrySiteFormExt(new ApexPages.StandardController(t));
        controller.objTSDetail = t;
         controller.StaffName = 'manikurella';
        string x = controller.calcTimeDiff;
        boolean y = controller.error;
    //    controller.isMobile = false;
        controller.jobId = testJob1.id;
        controller.getJobName();
        controller.getStaff();
        
       // controller.Cancel();
        controller.End();
        controller.getGLCodeOfTask();
        controller.getRemainHours();
        controller.getTaskName();
        controller.getStaffName();
        controller.getTotalHours();
        controller.Save();
        controller.start();
        
        
        controller.objTSDetail = t;
     //   controller.GLCodeVal=testGL.name;
       controller.JobNameStr = testJob1.id;
       controller.JobTaskNameStr = jTask.id;
   
        controller.ShowProductionEstimate = true;
       
        controller.Save();
        controller.getGLCodeOfTask();
        
        controller.isMobile = true;
       */
    }
    
   
    
    

}