objects/ProductionEstimate__c/ProductionEstimate__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>This is to use Production Estimate in place of Standard Estimate &amp; New Copy Schedule Button.</description>
    <label>Job Suite Controls</label>
</CustomObject>

objects/ProductionEstimate__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This One Is for to Activate Production Estimate in place of Standard Estimate</description>
    <inlineHelpText>This One Is for to Activate Production Estimate in place of Standard Estimate</inlineHelpText>
    <label>Production Estimate Active</label>
    <type>Checkbox</type>
</CustomField>

objects/Purchase_Order__c/Purchase_Order__c.object-meta.xml
<CustomObject>
    <description>This is Purchase Order object.</description>
    <label>Purchase Order</label>
    <nameField>
        <label>PO #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Purchase Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Purchase_Order__c/fields/Vendor__c.field-meta.xml
<CustomField>
    <fullName>Vendor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vendor</label>
    <referenceTo>Vendor__c</referenceTo>
    <relationshipLabel>Purchase Orders</relationshipLabel>
    <relationshipName>Purchase_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Purchase_Order__c/fields/Vendor_Contact__c.field-meta.xml
<CustomField>
    <fullName>Vendor_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vendor Contact</label>
    <referenceTo>Vendor_Contact__c</referenceTo>
    <relationshipLabel>Purchase Orders</relationshipLabel>
    <relationshipName>Purchase_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Vendor__c/Vendor__c.object-meta.xml
<CustomObject>
    <description>This is Vendor object. Vendors in JobSuite are assigned to the line items on Quotes, Estimates, Purchase Orders and Vendor Invoices.  A printer or photographer may be a vendor.</description>
    <label>Vendor</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vendors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Vendor__c/fields/Vendor__c.field-meta.xml
<CustomField>
    <fullName>Vendor__c</fullName>
    <label>Vendor #</label>
    <length>30</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

objects/Vendor_Contact__c/Vendor_Contact__c.object-meta.xml
<CustomObject>
    <description>This is Vendor Contact Object.</description>
    <label>Vendor Contact</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vendor Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Vendor_Contact__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>this is VC Status.</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

objects/Vendor_Contact__c/fields/Vendor__c.field-meta.xml
<CustomField>
    <fullName>Vendor__c</fullName>
    <label>Vendor</label>
    <referenceTo>Vendor__c</referenceTo>
    <relationshipName>Vendor_Contacts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

classes/PurchaseOrdersUnderVendorContacts.cls
public with sharing class PurchaseOrdersUnderVendorContacts {
public boolean isLtng{private set; get{
                                            String theme = UserInfo.getUITheme();
                                            return (theme=='Theme4d')?true:false;
                                          }
     }  
            
            
     public boolean isMob{private set; get{
                                            String theme = UserInfo.getUITheme();
                                            return (theme=='Theme4t')?true:false;
                                          }
    }  
    
    
    
   // public boolean displayPopup {get; set;}
    // Global variables
    public List<Purchase_Order__c> q{get;set;}
    public List<Purchase_Order__c> q2{get;set;}
    public String theID {get;set;}
    public string strPEID{get;set;}
    Public Boolean ShowProductionEstimate{get;set;}
   
    // End Global Variables 
    
    // Start constructor
    public PurchaseOrdersUnderVendorContacts () 
    {
        ProductionEstimate__c  activeSettings = ProductionEstimate__c.getOrgDefaults();
        ShowProductionEstimate =activeSettings.Active__c;
        
        theID = ApexPages.CurrentPage().getParameters().get('id');
        q=[SELECT Name, Id, Vendor_Contact__c, Vendor__c FROM Purchase_Order__c where Vendor_Contact__c= : theID limit 4];
        q2=[SELECT Name, Id, Vendor_Contact__c, Vendor__c FROM Purchase_Order__c where Vendor_Contact__c= : theID];
        
    }
    // End Constructor
    
    // show All Contacts for View All Link
    public void ViewAll(){
        q=[SELECT Name, Id, Vendor_Contact__c, Vendor__c FROM Purchase_Order__c where Vendor_Contact__c= : theID];
      
    }
    
     public void Showless(){
      
      q=[SELECT Name, Id, Vendor_Contact__c, Vendor__c FROM Purchase_Order__c where Vendor_Contact__c= : theID limit 4];
    }
    
    
    
    
    
    
 /*   public void closePopup() {
        displayPopup = false;
    }

    public void showPopup() {
        displayPopup = true;
    }
    
 */   
    
   // Method calles on to create Quote
   
    // This method is called on to handle Create Quote button
  
  
    public PageReference CreateQuote() 
    {
       
       String theId=ApexPages.CurrentPage().getParameters().get('id');
       Vendor_Contact__c vc = [select id, vendor__c from vendor_Contact__c where id =:theId];
              PageReference p = Page.newPurchaseorderLightning;
              p.setredirect(true);
              p.getParameters().put('vc',theID); 
              p.getParameters().put('v',vc.vendor__c);
              return p;
        
       
     
      
    }
    // End createQuote method
   
    // Method called on to save Quote
 /*  public PageReference save()
    {
     try
     {
          update q;
     }
    catch(System.DMLException e)
     {
          return null;
     }
         // AFter updating Quote navigate to Quote Tab under Jobs Tab
       
       if(isLtng)
        {
             PageReference p =  new Pagereference('/apex/JobdetailpageLightening07?id='+theID+'&tab=Jobcost');
             p.setRedirect(true);
             return p; 
        }
        else
        {
                // After inserting Job Spec, navigate to Creative Brief Tab        
                PageReference p =  new Pagereference('/apex/JobListView?id='+theID+'&intFocus=4');
                p.setRedirect(true);
                return p;
        }
       
       
       
        
    }
    // End save method
    
    // Method called on to handle Cancel button 
     Public PageReference cancelme()
     {
    
            if(isLtng)
            {
                 PageReference p =  new Pagereference('/apex/JobdetailpageLightening07?id='+theID+'&tab=Jobcost');
                 p.setRedirect(true);
                 return p; 
            }
            else
            {
                    // After inserting Job Spec, navigate to Creative Brief Tab        
                    PageReference p =  new Pagereference('/apex/JobListView?id='+theID+'&intFocus=4');
                    p.setRedirect(true);
                    return p;
            }
    
    
    
              
     }    
*/


}