objects/Campaign__c/Campaign__c.object-meta.xml
<CustomObject>
    <description>This is Campaign object.</description>
    <label>JS Campaign</label>
    <nameField>
        <label>Campaign Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>JS Campaigns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Client__c/Client__c.object-meta.xml
<CustomObject>
    <description>This is custom Client object used for Jobsuite application.</description>
    <label>Client</label>
    <nameField>
        <label>Client Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Job__c/Job__c.object-meta.xml
<CustomObject>
    <description>This is Job object.</description>
    <label>Job</label>
    <nameField>
        <label>Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Job__c/fields/Campaign__c.field-meta.xml
<CustomField>
    <fullName>Campaign__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Campaign</label>
    <referenceTo>Campaign__c</referenceTo>
    <relationshipName>Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Job__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Not using currently. Instead created a custom object Client.</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Job__c/fields/Completion_Date__c.field-meta.xml
<CustomField>
    <fullName>Completion_Date__c</fullName>
    <label>Completion Date</label>
    <type>Date</type>
</CustomField>

objects/Job__c/fields/Flag__c.field-meta.xml
<CustomField>
    <fullName>Flag__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This is flag field to check import process.</description>
    <label>Flag</label>
    <type>Checkbox</type>
</CustomField>

objects/Job__c/fields/Job_Auto_Number__c.field-meta.xml
<CustomField>
    <fullName>Job_Auto_Number__c</fullName>
    <defaultValue>&quot;Auto Fill&quot;</defaultValue>
    <externalId>true</externalId>
    <label>Job #</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

objects/Job__c/fields/Job_Id__c.field-meta.xml
<CustomField>
    <fullName>Job_Id__c</fullName>
    <description>Not in Use Now.</description>
    <label>Job Auto Number</label>
    <type>AutoNumber</type>
</CustomField>

objects/Job__c/fields/JS_Client__c.field-meta.xml
<CustomField>
    <fullName>JS_Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Job is associated with Client object.</description>
    <label>Client</label>
    <referenceTo>Client__c</referenceTo>
    <relationshipName>Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

classes/JobLogSheetTest1.cls
// This class is used to generate Job Log Sheet Report
// Job Log Sheet display all Jobs under Campaign
public with sharing class JobLogSheetTest1 
{
    // Global variables
     public String JName {get; set;}
     public DateTime dt{get;set;}
     public Date today{get;set;}
     public List<Campaign__c> allJobs {get; set;}
     public List<Document> lstDoc;
     public String imageBody{get;set;}
     public String imageURL{get;set;}
     public boolean imageNotFound{get;set;}
     // End of Global variables
 
   
  
     // Start Constructor
     public JobLogSheetTest1()
     {
        // Code to display subscriber logo in PDF header
        
        // If subscriber deletes the Document : JobSuite_OrganizationLogo from their Org then JobSuite App logo will be displayed
        
        imageURL = '/servlet/servlet.FileDownload?file='; 
        lstDoc = [Select Id, Name, Body from Document where Name =: 'JobSuite_OrganizationLogo' WITH SECURITY_ENFORCED LIMIT 1];
        if(!lstDoc.isEmpty())
        {
           String imageId =  lstDoc[0].Id;
           imageBody = imageURL+imageId; 
           imageNotFound = False;
        }    
        else
       {
           imageNotFound = True;
       }
        // End of code for Subscriber Logo
         today=System.Today();
         allJobs=[select id,Name,(Select Id,Job_Id__c,Job_Auto_Number__c,Flag__c,Name,JS_Client__c,JS_Client__r.Name,Campaign__c,Completion_Date__c,Start_Date__c,Due_Date__c from jobs__r Order By JS_Client__r.Name desc,Job_Auto_Number__c Limit 5000) from Campaign__c WITH SECURITY_ENFORCED limit 5000];
     }
     // End of Constructor
     
 /*  Public List<cNodes> hierarchy; 

   public class cNodes
    {
         public List<Job__c> parent {get; set;}
         Public Campaign__c gparent {get;set;}
         public cNodes(Campaign__c  gp, List<Job__c> p)
         {
             parent = p;
             gparent = gp;
         }
    }  
    

    

   Public List<cNodes> getmainnodes()
    {
        hierarchy = new List<cNodes>();
        List<Campaign__c> tempparent = [Select Id,Name from Campaign__c LIMIT 10000];
        for (Integer i =0; i< tempparent.size() ; i++)
        {
               List<Job__c> tempchildren = [Select Id,Name,Job_Id__c,Client__c,Client__r.Name,Campaign__c,Completion_Date__c,Start_Date__c,Due_Date__c from Job__c where Campaign__c = :tempparent[i].Id Order By Name Limit 800];
               hierarchy.add(new cNodes(tempparent[i],tempchildren));
        }   
        return hierarchy;
    } 
    
    */ 

   
}
// End of Class