objects/Campaign__c/Campaign__c.object-meta.xml
<CustomObject>
    <description>This is Campaign object.</description>
    <label>JS Campaign</label>
    <nameField>
        <label>Campaign Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>JS Campaigns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Campaign__c/fields/Budgeted_Cost__c.field-meta.xml
<CustomField>
    <fullName>Budgeted_Cost__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Budgeted Cost (Jobs Total)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

objects/Campaign__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Planned</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Campaign_Jobs__c/Campaign_Jobs__c.object-meta.xml
<CustomObject>
    <label>Campaign Jobs</label>
    <nameField>
        <label>Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Campaign Jobs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Campaign_Jobs__c/fields/Campaign_Template__c.field-meta.xml
<CustomField>
    <fullName>Campaign_Template__c</fullName>
    <label>Campaign Template</label>
    <referenceTo>Campaign_Template__c</referenceTo>
    <relationshipLabel>Campaign Jobs</relationshipLabel>
    <relationshipName>Campaign_Jobs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/Campaign_Jobs__c/fields/Media_Type__c.field-meta.xml
<CustomField>
    <fullName>Media_Type__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Media Type</label>
    <referenceTo>Media_Type__c</referenceTo>
    <relationshipLabel>Campaign Jobs</relationshipLabel>
    <relationshipName>Campaign_Jobs</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

objects/Campaign_Jobs__c/fields/Schedule_Template__c.field-meta.xml
<CustomField>
    <fullName>Schedule_Template__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Schedule Template</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Schedule_Template__c.Media_Types__c</field>
            <operation>equals</operation>
            <valueField>$Source.Media_Type__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Schedule_Template__c</referenceTo>
    <relationshipLabel>Campaign Jobs</relationshipLabel>
    <relationshipName>Campaign_Jobs</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

objects/Campaign_Template__c/Campaign_Template__c.object-meta.xml
<CustomObject>
    <description>Campaign Template used to import jobs under the  with this campaign.</description>
    <label>Campaign Template</label>
    <nameField>
        <label>Campaign Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Campaign Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Campaign_Template__c/fields/Schedule_Calc__c.field-meta.xml
<CustomField>
    <fullName>Schedule_Calc__c</fullName>
    <label>Schedule  Calc</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Start Date</fullName>
                <default>true</default>
                <label>Start Date</label>
            </value>
            <value>
                <fullName>End Date</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Client__c/Client__c.object-meta.xml
<CustomObject>
    <description>This is custom Client object used for Jobsuite application.</description>
    <label>Client</label>
    <nameField>
        <label>Client Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Job__c/Job__c.object-meta.xml
<CustomObject>
    <description>This is Job object.</description>
    <label>Job</label>
    <nameField>
        <label>Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Job__c/fields/Budgeted_Cost__c.field-meta.xml
<CustomField>
    <fullName>Budgeted_Cost__c</fullName>
    <defaultValue>0</defaultValue>
    <description>This is budgeted cost field. This field contains the budget amount for the current Job.</description>
    <label>Budgeted Job Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

objects/Job__c/fields/Campaign__c.field-meta.xml
<CustomField>
    <fullName>Campaign__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Campaign</label>
    <referenceTo>Campaign__c</referenceTo>
    <relationshipName>Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Job__c/fields/Campaign_Template__c.field-meta.xml
<CustomField>
    <fullName>Campaign_Template__c</fullName>
    <description>Campaign Template Id Store in the Job to avoid duplicate jobs insertion under the campaign when we are importing the campaign template.</description>
    <label>Campaign Template</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

objects/Job__c/fields/Estimate_Total__c.field-meta.xml
<CustomField>
    <fullName>Estimate_Total__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Estimate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

objects/Job__c/fields/Invoice_Actual_Amounts__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Actual_Amounts__c</fullName>
    <label>Invoices</label>
    <summarizedField>Invoice__c.Total_Amount__c</summarizedField>
    <summaryForeignKey>Invoice__c.Job__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

objects/Job__c/fields/Job_Auto_Number__c.field-meta.xml
<CustomField>
    <fullName>Job_Auto_Number__c</fullName>
    <defaultValue>&quot;Auto Fill&quot;</defaultValue>
    <externalId>true</externalId>
    <label>Job #</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

objects/Job__c/fields/Job_Id__c.field-meta.xml
<CustomField>
    <fullName>Job_Id__c</fullName>
    <description>Not in Use Now.</description>
    <label>Job Auto Number</label>
    <type>AutoNumber</type>
</CustomField>

objects/Job__c/fields/JS_Client__c.field-meta.xml
<CustomField>
    <fullName>JS_Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Job is associated with Client object.</description>
    <label>Client</label>
    <referenceTo>Client__c</referenceTo>
    <relationshipName>Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Job__c/fields/Media_Types__c.field-meta.xml
<CustomField>
    <fullName>Media_Types__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Media Type</label>
    <referenceTo>Media_Type__c</referenceTo>
    <relationshipName>Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Job__c/fields/Schedule_Calc__c.field-meta.xml
<CustomField>
    <fullName>Schedule_Calc__c</fullName>
    <label>Schedule  Calc</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Start Date</fullName>
                <default>true</default>
                <label>Start Date</label>
            </value>
            <value>
                <fullName>End Date</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Job__c/fields/Schedule_Template__c.field-meta.xml
<CustomField>
    <fullName>Schedule_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Schedule Template</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Schedule_Template__c.Media_Types__c</field>
            <operation>equals</operation>
            <valueField>$Source.Media_Types__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Schedule_Template__c</referenceTo>
    <relationshipName>Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Job__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Requested</fullName>
                <default>true</default>
                <label>Requested</label>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Media_Type__c/Media_Type__c.object-meta.xml
<CustomObject>
    <description>This is Media Type object.</description>
    <label>Media Type</label>
    <nameField>
        <label>Media Type</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Media Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Schedule_Template__c/Schedule_Template__c.object-meta.xml
<CustomObject>
    <description>This is Schedule Template object.</description>
    <label>Schedule Template</label>
    <nameField>
        <label>Schedule Template</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Schedule Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Schedule_Template__c/fields/Media_Types__c.field-meta.xml
<CustomField>
    <fullName>Media_Types__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Media Type</label>
    <referenceTo>Media_Type__c</referenceTo>
    <relationshipLabel>Schedule Templates</relationshipLabel>
    <relationshipName>Schedule_Templates</relationshipName>
    <type>Lookup</type>
</CustomField>

classes/DetailPageComponentController.cls
public class DetailPageComponentController {
    @AuraEnabled
    public static Map<String,list<SObject>> findjobsandnotes(Id recordId)
    {
        Map<String,list<SObject>> JobDataUnderCmp= new Map<String,list<SObject>>();
        List<Job__c> lstJob=[Select Id,Name,Job_Auto_Number__c,JS_Client__r.name,Status__c,Budgeted_Cost__c,Invoice_Actual_Amounts__c,Estimate_Total__c from Job__c where Campaign__c=:recordId and Status__c='Active' ORDER BY Job_Auto_Number__c DESC LIMIT 1000];
        List<Note> lstJobNotes=[Select Id,Title, Body,ParentId,Parent.Name from Note where ParentId IN:lstJob ORDER BY CreatedDate LIMIT 1000];
        List<Attachment> lstJobAttach=[Select Id,Name,ParentId,Parent.Name from Attachment where ParentId IN:lstJob ORDER BY CreatedDate LIMIT 1000];
        List<Job__c> lstJobChatter= [Select Id,Name,Job_Auto_Number__c,JS_Client__r.name,Status__c,Budgeted_Cost__c,Invoice_Actual_Amounts__c,Estimate_Total__c,(SELECT Id, ContentDocumentId, ContentDocument.LatestPublishedVersionId, ContentDocument.Title, ContentDocument.CreatedBy.Name, ContentDocument.LastModifiedDate FROM ContentDocumentLinks) from Job__c where Id IN:lstJob and  Status__c='Active' ORDER BY Job_Auto_Number__c DESC LIMIT 1000];        
        
        JobDataUnderCmp.put('JobSuite__Jobs',lstJob);
        JobDataUnderCmp.put('Job__Notes',lstJobNotes);
        JobDataUnderCmp.put('Job__Attachments',lstJobAttach);
        JobDataUnderCmp.put('Job__ChatterFiles',lstJobChatter);  
        return  JobDataUnderCmp;
    }
    
    @AuraEnabled
    public static list<String> fetchPicklistvalues(){
        list<String> Options=new list<String>();
        List<Schema.PicklistEntry> Picklist=Job__c.Status__c.getDescribe().getPicklistValues();
        Options.add('All Jobs');
        for(Schema.PicklistEntry Op:Picklist){
            Options.add(Op.getValue());
        }
        return Options;
    } 
    
    @AuraEnabled
    public static Map<Id,String> getCampaignTemplates(){
        Map<Id,String>  CmpTempMap=new Map<Id,String>(); 
        list<Campaign_Template__c> ctempLst=new list<Campaign_Template__c>();
        ctempLst=[select Id,Name from Campaign_Template__c];
        
        CmpTempMap.put(null,'--None--');
        for(Campaign_Template__c ct:ctempLst){
            CmpTempMap.put(ct.Id,ct.Name);
        }
        return CmpTempMap;  
    }
    
    @AuraEnabled
    public static String ImpCampTempJobs(Id CmpId,String selectedCTemp ){
        
        list<Job__c> CTJInsert=new list<Job__c>();
        list<Campaign_Jobs__c> cmpjobs=new list<Campaign_Jobs__c>();
        
        if(selectedCTemp!=null && selectedCTemp!=''){
            list<Job__c> CTjobs=[Select Id,Job_Id__c,Budgeted_Cost__c,Name,Campaign_Template__c,Job_Auto_Number__c,JS_Client__r.name,Invoice_Actual_Amounts__c,Status__c,Estimate_Total__c from Job__c where Campaign__c=:CmpId and Campaign_Template__c=:selectedCTemp];
            if(CTjobs.size()>0){
                return 'This Template already Imported for this Campaign';
            }
            else{
                cmpjobs=[select id,name,Media_Type__c,Schedule_Template__c,Campaign_Template__c from Campaign_Jobs__c where Campaign_Template__c=:selectedCTemp];
                if(cmpjobs.size()==0){
                    return 'This Template doesn\'t have jobs to import';
                }
                else{ 
                for(Campaign_Jobs__c cj:cmpjobs){
                    Job__c j=new Job__c();
                    j.Name=cj.name;
                    j.Campaign__c=CmpId;
                    j.Media_Types__c=cj.Media_Type__c;
                    j.Schedule_Template__c=cj.Schedule_Template__c;
                    J.Schedule_Calc__c='Start Date';
                    J.Start_Date__c=System.today();
                    J.Campaign_Template__c=cj.Campaign_Template__c;
                    CTJInsert.add(j);
                }
                
                
                try{
                    insert CTJInsert;
                }
                catch(System.DMLException e){
                    return ''+e.getMessage();
                }
              }
            }
        }
        else{
            return 'Please select the  Campaign Template';
        }
        
        return 'Sucessfully Imported Campaign Template Jobs';
    }
    
    
    @AuraEnabled 
    public static Map<String,list<SObject>> RefreshJobNotes(Id recordId,String JobStatus)
    {
        System.debug('===recordId======'+recordId);
        System.debug('===JobStatus======'+JobStatus);
        
        Map<String,list<SObject>> JobDataUnderCmp= new Map<String,list<SObject>>();
        List<Job__c> lstJob=new  List<Job__c>();
        if(JobStatus=='All Jobs')
            lstJob=[Select Id,Name,Job_Auto_Number__c,JS_Client__r.name,Status__c,Budgeted_Cost__c,Invoice_Actual_Amounts__c,Estimate_Total__c from Job__c where Campaign__c=:recordId  ORDER BY JOB_Auto_NUmber__c DESC LIMIT 1000];
        else
            lstJob=[Select Id,Job_Auto_Number__c,Name,JS_Client__r.name,Status__c,Budgeted_Cost__c,Invoice_Actual_Amounts__c,Estimate_Total__c from Job__c where Campaign__c=:recordId and Status__c=:JobStatus ORDER BY JOB_Auto_NUmber__c DESC LIMIT 1000];
        
        List<Note> lstJobNotes=[Select Id,Title, Body,ParentId,Parent.Name from Note where ParentId IN:lstJob ORDER BY CreatedDate LIMIT 1000];
        List<Attachment> lstJobAttach=[Select Id,Name,ParentId,Parent.Name from Attachment where ParentId IN:lstJob ORDER BY CreatedDate LIMIT 1000];
        List<Job__c> lstJobChatter= [Select Id,Name,Job_Auto_Number__c,JS_Client__r.name,Status__c,Budgeted_Cost__c,Invoice_Actual_Amounts__c,Estimate_Total__c,(SELECT Id, ContentDocumentId, ContentDocument.LatestPublishedVersionId, ContentDocument.Title, ContentDocument.CreatedBy.Name, ContentDocument.LastModifiedDate FROM ContentDocumentLinks) from Job__c where Id IN:lstJob  ORDER BY Job_Auto_Number__c DESC LIMIT 1000];        
        
        JobDataUnderCmp.put('JobSuite__Jobs',lstJob);
        JobDataUnderCmp.put('Job__Notes',lstJobNotes);
        JobDataUnderCmp.put('Job__Attachments',lstJobAttach);
        JobDataUnderCmp.put('Job__ChatterFiles',lstJobChatter);  
        
        return  JobDataUnderCmp;
        
    }
    
    
}