objects/Campaign__c/Campaign__c.object-meta.xml
<CustomObject>
    <description>This is Campaign object.</description>
    <label>JS Campaign</label>
    <nameField>
        <label>Campaign Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>JS Campaigns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Material_Item__c/Material_Item__c.object-meta.xml
<CustomObject>
    <description>This is Material Item object.</description>
    <label>Material Item</label>
    <nameField>
        <label>Material Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Material Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Material_Item__c/fields/Calc_Unit__c.field-meta.xml
<CustomField>
    <fullName>Calc_Unit__c</fullName>
    <label>Calc Unit</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Sheet</fullName>
            </value>
            <value>
                <fullName>Size</fullName>
            </value>
            <value>
                <fullName>Each</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Material_Item__c/recordTypes/Size.recordType-meta.xml
<RecordType>
    <fullName>Size</fullName>
    <active>true</active>
    <label>Size</label>
</RecordType>

classes/TestDeleteMIFeedAttachmentExtension.cls
//@isTest
public class TestDeleteMIFeedAttachmentExtension {
	// Test Coverage 
     /*   static testMethod void TestDeleteMIFeedAttachmentExtension()
        {
          Campaign__c  testC=new Campaign__c(name='test 123');
          insert testC;
            
            Material_Item__c  testI=new Material_Item__c (name='test 1234',Calc_Unit__c ='Size');
  		        insert testI;
               
           System.assertEquals('test 1234',testI.Name);
               
           Blob b = Blob.valueOf('Hello');

           FeedItem a=new FeedItem (parentId=testI.Id,Body='hello');
           
               insert a;
            
            FeedItem aa=new FeedItem (parentId=testC.Id,Body='hello');
           
               insert aa;
            
            
               
        // Instantiate the standard controller with the Job 
           ApexPages.StandardController con=new ApexPages.StandardController(a);
             System.currentPagereference().getParameters().put('Id', a.Id);
            
            ApexPages.StandardController con1=new ApexPages.StandardController(aa);
             System.currentPagereference().getParameters().put('Id', aa.Id);
        
        // Instantiate the extention instance with the standardcontroller
           DeleteMIFeedAttachmentExtension ext=new DeleteMIFeedAttachmentExtension(con);
           
        // Invoke the Delete method 
           ApexPages.Pagereference result=ext.checkDelete();
        
        // The below line covers the catch block in checkDetele method 
           ApexPages.Pagereference result1=ext.checkDelete();
            
            
           DeleteCampaignFeedAttachmentExtension ext1=new DeleteCampaignFeedAttachmentExtension(con1);
             ApexPages.Pagereference resultt=ext1.checkDelete();
     }*/
    // End of Test Coverage
}