objects/Billboard__c/Billboard__c.object-meta.xml
<CustomObject>
    <description>This is Billboard object.</description>
    <label>Billboard</label>
    <nameField>
        <label>BB #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billboards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Billboard_Contract__c/Billboard_Contract__c.object-meta.xml
<CustomObject>
    <description>This is Billboard Contract object</description>
    <label>Billboard Contract</label>
    <nameField>
        <displayFormat>BBC-{00000}</displayFormat>
        <label>BBC#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Billboard Contracts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Billboard_Contract__c/fields/BB_Vendor_Name__c.field-meta.xml
<CustomField>
    <fullName>BB_Vendor_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>BB Vendor Name</label>
    <referenceTo>Vendor__c</referenceTo>
    <relationshipLabel>Billboard Contracts</relationshipLabel>
    <relationshipName>Billboard_Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Billboard_Contract__c/fields/Billboard__c.field-meta.xml
<CustomField>
    <fullName>Billboard__c</fullName>
    <label>Billboard</label>
    <referenceTo>Billboard__c</referenceTo>
    <relationshipLabel>Billboard Contracts</relationshipLabel>
    <relationshipName>Billboard_Contracts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/Vendor__c/Vendor__c.object-meta.xml
<CustomObject>
    <description>This is Vendor object. Vendors in JobSuite are assigned to the line items on Quotes, Estimates, Purchase Orders and Vendor Invoices.  A printer or photographer may be a vendor.</description>
    <label>Vendor</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vendors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Vendor__c/fields/Vendor__c.field-meta.xml
<CustomField>
    <fullName>Vendor__c</fullName>
    <label>Vendor #</label>
    <length>30</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

objects/Vendor__c/fields/Vendor_Type__c.field-meta.xml
<CustomField>
    <fullName>Vendor_Type__c</fullName>
    <label>Vendor Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Outdoor</fullName>
            </value>
            <value>
                <fullName>Standard</fullName>
            </value>
            <value>
                <fullName>Printer</fullName>
            </value>
            <value>
                <fullName>POS</fullName>
            </value>
            <value>
                <fullName>Agency</fullName>
            </value>
            <value>
                <fullName>Freelancer</fullName>
            </value>
            <value>
                <fullName>Writer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

classes/EditBillboardContractExtension.cls
public with sharing class EditBillboardContractExtension {

   // Global Variables
   
   /* public boolean isLtng{private set; get{
                                            String theme = UserInfo.getUITheme();
                                            return (theme=='Theme4d')?true:false;
                                          }
                            }  
   
    private final Billboard_Contract__c objBBC;
    public Billboard_Contract__c objBBC1{get;set;}
    public String VendorName;
    public String getVendorName() { return VendorName; }
    public void setVendorName(String s) {  this.VendorName = s; }
    public String strid;
    // End of Global variables 
 
    // Standard Controller Extension
    public EditBillboardContractExtension(ApexPages.StandardController con) 
    {
        this.objBBC=(Billboard_Contract__c)con.getrecord();
        
        
        objBBC1 = [SELECT id, name,BB_Vendor_Name__c,Billboard__c FROM Billboard_Contract__c WHERE id =: objBBC.id];
        String st1 = objBBC1.BB_Vendor_Name__c;
        system.debug('st1 -----> ' + st1);
        if(String.isNotBlank(st1))
        {
            Vendor__c v=[Select id,Name from Vendor__c where id=: st1];
            VendorName= v.id; 
        }
        
        
        
        strid=objBBC1.Billboard__c;
        
        
    }
    // End of Standard Controller Extension 

   
    public List<selectOption> getVendors() 
    {
        List<selectOption> optionList = new List<selectOption>();
        optionList.add(new selectOption('', '- None -'));  
        for (Vendor__c v : [SELECT Id, name,Vendor_Type__c FROM Vendor__c where Vendor_Type__c ='Outdoor' order by Name]) 
        {  
            optionList.add(new selectOption(v.Id, v.Name));  
        }
        return optionList;  
    }
   
     Public PageReference saveme()
    {
        
        
        try 
        {   
            if(schema.SobjectType.Billboard_Contract__c.Fields.BB_Vendor_Name__c.isUpdateable()){
                objBBC.BB_Vendor_Name__c=VendorName;
            }
            if(Schema.sObjectType.Billboard_Contract__c.isUpdateable()) { 
                update objBBC;
            }
        }
        catch(System.DMLException e){return null; }
         
         
         PageReference p;
         if(isLtng)
         {
            p = new Pagereference('/apex/BillboardDetailPageLightning?id='+strid+'&section=BBC');
         }
        
         else
         {
           p = new Pagereference('/apex/BillboardDetailPage?id='+strid);
         }
        
         
         
    //    PageReference p =  new Pagereference('/apex/BillboardDetailPage?id='+strid);
        p.setRedirect(true);
        return p;
    }
    
    Public PageReference cancelme()
    {
       
         PageReference p;
         if(isLtng)
         {
            p = new Pagereference('/apex/BillboardDetailPageLightning?id='+strid+'&section=BBC');
         }
        
         else
         {
           p = new Pagereference('/apex/BillboardDetailPage?id='+strid);
         }
        
         
         
    //    PageReference p =  new Pagereference('/apex/BillboardDetailPage?id='+strid);
        p.setRedirect(true);
        return p;
    }*/
}