objects/Billboard__c/Billboard__c.object-meta.xml
<CustomObject>
    <description>This is Billboard object.</description>
    <label>Billboard</label>
    <nameField>
        <label>BB #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billboards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Billboard__c/fields/BB_Vendor__c.field-meta.xml
<CustomField>
    <fullName>BB_Vendor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>BB Vendor</label>
    <referenceTo>Vendor__c</referenceTo>
    <relationshipLabel>Billboards</relationshipLabel>
    <relationshipName>Billboards</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Billboard__c/fields/Billboard_Status__c.field-meta.xml
<CustomField>
    <fullName>Billboard_Status__c</fullName>
    <label>Billboard Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Active-Batch</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Billboard__c/fields/Billboard_Type__c.field-meta.xml
<CustomField>
    <fullName>Billboard_Type__c</fullName>
    <label>Billboard Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Billboard</fullName>
            </value>
            <value>
                <fullName>DOT</fullName>
            </value>
            <value>
                <fullName>Cost Share</fullName>
            </value>
            <value>
                <fullName>Land Lease</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Billboard__c/fields/Client_Name__c.field-meta.xml
<CustomField>
    <fullName>Client_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Client Name</label>
    <referenceTo>Client__c</referenceTo>
    <relationshipLabel>Billboards</relationshipLabel>
    <relationshipName>Billboards</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Billboard__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

objects/Billboard__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <label>Title</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

classes/DisplayBillboardUnderVendorController.cls
public with sharing class DisplayBillboardUnderVendorController {

/*
    // Start Global variables
        public String strStatus{get;set;}
        public List<Billboard__c> BB{get;set;} 
        Public String theID;
        public integer count;
        public integer countstr;
   // End of Global variables
      public List<selectOption> getStatusList() 
    {
        List<selectOption> optionList = new List<selectOption>();
        Schema.DescribeFieldResult field = Billboard__c.Billboard_Status__c.getDescribe();
         optionList.add(new selectOption('All Billboards', 'All Billboards')); 
        for (Schema.PicklistEntry a : field.getPicklistValues()) 
        {  
            optionList.add(new selectOption(a.getLabel(), a.getLabel()));  
        }
        
        return optionList;  
    }
    
    // Start Constructor
     public DisplayBillboardUnderVendorController ()
     {
         strStatus= 'Active';
         theID = ApexPages.CurrentPage().getParameters().get('id');
         BB= [Select id,Name,Billboard_Type__c,Expiration_Date__c,Client_Name__c,Location__c,BB_Vendor__c,Title__c,Billboard_Status__c from Billboard__c where BB_Vendor__c=: theID AND Billboard_Status__c=:'Active' Order By Name limit 1000];
     }
     // End constructor

    //Method to populate BBs based upon status
    
    
     public void populatebbList()
    {
    
      
       count = [select count() from Billboard__c where  BB_Vendor__c=: theID];
       
      if(strStatus != 'All Billboards')
     {
      countstr = [select count() from Billboard__c where BB_Vendor__c=: theID and Billboard_Status__c = :strStatus];
      }
      
      if(strStatus == 'All Billboards')
      {
       if(count>1000)
         {
           
         BB= [Select id,Name,Billboard_Type__c,Expiration_Date__c,Client_Name__c,Location__c,BB_Vendor__c,Title__c,Billboard_Status__c from Billboard__c where BB_Vendor__c=: theID  Order By Name limit 1000];
         system.debug('BB Status & size'+bb.size()+strStatus );
         }else
         {
            
         BB= [Select id,Name,Billboard_Type__c,Expiration_Date__c,Client_Name__c,Location__c,BB_Vendor__c,Title__c,Billboard_Status__c from Billboard__c where BB_Vendor__c=: theID  Order By Name limit 1000];
        system.debug('BB Status & size'+bb.size()+strStatus );
         }
      }else
      {
         if(countstr >1000 )
          {
              
         BB= [Select id,Name,Billboard_Type__c,Expiration_Date__c,Client_Name__c,Location__c,BB_Vendor__c,Title__c,Billboard_Status__c from Billboard__c where BB_Vendor__c=: theID AND Billboard_Status__c=:strStatus  Order By Name limit 1000];
            system.debug('BB Status & size'+bb.size()+strStatus );
           }
           else
           {
              
         BB= [Select id,Name,Billboard_Type__c,Expiration_Date__c,Client_Name__c,Location__c,BB_Vendor__c,Title__c,Billboard_Status__c from Billboard__c where BB_Vendor__c=: theID AND Billboard_Status__c=:strStatus  Order By Name limit 1000];
           
           system.debug('BB Status & size'+bb.size()+strStatus );
           
           }
        }
      } 
    
    
    
*/



}