objects/Billboard__c/Billboard__c.object-meta.xml
<CustomObject>
    <description>This is Billboard object.</description>
    <label>Billboard</label>
    <nameField>
        <label>BB #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billboards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Billboard__c/fields/BB_Vendor__c.field-meta.xml
<CustomField>
    <fullName>BB_Vendor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>BB Vendor</label>
    <referenceTo>Vendor__c</referenceTo>
    <relationshipLabel>Billboards</relationshipLabel>
    <relationshipName>Billboards</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Billboard__c/fields/Client_Name__c.field-meta.xml
<CustomField>
    <fullName>Client_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Client Name</label>
    <referenceTo>Client__c</referenceTo>
    <relationshipLabel>Billboards</relationshipLabel>
    <relationshipName>Billboards</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Billboard_Contract__c/Billboard_Contract__c.object-meta.xml
<CustomObject>
    <description>This is Billboard Contract object</description>
    <label>Billboard Contract</label>
    <nameField>
        <displayFormat>BBC-{00000}</displayFormat>
        <label>BBC#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Billboard Contracts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Billboard_Contract__c/fields/BB_Vendor_Name__c.field-meta.xml
<CustomField>
    <fullName>BB_Vendor_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>BB Vendor Name</label>
    <referenceTo>Vendor__c</referenceTo>
    <relationshipLabel>Billboard Contracts</relationshipLabel>
    <relationshipName>Billboard_Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Billboard_Contract__c/fields/Billboard__c.field-meta.xml
<CustomField>
    <fullName>Billboard__c</fullName>
    <label>Billboard</label>
    <referenceTo>Billboard__c</referenceTo>
    <relationshipLabel>Billboard Contracts</relationshipLabel>
    <relationshipName>Billboard_Contracts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/Client__c/Client__c.object-meta.xml
<CustomObject>
    <description>This is custom Client object used for Jobsuite application.</description>
    <label>Client</label>
    <nameField>
        <label>Client Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Vendor__c/Vendor__c.object-meta.xml
<CustomObject>
    <description>This is Vendor object. Vendors in JobSuite are assigned to the line items on Quotes, Estimates, Purchase Orders and Vendor Invoices.  A printer or photographer may be a vendor.</description>
    <label>Vendor</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vendors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Vendor__c/fields/Vendor__c.field-meta.xml
<CustomField>
    <fullName>Vendor__c</fullName>
    <label>Vendor #</label>
    <length>30</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

objects/Vendor__c/fields/Vendor_Type__c.field-meta.xml
<CustomField>
    <fullName>Vendor_Type__c</fullName>
    <label>Vendor Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Outdoor</fullName>
            </value>
            <value>
                <fullName>Standard</fullName>
            </value>
            <value>
                <fullName>Printer</fullName>
            </value>
            <value>
                <fullName>POS</fullName>
            </value>
            <value>
                <fullName>Agency</fullName>
            </value>
            <value>
                <fullName>Freelancer</fullName>
            </value>
            <value>
                <fullName>Writer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

classes/TestDisplayBillboardContractController.cls
//@isTest
Public Class TestDisplayBillboardContractController{

/*static testMethod void TestDisplayBillboardContractController()
     {
            
          Client__c testClient=new Client__c(Name='Client 623');
           insert testClient; 
          Vendor__c testvendor=new Vendor__c (Name='Vendor 623',Vendor_Type__c ='Outdoor');
           insert testvendor; 
   
          Billboard__c  testI=new Billboard__c(Client_Name__c=testClient.Id,name='test 123',BB_Vendor__c=testvendor.id);
            insert testI;
           
          Billboard_Contract__c bbc=new Billboard_Contract__c(Billboard__c=testI.id,BB_Vendor_Name__c=testvendor.id);
            insert bbc;
           
           
            
            ApexPages.currentPage().getParameters().put('id',testI.Id);
         // Instantiate the extention instance with the Custom Controller
           DisplayBillboardContractController ext1=new DisplayBillboardContractController();
          
            // Invoke the primary method on the extension
           ApexPages.PageReference result1=ext1.createBBC();
           
           ext1.strBBC= bbc.Id;
           result1 = ext1.deleteBBC();
      } 
     // End of test Method
*/

}