objects/Billboard__c/Billboard__c.object-meta.xml
<CustomObject>
    <description>This is Billboard object.</description>
    <label>Billboard</label>
    <nameField>
        <label>BB #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billboards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Billboard__c/fields/BB_Vendor__c.field-meta.xml
<CustomField>
    <fullName>BB_Vendor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>BB Vendor</label>
    <referenceTo>Vendor__c</referenceTo>
    <relationshipLabel>Billboards</relationshipLabel>
    <relationshipName>Billboards</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Billboard__c/fields/Client_Name__c.field-meta.xml
<CustomField>
    <fullName>Client_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Client Name</label>
    <referenceTo>Client__c</referenceTo>
    <relationshipLabel>Billboards</relationshipLabel>
    <relationshipName>Billboards</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Billboard__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

objects/Client__c/Client__c.object-meta.xml
<CustomObject>
    <description>This is custom Client object used for Jobsuite application.</description>
    <label>Client</label>
    <nameField>
        <label>Client Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Client__c/fields/Client_Code__c.field-meta.xml
<CustomField>
    <fullName>Client_Code__c</fullName>
    <label>Client Code</label>
    <length>6</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

objects/Vendor__c/Vendor__c.object-meta.xml
<CustomObject>
    <description>This is Vendor object. Vendors in JobSuite are assigned to the line items on Quotes, Estimates, Purchase Orders and Vendor Invoices.  A printer or photographer may be a vendor.</description>
    <label>Vendor</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vendors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/BB_Search_Controller.cls
public with sharing class BB_Search_Controller {
    
    @AuraEnabled
    public static Integer getTotalNoOfBB(){
        AggregateResult results=[SELECT Count(Id)TotalBB From Billboard__c Where Name!=null WITH SECURITY_ENFORCED];
        Integer totalBB=(Integer)results.get('TotalBB');
        return totalBB;
    }
    
    @AuraEnabled
    public static list<Billboard__c> getBB(Integer intOffSet){
        list<Billboard__c> BBlist=Database.query('select Id, Name,BB_Vendor__r.Name,BB_Vendor__c,Client_Name__r.Name, Client_Name__r.Client_Code__c,Client_Name__c,Expiration_Date__c,Location__c from Billboard__c where name != null WITH SECURITY_ENFORCED LIMIT 50 OFFSET :intOffSet');
        System.debug('=====BBlist==='+BBlist);
        return BBlist;
    }
    
    @AuraEnabled
    public static list<Billboard__c> runSearch(String BB,String CLI,String CLICode,String BBV,String LOC,String ED1,String ED2)
    {
        String soql;
        soql = 'select Id, Name,BB_Vendor__r.Name,BB_Vendor__c,Client_Name__r.Name,Client_Name__r.Client_Code__c,Client_Name__c,Expiration_Date__c,Location__c from Billboard__c where name != null';
        
        if (!BB.equals(''))
            soql += ' and name LIKE \''+String.escapeSingleQuotes(BB)+'%\'';
        
        if (!CLI.equals(''))
            soql += ' and Client_Name__r.Name LIKE \''+String.escapeSingleQuotes(CLI)+'%\'';
        
        if (!CLICode.equals(''))
            soql += ' and Client_Name__r.Client_Code__c LIKE \''+String.escapeSingleQuotes(CLICode)+'%\'';
        
        if (!BBV.equals(''))
            soql += ' and BB_Vendor__r.Name LIKE \''+String.escapeSingleQuotes(BBV)+'%\'';  
        
        if (!LOC.equals(''))
            soql += ' and Location__c LIKE \''+String.escapeSingleQuotes(LOC)+'\'';
        
        if(ED1!=null){
            if(!ED1.equals(''))
                soql += ' and Expiration_Date__c >= '+ String.escapeSingleQuotes(ED1)+' '; 
        }
        if(ED2!=null){
            if(!ED2.equals(''))
                soql += ' and Expiration_Date__c <= '+ String.escapeSingleQuotes(ED2)+' '; 
        }
        soql +=' WITH SECURITY_ENFORCED';
        
       // soql+=' Order by Job_Auto_Number__c desc';
        
        System.debug('======soql========='+soql);
        list<Billboard__c> BBlist=Database.query(soql);
        return BBlist;
    }
   
}