objects/Billboard__c/Billboard__c.object-meta.xml
<CustomObject>
    <description>This is Billboard object.</description>
    <label>Billboard</label>
    <nameField>
        <label>BB #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billboards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Billboard_Invoice__c/Billboard_Invoice__c.object-meta.xml
<CustomObject>
    <description>This is Billboard invoice object. It is child object of Billboard.</description>
    <label>Billboard Invoice</label>
    <nameField>
        <label>BB Invoice #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billboard Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Billboard_Invoice__c/fields/Billboard__c.field-meta.xml
<CustomField>
    <fullName>Billboard__c</fullName>
    <label>Billboard #</label>
    <referenceTo>Billboard__c</referenceTo>
    <relationshipLabel>Billboard Invoices</relationshipLabel>
    <relationshipName>Billboard_Invoices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

objects/Billboard_Invoice__c/fields/Billboard_Vendor__c.field-meta.xml
<CustomField>
    <fullName>Billboard_Vendor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Billboard Vendor</label>
    <referenceTo>Vendor__c</referenceTo>
    <relationshipLabel>Billboard Invoices</relationshipLabel>
    <relationshipName>Billboard_Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Vendor__c/Vendor__c.object-meta.xml
<CustomObject>
    <description>This is Vendor object. Vendors in JobSuite are assigned to the line items on Quotes, Estimates, Purchase Orders and Vendor Invoices.  A printer or photographer may be a vendor.</description>
    <label>Vendor</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vendors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Vendor__c/fields/Vendor__c.field-meta.xml
<CustomField>
    <fullName>Vendor__c</fullName>
    <label>Vendor #</label>
    <length>30</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

objects/Vendor__c/fields/Vendor_Type__c.field-meta.xml
<CustomField>
    <fullName>Vendor_Type__c</fullName>
    <label>Vendor Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Outdoor</fullName>
            </value>
            <value>
                <fullName>Standard</fullName>
            </value>
            <value>
                <fullName>Printer</fullName>
            </value>
            <value>
                <fullName>POS</fullName>
            </value>
            <value>
                <fullName>Agency</fullName>
            </value>
            <value>
                <fullName>Freelancer</fullName>
            </value>
            <value>
                <fullName>Writer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

classes/CreateBillboardInvoiceExtension.cls
public with sharing class CreateBillboardInvoiceExtension {

   /*
    public boolean isLtng{private set; get{
                                            String theme = UserInfo.getUITheme();
                                            return (theme=='Theme4d')?true:false;
                                          }
    }  
   
    private final Billboard_Invoice__c bbi;
    public String bbid{get;set;}
    public String BillboardName{get;set;}
    public String VendorName;
    
    public String getVendorName() { return VendorName; }
    public void setVendorName(String s) {  this.VendorName = s; }
    
    
    // Start Constructor
    public CreateBillboardInvoiceExtension(ApexPages.StandardController controller) {
    
     this.bbi=(Billboard_Invoice__c)controller.getRecord();
        bbid=ApexPages.CurrentPage().getParameters().get('bbid');
        Billboard__c objBB=[Select id,name from Billboard__c where id=:bbid];
        BillboardName=objBB.Name;
        bbi.Billboard__c= bbid;
        
    }
    
    public List<selectOption> getVendors() 
    {
        List<selectOption> optionList = new List<selectOption>();
        optionList.add(new selectOption('', '- None -'));  
        for (Vendor__c v : [SELECT Id, name,Vendor_Type__c FROM Vendor__c where Vendor_Type__c ='Outdoor' order by Name]) 
        {  
            optionList.add(new selectOption(v.Id, v.Name));  
        }
        return optionList;  
    }

            
          // Save Method
            public PageReference saveme() 
                { 
                
                   
                    string strbbiId;
                    try
                    {
                        if(schema.SobjectType.Billboard_Invoice__c.Fields.Billboard_Vendor__c.isCreateable()){ 
                            bbi.Billboard_Vendor__c=VendorName;
                        }
                        if(Schema.sObjectType.Billboard_Invoice__c.isCreateable()){
                            insert bbi;
                        }
                        strbbiId =bbi.id;
                    }
                    catch(DMLException e)
                    {
                        return null;
                    }
                    
                
                PageReference p;   
                 if(isLtng)
                 {
                    p = new Pagereference('/apex/BillboardDetailPageLightning?id='+bbid+'&section=BBI');
                 }
                
                else
                 {
                   p = new Pagereference('/apex/BillboardDetailPage?id='+bbid);
                 }
                
                
             //    PageReference pageRef = new PageReference('/apex/BillboardDetailPage?id='+bbid);
                  p.setRedirect(true);
                  return p;
                  
                  
               }
            // End of Save Method

        // Cancel Method
        Public PageReference cancelme()
        {       
            PageReference p;   
             if(isLtng)
             {
                p = new Pagereference('/apex/BillboardDetailPageLightning?id='+bbid+'&section=BBI');
             }
            
            else
             {
               p = new Pagereference('/apex/BillboardDetailPage?id='+bbid);
             }
            
            
            
          //  PageReference p = new PageReference('/apex/BillboardDetailPage?id='+bbid);
            p.setRedirect(true);
            return p;   
            
        }
        // Cancel Method        
        
*/


}