objects/Billboard__c/Billboard__c.object-meta.xml
<CustomObject>
    <description>This is Billboard object.</description>
    <label>Billboard</label>
    <nameField>
        <label>BB #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billboards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Billboard__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

objects/Billboard_Invoice__c/Billboard_Invoice__c.object-meta.xml
<CustomObject>
    <description>This is Billboard invoice object. It is child object of Billboard.</description>
    <label>Billboard Invoice</label>
    <nameField>
        <label>BB Invoice #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billboard Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Billboard_Invoice__c/fields/BB_Invoice_Amount__c.field-meta.xml
<CustomField>
    <fullName>BB_Invoice_Amount__c</fullName>
    <label>BB Invoice Amount</label>
    <summarizedField>Billboard_Invoice_Line_Item__c.Amount__c</summarizedField>
    <summaryForeignKey>Billboard_Invoice_Line_Item__c.Billboard_Invoice__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

objects/Billboard_Invoice__c/fields/BB_Invoice_Due_Date__c.field-meta.xml
<CustomField>
    <fullName>BB_Invoice_Due_Date__c</fullName>
    <label>BB Invoice Due Date</label>
    <type>Date</type>
</CustomField>

objects/Billboard_Invoice__c/fields/Billboard__c.field-meta.xml
<CustomField>
    <fullName>Billboard__c</fullName>
    <label>Billboard #</label>
    <referenceTo>Billboard__c</referenceTo>
    <relationshipLabel>Billboard Invoices</relationshipLabel>
    <relationshipName>Billboard_Invoices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

objects/Billboard_Invoice__c/fields/Billboard_Vendor__c.field-meta.xml
<CustomField>
    <fullName>Billboard_Vendor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Billboard Vendor</label>
    <referenceTo>Vendor__c</referenceTo>
    <relationshipLabel>Billboard Invoices</relationshipLabel>
    <relationshipName>Billboard_Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Billboard_Invoice__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <formula>Billboard__r.Location__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Location</label>
    <type>Text</type>
</CustomField>

objects/Vendor__c/Vendor__c.object-meta.xml
<CustomObject>
    <description>This is Vendor object. Vendors in JobSuite are assigned to the line items on Quotes, Estimates, Purchase Orders and Vendor Invoices.  A printer or photographer may be a vendor.</description>
    <label>Vendor</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vendors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/DisplayBBInvoiceUnderVendor.cls
public with sharing class DisplayBBInvoiceUnderVendor {
/*
// Start Global variables
        transient public List<Billboard_Invoice__c> invoice{get;set;}
        Public String theID;
        public boolean displayinvoice{get;set;}
        public boolean noinvoice{get;set;}
    // End of Global variables
    
    // Start Constructor
     public DisplayBBInvoiceUnderVendor ()
     {
      
         theID = ApexPages.CurrentPage().getParameters().get('id');
         invoice = [Select id,Name,Billboard_Vendor__c,Billboard__c,Billboard__r.Name,BB_Invoice_Due_Date__c,BB_Invoice_Amount__c,Location__c,Billboard_Vendor__r.Name from Billboard_Invoice__c where Billboard_Vendor__c=: theID Order By Name ];
         If(invoice.size()>0)
         {
             displayinvoice=true;
             noinvoice=false;
         }else{
                 noinvoice=true;
                 displayinvoice=false;
               }
     }
     // End constructor


*/

}