objects/Billboard__c/Billboard__c.object-meta.xml
<CustomObject>
    <description>This is Billboard object.</description>
    <label>Billboard</label>
    <nameField>
        <label>BB #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billboards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Billboard__c/fields/BB_Vendor__c.field-meta.xml
<CustomField>
    <fullName>BB_Vendor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>BB Vendor</label>
    <referenceTo>Vendor__c</referenceTo>
    <relationshipLabel>Billboards</relationshipLabel>
    <relationshipName>Billboards</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Billboard__c/fields/Client_Name__c.field-meta.xml
<CustomField>
    <fullName>Client_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Client Name</label>
    <referenceTo>Client__c</referenceTo>
    <relationshipLabel>Billboards</relationshipLabel>
    <relationshipName>Billboards</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Client__c/Client__c.object-meta.xml
<CustomObject>
    <description>This is custom Client object used for Jobsuite application.</description>
    <label>Client</label>
    <nameField>
        <label>Client Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ClientControl__c/ClientControl__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Client Control</label>
</CustomObject>

objects/ClientControl__c/fields/Detail_Page_Map__c.field-meta.xml
<CustomField>
    <fullName>Detail_Page_Map__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Detail Page Map</label>
    <type>Checkbox</type>
</CustomField>

classes/ClientViewPageExt.cls
public with sharing class ClientViewPageExt {

  /* Public boolean ShowBBS{get;set;}
    Public Client__c v{get;set;}
    Public boolean showMap{get;set;}
    public ClientViewPageExt(ApexPages.StandardController controller) {
    
        this.v=(Client__c)controller.getrecord();
        
        List<Billboard__c> objBB = [SELECT id, name,BB_Vendor__c,Client_Name__c FROM Billboard__c limit 1];
        If(objBB.size()>0)ShowBBS=true;
        
        ClientControl__c  activeSettings = ClientControl__c.getOrgDefaults();
        showMap = activeSettings.Detail_Page_Map__c;
 
    }*/

}