objects/Campaign_Jobs__c/Campaign_Jobs__c.object-meta.xml
<CustomObject>
    <label>Campaign Jobs</label>
    <nameField>
        <label>Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Campaign Jobs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Campaign_Jobs__c/fields/Campaign_Template__c.field-meta.xml
<CustomField>
    <fullName>Campaign_Template__c</fullName>
    <label>Campaign Template</label>
    <referenceTo>Campaign_Template__c</referenceTo>
    <relationshipLabel>Campaign Jobs</relationshipLabel>
    <relationshipName>Campaign_Jobs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/Campaign_Jobs__c/fields/Media_Type__c.field-meta.xml
<CustomField>
    <fullName>Media_Type__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Media Type</label>
    <referenceTo>Media_Type__c</referenceTo>
    <relationshipLabel>Campaign Jobs</relationshipLabel>
    <relationshipName>Campaign_Jobs</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

objects/Campaign_Jobs__c/fields/Schedule_Template__c.field-meta.xml
<CustomField>
    <fullName>Schedule_Template__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Schedule Template</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Schedule_Template__c.Media_Types__c</field>
            <operation>equals</operation>
            <valueField>$Source.Media_Type__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Schedule_Template__c</referenceTo>
    <relationshipLabel>Campaign Jobs</relationshipLabel>
    <relationshipName>Campaign_Jobs</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

objects/Campaign_Template__c/Campaign_Template__c.object-meta.xml
<CustomObject>
    <description>Campaign Template used to import jobs under the  with this campaign.</description>
    <label>Campaign Template</label>
    <nameField>
        <label>Campaign Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Campaign Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Media_Type__c/Media_Type__c.object-meta.xml
<CustomObject>
    <description>This is Media Type object.</description>
    <label>Media Type</label>
    <nameField>
        <label>Media Type</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Media Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Schedule_Template__c/Schedule_Template__c.object-meta.xml
<CustomObject>
    <description>This is Schedule Template object.</description>
    <label>Schedule Template</label>
    <nameField>
        <label>Schedule Template</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Schedule Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Schedule_Template__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

objects/Schedule_Template__c/fields/Media_Types__c.field-meta.xml
<CustomField>
    <fullName>Media_Types__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Media Type</label>
    <referenceTo>Media_Type__c</referenceTo>
    <relationshipLabel>Schedule Templates</relationshipLabel>
    <relationshipName>Schedule_Templates</relationshipName>
    <type>Lookup</type>
</CustomField>

classes/NewCampaignJobExt.cls
public with sharing class NewCampaignJobExt {

  /*  public boolean isLtng{private set; get{
                                            String theme = UserInfo.getUITheme();
                                            return (theme=='Theme4d')?true:false;
                                        }
            }  
            
    public string CTempName{set;get;}
  
    public string CTempId;
    public  Campaign_Jobs__c CampJob;
    public string MTName {set;get;}
    public string ScheduleTemp {set;get;}
    // End of Global variables
    

    public NewCampaignJobExt(ApexPages.StandardController controller) {
     this.CampJob=(Campaign_Jobs__c)controller.getRecord();
     CTempId=Apexpages.currentpage().getParameters().get('CTempId');
     
     Campaign_Template__c  CTemRec=[select id,name from Campaign_Template__c where id=:CTempId];
     CTempName=CTemRec.Name;
     
    }
    
     public List<selectOption> getMediaTypes() 
    {
        List<selectOption> optionList = new List<selectOption>();
        optionList.add(new selectOption('', '- None -'));  
        for (Media_Type__c a : [SELECT Id, name FROM Media_Type__c order by Name]) 
        {  
            optionList.add(new selectOption(a.Id, a.Name));  
        }
               
        return optionList;  
    }
    
    
    public List<selectOption> getScheduleTemplates()
    {
        List<selectOption> optionList = new List<selectOption>();   
        optionList.add(new selectOption('', '- None -')); 
        for (Schedule_Template__c r : [SELECT Id,Name FROM Schedule_Template__c where Media_Types__c=: MTName and Active__c=True order by Name]) 
        { 
            optionList.add(new selectOption(r.Id, r.Name));  
        }
        return optionList;
    }
 
   public Pagereference SaveCampaignJob(){
   
   try{
         if(MTName == null)
            {
                String stringMTName = Schema.Campaign_Jobs__c.fields.Media_Type__c.getDescribe().getLabel();
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR,stringMTName+' : You must select a '+stringMTName+'.'));
                return null;
            }
         if(ScheduleTemp == null)
            {
                String strSchedule = Schema.Campaign_Jobs__c.fields.Schedule_Template__c.getDescribe().getLabel();
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR,+strSchedule+' : You must select a '+strSchedule));
                return null;
            }
         
         else{
           if (Schema.sObjectType.Campaign_Jobs__c.fields.Campaign_Template__c.isCreateable()) {   
               CampJob.Campaign_Template__c=CTempId;}
           if (Schema.sObjectType.Campaign_Jobs__c.fields.Media_Type__c.isCreateable()) {   
               CampJob.Media_Type__c=MTName;}
           if (Schema.sObjectType.Campaign_Jobs__c.fields.Schedule_Template__c.isCreateable()) {   
               CampJob.Schedule_Template__c=ScheduleTemp;}
           if(Schema.sObjectType.Campaign_Jobs__c.isCreateable()){
               insert CampJob;}
          
          
         String StrCTempId=CampJob.Campaign_Template__c; 
            PageReference p;
            if(isLtng)
               p= new Pagereference('/apex/detailCampaignTemplateLightning?id='+StrCTempId);
           else
               p= new Pagereference('/apex/detailCampaignTemplate?id='+StrCTempId);
               p.setRedirect(true);
               return p;
          }
          
       }    
   
   Catch(System.DMLException e){
    ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR,''+e.getMessage()));
    return null;
   }
   
  }
  
  
   public Pagereference cancel(){
   Pagereference p;
   if(isLtng)
      p= new Pagereference('/apex/detailCampaignTemplateLightning?id='+CTempId);
     else
       p= new Pagereference('/apex/detailCampaignTemplate?id='+CTempId);
       p.setRedirect(true);
       return p;
  }
   */
}