objects/Client_Invoice__c/Client_Invoice__c.object-meta.xml
<CustomObject>
    <description>This is Client Invoice object.</description>
    <label>Client Invoice</label>
    <nameField>
        <label>Invoice #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Client Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Client_Invoice_Line_Item__c/Client_Invoice_Line_Item__c.object-meta.xml
<CustomObject>
    <description>This is Client Invoice Line Item object. It is child object of Client Invoice.</description>
    <label>Client Invoice Line Item</label>
    <nameField>
        <displayFormat>CILI-{00000}</displayFormat>
        <label>CILI</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Client Invoice Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Client_Invoice_Line_Item__c/fields/Billable_Amount__c.field-meta.xml
<CustomField>
    <fullName>Billable_Amount__c</fullName>
    <label>Billable Amount</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Currency</type>
</CustomField>

objects/Client_Invoice_Line_Item__c/fields/Client_Invoice__c.field-meta.xml
<CustomField>
    <fullName>Client_Invoice__c</fullName>
    <label>Client Invoice</label>
    <referenceTo>Client_Invoice__c</referenceTo>
    <relationshipLabel>Client Invoice Line Items</relationshipLabel>
    <relationshipName>Client_Invoice_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/Client_Invoice_Line_Item__c/fields/Equipment_Type__c.field-meta.xml
<CustomField>
    <fullName>Equipment_Type__c</fullName>
    <label>Equipment Type</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

objects/Client_Invoice_Line_Item__c/fields/Estimate_Line_Item__c.field-meta.xml
<CustomField>
    <fullName>Estimate_Line_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Estimate Line Item</label>
    <referenceTo>Estimate_Line_Items__c</referenceTo>
    <relationshipLabel>Client Invoice Line Items</relationshipLabel>
    <relationshipName>Client_Invoice_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Client_Invoice_Line_Item__c/fields/GL_Code__c.field-meta.xml
<CustomField>
    <fullName>GL_Code__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GL Description</label>
    <referenceTo>GL_Code__c</referenceTo>
    <relationshipLabel>Client Invoice Line Items</relationshipLabel>
    <relationshipName>Client_Invoice_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Client_Invoice_Line_Item__c/fields/Production_Estimate__c.field-meta.xml
<CustomField>
    <fullName>Production_Estimate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Production Estimate</label>
    <referenceTo>Production_Estimate__c</referenceTo>
    <relationshipLabel>Client Invoice Line Items</relationshipLabel>
    <relationshipName>Client_Invoice_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Client_Invoice_Line_Item__c/fields/Unit_Type__c.field-meta.xml
<CustomField>
    <fullName>Unit_Type__c</fullName>
    <formula>Text(GL_Code__r.Unit_Type__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Unit Type</label>
    <type>Text</type>
</CustomField>

objects/Estimate_Line_Items__c/Estimate_Line_Items__c.object-meta.xml
<CustomObject>
    <description>This is Estimate Line Item object.</description>
    <label>Estimate Line Item</label>
    <nameField>
        <label>Line Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Estimate Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Estimate_Line_Items__c/fields/GL_Code__c.field-meta.xml
<CustomField>
    <fullName>GL_Code__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GL Description</label>
    <referenceTo>GL_Code__c</referenceTo>
    <relationshipLabel>Line Items</relationshipLabel>
    <relationshipName>Estimate</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Estimate_Line_Items__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <label>Quantity</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

objects/Estimate_Line_Items__c/fields/Unit_Type__c.field-meta.xml
<CustomField>
    <fullName>Unit_Type__c</fullName>
    <formula>Text( GL_Code__r.Unit_Type__c )</formula>
    <label>Unit Type</label>
    <type>Text</type>
</CustomField>

objects/Estimate_Spec_Item__c/Estimate_Spec_Item__c.object-meta.xml
<CustomObject>
    <description>This is Estimate Spec Item object. It act as line items of Estimate Line Item Object.</description>
    <label>Spec  Item</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Estimate Spec Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Estimate_Spec_Item__c/fields/Estimates__c.field-meta.xml
<CustomField>
    <fullName>Estimates__c</fullName>
    <label>Estimates</label>
    <referenceTo>Estimate_Line_Items__c</referenceTo>
    <relationshipName>Estimate_Line_Item</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/GL_Code__c/GL_Code__c.object-meta.xml
<CustomObject>
    <description>GL Codes are used to build line items on our Job Cost Layouts.  The Job Cost Layouts are the Quote, Estimate, Purchase Order, and Vendor Invoice.   The line items on each of these follow similar logic.</description>
    <label>GL Code</label>
    <nameField>
        <label>Description</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GL Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/GL_Code__c/fields/GL_ID__c.field-meta.xml
<CustomField>
    <fullName>GL_ID__c</fullName>
    <description>This is GL ID field. These id&apos;s are auto generated.</description>
    <label>GL Code</label>
    <length>15</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

objects/GL_Code__c/fields/Unit_Type__c.field-meta.xml
<CustomField>
    <fullName>Unit_Type__c</fullName>
    <label>Unit Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Days</fullName>
                <default>true</default>
                <label>Days</label>
            </value>
            <value>
                <fullName>Each</fullName>
            </value>
            <value>
                <fullName>Hours</fullName>
            </value>
            <value>
                <fullName>Project</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Production_Estimate__c/Production_Estimate__c.object-meta.xml
<CustomObject>
    <description>This is Production Estimate object.</description>
    <label>Production Estimate</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Production Estimates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Production_Estimate__c/fields/Equipment_Type__c.field-meta.xml
<CustomField>
    <fullName>Equipment_Type__c</fullName>
    <label>Equipment Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Test1</fullName>
            </value>
            <value>
                <fullName>Roland</fullName>
            </value>
            <value>
                <fullName>Xerox</fullName>
            </value>
            <value>
                <fullName>Binding</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Production_Estimate__c/fields/GL_Code__c.field-meta.xml
<CustomField>
    <fullName>GL_Code__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GL Description</label>
    <referenceTo>GL_Code__c</referenceTo>
    <relationshipLabel>Production Estimates</relationshipLabel>
    <relationshipName>Production_Estimates</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Production_Estimate_Spec_Item__c/Production_Estimate_Spec_Item__c.object-meta.xml
<CustomObject>
    <description>This is Production Estimate Spec Item object. It act as line items of Production Estimate Object.</description>
    <label>Production Estimate Spec Item</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Production Estimate Spec Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Production_Estimate_Spec_Item__c/fields/Production_Estimate__c.field-meta.xml
<CustomField>
    <fullName>Production_Estimate__c</fullName>
    <label>Production Estimate</label>
    <referenceTo>Production_Estimate__c</referenceTo>
    <relationshipLabel>Production Estimate Spec Items</relationshipLabel>
    <relationshipName>Production_Estimate_Spec_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/ProductionEstimate__c/ProductionEstimate__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>This is to use Production Estimate in place of Standard Estimate &amp; New Copy Schedule Button.</description>
    <label>Job Suite Controls</label>
</CustomObject>

objects/ProductionEstimate__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This One Is for to Activate Production Estimate in place of Standard Estimate</description>
    <inlineHelpText>This One Is for to Activate Production Estimate in place of Standard Estimate</inlineHelpText>
    <label>Production Estimate Active</label>
    <type>Checkbox</type>
</CustomField>

classes/ClientInvoicePrintExtension.cls
public with sharing class ClientInvoicePrintExtension {
    
    String theID;
    public List<Client_Invoice_Line_Item__c> tempCILI{get;set;} // = new List<Client_Invoice_Line_Item__c>();
    public Map<ID,List<Estimate_Spec_Item__c>> ELI_ESI_Map = new Map<ID,List<Estimate_Spec_Item__c>>(); 
    public Set<ID> ELIIds = new Set<ID>();
    public Map<ID,List<Production_Estimate_Spec_Item__c>> PELI_ESI_Map = new Map<ID,List<Production_Estimate_Spec_Item__c>>(); 
    public Set<ID> PELIIds = new Set<ID>();
    public list<wrapper> wrapout{get;set;}
    public DateTime today{get;set;}
    public List<Document> lstDoc;
    public String imageBody{get;set;}
    public String imageURL{get;set;}
    public boolean imageNotFound{get;set;}
    Public Boolean ShowProductionEstimate{get;set;}
    // End of Global variables
    // Start constructor
    public ClientInvoicePrintExtension(ApexPages.StandardController controller)
    {
        ProductionEstimate__c  activeSettings = ProductionEstimate__c.getOrgDefaults();
        ShowProductionEstimate =activeSettings.Active__c;
        // Code to display Subsriber Organization Logo
        // If subscriber deletes the Document : JobSuite_OrganizationLogo from their Org then JobSuite App logo will be displayed
        imageURL = '/servlet/servlet.FileDownload?file='; 
        lstDoc = [Select Id, Name, Body from Document where Name =: 'JobSuite_OrganizationLogo' WITH SECURITY_ENFORCED LIMIT 1];
        if(!lstDoc.isEmpty())
        {
            String imageId =  lstDoc[0].Id;
            imageBody = imageURL+imageId;    imageNotFound = False;
        }    
        else
        {
            imageNotFound = True;
        }
        // End of code to display Subscriber Organization Logo
        wrapout = new List<Wrapper>();
        theID = ApexPages.CurrentPage().getParameters().get('id');
        tempCILI = [select id,Name,Production_Estimate__c,Equipment_Type__c,Production_Estimate__r.name,Billable_Amount__c,Estimate_Line_Item__c,Estimate_Line_Item__r.Name,GL_Code__c,Quantity__c,GL_Code_No__c,GL_Code__r.Name,Unit_Type__c,GL_Code__r.GL_ID__c,Client_Invoice__c from Client_Invoice_Line_Item__c where Client_Invoice__c  =: [Select id from Client_Invoice__c  where id =: theID] WITH SECURITY_ENFORCED Order By Name];
        setupGrouping();
        today=System.NOW();
    }
    Public class wrapper
    {
        public Client_Invoice_Line_Item__c cili{get;set;}
        public list<Wrapper2> esis{get;set;}
        public list<Wrapper3> pesis{get;set;}
        public wrapper()
        {
            if(cili == null)
            {
                cili = new Client_Invoice_Line_Item__c();
            }
            if(esis == null)
            {
                esis = new List<Wrapper2>();
            }  
            if(pesis == null)
            {
                pesis = new List<Wrapper3>();
            }   
        }
    }
    Public class wrapper2
    {
        public Estimate_Spec_Item__c esi{get;set;}
        public wrapper2()
        {
            if(esi == null)
            {
                esi = new Estimate_Spec_Item__c();
            }
        }
    }  
    Public class wrapper3
    {
        public Production_Estimate_Spec_Item__c pesi{get;set;}
        public wrapper3()
        {
            if(pesi == null)
            {
                pesi = new Production_Estimate_Spec_Item__c ();
            }
        }
    }  
    Public void setupGrouping()
    {
        for(Client_Invoice_Line_Item__c CILIRecord : tempCILI)
        {  
            if(ShowProductionEstimate){
                PELIIds.add(CILIRecord.Production_Estimate__c);
            }
            else{
                ELIIds.add(CILIRecord.Estimate_Line_Item__c);
            }
        }
        if(ShowProductionEstimate){
            for(Production_Estimate_Spec_Item__c pesiRecord : [select id,Name,Production_Estimate__c,Description__c from Production_Estimate_Spec_Item__c where Production_Estimate__c=: PELIIds WITH SECURITY_ENFORCED order by CreatedDate])
            {
                if(PELI_ESI_Map.containskey(PesiRecord.Production_Estimate__c))
                {
                    PELI_ESI_Map.get(PesiRecord.Production_Estimate__c).add(PesiRecord);
                }
                else
                {
                    PELI_ESI_Map.put(PesiRecord.Production_Estimate__c,new List<Production_Estimate_Spec_Item__c>{PesiRecord});
                } 
            }
        }
        else{
            for(Estimate_Spec_Item__c esiRecord : [select id,Name,Estimates__c,Description__c from Estimate_Spec_Item__c where Estimates__c =: ELIIds WITH SECURITY_ENFORCED order by CreatedDate])
            {
                if(ELI_ESI_Map.containskey(esiRecord.Estimates__c))
                {
                    ELI_ESI_Map.get(esiRecord.Estimates__c).add(esiRecord);
                }
                else
                {
                    ELI_ESI_Map.put(esiRecord.Estimates__c,new List<Estimate_Spec_Item__c>{esiRecord});
                } 
            }
        }
        for(Client_Invoice_Line_Item__c CILIRecord1 : tempCILI)
        {
            wrapper tmpWrapper = new wrapper();
            tmpWrapper.cili = CILIRecord1;
            List<Wrapper2> t2 = new List<Wrapper2>();
            List<Wrapper3> t3 = new List<Wrapper3>();
            if(ShowProductionEstimate){
                
                if(PELI_ESI_Map.containskey(CILIRecord1.Production_Estimate__c))
                {
                    for(Production_Estimate_Spec_Item__c esi3:PELI_ESI_Map.get(CILIRecord1.Production_Estimate__c))
                    { 
                        wrapper3 twrap3 = new Wrapper3();
                        twrap3.pesi = esi3;    t3.add(twrap3);
                    }
                }
                tmpWrapper.pesis=t3;
                wrapout.add(tmpWrapper); 
            }
            else{
                if(ELI_ESI_Map.containskey(CILIRecord1.Estimate_Line_Item__c))
                {
                    for(Estimate_Spec_Item__c esi2:ELI_ESI_Map.get(CILIRecord1.Estimate_Line_Item__c))
                    { 
                        wrapper2 twrap2 = new Wrapper2();
                        twrap2.esi = esi2;
                        t2.add(twrap2);
                    }
                }
                tmpWrapper.esis=t2;
                wrapout.add(tmpWrapper); 
                
            }
        } 
    } 
}