objects/Material_Item__c/Material_Item__c.object-meta.xml
<CustomObject>
    <description>This is Material Item object.</description>
    <label>Material Item</label>
    <nameField>
        <label>Material Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Material Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Material_Item__c/fields/Calc_Unit__c.field-meta.xml
<CustomField>
    <fullName>Calc_Unit__c</fullName>
    <label>Calc Unit</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Sheet</fullName>
            </value>
            <value>
                <fullName>Size</fullName>
            </value>
            <value>
                <fullName>Each</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Material_Order__c/Material_Order__c.object-meta.xml
<CustomObject>
    <label>Material Order</label>
    <nameField>
        <displayFormat>MO-{00000}</displayFormat>
        <label>MO#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Material Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Material_Order_Line_Item_Receipt__c/Material_Order_Line_Item_Receipt__c.object-meta.xml
<CustomObject>
    <label>Material Order Line Item Receipt</label>
    <nameField>
        <displayFormat>MOLI-{000000}</displayFormat>
        <label>Material Order Line Item Receipt Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Material Order Line Item Receipts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Material_Order_Line_Item_Receipt__c/fields/Material_Purchase_Line_Item__c.field-meta.xml
<CustomField>
    <fullName>Material_Purchase_Line_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Material Order Line Item</label>
    <referenceTo>Material_Purchase_Line_Item__c</referenceTo>
    <relationshipLabel>Material Order Line Item Receipts</relationshipLabel>
    <relationshipName>Material_Order_Line_Item_Receipts</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Material_Order_Line_Item_Receipt__c/fields/MOLI_Receipt_Date__c.field-meta.xml
<CustomField>
    <fullName>MOLI_Receipt_Date__c</fullName>
    <label>MOLI Receipt Date</label>
    <type>Date</type>
</CustomField>

objects/Material_Order_Line_Item_Receipt__c/fields/MOLI_Receipt_Qty__c.field-meta.xml
<CustomField>
    <fullName>MOLI_Receipt_Qty__c</fullName>
    <label>MOLI Receipt Qty</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

objects/Material_Order_Line_Item_Receipt__c/fields/MPLI_Receipt_Status__c.field-meta.xml
<CustomField>
    <fullName>MPLI_Receipt_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Outstanding</fullName>
            </value>
            <value>
                <fullName>Received</fullName>
                <default>true</default>
                <label>Received</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Material_Purchase_Line_Item__c/Material_Purchase_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Material Purchase Line Item</label>
    <nameField>
        <displayFormat>MPLI-{000000}</displayFormat>
        <label>Material Purchase Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Material Purchase Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Material_Purchase_Line_Item__c/fields/Calc_Unit__c.field-meta.xml
<CustomField>
    <fullName>Calc_Unit__c</fullName>
    <label>Calc Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sheet</fullName>
            </value>
            <value>
                <fullName>Size</fullName>
            </value>
            <value>
                <fullName>Each</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Material_Purchase_Line_Item__c/fields/Material_Item__c.field-meta.xml
<CustomField>
    <fullName>Material_Item__c</fullName>
    <label>Material Item</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Material_Item__c.Mt_Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Material_Item__c</referenceTo>
    <relationshipLabel>Material Purchase Line Items</relationshipLabel>
    <relationshipName>Material_Purchase_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/Material_Purchase_Line_Item__c/fields/Material_Order__c.field-meta.xml
<CustomField>
    <fullName>Material_Order__c</fullName>
    <label>Material Order</label>
    <referenceTo>Material_Order__c</referenceTo>
    <relationshipLabel>Material Purchase Line Items</relationshipLabel>
    <relationshipName>Material_Purchase_Line_Items</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/Material_Purchase_Line_Item__c/fields/MPLI_Status__c.field-meta.xml
<CustomField>
    <fullName>MPLI_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Outstanding</fullName>
            </value>
            <value>
                <fullName>Received</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Material_Purchase_Line_Item__c/fields/Qty__c.field-meta.xml
<CustomField>
    <fullName>Qty__c</fullName>
    <label>Qty Ordered</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

objects/Material_Purchase_Line_Item__c/fields/Qty_Outstanding__c.field-meta.xml
<CustomField>
    <fullName>Qty_Outstanding__c</fullName>
    <label>Qty Outstanding</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

objects/ProductionEstimate__c/ProductionEstimate__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>This is to use Production Estimate in place of Standard Estimate &amp; New Copy Schedule Button.</description>
    <label>Job Suite Controls</label>
</CustomObject>

objects/ProductionEstimate__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This One Is for to Activate Production Estimate in place of Standard Estimate</description>
    <inlineHelpText>This One Is for to Activate Production Estimate in place of Standard Estimate</inlineHelpText>
    <label>Production Estimate Active</label>
    <type>Checkbox</type>
</CustomField>

classes/Print_MO_Apexclass.cls
public class Print_MO_Apexclass {
    
    public String imageBody{get;set;}
    public String imageURL{get;set;}
    public boolean imageNotFound{get;set;}
    public List<Document> lstDoc;
    Public Boolean ShowProductionEstimate{get;set;}
    public list<Material_Purchase_Line_Item__c> molircds{get;set;}
    public list<Material_Order_Line_Item_Receipt__c>moliReceiptrcds{get;set;}
    String MOid;
    
    
    public Print_MO_Apexclass(ApexPages.StandardController controller){
        ProductionEstimate__c  activeSettings = ProductionEstimate__c.getOrgDefaults();
        ShowProductionEstimate =activeSettings.Active__c;
        
        // Code to display Subsriber Organization Logo
        
        // If subscriber deletes the Document : JobSuite_OrganizationLogo from their Org then JobSuite App logo will be displayed
        
        imageURL = '/servlet/servlet.FileDownload?file='; 
        lstDoc = [Select Id, Name, Body from Document where Name =: 'JobSuite_OrganizationLogo' WITH SECURITY_ENFORCED LIMIT 1];
        if(!lstDoc.isEmpty())
        {
            String imageId =  lstDoc[0].Id;
            imageBody = imageURL+imageId; 
            imageNotFound = False;
        }    
        else
        {
            imageNotFound = True;
        }
        
        MOid = ApexPages.currentpage().getParameters().get('id');
        
        molircds =   [select id,name,Material_Item__c, Material_Item__r.name,Material_Order__c, Material_Order__r.name,MPLI_Status__c, Calc_Unit__c,Qty__c,Qty_Outstanding__c from Material_Purchase_Line_Item__c where Material_Order__c =: MOid WITH SECURITY_ENFORCED Order By CreatedDate desc];
        
        moliReceiptrcds =[select id,name,Material_Purchase_Line_Item__c,Material_Purchase_Line_Item__r.name,MOLI_Receipt_Date__c,MOLI_Receipt_Qty__c,MPLI_Receipt_Status__c from Material_Order_Line_Item_Receipt__c where Material_Purchase_Line_Item__c =: molircds WITH SECURITY_ENFORCED Order By CreatedDate desc];   
        
    }
    
}