objects/Material_Item__c/Material_Item__c.object-meta.xml
<CustomObject>
    <description>This is Material Item object.</description>
    <label>Material Item</label>
    <nameField>
        <label>Material Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Material Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Material_Item__c/fields/Calc_Unit__c.field-meta.xml
<CustomField>
    <fullName>Calc_Unit__c</fullName>
    <label>Calc Unit</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Sheet</fullName>
            </value>
            <value>
                <fullName>Size</fullName>
            </value>
            <value>
                <fullName>Each</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Material_Item__c/fields/Case_Pack__c.field-meta.xml
<CustomField>
    <fullName>Case_Pack__c</fullName>
    <label>Case Pack</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

objects/Material_Item__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

objects/Material_Item__c/fields/Qty_On_Hand__c.field-meta.xml
<CustomField>
    <fullName>Qty_On_Hand__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Qty On Hand</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

objects/Material_Item__c/fields/Roll_LF__c.field-meta.xml
<CustomField>
    <fullName>Roll_LF__c</fullName>
    <formula>Length_inches__c  / 12</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Roll LF</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

objects/Material_Item__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Item Category</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Test</fullName>
            </value>
            <value>
                <fullName>CNG</fullName>
            </value>
            <value>
                <fullName>Banners</fullName>
            </value>
            <value>
                <fullName>Forms</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Material_Item__c/recordTypes/Sheet.recordType-meta.xml
<RecordType>
    <fullName>Sheet</fullName>
    <active>true</active>
    <label>Sheet</label>
</RecordType>

objects/Material_Item__c/recordTypes/Size.recordType-meta.xml
<RecordType>
    <fullName>Size</fullName>
    <active>true</active>
    <label>Size</label>
</RecordType>

objects/Material_Usage_line_item__c/Material_Usage_line_item__c.object-meta.xml
<CustomObject>
    <description>This  Material Usage line item  object is child object of Material Item object</description>
    <label>Material Usage line item</label>
    <nameField>
        <displayFormat>MULI-{00000}</displayFormat>
        <label>MULI#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Material Usage line items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Material_Usage_line_item__c/fields/Credit__c.field-meta.xml
<CustomField>
    <fullName>Credit__c</fullName>
    <label>Credit</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

objects/Material_Usage_line_item__c/fields/Debit__c.field-meta.xml
<CustomField>
    <fullName>Debit__c</fullName>
    <label>Debit</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

objects/Material_Usage_line_item__c/fields/Material_Item__c.field-meta.xml
<CustomField>
    <fullName>Material_Item__c</fullName>
    <label>Material Item</label>
    <referenceTo>Material_Item__c</referenceTo>
    <relationshipLabel>Material Usage line items</relationshipLabel>
    <relationshipName>Material_Usage_line_items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/Material_Usage_line_item__c/fields/Qty_On_Hand__c.field-meta.xml
<CustomField>
    <fullName>Qty_On_Hand__c</fullName>
    <label>Qty On Hand</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

objects/Material_Usage_line_item__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Reconciliation</fullName>
            </value>
            <value>
                <fullName>Job</fullName>
            </value>
            <value>
                <fullName>Purchase</fullName>
                <default>true</default>
                <label>Purchase</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

classes/CreateMaterialUsageExtension.cls
public with sharing class CreateMaterialUsageExtension {

   /* public boolean isLtng{private set; get{
                                            String theme = UserInfo.getUITheme();
                                            return (theme=='Theme4d')?true:false;
                                          }
                            }  
    
    private final Material_Usage_line_item__c mu;
    public Material_Usage_line_item__c muc{get;set;}
    public String Materialid{get;set;}
    public String MaterialName{get;set;}
    public Material_Item__c objMaterial{get;set;}

    // Start Constructor
    public CreateMaterialUsageExtension (ApexPages.StandardController controller) {
        
        this.mu=(Material_Usage_line_item__c )controller.getRecord();
        
        Materialid=ApexPages.CurrentPage().getParameters().get('materialid');
        
        
        objMaterial=[Select id,name ,Qty_On_Hand__c,Calc_Unit__c,Case_Pack__c,Roll_LF__c,(select id,name from Material_Usage_line_items__r ) from Material_Item__c  where id=:Materialid];
        
        if(objMaterial.Material_Usage_line_items__r.size()>0){
            muc =[Select id,name,Qty_On_Hand__c,Date__c,Credit__c,Debit__c,Description__c,Type__c  from Material_Usage_line_item__c  where Material_Item__c=:objMaterial.id Order by Createddate DESC, Qty_On_Hand__c limit 1];
        }
        
        
        MaterialName=objMaterial.Name;
        mu.Material_Item__c = Materialid;
        
    }
    
    
    // Save Method
    public PageReference saveme() 
    { 
        
        integer qtyonhand;
        if(objMaterial.Material_Usage_line_items__r.size()> 0){
            qtyonhand=integer.valueof(muc.Qty_On_Hand__c);
            
        }
        
        else{ 
        qtyonhand=0;
        }
        
        
        string strciId;        
        try
        {  
            
            if(objMaterial.Calc_Unit__c=='Size'){
                
                if(schema.SobjectType.Material_Usage_line_item__c.Fields.Material_Item__c.isCreateable()){
                    mu.Material_Item__c =Materialid;
                }
                
                if(schema.SobjectType.Material_Usage_line_item__c.Fields.Qty_On_Hand__c.isCreateable()){ 
                    mu.Qty_On_Hand__c= (qtyonhand +(mu.Credit__c != null ? mu.Credit__c * objMaterial.Roll_LF__c : 0))- (mu.Debit__c != null ? mu.Debit__c * objMaterial.Roll_LF__c : 0);
                }
                
                if(schema.SobjectType.Material_Item__c.Fields.Qty_On_Hand__c.isUpdateable()){
                    objMaterial.Qty_On_Hand__c=(qtyonhand +(mu.Credit__c != null ? mu.Credit__c * objMaterial.Roll_LF__c: 0))- (mu.Debit__c != null ? mu.Debit__c * objMaterial.Roll_LF__c: 0);
                }
                if(schema.SobjectType.Material_Usage_line_item__c.Fields.Credit__c.isCreateable()){ 
                    mu.Credit__c=(mu.Credit__c != null ? mu.Credit__c * objMaterial.Roll_LF__c : 0);
                }
                if(schema.SobjectType.Material_Usage_line_item__c.Fields.Debit__c.isCreateable()){ 
                    mu.Debit__c=(mu.Debit__c != null ? mu.Debit__c * objMaterial.Roll_LF__c: 0);
                }
                if(Schema.sObjectType.Material_Usage_line_item__c.isCreateable()){
                    insert mu;
                }
                
                if(Schema.sObjectType.Material_Item__c.isUpdateable()) {
                    update objMaterial;
                }
                
            }
            
            else if(objMaterial.Calc_Unit__c =='Sheet')
                
            {
               if(schema.SobjectType.Material_Usage_line_item__c.Fields.Material_Item__c.isCreateable()){
                    mu.Material_Item__c =Materialid;
                }
                if(schema.SobjectType.Material_Usage_line_item__c.Fields.Qty_On_Hand__c.isCreateable()){
                    mu.Qty_On_Hand__c= (qtyonhand +(mu.Credit__c != null ? mu.Credit__c * objMaterial.Case_Pack__c: 0))- (mu.Debit__c != null ? mu.Debit__c * objMaterial.Case_Pack__c: 0);
                }
                if(schema.SobjectType.Material_Item__c.Fields.Qty_On_Hand__c.isUpdateable()){
                    objMaterial.Qty_On_Hand__c=(qtyonhand +(mu.Credit__c != null ? mu.Credit__c * objMaterial.Case_Pack__c: 0))- (mu.Debit__c != null ? mu.Debit__c * objMaterial.Case_Pack__c: 0);
                }
                
                if(schema.SobjectType.Material_Usage_line_item__c.Fields.Credit__c.isCreateable()){
                    mu.Credit__c=(mu.Credit__c != null ? mu.Credit__c * objMaterial.Case_Pack__c : 0);
                }
                if(schema.SobjectType.Material_Usage_line_item__c.Fields.Debit__c.isCreateable()){
                    mu.Debit__c=(mu.Debit__c != null ? mu.Debit__c * objMaterial.Case_Pack__c: 0);
                }
                if(Schema.sObjectType.Material_Usage_line_item__c.isCreateable()){
                    insert mu;
                }
                if(Schema.sObjectType.Material_Item__c.isUpdateable()) {
                    update objMaterial;
                }
                
            }
            
            else{
                if(schema.SobjectType.Material_Usage_line_item__c.Fields.Material_Item__c.isCreateable()){
                    mu.Material_Item__c =Materialid;
                }
                if(schema.SobjectType.Material_Usage_line_item__c.Fields.Qty_On_Hand__c.isCreateable()){
                    mu.Qty_On_Hand__c= (qtyonhand +(mu.Credit__c != null ? mu.Credit__c : 0))- (mu.Debit__c != null ? mu.Debit__c : 0);
                }
                if(Schema.sObjectType.Material_Usage_line_item__c.isCreateable()){
                    insert mu;
                }
                
                if(schema.SobjectType.Material_Item__c.Fields.Qty_On_Hand__c.isUpdateable()){
                    objMaterial.Qty_On_Hand__c=(qtyonhand +(mu.Credit__c != null ? mu.Credit__c : 0))- (mu.Debit__c != null ? mu.Debit__c : 0);
                }
                if(Schema.sObjectType.Material_Item__c.isUpdateable()) {
                    update objMaterial;
                }
                
            } 
            
        }
        catch(DMLException e){ return null;}
        
        
        PageReference p;   
        if(isLtng)
        {
            p= new Pagereference('/apex/MaterialLineDetailPageLightning?id='+Materialid+'&section=MU');
        }
        
        else
        {
            p= new Pagereference('/apex/MaterialLineDetailPage?id='+Materialid);
        }   
        
        
        
        //   PageReference pageRef = new PageReference('/apex/MaterialLineDetailPage?id='+Materialid);
        p.setRedirect(true);
        return p;
        
        
    }
    // End of Save Method
    
    // Cancel Method
    Public PageReference cancelme()
    {       
        
        PageReference p;   
        if(isLtng)
        {
            p= new Pagereference('/apex/MaterialLineDetailPageLightning?id='+Materialid+'&section=MU');
        }
        
        else
        {
            p= new Pagereference('/apex/MaterialLineDetailPage?id='+Materialid);
        }   
        
        
        // PageReference p =  new Pagereference('/apex/MaterialLineDetailPage?id='+Materialid);
        p.setRedirect(true);
        return p;   
        
    }*/
    // Cancel Method        
     
}