objects/Material_Item__c/Material_Item__c.object-meta.xml
<CustomObject>
    <description>This is Material Item object.</description>
    <label>Material Item</label>
    <nameField>
        <label>Material Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Material Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Material_Item__c/fields/Calc_Unit__c.field-meta.xml
<CustomField>
    <fullName>Calc_Unit__c</fullName>
    <label>Calc Unit</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Sheet</fullName>
            </value>
            <value>
                <fullName>Size</fullName>
            </value>
            <value>
                <fullName>Each</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Material_Item__c/recordTypes/Size.recordType-meta.xml
<RecordType>
    <fullName>Size</fullName>
    <active>true</active>
    <label>Size</label>
</RecordType>

classes/TestMIAttachmentExtensions.cls
//@isTest
public class TestMIAttachmentExtensions {
	/* static testMethod void TestMIAttachmentExtensions()
        {
             
          Material_Item__c  testI=new Material_Item__c (name='test 123',Calc_Unit__c ='Size');
  		  insert testI;
               
               ApexPages.StandardController con=new ApexPages.StandardController(testI);
                   
               ApexPages.currentPage().getParameters().put('Id', testI.Id);
               
               // Instantiate the extention instance with the standard controller 
               MIAttachmentExtensions ext= new MIAttachmentExtensions(con);
               
               test.startTest();
               
               ext.getmyfile();
               
               // Invoke the primary method on the extension   
               Pagereference pg=ext.SaveDoc();
               
               Pagereference pg1=ext.cancelme();
               
               Material_Item__c obj1=[Select id,name from Material_Item__c where Name=: 'test 123'];
               obj1.name='Test 234';
               update obj1;
         
               Material_Item__c obj2=[Select id from Material_Item__c where Name=: 'Test 234'];
               delete obj2;
               pg=ext.SaveDoc();
               
               test.stopTest();
        }*/
    /* End of Test Coverage*/
}