objects/Material_Item__c/Material_Item__c.object-meta.xml
<CustomObject>
    <description>This is Material Item object.</description>
    <label>Material Item</label>
    <nameField>
        <label>Material Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Material Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Material_Item__c/fields/Calc_Unit__c.field-meta.xml
<CustomField>
    <fullName>Calc_Unit__c</fullName>
    <label>Calc Unit</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Sheet</fullName>
            </value>
            <value>
                <fullName>Size</fullName>
            </value>
            <value>
                <fullName>Each</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Material_Item__c/recordTypes/Size.recordType-meta.xml
<RecordType>
    <fullName>Size</fullName>
    <active>true</active>
    <label>Size</label>
</RecordType>

classes/TestEditMIAttachmentExtension.cls
//@isTest
public class TestEditMIAttachmentExtension {
	// Start Test Coverage
   /*  static testMethod void TestEditMIAttachmentExtension()
    {
          Material_Item__c  testI=new Material_Item__c (name='test 123',Calc_Unit__c ='Size');
  		  insert testI;
               
          System.assertEquals('test 123',testI.Name); 
        
               Blob b = Blob.valueOf('Hello World');
               

               Attachment a=new Attachment(parentId=testI.Id,Name='Test File',Body=b);
               insert a;
               
               ApexPages.currentPage().getParameters().put('Id', a.Id);
            
               // Instantiate the standard controller with the Attachment 
               ApexPages.StandardController con=new ApexPages.StandardController(a);
        
               // Instantiate the extention instance with the standardcontroller 
               EditJobAttachmentExtension ext=new EditJobAttachmentExtension(con);
        
               // Invoke the primary method on the extension
               ApexPages.PageReference result=ext.SaveAttachment();
        
               ApexPages.currentPage().getParameters().put('Id', a.Id);
            
               // Instantiate the standard controller with the Job 
               ApexPages.StandardController con1=new ApexPages.StandardController(a);
        
              // Instantiate the extention instance with the standardcontroller 
              EditMIAttachmentExtension ext1=new EditMIAttachmentExtension(con1);
        
              // Invoke the primary method on the extension
                result=ext1.cancelme();
        
                delete a;
                result=ext1.SaveAttachment();
        
        	EditMaterialItemSwitchExt ext2=new EditMaterialItemSwitchExt(con1);
        
        
           }*/
    // End of Test Coverage
}