objects/Material_Item__c/Material_Item__c.object-meta.xml
<CustomObject>
    <description>This is Material Item object.</description>
    <label>Material Item</label>
    <nameField>
        <label>Material Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Material Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Material_Item__c/fields/Qty_On_Hand__c.field-meta.xml
<CustomField>
    <fullName>Qty_On_Hand__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Qty On Hand</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

objects/Material_Usage_line_item__c/Material_Usage_line_item__c.object-meta.xml
<CustomObject>
    <description>This  Material Usage line item  object is child object of Material Item object</description>
    <label>Material Usage line item</label>
    <nameField>
        <displayFormat>MULI-{00000}</displayFormat>
        <label>MULI#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Material Usage line items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Material_Usage_line_item__c/fields/Material_Item__c.field-meta.xml
<CustomField>
    <fullName>Material_Item__c</fullName>
    <label>Material Item</label>
    <referenceTo>Material_Item__c</referenceTo>
    <relationshipLabel>Material Usage line items</relationshipLabel>
    <relationshipName>Material_Usage_line_items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/Material_Usage_line_item__c/fields/Qty_On_Hand__c.field-meta.xml
<CustomField>
    <fullName>Qty_On_Hand__c</fullName>
    <label>Qty On Hand</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

classes/TestDisplayMaterialUsageController.cls
//@isTest
Public class TestDisplayMaterialUsageController{

/*Static testMethod void TestDisplayMaterialUsageController()
     {
            Material_Item__c  testI=new Material_Item__c (name='test 123');
            insert testI;
            Material_Usage_line_item__c  Tmuli= new Material_Usage_line_item__c (Material_Item__c=testI.id,Qty_On_Hand__c=100);
            insert Tmuli;
                    
            ApexPages.currentPage().getParameters().put('id',testI.Id);
         // Instantiate the extention instance with the Custom Controller
           DisplayMaterialUsageController ext1=new DisplayMaterialUsageController ();
          
            // Invoke the primary method on the extension
           ApexPages.PageReference result1=ext1.createMU();
           
           ext1.strMU = Tmuli.Id;
           result1 = ext1.deleteMU();
      } 
     // End of test Method


*/
}