objects/Purchase_Order__c/Purchase_Order__c.object-meta.xml
<CustomObject>
    <description>This is Purchase Order object.</description>
    <label>Purchase Order</label>
    <nameField>
        <label>PO #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Purchase Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Purchase_Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Cancelled</fullName>
                <color>#0B6FCE</color>
                <label>Cancelled</label>
            </value>
            <value>
                <fullName>Open</fullName>
                <color>#78C953</color>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Pending</fullName>
                <color>#E27001</color>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Sent</fullName>
                <color>#A845DC</color>
                <label>Sent</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

classes/PODetailPageExtension.cls
// This class is used to display PO Detail page
public with sharing class PODetailPageExtension 
{
    // Global variables
    public List<Purchase_Order__c> po{get;set;} 
    String theID;
    // End of Global variables
    
    // Start Constructor
    public PODetailPageExtension(ApexPages.StandardController controller) 
    {
         theID = ApexPages.CurrentPage().getParameters().get('id');
         po=[select id,Name,Status__c from Purchase_Order__c where id =: theID AND Status__c = 'Sent'];
         //  po=[select id,Name,Status__c from Purchase_Order__c where id =: theID];
    }
    // End of Constructor
     
    // Test Method 
  static testMethod void PODetail()
    {
       Purchase_Order__c PO = new Purchase_Order__c();
       ApexPages.StandardController con=new ApexPages.StandardController(PO);
       PODetailPageExtension ext=new PODetailPageExtension(con);
       System.assertEquals(PO.id,ext.theID);
    } 
 // End of test Method
} // End of Class