objects/Client__c/Client__c.object-meta.xml
<CustomObject>
    <description>This is custom Client object used for Jobsuite application.</description>
    <label>Client</label>
    <nameField>
        <label>Client Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Job__c/Job__c.object-meta.xml
<CustomObject>
    <description>This is Job object.</description>
    <label>Job</label>
    <nameField>
        <label>Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Job__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Not using currently. Instead created a custom object Client.</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Job__c/fields/Flag__c.field-meta.xml
<CustomField>
    <fullName>Flag__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This is flag field to check import process.</description>
    <label>Flag</label>
    <type>Checkbox</type>
</CustomField>

objects/Job__c/fields/Job_Auto_Number__c.field-meta.xml
<CustomField>
    <fullName>Job_Auto_Number__c</fullName>
    <defaultValue>&quot;Auto Fill&quot;</defaultValue>
    <externalId>true</externalId>
    <label>Job #</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

objects/Job__c/fields/JS_Client__c.field-meta.xml
<CustomField>
    <fullName>JS_Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Job is associated with Client object.</description>
    <label>Client</label>
    <referenceTo>Client__c</referenceTo>
    <relationshipName>Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Job__c/fields/Media_Types__c.field-meta.xml
<CustomField>
    <fullName>Media_Types__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Media Type</label>
    <referenceTo>Media_Type__c</referenceTo>
    <relationshipName>Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Job__c/fields/Schedule_Template__c.field-meta.xml
<CustomField>
    <fullName>Schedule_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Schedule Template</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Schedule_Template__c.Media_Types__c</field>
            <operation>equals</operation>
            <valueField>$Source.Media_Types__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Schedule_Template__c</referenceTo>
    <relationshipName>Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Job__c/fields/Specification_Template__c.field-meta.xml
<CustomField>
    <fullName>Specification_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Creative Brief Template</label>
    <referenceTo>Specification_Template__c</referenceTo>
    <relationshipName>Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Job__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Requested</fullName>
                <default>true</default>
                <label>Requested</label>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Job_Number_Setting__c/Job_Number_Setting__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This is Job Auto Number setting to set the Job Number format.</description>
    <label>Job Number</label>
</CustomObject>

objects/Job_Task__c/Job_Task__c.object-meta.xml
<CustomObject>
    <description>This is Job Task object. Also known as Schedule.</description>
    <label>Job Task</label>
    <nameField>
        <label>Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Job_Task__c/fields/Assigned_Users__c.field-meta.xml
<CustomField>
    <fullName>Assigned_Users__c</fullName>
    <label>Staff</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

objects/Job_Task__c/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <label>Job Name</label>
    <referenceTo>Job__c</referenceTo>
    <relationshipName>Job_Task</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/Job_Task__c/fields/Revised_Due_Date__c.field-meta.xml
<CustomField>
    <fullName>Revised_Due_Date__c</fullName>
    <label>Final Due Date</label>
    <type>Date</type>
</CustomField>

objects/Job_Task__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Requested</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Job_Task_Role__c/Job_Task_Role__c.object-meta.xml
<CustomObject>
    <description>Staff assigned to the Job Tasks.</description>
    <label>Task Staff Assigned</label>
    <nameField>
        <label>Role</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Task Staff Assigned</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Job_Task_Role__c/fields/Job_Task__c.field-meta.xml
<CustomField>
    <fullName>Job_Task__c</fullName>
    <label>Job Task</label>
    <referenceTo>Job_Task__c</referenceTo>
    <relationshipName>Job_Task_Roles</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/Media_Type__c/Media_Type__c.object-meta.xml
<CustomObject>
    <description>This is Media Type object.</description>
    <label>Media Type</label>
    <nameField>
        <label>Media Type</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Media Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Schedule_Template__c/Schedule_Template__c.object-meta.xml
<CustomObject>
    <description>This is Schedule Template object.</description>
    <label>Schedule Template</label>
    <nameField>
        <label>Schedule Template</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Schedule Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Schedule_Template__c/fields/Media_Types__c.field-meta.xml
<CustomField>
    <fullName>Media_Types__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Media Type</label>
    <referenceTo>Media_Type__c</referenceTo>
    <relationshipLabel>Schedule Templates</relationshipLabel>
    <relationshipName>Schedule_Templates</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Specification_Template__c/Specification_Template__c.object-meta.xml
<CustomObject>
    <description>This is Creative Brief Template object. Also known as Specification Template.</description>
    <label>Creative Brief Template</label>
    <nameField>
        <label>Creative Brief Template</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Creative Brief Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Staff__c/Staff__c.object-meta.xml
<CustomObject>
    <description>This is Staff object.</description>
    <label>Staff</label>
    <nameField>
        <label>Staff Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Staff</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Staff__c/fields/Username__c.field-meta.xml
<CustomField>
    <fullName>Username__c</fullName>
    <label>Username</label>
    <type>Email</type>
</CustomField>

classes/DisplayCalendarFilterByStaffExtension.cls
// This class is used to display tasks in Calendar for selected Staff
public with sharing class DisplayCalendarFilterByStaffExtension {
/*
    // Global variables
    public JsonObject json{get;set;}
    public List<Job_Task__c> lstJT{get;set;}
    public List<Job_Task_Role__c> lstJTR{get;set;}
    public List<Job__c> lstJob{get;set;}
    public String jsonString{get;set;}
    public String strStaff{get;set;}
    public String strCampaignId{get;set;}
    Set<Id> stJobId=new Set<Id>();
    Set<Id> stJobTaskId=new Set<Id>();
    Set<Id> stJobTaskRoleId=new Set<Id>();
    public List<Job_Task__c> lstJT1{get;set;}
    public Id staffId{get;set;}
    public List<Document> lstDoc;
    public String imageBody{get;set;}
    public String imageURL{get;set;}
    public boolean imageNotFound{get;set;}
    // End of Global variables
    
    // Start Constructor 
    public DisplayCalendarFilterByStaffExtension(ApexPages.StandardController controller)
    {
        // Code to display Subsriber Organization Logo

        // If subscriber deletes the Document : JobSuite_OrganizationLogo from their Org then JobSuite App logo will be displayed
        imageURL = '/servlet/servlet.FileDownload?file='; 
        lstDoc = [Select Id, Name, Body from Document where Name =: 'JobSuite_OrganizationLogo' LIMIT 1];
        if(!lstDoc.isEmpty())
        {
           String imageId =  lstDoc[0].Id;
           imageBody = imageURL+imageId; 
           imageNotFound = False;
        }    
        else
        {
           imageNotFound = True;
        }

        // End of code to display Subscriber Organization Logo 
        
       staffId=ApexPages.CurrentPage().getParameters().get('id');
       
       // Retrieve Active Jobs
       lstJob=[Select Id,Name from Job__c where Status__c=: 'Active'];
       for(Job__c j:lstJob)
       {
           stJobId.add(j.id);
       }
       // Retrieve Active Tasks of Active Jobs
       lstJT=[Select Id,Name,Revised_Due_Date__c,Assigned_Users__c,Status__c,Job__c,Job__r.Name from Job_Task__c where Job__c in : stJobId and Status__c=:'Active' Order By Name];
       
       for(Job_Task__c jt: lstJT)
       {
           stJobTaskId.add(jt.id);
       } 
       
       Staff__c s=[Select Id,Name from Staff__c where Id=: staffId];
       strStaff=s.Name;
       System.debug('Select Role : '+strStaff);
       lstJTR=[Select Id,Job_Task__r.Name,Job_Task__c from Job_Task_Role__c where Job_Task__c IN : stJobTaskId and User__c =: strStaff];
       
       for(Job_Task_Role__c jtr:lstJTR)
       {
           stJobTaskRoleId.add(jtr.Job_Task__c);
       }
        lstJT1=[Select Id,Name,Revised_Due_Date__c,Assigned_Users__c,Status__c,Job__c,Job__r.Name from Job_Task__c where id In: stJobTaskRoleId and Status__c=:'Active' Order By Name];
        json=new JsonObject();
        List<JSONObject.Value> values=new List<JSONObject.value>();
        
        if(!lstJT1.isEmpty())
        {
            for(Job_Task__c c:lstJT1)
            {
                try
                {
                    JSONObject cjson=new JSONObject();        
                    cjson.putOpt('"id"', new JSONObject.value(c.Id));
                    String str=c.Id;
                    
                    //Code added for double quotes escape
                    String strJobName = c.Job__r.Name;
                    String strTaskName = c.Name;
                    if(strJobName.contains('"'))
                    {
                     strJobName = strJobName.replaceAll('"','\'');
                     System.debug('The job name contains the double quotes :: '+ strJobName );
                    }
                    if(strTaskName.contains('"'))
                    {
                        strTaskName = strTaskName.replaceAll('"','\'');
                    }
                    
                    // end of added code
                    
                    String str1=strJobName+' : '+strTaskName;
                    cjson.putOpt('"title"',new JSONObject.value(str1));
                    cjson.putOpt('"staff"',new JSONObject.value(c.Assigned_Users__c));
                    cjson.putOpt('"status"',new JSONObject.value(c.Status__c));
                    
                    //cjson.putOpt('"job"',new JSONObject.value(c.Job__r.Name));
                    cjson.putOpt('"job"',new JSONObject.value(strJobName));
                    
                    Datetime dt1 = datetime.newInstance(c.Revised_Due_Date__c.year(), c.Revised_Due_Date__c.month(),c.Revised_Due_Date__c.day());
                    Long startDateTime = dt1.getTime()/1000;
                    cjson.putOpt('"start"', new JSONObject.value(startDateTime.intValue()));
                    values.add(new JSONObject.value(cjson));
                }
                catch(Exception e)
                {
                   
                }
            }
        }
        else
        {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Info, 'This Staff has no Tasks to display on Calendar'));
        }
        // Prepare JSONString to display it into Calendar
        json.putOpt('events', new JSONObject.value(values));
        System.debug('Json Value :'+json);
        jsonString = json.ValuetoString();
        jsonString = jsonString.replace('{events: [' , '[');
        jsonString = jsonString.replace('}]}' , '}]');
        System.debug('My Json String is'+jsonString);
    }
    // End Constructor

    // Method called on handle Cancel button
    public Pagereference cancel()
    {
        Pagereference p=new Pagereference('/apex/StaffDetailPage?id='+staffId);
        p.setRedirect(true);
        return p;    
    }
    // End Cancel method

    // Start Test Coverage Code
        static testMethod void Test_DisplayCalendarFilterByStaffExtension()
        {
            Job_Number_Setting__c customSetting1006 = new  Job_Number_Setting__c(Name= 'NO');

            insert customSetting1006;
            
            Media_Type__c testMedia=new Media_Type__c(Name='Test Media 806');
             
                 insert testMedia;
             
            Schedule_Template__c testST=new Schedule_Template__c(Name='Test Schedule Template 806',Media_Types__c=testMedia.Id);
             
                 insert testST;
                 
            Specification_Template__c testSpec=new Specification_Template__c(Name='Testing Spcification Template 806');
            
                 insert testSpec;
                
            Client__c testClient=new Client__c(Name='Test Client 806');
         
                  insert testClient;      
                
           Job__c testJob1=new Job__c(Name='Test Job 806',Job_Auto_Number__c = 'J 806', Flag__c = True ,Start_Date__c=System.Today(),Media_Types__c=testMedia.Id,Schedule_Template__c=testST.Id,Specification_Template__c=testSpec.Id,JS_Client__c=testClient.id,Status__c='Active');
         
                 insert testJob1;
                 
           System.assertEquals('Test Job 806',testJob1.Name);       
                 
           Job_Task__c testJT=new Job_Task__c(Name='Test Job Task 806',Status__c='Active',Job__c=testJob1.id,Revised_Due_Date__c=System.Today());

                 insert testJT;        
                 
           Job_Task_Role__c testJTR=new Job_Task_Role__c(Name='Designer',User__c='Ajay Kumar',Job_Task__c=testJT.id);
         
                 insert testJTR;        
                 
          Staff__c testStaff=new Staff__c(First_Name__c='Ajay',Last_Name__c='Kumar',Name='Ajay Kumar',UserName__c='test@test.com');
                 insert testStaff;
                 
          ApexPages.currentPage().getParameters().put('id',testStaff.Id);
          
          // Instantiate the standard controller with the Staff
          ApexPages.StandardController con=new ApexPages.standardController(testStaff);
          
           // Instantiate the extention instance with the standardcontroller
          DisplayCalendarFilterByStaffExtension ext=new DisplayCalendarFilterByStaffExtension(con);
          
          // Invoke the primary method on the extension
          ApexPages.Pagereference result1=ext.cancel();
         
         Staff__c testStaff1=new Staff__c(First_Name__c='Test',Last_Name__c='User 806',Name='Test User 806',UserName__c='test@test1.com');
             insert testStaff1;
         
         ApexPages.currentPage().getParameters().put('id',testStaff1.Id);
         
         // Instantiate the standard controller with the Staff
         ApexPages.StandardController con1=new ApexPages.standardController(testStaff1);
         
          // Instantiate the extention instance with the standardcontroller
         DisplayCalendarFilterByStaffExtension ext1=new DisplayCalendarFilterByStaffExtension(con1);
        }*/
    // End Test Coverage
}
// End of Class