objects/Client__c/Client__c.object-meta.xml
<CustomObject>
    <description>This is custom Client object used for Jobsuite application.</description>
    <label>Client</label>
    <nameField>
        <label>Client Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Estimate_Line_Items__c/Estimate_Line_Items__c.object-meta.xml
<CustomObject>
    <description>This is Estimate Line Item object.</description>
    <label>Estimate Line Item</label>
    <nameField>
        <label>Line Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Estimate Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Estimate_Line_Items__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Unit Cost</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

objects/Estimate_Line_Items__c/fields/GL_Code__c.field-meta.xml
<CustomField>
    <fullName>GL_Code__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GL Description</label>
    <referenceTo>GL_Code__c</referenceTo>
    <relationshipLabel>Line Items</relationshipLabel>
    <relationshipName>Estimate</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Estimate_Line_Items__c/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <label>Job Name</label>
    <referenceTo>Job__c</referenceTo>
    <relationshipLabel>Line Items</relationshipLabel>
    <relationshipName>Estimate</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/Estimate_Line_Items__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <label>Quantity</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

objects/Estimate_Line_Items__c/fields/Shippment_status__c.field-meta.xml
<CustomField>
    <fullName>Shippment_status__c</fullName>
    <label>Shipment status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Ready to be shipped</fullName>
            </value>
            <value>
                <fullName>Shipped</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Estimate_Line_Items__c/fields/Total_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Amount__c</fullName>
    <formula>IF( Unit_Type__c =&quot;Project&quot;, Amount__c , (Amount__c  *   Quantity__c ))</formula>
    <label>Total Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

objects/Estimate_Line_Items__c/fields/Vendor__c.field-meta.xml
<CustomField>
    <fullName>Vendor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vendor</label>
    <referenceTo>Vendor__c</referenceTo>
    <relationshipLabel>Estimate Line Items</relationshipLabel>
    <relationshipName>Estimate</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/GL_Code__c/GL_Code__c.object-meta.xml
<CustomObject>
    <description>GL Codes are used to build line items on our Job Cost Layouts.  The Job Cost Layouts are the Quote, Estimate, Purchase Order, and Vendor Invoice.   The line items on each of these follow similar logic.</description>
    <label>GL Code</label>
    <nameField>
        <label>Description</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GL Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Job__c/Job__c.object-meta.xml
<CustomObject>
    <description>This is Job object.</description>
    <label>Job</label>
    <nameField>
        <label>Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Job__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Not using currently. Instead created a custom object Client.</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Job__c/fields/Job_Auto_Number__c.field-meta.xml
<CustomField>
    <fullName>Job_Auto_Number__c</fullName>
    <defaultValue>&quot;Auto Fill&quot;</defaultValue>
    <externalId>true</externalId>
    <label>Job #</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

objects/Job__c/fields/JS_Client__c.field-meta.xml
<CustomField>
    <fullName>JS_Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Job is associated with Client object.</description>
    <label>Client</label>
    <referenceTo>Client__c</referenceTo>
    <relationshipName>Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Job__c/fields/Media_Types__c.field-meta.xml
<CustomField>
    <fullName>Media_Types__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Media Type</label>
    <referenceTo>Media_Type__c</referenceTo>
    <relationshipName>Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Job__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Requested</fullName>
                <default>true</default>
                <label>Requested</label>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Media_Type__c/Media_Type__c.object-meta.xml
<CustomObject>
    <description>This is Media Type object.</description>
    <label>Media Type</label>
    <nameField>
        <label>Media Type</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Media Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Production_Estimate__c/Production_Estimate__c.object-meta.xml
<CustomObject>
    <description>This is Production Estimate object.</description>
    <label>Production Estimate</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Production Estimates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Production_Estimate__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Cost</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Currency</type>
</CustomField>

objects/Production_Estimate__c/fields/GL_Code__c.field-meta.xml
<CustomField>
    <fullName>GL_Code__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GL Description</label>
    <referenceTo>GL_Code__c</referenceTo>
    <relationshipLabel>Production Estimates</relationshipLabel>
    <relationshipName>Production_Estimates</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Production_Estimate__c/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <label>Job Name</label>
    <referenceTo>Job__c</referenceTo>
    <relationshipLabel>Production Estimates</relationshipLabel>
    <relationshipName>Production_Estimates</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/Production_Estimate__c/fields/Shippment_status__c.field-meta.xml
<CustomField>
    <fullName>Shippment_status__c</fullName>
    <label>Shippment status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Ready to be shipped</fullName>
            </value>
            <value>
                <fullName>Shipped</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Production_Estimate__c/fields/Total_Cost__c.field-meta.xml
<CustomField>
    <fullName>Total_Cost__c</fullName>
    <formula>Amount__c  +  Commission_cost__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Cost</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Currency</type>
</CustomField>

objects/Production_Estimate__c/fields/Vendor__c.field-meta.xml
<CustomField>
    <fullName>Vendor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vendor</label>
    <referenceTo>Vendor__c</referenceTo>
    <relationshipLabel>Production Estimates</relationshipLabel>
    <relationshipName>Production_Estimates</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/ProductionEstimate__c/ProductionEstimate__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>This is to use Production Estimate in place of Standard Estimate &amp; New Copy Schedule Button.</description>
    <label>Job Suite Controls</label>
</CustomObject>

objects/ProductionEstimate__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This One Is for to Activate Production Estimate in place of Standard Estimate</description>
    <inlineHelpText>This One Is for to Activate Production Estimate in place of Standard Estimate</inlineHelpText>
    <label>Production Estimate Active</label>
    <type>Checkbox</type>
</CustomField>

objects/Shipment__c/Shipment__c.object-meta.xml
<CustomObject>
    <description>This is shipment object used for production estimate process</description>
    <label>Shipment</label>
    <nameField>
        <displayFormat>Ship-{000000}</displayFormat>
        <label>Shipment #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shipments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Shipment__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Client</label>
    <referenceTo>Client__c</referenceTo>
    <relationshipLabel>Shipments</relationshipLabel>
    <relationshipName>Shipments</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Shipment__c/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Job</label>
    <referenceTo>Job__c</referenceTo>
    <relationshipLabel>Shipments</relationshipLabel>
    <relationshipName>Shipments</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

objects/Shipment_Line_Item__c/Shipment_Line_Item__c.object-meta.xml
<CustomObject>
    <description>This Shipment Line Item object is child object of Shipment  object</description>
    <label>Shipment Line Item</label>
    <nameField>
        <displayFormat>SLI-{00000}</displayFormat>
        <label>Shipment Line Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shipment Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Shipment_Line_Item__c/fields/Estimate_Line_Item__c.field-meta.xml
<CustomField>
    <fullName>Estimate_Line_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Estimate Line Item</label>
    <referenceTo>Estimate_Line_Items__c</referenceTo>
    <relationshipLabel>Shipment Line Items</relationshipLabel>
    <relationshipName>Shipment_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Shipment_Line_Item__c/fields/Item_Status__c.field-meta.xml
<CustomField>
    <fullName>Item_Status__c</fullName>
    <label>Item Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Packed</fullName>
            </value>
            <value>
                <fullName>Shipped</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Shipment_Line_Item__c/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <formula>IF(($Setup.ProductionEstimate__c.Active__c==True), Production_Estimate__r.Job__r.Job_Auto_Number__c,  Estimate_Line_Item__r.Job__r.Job_Auto_Number__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Job #</label>
    <type>Text</type>
</CustomField>

objects/Shipment_Line_Item__c/fields/Production_Estimate__c.field-meta.xml
<CustomField>
    <fullName>Production_Estimate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Item Name</label>
    <referenceTo>Production_Estimate__c</referenceTo>
    <relationshipLabel>Shipment Line Items</relationshipLabel>
    <relationshipName>Shipment_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Shipment_Line_Item__c/fields/Qty_Shipped__c.field-meta.xml
<CustomField>
    <fullName>Qty_Shipped__c</fullName>
    <label>Qty Shipped</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

objects/Shipment_Line_Item__c/fields/Shipment__c.field-meta.xml
<CustomField>
    <fullName>Shipment__c</fullName>
    <label>Shipment</label>
    <referenceTo>Shipment__c</referenceTo>
    <relationshipLabel>Shipment Line Items</relationshipLabel>
    <relationshipName>Shipment_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/Vendor__c/Vendor__c.object-meta.xml
<CustomObject>
    <description>This is Vendor object. Vendors in JobSuite are assigned to the line items on Quotes, Estimates, Purchase Orders and Vendor Invoices.  A printer or photographer may be a vendor.</description>
    <label>Vendor</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vendors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Vendor__c/fields/Vendor__c.field-meta.xml
<CustomField>
    <fullName>Vendor__c</fullName>
    <label>Vendor #</label>
    <length>30</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

classes/addPELineitemToSLineitem.cls
public with sharing class addPELineitemToSLineitem {

//Global variables

 /*   public boolean isLtng{private set; get{
                                            String theme = UserInfo.getUITheme();
                                            return (theme=='Theme4d')?true:false;
                                          }
    }  

    public String Sid{get;set;}
    Public string Clientname,JobName;
    public List<ELIWrapper> rolewraps{get;set;}
    public List<EstLTWrapper> EstLTwrapper{get;set;}
    public List<Shipment_Line_Item__c> lstSLI{get;set;}
    public List<Shipment_Line_Item__c> lst{get;set;}
    public List<Shipment_Line_Item__c> Elst{get;set;}
    public List<Production_Estimate__c> ELIlst{get;set;}
    public List<Estimate_Line_Items__c> EstLTlst{get;set;}
    public boolean ShowProductionEstimate{get;set;}
   
    Shipment__c S = new Shipment__c();
   
    
    // End of Global variables

   // Start Constructor 
   public addPELineitemToSLineitem ()
   {
       EstLTWrapper eswraptest = new EstLTWrapper();
       Sid = ApexPages.currentPage().getParameters().get('id');
       roleWraps=new List<ELIWrapper>();
       EstLTwrapper=new List<EstLTWrapper>();
         
       ProductionEstimate__c  activeSettings = ProductionEstimate__c.getOrgDefaults();
       ShowProductionEstimate =activeSettings.Active__c;
       
       system.debug('>>>>>>>>>>>>>>>>>>>>>>>>ShowProductionEstimate>>>>>>>>>'+ShowProductionEstimate);
       
       S= [Select id,Name,Client__c,Client__r.name,job__r.name from Shipment__c where id =:Sid];
       Clientname=s.Client__r.name;
       JobName=s.job__r.name;
     
       lstSLI=[Select Id,name,Production_Estimate__c,Production_Estimate__r.name from Shipment_Line_Item__c where Shipment__c =:Sid order by CreatedDate];
       system.debug('============'+lstSLI.size());
       
         if(ShowProductionEstimate==true)
         {
               List<Production_Estimate__c> ELI=[Select id,Name,Amount__c,Vendor__c,Job__c,Approved__c,Shippment_status__c,Total_Cost__c,GL_Code__c, Quantity__c,Job__r.name,Job__r.Status__c,Job__r.Job_Auto_Number__c,Job__r.Media_Types__c,Job__r.JS_Client__c,Job__r.JS_Client__r.name From Production_Estimate__c  where job__r.name=:JobName and Job__r.Status__c='Active' and  Shippment_status__c='Ready to be shipped'  /* where  Shippment_status__c='Ready to be shipped' and Job__r.Status__c='Active' and Job__r.Media_Types__r.name='Supplies' and Job__r.JS_Client__r.name=:Clientname Order By Name];
               
               for(Production_Estimate__c e: ELI)
               {
                    ELIWrapper rw=new ELIWrapper();
                    rw.e=e;
                    rw.checked=false;
                    roleWraps.add(rw);        
               }
         }
         
         else
         {
               List<Estimate_Line_Items__c> EstLI=[Select id,Name,Vendor__c,Job__c,Approved__c,Shippment_status__c,Total_Amount__c,GL_Code__c, Quantity__c,Job__r.name,Job__r.Status__c,Job__r.Job_Auto_Number__c,Job__r.Media_Types__c,Job__r.JS_Client__c,Job__r.JS_Client__r.name From Estimate_Line_Items__c where job__r.name=:JobName and Job__r.Status__c='Active' and  Shippment_status__c='Ready to be shipped'  /* where  Shippment_status__c='Ready to be shipped' and Job__r.Status__c='Active' and Job__r.Media_Types__r.name='Supplies' and Job__r.JS_Client__r.name=:Clientname Order By Name];

               for(Estimate_Line_Items__c es: EstLI)
               {
                   EstLTWrapper eswrap = new EstLTWrapper();
                    eswrap.est=es;
                    eswrap.checked=false;
                    EstLTWrapper.add(eswrap);   
                    
                    system.debug('>>>>>>>>>>>>>>>>>>>>>>>>EstLTWrapper>>>>>>>>>'+EstLTWrapper);
               }
         }
       
   }
   // End Constructor 

    // Start Wrapper Class for Production_Estimate__c 
     public class ELIWrapper
     {
           public Production_Estimate__c e{get;set;}
           public Boolean checked{get;set;}
     }
     // End of Wrapper Class

    // Start Wrapper Class for Estimate_Line_Items__c 
     public class EstLTWrapper
     {
           public Estimate_Line_Items__c est{get;set;}
           public Boolean checked{get;set;}
     }
     // End of Wrapper Class


    // Save Method
    public pagereference Save()
    {
        ProductionEstimate__c  activeSettings = ProductionEstimate__c.getOrgDefaults();
        ShowProductionEstimate =activeSettings.Active__c;
        
        Set<Id> PestIDS=new Set<id>();
        Set<Id> EstIDS=new Set<id>();
        List<Production_Estimate__c> UPestIDS=new List<Production_Estimate__c>();
        List<Estimate_Line_Items__c > UEstIDS=new List<Estimate_Line_Items__c >();
        try
        {
            if(ShowProductionEstimate==true)
            {
                 lst=new List<Shipment_Line_Item__c>();
                 for(ELIWrapper rw:roleWraps)
                 {
                     PestIDS.add(rw.e.id);
                     if(rw.checked == true)
                     {
                        Shipment_Line_Item__c stRole=new Shipment_Line_Item__c();
                        if(schema.SobjectType.Shipment_Line_Item__c.Fields.Production_Estimate__c.isCreateable()){ 
                            stRole.Production_Estimate__c=rw.e.id;
                        }
                        if(schema.SobjectType.Shipment_Line_Item__c.Fields.Qty_Shipped__c.isCreateable()){ 
                            stRole.Qty_Shipped__c=rw.e.Quantity__c;
                        }
                        if(schema.SobjectType.Shipment_Line_Item__c.Fields.Item_Status__c.isCreateable()){ 
                            stRole.Item_Status__c='Pending';
                        }
                        if(schema.SobjectType.Shipment_Line_Item__c.Fields.Shipment__c.isCreateable()){ 
                            stRole.Shipment__c=ApexPages.currentPage().getParameters().get('id');
                        }
                            lst.add(stRole);
                     }
                  }
                 System.debug('Inserted value @@@ '+lst);
                  if(Schema.sObjectType.Shipment_Line_Item__c.isCreateable()){
                 insert lst;
                 }
             
                 ELIlst=[Select id,name,Shippment_status__c from Production_Estimate__c where id in :PestIDS];
                 for(Production_Estimate__c  pei :ELIlst)
                 {
                    if (Schema.sObjectType.Production_Estimate__c.fields.Shippment_status__c.isUpdateable()) {   
                        pei.Shippment_status__c ='Shipped';
                         UPestIDS.add(pei);
                     }
                 }
                if(Schema.sObjectType.Production_Estimate__c.isUpdateable())
                {
                    Update UPestIDS;
                }
       
                 Pagereference p;
               
                if(isLtng)
                {
                     p = new Pagereference('/apex/ShipmentDetailPageLightning?id='+SID);
                }
                else
                {
                      p = new Pagereference('/apex/ShipmentDetailPage?id='+SID);
                }
               
               p.setRedirect(true);
               return p;
             }
             else
             {
             
                 Elst=new List<Shipment_Line_Item__c>();
                 for(EstLTWrapper Erw:EstLTWrapper)
                 {
                    
                     if(Erw.checked == true)
                     {
                     
                          EstIDS.add(Erw.est.id);
                            Shipment_Line_Item__c stRoleE=new Shipment_Line_Item__c(Item_Status__c='Pending',Estimate_Line_Item__c=Erw.est.id,Qty_Shipped__c=Erw.est.Quantity__c,Shipment__c=ApexPages.currentPage().getParameters().get('id'));
                            
                            Elst.add(stRoleE);
                     }
                  }
                 System.debug('Inserted value @@@ '+lst);
                 insert Elst;
             
                 EstLTlst=[Select id,name,Shippment_status__c from Estimate_Line_Items__c where id in :EstIDS];
                 for(Estimate_Line_Items__c ei :EstLTlst)
                 {
                     if (Schema.sObjectType.Estimate_Line_Items__c.fields.Shippment_status__c.isUpdateable()) { 
                         ei.Shippment_status__c ='Shipped';
                         UEstIDS.add(ei);
                     }
                 }
                if(Schema.sObjectType.Estimate_Line_Items__c.isUpdateable())
                 {
                     Update UEstIDS;
                 }
       
                Pagereference p;
               
                if(isLtng)
                {
                     p = new Pagereference('/apex/ShipmentDetailPageLightning?id='+SID);
                }
                else
                {
                      p = new Pagereference('/apex/ShipmentDetailPage?id='+SID);
                }
               
               p.setRedirect(true);
               return p;
             
             }
             
        
        }
        catch(DMLException e)
        {
            return null;
        }
             
    }
      
 
 // End of Save Method
 
     // Method called on to handle Back Button
   public pagereference Back()
  {
      Pagereference p;
               
                if(isLtng)
                {
                     p = new Pagereference('/apex/ShipmentDetailPageLightning?id='+SID);
                }
                else
                {
                      p = new Pagereference('/apex/ShipmentDetailPage?id='+SID);
                }
               
               p.setRedirect(true);
               return p;
  }
  // End of Back

*/
}