objects/Client__c/Client__c.object-meta.xml
<CustomObject>
    <description>This is custom Client object used for Jobsuite application.</description>
    <label>Client</label>
    <nameField>
        <label>Client Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Invoice_Allocation_Template__c/Invoice_Allocation_Template__c.object-meta.xml
<CustomObject>
    <description>This is Invoice Allocation Template object, will be used for client invoice invoice allocation line items.</description>
    <label>Invoice Allocation Template</label>
    <nameField>
        <label>Invoice Allocation Template</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoice Allocation Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Invoice_Allocation_Template_Line_Item__c/Invoice_Allocation_Template_Line_Item__c.object-meta.xml
<CustomObject>
    <description>This is Invoice Allocation Template Line Item object, will be used for client invoice invoice allocation line items.</description>
    <label>Invoice Allocation Template Line Item</label>
    <nameField>
        <displayFormat>IATLI-{000000}</displayFormat>
        <label>IATLI</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Allocation Template Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Invoice_Allocation_Template_Line_Item__c/fields/Allocation_Qty__c.field-meta.xml
<CustomField>
    <fullName>Allocation_Qty__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Allocation Qty</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

objects/Invoice_Allocation_Template_Line_Item__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Client</label>
    <referenceTo>Client__c</referenceTo>
    <relationshipLabel>Invoice Allocation Template Line Items</relationshipLabel>
    <relationshipName>Invoice_Allocation_Template_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Invoice_Allocation_Template_Line_Item__c/fields/Invoice_Allocation_Template__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Allocation_Template__c</fullName>
    <label>Invoice Allocation Template</label>
    <referenceTo>Invoice_Allocation_Template__c</referenceTo>
    <relationshipLabel>Invoice Allocation Template Line Items</relationshipLabel>
    <relationshipName>Invoice_Allocation_Template_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/Tag_Template_Item__c/Tag_Template_Item__c.object-meta.xml
<CustomObject>
    <description>This object holds the tag template items.</description>
    <label>Tags Admin</label>
    <nameField>
        <label>Tag Line Item</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tags_Admin</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Tag_Template_Item__c/fields/Air_Date__c.field-meta.xml
<CustomField>
    <fullName>Air_Date__c</fullName>
    <label>Air Date</label>
    <type>Date</type>
</CustomField>

objects/Tag_Template_Item__c/fields/Air_Time__c.field-meta.xml
<CustomField>
    <fullName>Air_Time__c</fullName>
    <label>Air Time</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

objects/Tag_Template_Item__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Tag Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

objects/Tag_Template_Item__c/fields/Lengths__c.field-meta.xml
<CustomField>
    <fullName>Lengths__c</fullName>
    <label>Lengths</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

objects/Tag_Template_Item__c/fields/Promo_Due_Date__c.field-meta.xml
<CustomField>
    <fullName>Promo_Due_Date__c</fullName>
    <label>Promo Due Date</label>
    <type>Date</type>
</CustomField>

objects/Tag_Template_Item__c/fields/Promo_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Promo_End_Date__c</fullName>
    <label>Promo End Date</label>
    <type>Date</type>
</CustomField>

objects/Tag_Template_Item__c/fields/Show_Air_Date__c.field-meta.xml
<CustomField>
    <fullName>Show_Air_Date__c</fullName>
    <label>Show Air Date</label>
    <type>Date</type>
</CustomField>

objects/Tag_Template_Item__c/fields/TagTemplate__c.field-meta.xml
<CustomField>
    <fullName>TagTemplate__c</fullName>
    <description>This is master for tag line item</description>
    <label>Tag Template</label>
    <referenceTo>Tag_Template__c</referenceTo>
    <relationshipName>Tag_Template_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

classes/DisplayTagTempLitemController.cls
public with sharing class DisplayTagTempLitemController{

// Global variables 
     /*   public boolean isLtng{private set; get{
                                            String theme = UserInfo.getUITheme();
                                            return (theme=='Theme4d')?true:false;
                                          }
    }  


        String theID;
        public List<Tag_Template_Item__c> TagLI{get;set;} 
        public id strTagLI{get;set;}
        // End Global variables 
        
        // Start Constructor 
        public DisplayTagTempLitemController() 
        {
             theID = ApexPages.CurrentPage().getParameters().get('id');
             TagLI=[select id,Name,TagTemplate__c,Air_Date__c,Air_Time__c,Lengths__c,Promo_Due_Date__c,Promo_End_Date__c,Show_Air_Date__c,Description__c from Tag_Template_Item__c where TagTemplate__c=: theID ORDER BY Name];
        }
        // End Constructor
       
        
        // THis methos is called on to Create 
        public PageReference createTagLI()
        {
           // PageReference p =  Page.CreateInvAllocTempLItem;
            
            PageReference p;
            if(isLtng)
            {
                p = new PageReference('/apex/CreateTagtempLineItemsLightning?TagID='+theID);
            }
            else
            {
              p = new PageReference('/apex/CreateTagtempLineItems?TagID='+theID);
            }
             p.setRedirect(true);
           return p;
          
          /*  p =  Page.CreateTagtempLineItems;
            p.setRedirect(true);
            p.getParameters().put('TagID',theID);
            return p
        }
        // End method 
        
         // This method is called on to handle Edit button
        /*   public Pagereference EditIATLI()
           {
                  system.debug('IATLI EDIT' + strIATLI);
                  
                    PageReference p;
                    if(isLtng)
                    {
                         p=new Pagereference('/apex/EditInvAllocTempLItemLightning?id='+strIATLI);
                    }
                    else
                    {
                          p=new Pagereference('/apex/EditInvAllocTempLItem?id='+strIATLI);
                    }
                  
               //   Pagereference p=new Pagereference('/apex/EditInvAllocTempLItem?id='+strIATLI);
                  p.setRedirect(true);
                  return p;
           }
   // End of Method Edit
        
        
        
        
        // This method is called on to handle delete Billboard Invoice Line Item
         public pagereference deleteIATLI()
         
         {
            system.debug('IATLI DELETE ' + strIATLI);
         
             Invoice_Allocation_Template_Line_Item__c  objIATLI=[Select id,Name,Allocation_Qty__c,Client__c ,Invoice_Allocation_Template__c  from Invoice_Allocation_Template_Line_Item__c where id=:strIATLI];
               Id IAT=objIATLI.Invoice_Allocation_Template__c  ;
               
               Database.Delete(objIATLI);
          
           
               // After deletion, navigate to CI Detail Page
               
               
                PageReference p;
                if(isLtng)
                {
                     p = new PageReference('/apex/InvAllocationTempDetailpageLightning?id='+IAT);
                }
                else
                {
                      p = new PageReference('/apex/InvAllocationTempDetailpage?id='+IAT);
                }
               
              // Pagereference p=new Pagereference('/apex/InvAllocationTempDetailpage?id='+IAT);
               p.setRedirect(true);
               return p;
         }
         // End of method deleteBBILI
        
        */
        
      

}