objects/Client__c/Client__c.object-meta.xml
<CustomObject>
    <description>This is custom Client object used for Jobsuite application.</description>
    <label>Client</label>
    <nameField>
        <label>Client Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Client_Contact__c/Client_Contact__c.object-meta.xml
<CustomObject>
    <description>This Object is used as Child of Client Object.</description>
    <label>Client Contact</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Client Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Client_Contact__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <label>Client</label>
    <referenceTo>Client__c</referenceTo>
    <relationshipLabel>Client Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

objects/Client_Contact__c/fields/Salesforce_User__c.field-meta.xml
<CustomField>
    <fullName>Salesforce_User__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Salesforce User</label>
    <type>Checkbox</type>
</CustomField>

objects/Client_Contact__c/fields/UserName__c.field-meta.xml
<CustomField>
    <fullName>UserName__c</fullName>
    <description>UserName</description>
    <label>UserName</label>
    <type>Email</type>
</CustomField>

objects/Job_Task_Role__c/Job_Task_Role__c.object-meta.xml
<CustomObject>
    <description>Staff assigned to the Job Tasks.</description>
    <label>Task Staff Assigned</label>
    <nameField>
        <label>Role</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Task Staff Assigned</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/BatchStaffNameUpdateforTaskrole.cls
global class BatchStaffNameUpdateforTaskrole implements Database.Batchable<Job_Task_Role__c> {
	global List<Job_Task_Role__c> JobTaskRolelist = new List<Job_Task_Role__c>(); 
    global BatchStaffNameUpdateforTaskrole(List<Job_Task_Role__c> listJobTaskRole) { 
        JobTaskRolelist = listJobTaskRole; 
    }
    
    global Iterable<Job_Task_Role__c> start(Database.BatchableContext BC) {
        //list<Client_Contact__c> query = [select id, name,Salesforce_User__c,Client__c,UserName__c from Client_Contact__c where id in :MainAccounts];
        return JobTaskRolelist;
    }
   
    global void execute(Database.BatchableContext BC, List<Job_Task_Role__c> scope) {
          if(Schema.sObjectType.Job_Task_Role__c.isUpdateable()){
              update scope;}
    }   
    
    global void finish(Database.BatchableContext BC) {
    }
}