objects/Client__c/Client__c.object-meta.xml
<CustomObject>
    <description>This is custom Client object used for Jobsuite application.</description>
    <label>Client</label>
    <nameField>
        <label>Client Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Client__c/fields/Client_Code__c.field-meta.xml
<CustomField>
    <fullName>Client_Code__c</fullName>
    <label>Client Code</label>
    <length>6</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

objects/Invoice_Allocation_Template__c/Invoice_Allocation_Template__c.object-meta.xml
<CustomObject>
    <description>This is Invoice Allocation Template object, will be used for client invoice invoice allocation line items.</description>
    <label>Invoice Allocation Template</label>
    <nameField>
        <label>Invoice Allocation Template</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoice Allocation Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/TestInvAllocationTempEnhancedListExt.cls
@isTest
Public class TestInvAllocationTempEnhancedListExt{

static Testmethod Void TestInvAllocationTempEnhancedListExt(){
    
     /*  Test.StartTest();
        
        
           Client__c client= new Client__c(name='test', client_code__c='123');
           insert client;
           
          Invoice_Allocation_Template__c TestIAT=new Invoice_Allocation_Template__c(Name='Test IAT');
            Insert TestIAT;
        
       
        
        ApexPages.currentPage().getParameters().put('strIAT',TestIAT.Id);
        ApexPages.StandardController con=new ApexPages.StandardController(TestIAT);    
        InvAllocationTempEnhancedListExt ext = new InvAllocationTempEnhancedListExt(con);
        
        ApexPages.Pagereference result1 = ext.editIAT();
        
        result1 = ext.deleteIAT();
        
        result1 = ext.createNewIAt();
        
        Test.StopTest();*/
        
    }// End of Test Coverage code       


}