objects/Client__c/Client__c.object-meta.xml
<CustomObject>
    <description>This is custom Client object used for Jobsuite application.</description>
    <label>Client</label>
    <nameField>
        <label>Client Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Job__c/Job__c.object-meta.xml
<CustomObject>
    <description>This is Job object.</description>
    <label>Job</label>
    <nameField>
        <label>Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Job__c/fields/Job_Auto_Number__c.field-meta.xml
<CustomField>
    <fullName>Job_Auto_Number__c</fullName>
    <defaultValue>&quot;Auto Fill&quot;</defaultValue>
    <externalId>true</externalId>
    <label>Job #</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

objects/Job__c/fields/JS_Client__c.field-meta.xml
<CustomField>
    <fullName>JS_Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Job is associated with Client object.</description>
    <label>Client</label>
    <referenceTo>Client__c</referenceTo>
    <relationshipName>Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Job__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Requested</fullName>
                <default>true</default>
                <label>Requested</label>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Shipment__c/Shipment__c.object-meta.xml
<CustomObject>
    <description>This is shipment object used for production estimate process</description>
    <label>Shipment</label>
    <nameField>
        <displayFormat>Ship-{000000}</displayFormat>
        <label>Shipment #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shipments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Shipment__c/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Job</label>
    <referenceTo>Job__c</referenceTo>
    <relationshipLabel>Shipments</relationshipLabel>
    <relationshipName>Shipments</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

classes/CreateNewShipmentUnderJobExt.cls
public with sharing class CreateNewShipmentUnderJobExt{

  /* public boolean isLtng{private set; get{
                                            String theme = UserInfo.getUITheme();
                                            return (theme=='Theme4d')?true:false;
                                          }
    }  
   
    private final Shipment__c SP;
    public String ClientName,shipid,JobName,jobn;
  //  public String getClientName() { return JobName; }
   // public void setClientName(String s) {  this.JobName= s; }
    public String getJobName() { return JobName; }
    public void setJobName(String s) {  this.JobName= s; }
     public String getjobn() { return jobn; }
    public void setjobn(String s) {  this.jobn= s; }
    public String jobid{get;set;}

  
   // Start of Constructor
    public CreateNewShipmentUnderJobExt(ApexPages.StandardController controller) 
     {
          this.SP=(Shipment__c)controller.getRecord();
          jobId = ApexPages.currentPage().getParameters().get('jobId');
        
           Job__c objJob=[Select id,name,JS_Client__r.name,Job_Auto_Number__c  from Job__c where id=:jobId ];
           JobName=objJob.id;
           jobn=objJob.name;
           SP.Job__c = jobid;
     
         
        
     }
   // End of Constructor 
   
 
    
    
    public List<selectOption> getjobs() 
    {
        List<selectOption> optionList = new List<selectOption>();
        optionList.add(new selectOption('', '- None -'));  
        for (job__c c : [SELECT Id, name FROM job__c where status__c!='completed' order by Name limit 1000]) 
        {  
            optionList.add(new selectOption(c.Id, c.Name));  
        }
        return optionList;  
    }
        
      // Save Method
        public PageReference saveme()
        { 
                 
                 try{
                        if (Schema.sObjectType.Shipment__c.fields.job__c.isCreateable()) {
                            sp.job__c=JobName;}
                     if(Schema.sObjectType.Shipment__c.isCreateable()){insert SP;}
                        shipid=sp.id;
                        
                    }
                    catch(DMLException e)
                    {
                        return null;
                    }
                    
                    
                    
                    PageReference pageRef;
                    if(isLtng)
                    {
                         pageRef =  new Pagereference('/apex/ShipmentDetailPageLightning?id='+shipid); 
                    }
                    else
                    {
                        pageRef =  new Pagereference('/apex/ShipmentDetailPage?id='+shipid); 
                    }
                  
              
                  pageRef.setRedirect(true);
                  return pageRef;
                  
         }
            // End of Save Method

        // Cancel Method
        Public PageReference cancelme()
        {    
        
             PageReference p;
            if(isLtng)
            {
                p = new Pagereference('/apex/JobdetailpageLightening07?id='+JobName+'&tab=Jobcost'+'&section=shipment'); 
            }
            else
            {
                p =  new Pagereference('/apex/JobListView?id='+JobName+'&intFocus=16'); 
            }
                  
              
            p.setRedirect(true);
            return p;   
            
          }
        // Cancel Method         

*/
}