objects/Client__c/Client__c.object-meta.xml
<CustomObject>
    <description>This is custom Client object used for Jobsuite application.</description>
    <label>Client</label>
    <nameField>
        <label>Client Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/GL_Code__c/GL_Code__c.object-meta.xml
<CustomObject>
    <description>GL Codes are used to build line items on our Job Cost Layouts.  The Job Cost Layouts are the Quote, Estimate, Purchase Order, and Vendor Invoice.   The line items on each of these follow similar logic.</description>
    <label>GL Code</label>
    <nameField>
        <label>Description</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GL Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/GL_Code__c/fields/GL_ID__c.field-meta.xml
<CustomField>
    <fullName>GL_ID__c</fullName>
    <description>This is GL ID field. These id&apos;s are auto generated.</description>
    <label>GL Code</label>
    <length>15</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

objects/Job_Number_Setting__c/Job_Number_Setting__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This is Job Auto Number setting to set the Job Number format.</description>
    <label>Job Number</label>
</CustomObject>

objects/Media_Type__c/Media_Type__c.object-meta.xml
<CustomObject>
    <description>This is Media Type object.</description>
    <label>Media Type</label>
    <nameField>
        <label>Media Type</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Media Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Schedule_Task__c/Schedule_Task__c.object-meta.xml
<CustomObject>
    <description>This is Schedule Task object. It is child object of Schedule Template object.</description>
    <label>Schedule Task</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Schedule Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Schedule_Task__c/fields/Days__c.field-meta.xml
<CustomField>
    <fullName>Days__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Days</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

objects/Schedule_Task__c/fields/GL_Code__c.field-meta.xml
<CustomField>
    <fullName>GL_Code__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GL Code</label>
    <referenceTo>GL_Code__c</referenceTo>
    <relationshipLabel>Schedule Tasks</relationshipLabel>
    <relationshipName>Schedule_Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Schedule_Task__c/fields/Schedule_Template__c.field-meta.xml
<CustomField>
    <fullName>Schedule_Template__c</fullName>
    <label>Schedule Template</label>
    <referenceTo>Schedule_Template__c</referenceTo>
    <relationshipLabel>Schedule Tasks</relationshipLabel>
    <relationshipName>Schedule_Tasks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/Schedule_Template__c/Schedule_Template__c.object-meta.xml
<CustomObject>
    <description>This is Schedule Template object.</description>
    <label>Schedule Template</label>
    <nameField>
        <label>Schedule Template</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Schedule Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Schedule_Template__c/fields/Media_Types__c.field-meta.xml
<CustomField>
    <fullName>Media_Types__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Media Type</label>
    <referenceTo>Media_Type__c</referenceTo>
    <relationshipLabel>Schedule Templates</relationshipLabel>
    <relationshipName>Schedule_Templates</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Vendor__c/Vendor__c.object-meta.xml
<CustomObject>
    <description>This is Vendor object. Vendors in JobSuite are assigned to the line items on Quotes, Estimates, Purchase Orders and Vendor Invoices.  A printer or photographer may be a vendor.</description>
    <label>Vendor</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vendors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Vendor__c/fields/Vendor__c.field-meta.xml
<CustomField>
    <fullName>Vendor__c</fullName>
    <label>Vendor #</label>
    <length>30</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

classes/TestData.cls
public class TestData 
{
       public list<Job_Number_Setting__c> jobNumSettings = new list<Job_Number_Setting__c>();
       public list<Client__c> clients= new list<Client__c>();
       public list<Vendor__c> vendors= new list<Vendor__c>();
       public list<Media_Type__c> mediaTypes= new list<Media_Type__c>();
       public list<Schedule_Template__c> scheduleTemplates= new list<Schedule_Template__c>();
       public list<GL_Code__c> glCodes= new list<GL_Code__c>();
       public list<Schedule_Task__c> scheduleTasks= new list<Schedule_Task__c>();
    
       /****************************************  JobNumSettings   ******************************************/  
    
        public void generateJobNumSettings()
        {
            if(jobNumSettings.isempty())
            {
                Job_Number_Setting__c customSetting997 = new  Job_Number_Setting__c(Name= 'yy');		 
                jobNumSettings.add(customSetting997);
                insert jobNumSettings;
            }
        }
    
       /******************************************  Clients   ***********************************************/  
    
        public void generateClients()
        {
            if(clients.isempty())
            {
                Client__c c=new Client__c(name='test client');
                clients.add(c);
                insert clients;
            }
        }
    
        /******************************************  Vendors   ***********************************************/
    
        public void generateVendors()
        {
            if(vendors.isempty())
            {
                Vendor__c v=new Vendor__c(name='test Vendor');
                vendors.add(v);
                insert vendors;
            }
        }
    
        /******************************************  Media Types   ***********************************************/
    
        public void generateMediaTypes()
        {
            if(mediaTypes.isempty())
            {
                Media_Type__c testMedia=new Media_Type__c(Name='Test Media 358');
                mediaTypes.add(testMedia);
                insert mediaTypes;
            }
        }
    
        /******************************************  Schedule Templates   ***********************************************/
    
        public void generateScheduleTemplates()
        {
            if(mediaTypes.isempty())
            {
                generateMediaTypes();
            }
            if(scheduleTemplates.isempty())
            {
                Schedule_Template__c testST=new Schedule_Template__c(Name='Test Schedule Template 358',Media_Types__c=mediaTypes.get(0).Id);
                scheduleTemplates.add(testST);
                insert scheduleTemplates;
            }
        }
    
       /******************************************  Gl Codes   ***********************************************/
    
        public void generateGlCodes()
        {
            if(glCodes.isempty())
            {
                GL_Code__c testGL=new GL_Code__c(Name='Test GL Code',GL_ID__c='Test GL009');
                glCodes.add(testGL);
                insert glCodes;
            }
        }
    
      /******************************************  ScheduleTasks   ***********************************************/
    
        public void generateScheduleTasks()
        {
            if(glCodes.isempty())
            {
                generateGlCodes();
            }
            if(scheduleTemplates.isempty())
            {
                generateScheduleTemplates();
            }
            if(scheduleTasks.isempty())
            {
                Schedule_Task__c testSCT1=new Schedule_Task__c(Name='Test Schedule Task 358',Schedule_Template__c=scheduleTemplates.get(0).id,Days__c=5,GL_Code__c=glCodes.get(0).Id);
            	Schedule_Task__c testSCT2=new Schedule_Task__c(Name='Test Schedule Task 359',Schedule_Template__c=scheduleTemplates.get(0).id,Days__c=3,GL_Code__c=glCodes.get(0).Id);
                scheduleTasks.add(testSCT1);
                scheduleTasks.add(testSCT2);
                insert scheduleTasks;
            }
        }

}