objects/Client__c/Client__c.object-meta.xml
<CustomObject>
    <description>This is custom Client object used for Jobsuite application.</description>
    <label>Client</label>
    <nameField>
        <label>Client Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Client_Invoice__c/Client_Invoice__c.object-meta.xml
<CustomObject>
    <description>This is Client Invoice object.</description>
    <label>Client Invoice</label>
    <nameField>
        <label>Invoice #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Client Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Client_Invoice__c/fields/Client_Name__c.field-meta.xml
<CustomField>
    <fullName>Client_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Client Name</label>
    <referenceTo>Client__c</referenceTo>
    <relationshipLabel>Client Invoices</relationshipLabel>
    <relationshipName>Client_Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/GL_Code__c/GL_Code__c.object-meta.xml
<CustomObject>
    <description>GL Codes are used to build line items on our Job Cost Layouts.  The Job Cost Layouts are the Quote, Estimate, Purchase Order, and Vendor Invoice.   The line items on each of these follow similar logic.</description>
    <label>GL Code</label>
    <nameField>
        <label>Description</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GL Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/GL_Code__c/fields/GL_Department__c.field-meta.xml
<CustomField>
    <fullName>GL_Department__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GL Department</label>
    <referenceTo>GL_Department__c</referenceTo>
    <relationshipLabel>GL Codes</relationshipLabel>
    <relationshipName>GL_Codes</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/GL_Department__c/GL_Department__c.object-meta.xml
<CustomObject>
    <description>This Object is Master of GLCode Object in JobSuite Application.</description>
    <label>GL Department</label>
    <nameField>
        <label>GL Department</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GL Department</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Invoice_Allocation_Line_Item__c/Invoice_Allocation_Line_Item__c.object-meta.xml
<CustomObject>
    <description>This is Invoice Allocation Line Item object. It is child object of Client Invoice.</description>
    <label>Invoice Allocation Line Item</label>
    <nameField>
        <displayFormat>IALI-{00000}</displayFormat>
        <label>IALI</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Allocation Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Invoice_Allocation_Line_Item__c/fields/Allocation_Amount__c.field-meta.xml
<CustomField>
    <fullName>Allocation_Amount__c</fullName>
    <formula>Client_Invoice__r.Cost_Per__c  * Allocation_Qty__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Allocation Amount</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Currency</type>
</CustomField>

objects/Invoice_Allocation_Line_Item__c/fields/Allocation_Qty__c.field-meta.xml
<CustomField>
    <fullName>Allocation_Qty__c</fullName>
    <label>Allocation Qty</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

objects/Invoice_Allocation_Line_Item__c/fields/Client_Invoice__c.field-meta.xml
<CustomField>
    <fullName>Client_Invoice__c</fullName>
    <label>Client Invoice</label>
    <referenceTo>Client_Invoice__c</referenceTo>
    <relationshipLabel>Invoice Allocation Line Items</relationshipLabel>
    <relationshipName>Invoice_Allocation_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/Invoice_Allocation_Line_Item__c/fields/Client_Name__c.field-meta.xml
<CustomField>
    <fullName>Client_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Client Name</label>
    <referenceTo>Client__c</referenceTo>
    <relationshipLabel>Invoice Allocation Line Items</relationshipLabel>
    <relationshipName>Invoice_Allocation_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Invoice_Allocation_Line_Item__c/fields/GL_Code__c.field-meta.xml
<CustomField>
    <fullName>GL_Code__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GL Description</label>
    <referenceTo>GL_Code__c</referenceTo>
    <relationshipLabel>Invoice Allocation Line Items</relationshipLabel>
    <relationshipName>Invoice_Allocation_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Invoice_Allocation_Line_Item__c/fields/GL_Code_No__c.field-meta.xml
<CustomField>
    <fullName>GL_Code_No__c</fullName>
    <formula>GL_Code__r.GL_ID__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>GL Code</label>
    <type>Text</type>
</CustomField>

objects/Invoice_Allocation_Line_Item__c/fields/GL_Department__c.field-meta.xml
<CustomField>
    <fullName>GL_Department__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GL Department</label>
    <referenceTo>GL_Department__c</referenceTo>
    <relationshipLabel>Invoice Allocation Line Items</relationshipLabel>
    <relationshipName>Invoice_Allocation_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Invoice_Allocation_Template__c/Invoice_Allocation_Template__c.object-meta.xml
<CustomObject>
    <description>This is Invoice Allocation Template object, will be used for client invoice invoice allocation line items.</description>
    <label>Invoice Allocation Template</label>
    <nameField>
        <label>Invoice Allocation Template</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoice Allocation Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Invoice_Allocation_Template_Line_Item__c/Invoice_Allocation_Template_Line_Item__c.object-meta.xml
<CustomObject>
    <description>This is Invoice Allocation Template Line Item object, will be used for client invoice invoice allocation line items.</description>
    <label>Invoice Allocation Template Line Item</label>
    <nameField>
        <displayFormat>IATLI-{000000}</displayFormat>
        <label>IATLI</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Allocation Template Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Invoice_Allocation_Template_Line_Item__c/fields/Allocation_Qty__c.field-meta.xml
<CustomField>
    <fullName>Allocation_Qty__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Allocation Qty</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

objects/Invoice_Allocation_Template_Line_Item__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Client</label>
    <referenceTo>Client__c</referenceTo>
    <relationshipLabel>Invoice Allocation Template Line Items</relationshipLabel>
    <relationshipName>Invoice_Allocation_Template_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Invoice_Allocation_Template_Line_Item__c/fields/Invoice_Allocation_Template__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Allocation_Template__c</fullName>
    <label>Invoice Allocation Template</label>
    <referenceTo>Invoice_Allocation_Template__c</referenceTo>
    <relationshipLabel>Invoice Allocation Template Line Items</relationshipLabel>
    <relationshipName>Invoice_Allocation_Template_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

classes/DisplayInvoiceAllocationLIController.cls
public with sharing class DisplayInvoiceAllocationLIController {

/*
 public boolean isLtng{private set; get{
                                            String theme = UserInfo.getUITheme();
                                            return (theme=='Theme4d')?true:false;
                                          }
            }  
   

// Global variables 
        String theID;
        public List<Invoice_Allocation_Line_Item__c> IALI{get;set;} 
        public String strIALI{get;set;}
        public String InvAllocationTempName{get;set;}
        // End Global variables 
        public integer Quantity {set;get;}
        public integer rowIndex {set;get;}
        public boolean isEdit {set;get;}
        // Start Constructor 
        public DisplayInvoiceAllocationLIController () 
        {
           isEdit=false;
            IALI=new list<Invoice_Allocation_Line_Item__c>();
             theID = ApexPages.CurrentPage().getParameters().get('id');
             IALI=[select id,Name,Client_Invoice__c,Allocation_Qty__c,Allocation_Amount__c,Client_Name__c,GL_Department__c,GL_Code__c,GL_Code_No__c from Invoice_Allocation_Line_Item__c where Client_Invoice__c =: theID ORDER BY Name];
        }
        // End Constructor
        
        Sobject sumCash; 
        Sobject sumQuant;
        
        
     
     public void inlineInAllTemp(){
        isEdit=true;
     }
         

   // This method is called on to calculate Total Allocation Amount of  Invoice Allocation Line Items
   public double getSumCash()
   { 
        sumCash = [SELECT SUM(Allocation_Amount__c) sum FROM Invoice_Allocation_Line_Item__c WHERE Client_Invoice__c =: [Select id from Client_Invoice__c where id =: theID]];   
        return double.valueOf(sumCash.get('sum')); 
    }  
    // End of method getSumCash
   // This method is called on to calculate Total Allocation Qty of  Invoice Allocation Line Items
   public Integer getSumQuant()
   { 
        sumQuant = [SELECT SUM(Allocation_Qty__c) sum FROM Invoice_Allocation_Line_Item__c WHERE Client_Invoice__c =: [Select id from Client_Invoice__c where id =: theID]];   
        return Integer.valueOf(sumQuant.get('sum')); 
    }  
    // End of method getsumQuant     
        
        
        
        // THis methos is called on to Create Invoice Allocation Line Item
     public PageReference createIALI()
        {
        PageReference p;
        
          if(isLtng){
             p=Page.CreateInvoiceAllocationLILightning;
             }
          else{
             p=Page.CreateInvoiceAllocationLI;
           }
             p.setRedirect(true);
             p.getParameters().put('id',theID);
             return p;
        }
        // End method 
        
        // This method is called on to handle delete Invoice Allocation Line Item
         public PageReference deleteIALI()
         {
             Invoice_Allocation_Line_Item__c objIALI=[Select id,Client_Invoice__c from Invoice_Allocation_Line_Item__c where id=:strIALI];
               Id CIid=objIALI.Client_Invoice__c;
               
                if(Invoice_Allocation_Line_Item__c.sObjectType.getDescribe().isDeletable()){
                    Database.Delete(objIALI);}
          
       PageReference p;
        if(isLtng)
        p =new Pagereference('/apex/ClientInvoiceDetailPageLightning?id='+theID+'&section=invoiceallocationlineitem');
        else
        p= new Pagereference('/apex/ClientInvoiceDetailPage?id='+theID);
        p.setRedirect(true);
        return p;
         }
         // End of method deleteIALI
        
        
        // This method is called on to populate all InvAllocationTemplates into drop down list
        
    public List<selectOption> getInvAllocationTemplates() 
    {
       
        List<selectOption> optionList = new List<selectOption>();
        optionList.add(new SelectOption('','-None-'));
        for (Invoice_Allocation_Template__c a : [SELECT Id, name FROM Invoice_Allocation_Template__c  ORDER BY Name]) 
        {  
            optionList.add(new selectOption(a.Id, a.Name));  
        }
        return optionList;  
    }
    // End of method getInvAllocationTemplates
        
        
        
        
        
     // This method is called on to Import Allocation Template
   public PageReference importIATLI()
    {
        List<Invoice_Allocation_Line_Item__c> insertClientInvAllocation=new List<Invoice_Allocation_Line_Item__c>();    
        
        if(InvAllocationTempName==NULL || InvAllocationTempName=='-None-')
        {
           ApexPages.Message msg1 = new ApexPages.Message(ApexPages.Severity.ERROR,'Invoice Allocation Template : You must select a Template.');
           ApexPages.addMessage(msg1);
        }
        else
        {
            try
            {
                List<Invoice_Allocation_Template_Line_Item__c> lstIATLI=[Select id,Name,Allocation_Qty__c,Client__c from Invoice_Allocation_Template_Line_Item__c where Invoice_Allocation_Template__c=:InvAllocationTempName Order By CreatedDate ];
                for(Invoice_Allocation_Template_Line_Item__c sp:lstIATLI)
                {
                    Invoice_Allocation_Line_Item__c js=new Invoice_Allocation_Line_Item__c();
                    if(schema.SobjectType.Invoice_Allocation_Line_Item__c.Fields.Allocation_Qty__c.isCreateable()){ 
                        js.Allocation_Qty__c=sp.Allocation_Qty__c;
                    }
                    if(schema.SobjectType.Invoice_Allocation_Line_Item__c.Fields.Client_Name__c.isCreateable()){ 
                        js.Client_Name__c=sp.Client__c ;
                    }
                    if(schema.SobjectType.Invoice_Allocation_Line_Item__c.Fields.Client_Invoice__c.isCreateable()){ 
                        js.Client_Invoice__c=theID;
                    }
                    
                    insertClientInvAllocation.add(js);
                }
                if(Schema.sObjectType.Invoice_Allocation_Line_Item__c.isCreateable()){ 
                    insert insertClientInvAllocation;
                }
                // InvAllocationTempName='';
            }
            catch(System.DMLException e)
            {
              return NULL;
            }
        }   
        
        PageReference p;
        if(isLtng)
        p =new Pagereference('/apex/ClientInvoiceDetailPageLightning?id='+theID+'&section=invoiceallocationlineitem');
        else
        p= new Pagereference('/apex/ClientInvoiceDetailPage?id='+theID);
        p.setRedirect(true);
        return p;
       // return null;
       
        //IALI.clear();
       // IALI=[select id,Name,Client_Invoice__c,Allocation_Qty__c,Allocation_Amount__c,Client_Name__c,GL_Department__c,GL_Code__c,GL_Code_No__c from Invoice_Allocation_Line_Item__c where Client_Invoice__c =: theID ORDER BY Name];
    }
    // End of method Import Allocation Template 
        
        
        
        
        
        
    public PageReference save()
    {
     try
      {
        update IALI;
      }
     catch(System.DMLException e){
     Apexpages.addMessage(New Apexpages.Message(Apexpages.Severity.Error,''+e.getMessage()));
     return null;
     }
      
      // After updating AI, navigate to Client Invoice Tab
     PageReference p;
     if(isLtng)
     p=new Pagereference('/apex/ClientInvoiceDetailPageLightning?id='+theID+'&section=invoiceallocationlineitem');
     else
     p=new Pagereference('/apex/ClientInvoiceDetailPage?id='+theID);
     p.setRedirect(true);
     return p; 
     
   }
    //End Of Save Method  
    
    public void inlineSave(){
   
    try{
     
   update IALI[rowIndex];
       IALI.clear();
       IALI=[select id,Name,Client_Invoice__c,Allocation_Qty__c,Allocation_Amount__c,Client_Name__c,GL_Department__c,GL_Code__c,GL_Code_No__c from Invoice_Allocation_Line_Item__c where Client_Invoice__c =: theID ORDER BY Name];
       isEdit=false;
      }
    catch(System.DMLException e){
     Apexpages.addMessage(New Apexpages.Message(Apexpages.Severity.Error,''+e.getMessage()));
     }
    
    }
    
    //Method For Cancel button    
     public PageReference cancelme()
       {
       // PageReference p =  new Pagereference('/apex/ClientInvoiceDetailPage?id='+theID);
       // p.setRedirect(true);
       // return p;   
       return null;  
       }
    //End Of Cancel Buttons method  
        
        */
        
        

}