objects/Client_Contact__c/Client_Contact__c.object-meta.xml
<CustomObject>
    <description>This Object is used as Child of Client Object.</description>
    <label>Client Contact</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Client Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Client_Contact__c/fields/Client_Contact_Role__c.field-meta.xml
<CustomField>
    <fullName>Client_Contact_Role__c</fullName>
    <label>Client Contact Role</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

objects/Client_Contact__c/fields/UserName__c.field-meta.xml
<CustomField>
    <fullName>UserName__c</fullName>
    <description>UserName</description>
    <label>UserName</label>
    <type>Email</type>
</CustomField>

objects/Job__c/Job__c.object-meta.xml
<CustomObject>
    <description>This is Job object.</description>
    <label>Job</label>
    <nameField>
        <label>Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Job__c/fields/Client_Contact__c.field-meta.xml
<CustomField>
    <fullName>Client_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Not using. Instead created a custom object Client Contact.</description>
    <label>Contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.Client__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Job__c/fields/Media_Types__c.field-meta.xml
<CustomField>
    <fullName>Media_Types__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Media Type</label>
    <referenceTo>Media_Type__c</referenceTo>
    <relationshipName>Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Job__c/fields/Schedule_Template__c.field-meta.xml
<CustomField>
    <fullName>Schedule_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Schedule Template</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Schedule_Template__c.Media_Types__c</field>
            <operation>equals</operation>
            <valueField>$Source.Media_Types__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Schedule_Template__c</referenceTo>
    <relationshipName>Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Job__c/fields/Specification_Template__c.field-meta.xml
<CustomField>
    <fullName>Specification_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Creative Brief Template</label>
    <referenceTo>Specification_Template__c</referenceTo>
    <relationshipName>Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Job_Task_Role__c/Job_Task_Role__c.object-meta.xml
<CustomObject>
    <description>Staff assigned to the Job Tasks.</description>
    <label>Task Staff Assigned</label>
    <nameField>
        <label>Role</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Task Staff Assigned</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Job_Team__c/Job_Team__c.object-meta.xml
<CustomObject>
    <description>This is Job Team object. It is used to store role and assigned staff to that role for a Job record.</description>
    <label>Job Team</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>JobTeam Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Team</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Job_Team__c/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <label>Job Name</label>
    <referenceTo>Job__c</referenceTo>
    <relationshipLabel>Job Team</relationshipLabel>
    <relationshipName>Job_Team</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/Job_Team__c/fields/Staff__c.field-meta.xml
<CustomField>
    <fullName>Staff__c</fullName>
    <label>Staff</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

objects/Media_Type__c/Media_Type__c.object-meta.xml
<CustomObject>
    <description>This is Media Type object.</description>
    <label>Media Type</label>
    <nameField>
        <label>Media Type</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Media Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Schedule_Template__c/Schedule_Template__c.object-meta.xml
<CustomObject>
    <description>This is Schedule Template object.</description>
    <label>Schedule Template</label>
    <nameField>
        <label>Schedule Template</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Schedule Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Schedule_Template__c/fields/Media_Types__c.field-meta.xml
<CustomField>
    <fullName>Media_Types__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Media Type</label>
    <referenceTo>Media_Type__c</referenceTo>
    <relationshipLabel>Schedule Templates</relationshipLabel>
    <relationshipName>Schedule_Templates</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Specification_Template__c/Specification_Template__c.object-meta.xml
<CustomObject>
    <description>This is Creative Brief Template object. Also known as Specification Template.</description>
    <label>Creative Brief Template</label>
    <nameField>
        <label>Creative Brief Template</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Creative Brief Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Staff__c/Staff__c.object-meta.xml
<CustomObject>
    <description>This is Staff object.</description>
    <label>Staff</label>
    <nameField>
        <label>Staff Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Staff</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Staff__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <label>Email</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

objects/Staff__c/fields/User_Type__c.field-meta.xml
<CustomField>
    <fullName>User_Type__c</fullName>
    <label>User Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Licensed User</fullName>
            </value>
            <value>
                <fullName>Unlicensed Staff</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Staff__c/fields/Username__c.field-meta.xml
<CustomField>
    <fullName>Username__c</fullName>
    <label>Username</label>
    <type>Email</type>
</CustomField>

objects/Vendor_Contact__c/Vendor_Contact__c.object-meta.xml
<CustomObject>
    <description>This is Vendor Contact Object.</description>
    <label>Vendor Contact</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vendor Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Vendor_Contact__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>this is Email ID of Vendor Contact</description>
    <label>Email</label>
    <type>Email</type>
</CustomField>

objects/Vendor_Contact__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <description>This field contains first name of the vendor.</description>
    <label>First Name</label>
    <length>15</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

objects/Vendor_Contact__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <description>This field contains last name of the vendor.</description>
    <label>Last Name</label>
    <length>15</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

classes/JobTeamAssignUser.cls
// This class is used to Assign User To selected Role 
public with sharing class JobTeamAssignUser 
{
    // Global variables
  /*  public List<RoleWrapper> rolewraps{get;set;}
    public Job_Team__c objJTR{get;set;}
    Id JobTeamId;
    
    public list<CCWrapper> CCntwraps{get; set;}
    public list<VenWrapper> VenWraps{get; set;}
    // End of GLobal variables
    

    // Start Constructor
    public JobTeamAssignUser(ApexPages.StandardController controller)
      {
        Id aid=ApexPages.currentPage().getParameters().get('id');
        system.debug('aid is@@@ :'+aid);
        this.objJTR=(Job_Team__c)controller.getrecord();
        
        Job_Team__c objJTR = [select Role__c,Job__c,Staff__c from Job_Team__c where id =: aid Limit 1];
        JobTeamId = objJTR.Job__c;
        roleWraps=new List<RoleWrapper>();
        
     /*   for(Job_Team__c j: [Select Id, Staff__c from Job_Team__c where Id =: aid])
        {
             selectedStaff.add(j.Staff__c);   
        }
        System.debug('Selected Staff : '+selectedStaff);
      
        
        for(Staff__c u: [Select Id, Name from Staff__c where Role__c =: objJTR.Role__c   and IsDeleted__c=:False])
         {
                RoleWrapper rw=new RoleWrapper();
                rw.u=u;
                rw.selected = false;
                roleWraps.add(rw);        
          }
        
        List<Staff__c> lstu = [select Name from Staff__c where User_Type__c =:'User'];
        set<string> uname = new set<string>();
        for(Staff__c obj : lstu)
        {
            uname.add(obj.Name);
        }  
          
        for(User ub : [select Name from user where Name in: uname])
        {
            system.debug('Name:::::'+ub.Name);
        }  
        
        //added this code by rahul for generating client contacts on 10 June 2014
        CCntwraps = new list<CCWrapper>();
        for(Client_Contact__c u: [Select Id, Name, Client_Contact_Role__c from Client_Contact__c where Client_Contact_Role__c =: objJTR.Role__c]){
            CCWrapper cw=new CCWrapper();
            cw.u=u;
            cw.selected = false;
            CCntwraps.add(cw);        
        }
        //Added code ends here
        
        //added this code by rahul for generating Vendor contacts on 12 June 2014
        VenWraps = new list<VenWrapper>();
        for(Vendor_Contact__c u: [Select Id, Name, Role__c from Vendor_Contact__c where Role__c =: objJTR.Role__c]){
            VenWrapper cw=new VenWrapper();
            cw.u=u;
            cw.selected = false;
            VenWraps.add(cw);        
        }
        //Added code ends here
    
       }
       // End of Constructor
         
    // Start Wrapper Class : This class will bind checkbox and its associated Staff on layout
    public class RoleWrapper
     {
         public Staff__c u{get;set;}
         public Boolean selected{get;set;}
     }   
     // End of Wrapper Class
     
     // Start Wrapper Class : This class will bind checkbox and its associated Client on layout
    public class CCWrapper
     {
         public Client_Contact__c u{get;set;}
         public Boolean selected{get;set;}
     }   
     // End of Wrapper Class

     // Start Wrapper Class : This class will bind checkbox and its associated Vendor on layout
    public class VenWrapper
     {
         public Vendor_Contact__c u{get;set;}
         public Boolean selected{get;set;}
     }   
     // End of Wrapper Class     
   
   // Save Method 
    public pagereference Save()
     {
     Boolean blnNothingSelected = false;
      for(RoleWrapper rw:roleWraps)
       {
       //lst=new List<Job_Task_Role__c>();
         if(rw.selected==true)
          {
              if(schema.SobjectType.Job_Team__c.Fields.Staff__c.isUpdateable()){ objJTR.Staff__c=rw.u.Name;}
                if(Schema.sObjectType.Job_Team__c.isUpdateable()){update objJTR;}
           blnNothingSelected = true; 
           break;      
           }
       }
       
       //Added by rahul on 10 June 2014.
       for(CCWrapper varCCw : CCntwraps)
       {
           if(varCCw.selected==true)
          {
           objJTR.Staff__c=varCCw.u.Name;
           update objJTR; 
           blnNothingSelected = true; 
           break;      
           }
       }
       //Addded code ends here

       //Added by rahul on 12 June 2014.
       for(VenWrapper varCCw : VenWraps)
       {
           if(varCCw.selected==true)
          {
           objJTR.Staff__c=varCCw.u.Name;
           update objJTR; 
           blnNothingSelected = true; 
           break;      
           }
       }
       //Addded code ends here       
       if(!blnNothingSelected)
       {
          objJTR.Staff__c='';
           update objJTR;  
       }
       
     PageReference p =  new Pagereference('/apex/JobListView?id='+JobTeamId);
     p.setRedirect(true);
     return p;
     }
       // End of Save Method
 
      // Cancel method to deal with Cancel button 
    public pagereference cancel()
     {
          PageReference p =  new Pagereference('/apex/JobListView?id='+JobTeamId);
          p.setRedirect(true);
          return p;
     }
     // End of Cancel Method 
 
 /* Test Method for Test Coverage 
 Private static testMethod void JobTaskRoleTest()
  {
   Profile p1=[Select Id, Name From Profile where Name=: 'System Administrator' LIMIT 1]; 
   
   //Set up user 
   User u2 = [Select id,IsActive from User where IsActive =: True and ProfileId =:p1.id Limit 1];
   System.RunAs(u2)
    {
      UserRole ur12 = new UserRole(Name = 'Design Manager');
      insert ur12;
      
      Media_Type__c testMedia=new Media_Type__c(Name='Test Media 326');
       try
        {
            insert testMedia;
        }
       catch(System.DMLException e)
        {
            System.assertEquals('FIELD_CUSTOM_VALIDATION',e.getDmlStatusCode(0));
        }
           
      Schedule_Template__c testST=new Schedule_Template__c(Name='Test Schedule Template 326',Media_Types__c=testMedia.Id);
          insert testST;
       
      Specification_Template__c testSpec=new Specification_Template__c(Name='Testing Spcification Template 326');
          insert testSpec;
     
      Job__c testJob1=new Job__c(Name='Test Job 326',Start_Date__c=System.Today(),Media_Types__c=testMedia.Id,Schedule_Template__c=testST.Id,Specification_Template__c=testSpec.Id);
       try
        {
            insert testJob1;
        }
       catch(System.DMLException e)
        {
            System.assertEquals('FIELD_CUSTOM_VALIDATION',e.getDmlStatusCode(0));
        }
       System.assertEquals('Test Job 326',testJob1.Name);       
               
      Job_Team__c testJT=new Job_Team__c(Job__c=testJob1.Id,Role__c='Design Manager');
       try
        {
            insert testJT;
        }       
       catch(System.DMLException e)
        {
            System.assertEquals('FIELD_CUSTOM_VALIDATION',e.getDmlStatusCode(0));
        }
              
      // Instantiate the standard controller with the Job Team 
      
        Staff__c testStaff1=new Staff__c(First_Name__c='Test First Name 1',Last_Name__c='Test Last Name 1',Role__c='Design Manager',Email__c='testEmailStaff1@gmail.com',UserName__c='testEmailStaff1@gmail.com',IsDeleted__c = False);
        insert testStaff1;
                             
        ApexPages.StandardController con = new ApexPages.StandardController(testJT);
        ApexPages.currentPage().getParameters().put('Id',testJT.Id);
    
        // Instantiate the extention instance with the standardcontroller 
        JobTeamAssignUser ext=new JobTeamAssignUser(con);
                
        // Invoke the Save method on the extension
        ApexPages.PageReference result=ext.Save();
        ext.roleWraps[0].selected=true;
        result=ext.Save();
        ApexPages.PageReference result1=ext.cancel();
      
      }//End of RunAs
     
     } End of Test Method */
}// End of Class