objects/Client_Contact__c/Client_Contact__c.object-meta.xml
<CustomObject>
    <description>This Object is used as Child of Client Object.</description>
    <label>Client Contact</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Client Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Client_Contact__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <label>Client</label>
    <referenceTo>Client__c</referenceTo>
    <relationshipLabel>Client Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

objects/GL_Code__c/GL_Code__c.object-meta.xml
<CustomObject>
    <description>GL Codes are used to build line items on our Job Cost Layouts.  The Job Cost Layouts are the Quote, Estimate, Purchase Order, and Vendor Invoice.   The line items on each of these follow similar logic.</description>
    <label>GL Code</label>
    <nameField>
        <label>Description</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GL Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/GL_Code__c/fields/GL_ID__c.field-meta.xml
<CustomField>
    <fullName>GL_ID__c</fullName>
    <description>This is GL ID field. These id&apos;s are auto generated.</description>
    <label>GL Code</label>
    <length>15</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

objects/Job__c/Job__c.object-meta.xml
<CustomObject>
    <description>This is Job object.</description>
    <label>Job</label>
    <nameField>
        <label>Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Job__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Not using currently. Instead created a custom object Client.</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Job__c/fields/JS_Client__c.field-meta.xml
<CustomField>
    <fullName>JS_Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Job is associated with Client object.</description>
    <label>Client</label>
    <referenceTo>Client__c</referenceTo>
    <relationshipName>Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Job__c/fields/Media_Types__c.field-meta.xml
<CustomField>
    <fullName>Media_Types__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Media Type</label>
    <referenceTo>Media_Type__c</referenceTo>
    <relationshipName>Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Job__c/fields/Schedule_Template__c.field-meta.xml
<CustomField>
    <fullName>Schedule_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Schedule Template</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Schedule_Template__c.Media_Types__c</field>
            <operation>equals</operation>
            <valueField>$Source.Media_Types__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Schedule_Template__c</referenceTo>
    <relationshipName>Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Job__c/fields/Specification_Template__c.field-meta.xml
<CustomField>
    <fullName>Specification_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Creative Brief Template</label>
    <referenceTo>Specification_Template__c</referenceTo>
    <relationshipName>Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Job_Task__c/Job_Task__c.object-meta.xml
<CustomObject>
    <description>This is Job Task object. Also known as Schedule.</description>
    <label>Job Task</label>
    <nameField>
        <label>Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Job_Task__c/fields/Days__c.field-meta.xml
<CustomField>
    <fullName>Days__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Days</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

objects/Job_Task__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <label>Staff Email</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

objects/Job_Task__c/fields/GL_Code__c.field-meta.xml
<CustomField>
    <fullName>GL_Code__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GL Code</label>
    <referenceTo>GL_Code__c</referenceTo>
    <relationshipName>Job_Task</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Job_Task__c/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <label>Job Name</label>
    <referenceTo>Job__c</referenceTo>
    <relationshipName>Job_Task</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/Job_Task__c/fields/Revised_Due_Date__c.field-meta.xml
<CustomField>
    <fullName>Revised_Due_Date__c</fullName>
    <label>Final Due Date</label>
    <type>Date</type>
</CustomField>

objects/Job_Task_Role__c/Job_Task_Role__c.object-meta.xml
<CustomObject>
    <description>Staff assigned to the Job Tasks.</description>
    <label>Task Staff Assigned</label>
    <nameField>
        <label>Role</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Task Staff Assigned</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Job_Task_Role__c/fields/Job_Task__c.field-meta.xml
<CustomField>
    <fullName>Job_Task__c</fullName>
    <label>Job Task</label>
    <referenceTo>Job_Task__c</referenceTo>
    <relationshipName>Job_Task_Roles</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/Job_Team__c/Job_Team__c.object-meta.xml
<CustomObject>
    <description>This is Job Team object. It is used to store role and assigned staff to that role for a Job record.</description>
    <label>Job Team</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>JobTeam Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Team</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Job_Team__c/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <label>Job Name</label>
    <referenceTo>Job__c</referenceTo>
    <relationshipLabel>Job Team</relationshipLabel>
    <relationshipName>Job_Team</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/Job_Team__c/fields/Staff__c.field-meta.xml
<CustomField>
    <fullName>Staff__c</fullName>
    <label>Staff</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

objects/Schedule_Task__c/Schedule_Task__c.object-meta.xml
<CustomObject>
    <description>This is Schedule Task object. It is child object of Schedule Template object.</description>
    <label>Schedule Task</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Schedule Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Schedule_Task__c/fields/Days__c.field-meta.xml
<CustomField>
    <fullName>Days__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Days</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

objects/Schedule_Task__c/fields/GL_Code__c.field-meta.xml
<CustomField>
    <fullName>GL_Code__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GL Code</label>
    <referenceTo>GL_Code__c</referenceTo>
    <relationshipLabel>Schedule Tasks</relationshipLabel>
    <relationshipName>Schedule_Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Schedule_Task__c/fields/Schedule_Template__c.field-meta.xml
<CustomField>
    <fullName>Schedule_Template__c</fullName>
    <label>Schedule Template</label>
    <referenceTo>Schedule_Template__c</referenceTo>
    <relationshipLabel>Schedule Tasks</relationshipLabel>
    <relationshipName>Schedule_Tasks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/Schedule_Template__c/Schedule_Template__c.object-meta.xml
<CustomObject>
    <description>This is Schedule Template object.</description>
    <label>Schedule Template</label>
    <nameField>
        <label>Schedule Template</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Schedule Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Schedule_Template__c/fields/Media_Types__c.field-meta.xml
<CustomField>
    <fullName>Media_Types__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Media Type</label>
    <referenceTo>Media_Type__c</referenceTo>
    <relationshipLabel>Schedule Templates</relationshipLabel>
    <relationshipName>Schedule_Templates</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/ScheduleTaskRole__c/ScheduleTaskRole__c.object-meta.xml
<CustomObject>
    <description>This is Schedule Task Role object. It is used to store assign roles to Schedule Task.</description>
    <label>ScheduleTask Role</label>
    <nameField>
        <label>Role</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ScheduleTaskRole</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/ScheduleTaskRole__c/fields/Schedule_Task__c.field-meta.xml
<CustomField>
    <fullName>Schedule_Task__c</fullName>
    <label>Schedule Task</label>
    <referenceTo>Schedule_Task__c</referenceTo>
    <relationshipName>ScheduleTaskRole</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/Staff__c/Staff__c.object-meta.xml
<CustomObject>
    <description>This is Staff object.</description>
    <label>Staff</label>
    <nameField>
        <label>Staff Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Staff</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Staff__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <label>Email</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

objects/Vendor__c/Vendor__c.object-meta.xml
<CustomObject>
    <description>This is Vendor object. Vendors in JobSuite are assigned to the line items on Quotes, Estimates, Purchase Orders and Vendor Invoices.  A printer or photographer may be a vendor.</description>
    <label>Vendor</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vendors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Vendor__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>This is Vendor Email field.</description>
    <label>Email</label>
    <type>Email</type>
</CustomField>

objects/Vendor__c/fields/Vendor__c.field-meta.xml
<CustomField>
    <fullName>Vendor__c</fullName>
    <label>Vendor #</label>
    <length>30</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

objects/Vendor_Contact__c/Vendor_Contact__c.object-meta.xml
<CustomObject>
    <description>This is Vendor Contact Object.</description>
    <label>Vendor Contact</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vendor Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Vendor_Contact__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>this is Email ID of Vendor Contact</description>
    <label>Email</label>
    <type>Email</type>
</CustomField>

objects/Vendor_Contact__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <description>This field contains first name of the vendor.</description>
    <label>First Name</label>
    <length>15</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

objects/Vendor_Contact__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <description>This field contains last name of the vendor.</description>
    <label>Last Name</label>
    <length>15</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

objects/Vendor_Contact__c/fields/Vendor__c.field-meta.xml
<CustomField>
    <fullName>Vendor__c</fullName>
    <label>Vendor</label>
    <referenceTo>Vendor__c</referenceTo>
    <relationshipName>Vendor_Contacts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

classes/Test_JobTeamAddEditStaffExtension.cls
//@isTest
public class Test_JobTeamAddEditStaffExtension{
     // Start Test Coverage 
    /*static testMethod void Test_JobTeamAddEditStaffExtension()
     {
          Job_Number_Setting__c customSetting997 = new  Job_Number_Setting__c(Name= 'yy');

            insert customSetting997;
            Client__c c=new Client__c(name='test client');
            insert c;
            Vendor__c v=new Vendor__c(name='test Vendor');
            insert v;
     
           Media_Type__c testMedia=new Media_Type__c(Name='Test Media 358');
             
                insert testMedia;
             
           Schedule_Template__c testST=new Schedule_Template__c(Name='Test Schedule Template 358',Media_Types__c=testMedia.Id);
             
                insert testST;
      
           GL_Code__c testGL=new GL_Code__c(Name='Test GL Code',GL_ID__c='Test GL009');
             
                insert testGL;
            
           Schedule_Task__c testSCT1=new Schedule_Task__c(Name='Test Schedule Task 358',Schedule_Template__c=testST.Id,Days__c=5,GL_Code__c=testGL.Id);
            
                insert testSCT1;
                
            Schedule_Task__c testSCT2=new Schedule_Task__c(Name='Test Schedule Task 359',Schedule_Template__c=testST.Id,Days__c=3,GL_Code__c=testGL.Id);
            
                insert testSCT2;
             
            ScheduleTaskRole__c testSTR1=new ScheduleTaskRole__c(Name='Designer',Schedule_Task__c=testSCT1.Id);
            
                insert testSTR1;
           
            ScheduleTaskRole__c testSTR3=new ScheduleTaskRole__c(Name='Art Director',Schedule_Task__c=testSCT1.Id);
            
                insert testSTR3;
           
            ScheduleTaskRole__c testSTR2=new ScheduleTaskRole__c(Name='Project Manager',Schedule_Task__c=testSCT2.Id);
               
                insert testSTR2;
           
           Specification_Template__c testSpec=new Specification_Template__c(Name='Testing Spcification Template 359');
           
                insert testSpec;
      
           Job__c testJob1=new Job__c(Name='Test Job 360',Start_Date__c=System.Today(),Media_Types__c=testMedia.Id,Schedule_Template__c=testST.Id,Specification_Template__c=testSpec.Id,JS_Client__c=c.id);
               try
               {
                   insert testJob1;
               }
               catch(System.DMLException e)
               {
                    System.assertEquals('FIELD_CUSTOM_VALIDATION_EXCEPTION', e.getDmlStatusCode(0));
               }
           System.assertEquals('Test Job 360',testJob1.Name);    
           
           Job_Task__c testJTS1=new Job_Task__c(Name='Test JT 897',Days__c=2,Job__c=testJob1.id,Revised_Due_Date__c=System.Today()+15,Email__C='mani@gmail.com');
          
                  insert testJTS1;
           Job_Task_Role__c testJTR1=new Job_Task_Role__c(Name='Test JT 897',Job_Task__c=testJTS1.Id,Email__C='mani@gmail.com');
        
                insert testJTR1;  
                      
                  
        
          
           Job_Team__c testJT1=new Job_Team__c(Job__c=testJob1.Id,Role__c='Designer');
           
               insert testJT1;
               
           Job_Team__c testJT2=new Job_Team__c(Job__c=testJob1.Id,Role__c='Project Manager',Staff__c='manikanta',Email__C='mani@gmail.com');
           
               insert testJT2;
               
           Job_Team__c testJT3=new Job_Team__c(Job__c=testJob1.Id,Role__c='Art Director',Staff__c='manikanta',Email__C='mani@gmail.com');
              
             insert testJT3;
             
             Job_Task__c testJTS12=new Job_Task__c(Name='Designer',Days__c=2,Job__c=testJob1.id,Revised_Due_Date__c=System.Today()+15,Email__C='mani@gmail.com');
          
                  insert testJTS12;
             
          Job_Task_Role__c testJTR2=new Job_Task_Role__c(Name='Designer',Job_Task__c=testJTS12.Id,Email__C='mani@gmail.com');
        
                insert testJTR2;   
             
         list<Job_Task_Role__c> lstJTRDelete11= [Select Id,Job_Task__c,Job_Task__r.Job__c from Job_Task_Role__c where Name=: testJT1.Role__c and Job_Task__r.Job__c =: testJT1.job__c ];

             delete lstJTRDelete11;
               
           ApexPages.currentPage().getParameters().put('Id', testJob1.Id);
         
               // Instantiate the standard controller with the Job
           ApexPages.StandardController con=new ApexPages.StandardController(testJob1);
        
           // Instantiate the extention instance with the standardcontroller 
               JobTeamAddEditStaffExtension ext=new JobTeamAddEditStaffExtension(con);
        
           // Invoke the primary method on the extension
         
           Job_Team__c testJT4=new Job_Team__c();
            try
             {
                insert testJT4;
             }
            catch(System.DMLException e)
             {
                System.assertEquals('REQUIRED_FIELD_MISSING' , e.getDmlStatusCode(0));
             }
             
           
        
           ApexPages.currentPage().getParameters().put('Id', testJob1.Id);
         
            // Instantiate the standard controller with the Job 
           ApexPages.StandardController con2=new ApexPages.StandardController(testJob1);
        
            // Instantiate the extention instance with the standardcontroller 
            JobTeamAddEditStaffExtension ext2=new JobTeamAddEditStaffExtension(con2);
        
            // Invoke the primary method on the extension 

          
        
            Staff__c testStaff1=new Staff__c(First_Name__c='Test First Name 1',Last_Name__c='Test Last Name 1',Role__c='Designer',Email__c='testEmailStaff1@gmail.com',UserName__c='testEmailStaff1@gmail.com');
            insert testStaff1;
            
            Staff__c testStaff2=new Staff__c(First_Name__c='Test First Name 2',Last_Name__c='Test Last Name 2',Role__c='Project Manager',Email__c='testEmailStaff2@gmail.com',UserName__c='testEmailStaff2@gmail.com');
            insert testStaff2;
            
            Staff__c testStaff3=new Staff__c(First_Name__c='Test First Name 3',Last_Name__c='Test Last Name 3',Role__c='Art Director',Email__c='testEmailStaff3@gmail.com',UserName__c='testEmailStaff3@gmail.com');
            insert testStaff3;
            
            
            Client_Contact__c  testcc1=new Client_Contact__c(Client__c=c.id,First_Name__c='TestFirstName6',Last_Name__c='TestLasNam1',Client_Contact_Role__c='Designer',Email__c='testEmailStaff17@gmail.com',UserName__c='testEmailStaff176@gmail.com');
            insert testcc1;
            
            Client_Contact__c  testcc2=new Client_Contact__c(Client__c=c.id,First_Name__c='TestFirstName6',Last_Name__c='TestLastName 1',Client_Contact_Role__c='Designer',Email__c='testEmailStaff17@gmail.com',UserName__c='testEmailStaff167@gmail.com');
            insert testcc2;
            
            Vendor_Contact__c testVC1=new Vendor_Contact__c(Vendor__c=v.id,First_Name__c='TestFirstName7',Last_Name__c='TestLastName2',Role__c='Project Manager',Email__c='testEmailStaff72@gmail.com',User_Name__c='testEmailStaff9602@gmail.com');
            insert testVC1;
            
            
            Vendor_Contact__c  testVC2=new Vendor_Contact__c(Vendor__c=v.id,First_Name__c='TestFirstName7',Last_Name__c='TestLasName2',Role__c='Project Manager',Email__c='testEmailStaff72@gmail.com',User_Name__c='testEmailStaff9602@gmail.com');
            insert testVC2;
           
              List<SelectOption> Rtypes=ext2.getStatusList();
              
              ext2.StatusString ='Staff';
              
            ext2.SerachStaff();
            Job_Team__c testJT5=new Job_Team__c(Job__c=testJob1.Id,Role__c='Art Director',staff__c='manikanta',Email__C='mani@gmail.com');
              
             insert testJT5;
            
            ApexPages.PageReference result4=ext2.Addstaff();
            ApexPages.PageReference result5=ext2.cancel();
         ext2.DisplayChart();
         ext2.DisplayChart1();
    }
  // End of Test method JobTeam Test 
  
    static testMethod void Test_JobTeamAddEditStaffExtension1()
     {
          Job_Number_Setting__c customSetting997 = new  Job_Number_Setting__c(Name= 'yy');

            insert customSetting997;
            Client__c c=new Client__c(name='test client');
            insert c;
            Vendor__c v=new Vendor__c(name='test Vendor');
            insert v;
     
           Media_Type__c testMedia=new Media_Type__c(Name='Test Media 358');
             
                insert testMedia;
             
           Schedule_Template__c testST=new Schedule_Template__c(Name='Test Schedule Template 358',Media_Types__c=testMedia.Id);
             
                insert testST;
      
           GL_Code__c testGL=new GL_Code__c(Name='Test GL Code',GL_ID__c='Test GL009');
             
                insert testGL;
            
           Schedule_Task__c testSCT1=new Schedule_Task__c(Name='Test Schedule Task 358',Schedule_Template__c=testST.Id,Days__c=5,GL_Code__c=testGL.Id);
            
                insert testSCT1;
                
            Schedule_Task__c testSCT2=new Schedule_Task__c(Name='Test Schedule Task 359',Schedule_Template__c=testST.Id,Days__c=3,GL_Code__c=testGL.Id);
            
                insert testSCT2;
             
            ScheduleTaskRole__c testSTR1=new ScheduleTaskRole__c(Name='Designer',Schedule_Task__c=testSCT1.Id);
            
                insert testSTR1;
           
            ScheduleTaskRole__c testSTR3=new ScheduleTaskRole__c(Name='Art Director',Schedule_Task__c=testSCT1.Id);
            
                insert testSTR3;
           
            ScheduleTaskRole__c testSTR2=new ScheduleTaskRole__c(Name='Project Manager',Schedule_Task__c=testSCT2.Id);
               
                insert testSTR2;
           
           Specification_Template__c testSpec=new Specification_Template__c(Name='Testing Spcification Template 359');
           
                insert testSpec;
      
           Job__c testJob1=new Job__c(Name='Test Job 360',Start_Date__c=System.Today(),Media_Types__c=testMedia.Id,Schedule_Template__c=testST.Id,Specification_Template__c=testSpec.Id,JS_Client__c=c.id);
               try
               {
                   insert testJob1;
               }
               catch(System.DMLException e)
               {
                    System.assertEquals('FIELD_CUSTOM_VALIDATION_EXCEPTION', e.getDmlStatusCode(0));
               }
           System.assertEquals('Test Job 360',testJob1.Name);    
           
           Job_Task__c testJTS1=new Job_Task__c(Name='Test JT 897',Days__c=2,Job__c=testJob1.id,Revised_Due_Date__c=System.Today()+15,Email__C='mani@gmail.com');
          
                  insert testJTS1;
           Job_Task_Role__c testJTR1=new Job_Task_Role__c(Name='Test JT 897',Job_Task__c=testJTS1.Id,Email__C='mani@gmail.com');
        
                insert testJTR1;  
                      
                  
        
          
           Job_Team__c testJT1=new Job_Team__c(Job__c=testJob1.Id,Role__c='Designer',Email__C='mani@gmail.com');
           
               insert testJT1;
               
           Job_Team__c testJT2=new Job_Team__c(Job__c=testJob1.Id,Role__c='Project Manager',Email__C='mani@gmail.com');
           
               insert testJT2;
               
           Job_Team__c testJT3=new Job_Team__c(Job__c=testJob1.Id,Role__c='Art Director',Email__C='mani@gmail.com');
              
             insert testJT3;
             
             Job_Task__c testJTS12=new Job_Task__c(Name='Designer',Days__c=2,Job__c=testJob1.id,Revised_Due_Date__c=System.Today()+15,Email__C='mani@gmail.com');
          
                  insert testJTS12;
             
          Job_Task_Role__c testJTR2=new Job_Task_Role__c(Name='Designer',Job_Task__c=testJTS12.Id,Email__C='mani@gmail.com');
        
                insert testJTR2;   
             
         list<Job_Task_Role__c> lstJTRDelete11= [Select Id,Job_Task__c,Job_Task__r.Job__c,Email__C from Job_Task_Role__c where Name=: testJT1.Role__c and Job_Task__r.Job__c =: testJT1.job__c ];

             delete lstJTRDelete11;
               
           ApexPages.currentPage().getParameters().put('Id', testJob1.Id);
         
               // Instantiate the standard controller with the Job
           ApexPages.StandardController con=new ApexPages.StandardController(testJob1);
        
           // Instantiate the extention instance with the standardcontroller 
               JobTeamAddEditStaffExtension ext=new JobTeamAddEditStaffExtension(con);
        
           // Invoke the primary method on the extension
         
           Job_Team__c testJT4=new Job_Team__c();
            try
             {
                insert testJT4;
             }
            catch(System.DMLException e)
             {
                System.assertEquals('REQUIRED_FIELD_MISSING' , e.getDmlStatusCode(0));
             }
             
           
        
           ApexPages.currentPage().getParameters().put('Id', testJob1.Id);
         
            // Instantiate the standard controller with the Job 
           ApexPages.StandardController con2=new ApexPages.StandardController(testJob1);
        
            // Instantiate the extention instance with the standardcontroller 
            JobTeamAddEditStaffExtension ext2=new JobTeamAddEditStaffExtension(con2);
        
            // Invoke the primary method on the extension 

          
        
            Staff__c testStaff1=new Staff__c(First_Name__c='Test First Name 1',Last_Name__c='Test Last Name 1',Role__c='Designer',Email__c='testEmailStaff1@gmail.com',UserName__c='testEmailStaff1@gmail.com');
            insert testStaff1;
            
            Staff__c testStaff2=new Staff__c(First_Name__c='Test First Name 2',Last_Name__c='Test Last Name 2',Role__c='Project Manager',Email__c='testEmailStaff2@gmail.com',UserName__c='testEmailStaff2@gmail.com');
            insert testStaff2;
            
            Staff__c testStaff3=new Staff__c(First_Name__c='Test First Name 3',Last_Name__c='Test Last Name 3',Role__c='Art Director',Email__c='testEmailStaff3@gmail.com',UserName__c='testEmailStaff3@gmail.com');
            insert testStaff3;
            
            
            Client_Contact__c  testcc1=new Client_Contact__c(Client__c=c.id,First_Name__c='TestFirstName6',Last_Name__c='TestLasNam1',Client_Contact_Role__c='Designer',Email__c='testEmailStaff17@gmail.com',UserName__c='testEmailStaff176@gmail.com');
            insert testcc1;
            
            Client_Contact__c  testcc2=new Client_Contact__c(Client__c=c.id,First_Name__c='TestFirstName6',Last_Name__c='TestLastName 1',Client_Contact_Role__c='Designer',Email__c='testEmailStaff17@gmail.com',UserName__c='testEmailStaff167@gmail.com');
            insert testcc2;
            
            Vendor_Contact__c testVC1=new Vendor_Contact__c(Vendor__c=v.id,First_Name__c='TestFirstName7',Last_Name__c='TestLastName2',Role__c='Project Manager',Email__c='testEmailStaff72@gmail.com',User_Name__c='testEmailStaff9602@gmail.com');
            insert testVC1;
            
            
            Vendor_Contact__c  testVC2=new Vendor_Contact__c(Vendor__c=v.id,First_Name__c='TestFirstName7',Last_Name__c='TestLasName2',Role__c='Project Manager',Email__c='testEmailStaff72@gmail.com',User_Name__c='testEmailStaff9602@gmail.com');
            insert testVC2;
           
              List<SelectOption> Rtypes=ext2.getStatusList();
              
              ext2.StatusString ='All';
              
            ext2.SerachStaff();
            Job_Team__c testJT5=new Job_Team__c(Job__c=testJob1.Id,Role__c='Art Director',staff__c='manikanta',Email__C='mani@gmail.com');
              
             insert testJT5;
            
            ApexPages.PageReference result4=ext2.Addstaff();
            ApexPages.PageReference result5=ext2.cancel();
          ext2.DisplayChart();
         ext2.DisplayChart1();
    }
  // End of Test method JobTeam Test 
  
   static testMethod void Test_JobTeamAddEditStaffExtension12()
     {
          Job_Number_Setting__c customSetting997 = new  Job_Number_Setting__c(Name= 'yy');

            insert customSetting997;
            Client__c c=new Client__c(name='test client');
            insert c;
            Vendor__c v=new Vendor__c(name='test Vendor');
            insert v;
     
           Media_Type__c testMedia=new Media_Type__c(Name='Test Media 358');
             
                insert testMedia;
             
           Schedule_Template__c testST=new Schedule_Template__c(Name='Test Schedule Template 358',Media_Types__c=testMedia.Id);
             
                insert testST;
      
           GL_Code__c testGL=new GL_Code__c(Name='Test GL Code',GL_ID__c='Test GL009');
             
                insert testGL;
            
           Schedule_Task__c testSCT1=new Schedule_Task__c(Name='Test Schedule Task 358',Schedule_Template__c=testST.Id,Days__c=5,GL_Code__c=testGL.Id);
            
                insert testSCT1;
                
            Schedule_Task__c testSCT2=new Schedule_Task__c(Name='Test Schedule Task 359',Schedule_Template__c=testST.Id,Days__c=3,GL_Code__c=testGL.Id);
            
                insert testSCT2;
             
            ScheduleTaskRole__c testSTR1=new ScheduleTaskRole__c(Name='Designer',Schedule_Task__c=testSCT1.Id);
            
                insert testSTR1;
           
            ScheduleTaskRole__c testSTR3=new ScheduleTaskRole__c(Name='Art Director',Schedule_Task__c=testSCT1.Id);
            
                insert testSTR3;
           
            ScheduleTaskRole__c testSTR2=new ScheduleTaskRole__c(Name='Project Manager',Schedule_Task__c=testSCT2.Id);
               
                insert testSTR2;
           
           Specification_Template__c testSpec=new Specification_Template__c(Name='Testing Spcification Template 359');
           
                insert testSpec;
      
           Job__c testJob1=new Job__c(Name='Test Job 360',Start_Date__c=System.Today(),Media_Types__c=testMedia.Id,Schedule_Template__c=testST.Id,Specification_Template__c=testSpec.Id,JS_Client__c=c.id);
               try
               {
                   insert testJob1;
               }
               catch(System.DMLException e)
               {
                    System.assertEquals('FIELD_CUSTOM_VALIDATION_EXCEPTION', e.getDmlStatusCode(0));
               }
           System.assertEquals('Test Job 360',testJob1.Name);    
           
           Job_Task__c testJTS1=new Job_Task__c(Name='Test JT 897',Days__c=2,Job__c=testJob1.id,Revised_Due_Date__c=System.Today()+15,Email__C='mani@gmail.com');
          
                  insert testJTS1;
           Job_Task_Role__c testJTR1=new Job_Task_Role__c(Name='Test JT 897',Job_Task__c=testJTS1.Id,Email__C='mani@gmail.com');
        
                insert testJTR1;  
                      
                  
        
          
           Job_Team__c testJT1=new Job_Team__c(Job__c=testJob1.Id,Role__c='Designer',Email__C='mani@gmail.com');
           
               insert testJT1;
               
           Job_Team__c testJT2=new Job_Team__c(Job__c=testJob1.Id,Role__c='Project Manager',Email__C='mani@gmail.com');
           
               insert testJT2;
               
           Job_Team__c testJT3=new Job_Team__c(Job__c=testJob1.Id,Role__c='Art Director',Email__C='mani@gmail.com');
              
             insert testJT3;
             
             Job_Task__c testJTS12=new Job_Task__c(Name='Designer',Days__c=2,Job__c=testJob1.id,Revised_Due_Date__c=System.Today()+15,Email__C='mani@gmail.com');
          
                  insert testJTS12;
             
          Job_Task_Role__c testJTR2=new Job_Task_Role__c(Name='Designer',Job_Task__c=testJTS12.Id,Email__C='mani@gmail.com');
        
                insert testJTR2;   
             
         list<Job_Task_Role__c> lstJTRDelete11= [Select Id,Job_Task__c,Job_Task__r.Job__c from Job_Task_Role__c where Name=: testJT1.Role__c and Job_Task__r.Job__c =: testJT1.job__c ];

             delete lstJTRDelete11;
               
           ApexPages.currentPage().getParameters().put('Id', testJob1.Id);
         
               // Instantiate the standard controller with the Job
           ApexPages.StandardController con=new ApexPages.StandardController(testJob1);
        
           // Instantiate the extention instance with the standardcontroller 
               JobTeamAddEditStaffExtension ext=new JobTeamAddEditStaffExtension(con);
        
           // Invoke the primary method on the extension
         
           Job_Team__c testJT4=new Job_Team__c();
            try
             {
                insert testJT4;
             }
            catch(System.DMLException e)
             {
                System.assertEquals('REQUIRED_FIELD_MISSING' , e.getDmlStatusCode(0));
             }
             
           
        
           ApexPages.currentPage().getParameters().put('Id', testJob1.Id);
         
            // Instantiate the standard controller with the Job 
           ApexPages.StandardController con2=new ApexPages.StandardController(testJob1);
        
            // Instantiate the extention instance with the standardcontroller 
            JobTeamAddEditStaffExtension ext2=new JobTeamAddEditStaffExtension(con2);
        
            // Invoke the primary method on the extension 

          
        
            Staff__c testStaff1=new Staff__c(First_Name__c='Test First Name 1',Last_Name__c='Test Last Name 1',Role__c='Designer',Email__c='testEmailStaff1@gmail.com',UserName__c='testEmailStaff1@gmail.com');
            insert testStaff1;
            
            Staff__c testStaff2=new Staff__c(First_Name__c='Test First Name 2',Last_Name__c='Test Last Name 2',Role__c='Project Manager',Email__c='testEmailStaff2@gmail.com',UserName__c='testEmailStaff2@gmail.com');
            insert testStaff2;
            
            Staff__c testStaff3=new Staff__c(First_Name__c='Test First Name 3',Last_Name__c='Test Last Name 3',Role__c='Art Director',Email__c='testEmailStaff3@gmail.com',UserName__c='testEmailStaff3@gmail.com');
            insert testStaff3;
            
            
            Client_Contact__c  testcc1=new Client_Contact__c(Client__c=c.id,First_Name__c='TestFirstName6',Last_Name__c='TestLasNam1',Client_Contact_Role__c='Designer',Email__c='testEmailStaff17@gmail.com',UserName__c='testEmailStaff176@gmail.com');
            insert testcc1;
            
            Client_Contact__c  testcc2=new Client_Contact__c(Client__c=c.id,First_Name__c='TestFirstName6',Last_Name__c='TestLastName 1',Client_Contact_Role__c='Designer',Email__c='testEmailStaff17@gmail.com',UserName__c='testEmailStaff167@gmail.com');
            insert testcc2;
            
            Vendor_Contact__c testVC1=new Vendor_Contact__c(Vendor__c=v.id,First_Name__c='TestFirstName7',Last_Name__c='TestLastName2',Role__c='Project Manager',Email__c='testEmailStaff72@gmail.com',User_Name__c='testEmailStaff9602@gmail.com');
            insert testVC1;
            
            
            Vendor_Contact__c  testVC2=new Vendor_Contact__c(Vendor__c=v.id,First_Name__c='TestFirstName7',Last_Name__c='TestLasName2',Role__c='Project Manager',Email__c='testEmailStaff72@gmail.com',User_Name__c='testEmailStaff9602@gmail.com');
            insert testVC2;
           
              List<SelectOption> Rtypes=ext2.getStatusList();
              
              ext2.StatusString ='Client Contact';
              
            ext2.SerachStaff();
            Job_Team__c testJT5=new Job_Team__c(Job__c=testJob1.Id,Role__c='Art Director',staff__c='manikanta',Email__C='mani@gmail.com');
              
             insert testJT5;
            
            ApexPages.PageReference result4=ext2.Addstaff();
            ApexPages.PageReference result5=ext2.cancel();
          ext2.DisplayChart();
         ext2.DisplayChart1();
    }
  // End of Test method JobTeam Test 
  
  static testMethod void Test_JobTeamAddEditStaffExtension123()
     {
          Job_Number_Setting__c customSetting997 = new  Job_Number_Setting__c(Name= 'yy');

            insert customSetting997;
            Client__c c=new Client__c(name='test client');
            insert c;
            Vendor__c v=new Vendor__c(name='test Vendor');
            insert v;
     
           Media_Type__c testMedia=new Media_Type__c(Name='Test Media 358');
             
                insert testMedia;
             
           Schedule_Template__c testST=new Schedule_Template__c(Name='Test Schedule Template 358',Media_Types__c=testMedia.Id);
             
                insert testST;
      
           GL_Code__c testGL=new GL_Code__c(Name='Test GL Code',GL_ID__c='Test GL009');
             
                insert testGL;
            
           Schedule_Task__c testSCT1=new Schedule_Task__c(Name='Test Schedule Task 358',Schedule_Template__c=testST.Id,Days__c=5,GL_Code__c=testGL.Id);
            
                insert testSCT1;
                
            Schedule_Task__c testSCT2=new Schedule_Task__c(Name='Test Schedule Task 359',Schedule_Template__c=testST.Id,Days__c=3,GL_Code__c=testGL.Id);
            
                insert testSCT2;
             
            ScheduleTaskRole__c testSTR1=new ScheduleTaskRole__c(Name='Designer',Schedule_Task__c=testSCT1.Id);
            
                insert testSTR1;
           
            ScheduleTaskRole__c testSTR3=new ScheduleTaskRole__c(Name='Art Director',Schedule_Task__c=testSCT1.Id);
            
                insert testSTR3;
           
            ScheduleTaskRole__c testSTR2=new ScheduleTaskRole__c(Name='Project Manager',Schedule_Task__c=testSCT2.Id);
               
                insert testSTR2;
           
           Specification_Template__c testSpec=new Specification_Template__c(Name='Testing Spcification Template 359');
           
                insert testSpec;
      
           Job__c testJob1=new Job__c(Name='Test Job 360',Start_Date__c=System.Today(),Media_Types__c=testMedia.Id,Schedule_Template__c=testST.Id,Specification_Template__c=testSpec.Id,JS_Client__c=c.id);
               try
               {
                   insert testJob1;
               }
               catch(System.DMLException e)
               {
                    System.assertEquals('FIELD_CUSTOM_VALIDATION_EXCEPTION', e.getDmlStatusCode(0));
               }
           System.assertEquals('Test Job 360',testJob1.Name);    
           
           Job_Task__c testJTS1=new Job_Task__c(Name='Test JT 897',Days__c=2,Job__c=testJob1.id,Revised_Due_Date__c=System.Today()+15,Email__C='mani@gmail.com');
          
                  insert testJTS1;
           Job_Task_Role__c testJTR1=new Job_Task_Role__c(Name='Test JT 897',Job_Task__c=testJTS1.Id,Email__C='mani@gmail.com');
        
                insert testJTR1;  
                      
                  
        
          
           Job_Team__c testJT1=new Job_Team__c(Job__c=testJob1.Id,Role__c='Designer',Email__C='mani@gmail.com');
           
               insert testJT1;
               
           Job_Team__c testJT2=new Job_Team__c(Job__c=testJob1.Id,Role__c='Project Manager',Email__C='mani@gmail.com');
           
               insert testJT2;
               
           Job_Team__c testJT3=new Job_Team__c(Job__c=testJob1.Id,Role__c='Art Director',Email__C='mani@gmail.com');
              
             insert testJT3;
             
             Job_Task__c testJTS12=new Job_Task__c(Name='Designer',Days__c=2,Job__c=testJob1.id,Revised_Due_Date__c=System.Today()+15,Email__C='mani@gmail.com');
          
                  insert testJTS12;
             
          Job_Task_Role__c testJTR2=new Job_Task_Role__c(Name='Designer',Job_Task__c=testJTS12.Id,Email__C='mani@gmail.com');
        
                insert testJTR2;   
             
         list<Job_Task_Role__c> lstJTRDelete11= [Select Id,Job_Task__c,Job_Task__r.Job__c from Job_Task_Role__c where Name=: testJT1.Role__c and Job_Task__r.Job__c =: testJT1.job__c ];

             delete lstJTRDelete11;
               
           ApexPages.currentPage().getParameters().put('Id', testJob1.Id);
         
               // Instantiate the standard controller with the Job
           ApexPages.StandardController con=new ApexPages.StandardController(testJob1);
        
           // Instantiate the extention instance with the standardcontroller 
               JobTeamAddEditStaffExtension ext=new JobTeamAddEditStaffExtension(con);
        
           // Invoke the primary method on the extension
         
           Job_Team__c testJT4=new Job_Team__c();
            try
             {
                insert testJT4;
             }
            catch(System.DMLException e)
             {
                System.assertEquals('REQUIRED_FIELD_MISSING' , e.getDmlStatusCode(0));
             }
             
           
        
           ApexPages.currentPage().getParameters().put('Id', testJob1.Id);
         
            // Instantiate the standard controller with the Job 
           ApexPages.StandardController con2=new ApexPages.StandardController(testJob1);
        
            // Instantiate the extention instance with the standardcontroller 
            JobTeamAddEditStaffExtension ext2=new JobTeamAddEditStaffExtension(con2);
        
            // Invoke the primary method on the extension 

          
        
            Staff__c testStaff1=new Staff__c(First_Name__c='Test First Name 1',Last_Name__c='Test Last Name 1',Role__c='Designer',Email__c='testEmailStaff1@gmail.com',UserName__c='testEmailStaff1@gmail.com');
            insert testStaff1;
            
            Staff__c testStaff2=new Staff__c(First_Name__c='Test First Name 2',Last_Name__c='Test Last Name 2',Role__c='Project Manager',Email__c='testEmailStaff2@gmail.com',UserName__c='testEmailStaff2@gmail.com');
            insert testStaff2;
            
            Staff__c testStaff3=new Staff__c(First_Name__c='Test First Name 3',Last_Name__c='Test Last Name 3',Role__c='Art Director',Email__c='testEmailStaff3@gmail.com',UserName__c='testEmailStaff3@gmail.com');
            insert testStaff3;
            
            
            Client_Contact__c  testcc1=new Client_Contact__c(Client__c=c.id,First_Name__c='TestFirstName6',Last_Name__c='TestLasNam1',Client_Contact_Role__c='Designer',Email__c='testEmailStaff17@gmail.com',UserName__c='testEmailStaff176@gmail.com');
            insert testcc1;
            
            Client_Contact__c  testcc2=new Client_Contact__c(Client__c=c.id,First_Name__c='TestFirstName6',Last_Name__c='TestLastName 1',Client_Contact_Role__c='Designer',Email__c='testEmailStaff17@gmail.com',UserName__c='testEmailStaff167@gmail.com');
            insert testcc2;
            
            Vendor_Contact__c testVC1=new Vendor_Contact__c(Vendor__c=v.id,First_Name__c='TestFirstName7',Last_Name__c='TestLastName2',Role__c='Project Manager',Email__c='testEmailStaff72@gmail.com',User_Name__c='testEmailStaff9602@gmail.com');
            insert testVC1;
            
            
            Vendor_Contact__c  testVC2=new Vendor_Contact__c(Vendor__c=v.id,First_Name__c='TestFirstName7',Last_Name__c='TestLasName2',Role__c='Project Manager',Email__c='testEmailStaff72@gmail.com',User_Name__c='testEmailStaff9602@gmail.com');
            insert testVC2;
           
              List<SelectOption> Rtypes=ext2.getStatusList();
              
              ext2.StatusString ='Vendor Contact';
              
            ext2.SerachStaff();
            Job_Team__c testJT5=new Job_Team__c(Job__c=testJob1.Id,Role__c='Art Director',staff__c='manikanta',Email__C='mani@gmail.com');
              
             insert testJT5;
            
            ApexPages.PageReference result4=ext2.Addstaff();
            ApexPages.PageReference result5=ext2.cancel();
          ext2.DisplayChart();
         ext2.DisplayChart1();
    }
  // End of Test method JobTeam Test
  
  */
  
  
  
  
}