objects/Graphics_Setting__c/Graphics_Setting__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This Setting is used to display Graphics for Job if record value is set to Yes.</description>
    <label>Graphics Setting</label>
</CustomObject>

objects/Job__c/Job__c.object-meta.xml
<CustomObject>
    <description>This is Job object.</description>
    <label>Job</label>
    <nameField>
        <label>Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Job__c/fields/Flag__c.field-meta.xml
<CustomField>
    <fullName>Flag__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This is flag field to check import process.</description>
    <label>Flag</label>
    <type>Checkbox</type>
</CustomField>

objects/Job__c/fields/Job_Auto_Number__c.field-meta.xml
<CustomField>
    <fullName>Job_Auto_Number__c</fullName>
    <defaultValue>&quot;Auto Fill&quot;</defaultValue>
    <externalId>true</externalId>
    <label>Job #</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

objects/Job__c/fields/Media_Types__c.field-meta.xml
<CustomField>
    <fullName>Media_Types__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Media Type</label>
    <referenceTo>Media_Type__c</referenceTo>
    <relationshipName>Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Job__c/fields/Schedule_Template__c.field-meta.xml
<CustomField>
    <fullName>Schedule_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Schedule Template</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Schedule_Template__c.Media_Types__c</field>
            <operation>equals</operation>
            <valueField>$Source.Media_Types__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Schedule_Template__c</referenceTo>
    <relationshipName>Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Job__c/fields/Specification_Template__c.field-meta.xml
<CustomField>
    <fullName>Specification_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Creative Brief Template</label>
    <referenceTo>Specification_Template__c</referenceTo>
    <relationshipName>Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Job_Number_Setting__c/Job_Number_Setting__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This is Job Auto Number setting to set the Job Number format.</description>
    <label>Job Number</label>
</CustomObject>

objects/Media_Type__c/Media_Type__c.object-meta.xml
<CustomObject>
    <description>This is Media Type object.</description>
    <label>Media Type</label>
    <nameField>
        <label>Media Type</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Media Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Music_Usage_Setting__c/Music_Usage_Setting__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This Setting is used to display Music Usage for Job if record value is set to YES.</description>
    <label>Music Usage</label>
</CustomObject>

objects/Schedule_Template__c/Schedule_Template__c.object-meta.xml
<CustomObject>
    <description>This is Schedule Template object.</description>
    <label>Schedule Template</label>
    <nameField>
        <label>Schedule Template</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Schedule Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Schedule_Template__c/fields/Media_Types__c.field-meta.xml
<CustomField>
    <fullName>Media_Types__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Media Type</label>
    <referenceTo>Media_Type__c</referenceTo>
    <relationshipLabel>Schedule Templates</relationshipLabel>
    <relationshipName>Schedule_Templates</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Session_setting__c/Session_setting__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This Custom setting is used to display Session under Job if record value is set to Yes.</description>
    <label>Session setting</label>
</CustomObject>

objects/Specification_Template__c/Specification_Template__c.object-meta.xml
<CustomObject>
    <description>This is Creative Brief Template object. Also known as Specification Template.</description>
    <label>Creative Brief Template</label>
    <nameField>
        <label>Creative Brief Template</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Creative Brief Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Tag_Setting__c/Tag_Setting__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This Setting is used to display Tag for Job if record value is set to Yes.</description>
    <label>Tag Setting</label>
</CustomObject>

classes/TesttestTabController.cls
//@isTest
Public class TesttestTabController{
/*
 
    // Test Coverage 
         static testMethod void TesttestTabController()
        {
             Job_Number_Setting__c customSetting001 = new  Job_Number_Setting__c(Name= 'yy');
              
                 insert customSetting001; 
             
              Graphics_Setting__c customGraphics= new Graphics_Setting__c(Name = 'YES');
              
                  insert customGraphics;
                  
              Session_Setting__c customSession= new Session_Setting__c(Name = 'YES');
                  
                  insert customSession;
                  
               Tag_Setting__c customTag = new Tag_Setting__c(Name = 'YES');
                   
                   insert customTag;   
                   
               Music_Usage_Setting__c  customMusic = new Music_Usage_Setting__c(Name = 'YES');  
                   
                    insert customMUsic;   
                  
               Media_Type__c testMedia=new Media_Type__c(Name='Test Media 301');
             
                     insert testMedia;
             
              Schedule_Template__c testST=new Schedule_Template__c(Name='Test Schedule Template 301',Media_Types__c=testMedia.Id);
             
                 insert testST;
                 
              Schedule_Template__c testST1=new Schedule_Template__c(Name='Test Schedule Template 302',Media_Types__c=testMedia.Id);
             
                  insert testST1;
                 
              Specification_Template__c testSpec=new Specification_Template__c(Name='Testing Spcification Template 301');
                insert testSpec;
                
                Specification_Template__c testSpec1=new Specification_Template__c(Name='Testing Spcification Template 302');
                insert testSpec1;
           
            
               Job__c testJob1=new Job__c(Name='Test Job 301',Flag__c=True,Job_Auto_Number__c='Job12347',Start_Date__c=System.Today(),Media_Types__c=testMedia.Id,Schedule_Template__c=testST.Id,Specification_Template__c=testSpec.Id);
               try
               {
                   insert testJob1;
               }
               catch(System.DMLException e)
               {
                   System.assert(e.getMessage().contains('Job with same name Exists'));
               }
               
               System.assertEquals('Test Job 301',testJob1.Name);
          
              // Instantiate the extention instance with the standard controller : Details Tab
              
              ApexPages.StandardController con1=new ApexPages.StandardController(testJob1);
              ApexPages.currentPage().getParameters().put('intFocus', '1');
              testTabController ext1=new testTabController(con1);
             
              // Instantiate the extention instance with the standard controller : Schedules Tab
              
              ApexPages.StandardController con2=new ApexPages.StandardController(testJob1);
              ApexPages.currentPage().getParameters().put('intFocus', '2');
              testTabController ext2=new testTabController(con2);
             
              // Instantiate the extention instance with the standard controller : Creative Brief Tab
              
              ApexPages.StandardController con3=new ApexPages.StandardController(testJob1);
              ApexPages.currentPage().getParameters().put('intFocus', '3');
              testTabController ext3=new testTabController(con3);
              
              // Instantiate the extention instance with the standard controller : Quotes Tab
              
              ApexPages.StandardController con4=new ApexPages.StandardController(testJob1);
              ApexPages.currentPage().getParameters().put('intFocus', '4');
              testTabController ext4=new testTabController(con4);
             
              // Instantiate the extention instance with the standard controller : Estimates Tab 
              
              ApexPages.StandardController con5=new ApexPages.StandardController(testJob1);
              ApexPages.currentPage().getParameters().put('intFocus', '5');
              testTabController ext5=new testTabController(con5);
             
              // Instantiate the extention instance with the standard controller : Purchase Order Tab
              
              ApexPages.StandardController con6=new ApexPages.StandardController(testJob1);
              ApexPages.currentPage().getParameters().put('intFocus', '6');
              testTabController ext6=new testTabController(con6);
              
              // Instantiate the extention instance with the standard controller : Invoices Tab
              
              ApexPages.StandardController con7=new ApexPages.StandardController(testJob1);
              ApexPages.currentPage().getParameters().put('intFocus', '7');
              testTabController ext7=new testTabController(con7);
             
              // Instantiate the extention instance with the standard controller : Notes Tab
              
              ApexPages.StandardController con8=new ApexPages.StandardController(testJob1);
              ApexPages.currentPage().getParameters().put('intFocus', '8');
              testTabController ext8=new testTabController(con8);
             
              // Instantiate the extention instance with the standard controller : Tags Tab
              
              ApexPages.StandardController con9=new ApexPages.StandardController(testJob1);
              ApexPages.currentPage().getParameters().put('intFocus', '9');
              testTabController ext9=new testTabController(con9);
              
              // Instantiate the extention instance with the standard controller : Sessions Tab
              
              ApexPages.StandardController con10=new ApexPages.StandardController(testJob1);
              ApexPages.currentPage().getParameters().put('intFocus', '10');
              testTabController ext10=new testTabController(con10);
              
               // Instantiate the extention instance with the standard controller : Graphics Deliverables Tab
              
              ApexPages.StandardController con11=new ApexPages.StandardController(testJob1);
              ApexPages.currentPage().getParameters().put('intFocus', '11');
              testTabController ext11=new testTabController(con11);
              
               // Instantiate the extention instance with the standard controller : Music Usage Tab
              
              ApexPages.StandardController con12=new ApexPages.StandardController(testJob1);
              ApexPages.currentPage().getParameters().put('intFocus', '12');
              testTabController ext12=new testTabController(con12);
              
              // Instantiate the extention instance with the standard controller : Graphics Deliverables Tab
              
              ApexPages.StandardController con13=new ApexPages.StandardController(testJob1);
              ApexPages.currentPage().getParameters().put('intFocus', '13');
              testTabController ext13=new testTabController(con11);
              
               // Instantiate the extention instance with the standard controller : Music Usage Tab
              
              ApexPages.StandardController con14=new ApexPages.StandardController(testJob1);
              ApexPages.currentPage().getParameters().put('intFocus', '14');
              testTabController ext14=new testTabController(con12);
            
                          ApexPages.StandardController con15=new ApexPages.StandardController(testJob1);
              ApexPages.currentPage().getParameters().put('intFocus', '15');
              testTabController ext15=new testTabController(con15);
            
                          ApexPages.StandardController con16=new ApexPages.StandardController(testJob1);
              ApexPages.currentPage().getParameters().put('intFocus', '16');
              testTabController ext16=new testTabController(con16);
              
              
              
              
              
              
        }    
        // End of Test Coverage
        */
        





}