objects/Production_Spec_Item__c/Production_Spec_Item__c.object-meta.xml
<CustomObject>
    <description>This Object is used as child object of Production Spec Template in Master detail relationship.</description>
    <label>Production Spec Item</label>
    <nameField>
        <label>Spec Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Production Spec Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Production_Spec_Item__c/fields/Production_Spec_Template__c.field-meta.xml
<CustomField>
    <fullName>Production_Spec_Template__c</fullName>
    <label>Production Spec Template</label>
    <referenceTo>Production_Spec_Template__c</referenceTo>
    <relationshipLabel>Production Spec Items</relationshipLabel>
    <relationshipName>Production_Spec_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/Production_Spec_Template__c/Production_Spec_Template__c.object-meta.xml
<CustomObject>
    <description>This object is used to import spec for Quote object.</description>
    <label>Production Spec Template</label>
    <nameField>
        <label>Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Production Spec Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ProductionSpecItemsController.cls
public with sharing class ProductionSpecItemsController {

   /*

 
 public string pstempid {set;get;}
 public list<Production_Spec_Item__c> prospecitems {set;get;}
 public string prospeid  {set;get;}
 
  public ProductionSpecItemsController()
  {
        pstempid =ApexPages.CurrentPage().getParameters().get('id');
        prospecitems =[select id,name,Production_Spec_Template__c,Description__c From Production_Spec_Item__c where Production_Spec_Template__c=:pstempid];
  }


  public pageReference CreateNewSpecItem()
  {
  
   pageReference p=page.CreateProductionSpecItemLightning;
    p.setredirect(true);
    p.getParameters().put('pstempid',pstempid );
    return p;
  
  }
  
 public PageReference deletemethod() {
       PageReference p=new PageReference('/apex/DeleteProductionSpecItem?id='+prospeid);
        p.setredirect(true);
        return p;
   
    }


    public PageReference editmethod() {
        PageReference p=new PageReference('/apex/EditProductionSpecItem?id='+prospeid);
        p.setredirect(true);
        return p;
    }*/

}