objects/Production_Estimate__c/Production_Estimate__c.object-meta.xml
<CustomObject>
    <description>This is Production Estimate object.</description>
    <label>Production Estimate</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Production Estimates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Production_Estimate_Spec_Item__c/Production_Estimate_Spec_Item__c.object-meta.xml
<CustomObject>
    <description>This is Production Estimate Spec Item object. It act as line items of Production Estimate Object.</description>
    <label>Production Estimate Spec Item</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Production Estimate Spec Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Production_Estimate_Spec_Item__c/fields/Production_Estimate__c.field-meta.xml
<CustomField>
    <fullName>Production_Estimate__c</fullName>
    <label>Production Estimate</label>
    <referenceTo>Production_Estimate__c</referenceTo>
    <relationshipLabel>Production Estimate Spec Items</relationshipLabel>
    <relationshipName>Production_Estimate_Spec_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

classes/createProductionEstimateSpecExtension.cls
public with sharing class createProductionEstimateSpecExtension {

   /* // Global variables
    private final Production_Estimate_Spec_Item__c  objESI;
    public Id ProdEstLIId {get;set;}
    // End of Global variables

    // Start Constructor
    public createProductionEstimateSpecExtension (ApexPages.StandardController controller) 
    {
        this.objESI = (Production_Estimate_Spec_Item__c)controller.getRecord(); 
        
       /*  ProdEstLIId =ApexPages.CurrentPage().getParameters().get('id');
        objESI.Production_Estimate__c= ProdEstLIId ;
        *
    }
    // End of Constructor
    
    // Method to insert Estimate Line Item 
    Public PageReference saveme()
     {
        String strid;
        strid = objESI.Production_Estimate__c;
        try
        {
            insert objESI;
        }
        catch(System.DMLException e)
        {
            return null;
        }       
        PageReference p =  new Pagereference('/apex/ProductionEstimatedetailpage?id='+strid);
        p.setRedirect(true);
        return p;
     }*/
    // End of saveme method

}