objects/Vendor__c/Vendor__c.object-meta.xml
<CustomObject>
    <description>This is Vendor object. Vendors in JobSuite are assigned to the line items on Quotes, Estimates, Purchase Orders and Vendor Invoices.  A printer or photographer may be a vendor.</description>
    <label>Vendor</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vendors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Vendor__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>This is Vendor Email field.</description>
    <label>Email</label>
    <type>Email</type>
</CustomField>

objects/Vendor__c/fields/Vendor__c.field-meta.xml
<CustomField>
    <fullName>Vendor__c</fullName>
    <label>Vendor #</label>
    <length>30</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

objects/Vendor__c/fields/Zip__c.field-meta.xml
<CustomField>
    <fullName>Zip__c</fullName>
    <description>This is vendor zip code field.</description>
    <label>Zip</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

objects/Vendor_Contact__c/Vendor_Contact__c.object-meta.xml
<CustomObject>
    <description>This is Vendor Contact Object.</description>
    <label>Vendor Contact</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vendor Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Vendor_Contact__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>this is Email ID of Vendor Contact</description>
    <label>Email</label>
    <type>Email</type>
</CustomField>

objects/Vendor_Contact__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <description>This field contains first name of the vendor.</description>
    <label>First Name</label>
    <length>15</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

objects/Vendor_Contact__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <description>This field contains last name of the vendor.</description>
    <label>Last Name</label>
    <length>15</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

objects/Vendor_Contact__c/fields/Vendor__c.field-meta.xml
<CustomField>
    <fullName>Vendor__c</fullName>
    <label>Vendor</label>
    <referenceTo>Vendor__c</referenceTo>
    <relationshipName>Vendor_Contacts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

classes/Test_CreateNewVendorContactController.cls
@isTest
public class Test_CreateNewVendorContactController {
    /*static testMethod void Test_CreateNewVendorContactController()
    {
        Profile p = [select id from profile where name='System Administrator' limit 1];
        User uId= [Select Id from User where ProfileId =: p.Id and IsActive =: True LIMIT 1];
        System.RunAs(uId)
        {
            UserRole ur=new UserRole(Name='Test UserRole');
            insert ur;
     
            Vendor__c testVendor=new Vendor__c(Name='Test Vendor9901',Email__c='abc@gmail.com',Zip__c='12345');
            try
            {
                insert testVendor;
            }
            catch(System.DMLException e)
            {
                System.assert(e.getMessage().contains('Vendor with same name Exists'));
            }
               
            Vendor__c testVendorerror=new Vendor__c(Name='Test Vendor9901',Email__c='abc@gmail.com',Zip__c='12345');
            try
            {
                insert testVendorerror;
            }
            catch(System.DMLException e)
            {
                System.assertEquals('FIELD_CUSTOM_VALIDATION_EXCEPTION',e.getDmlStatusCode(0));
            }
               
            Vendor_Contact__c testVC=new Vendor_Contact__c(Vendor__c=testVendor.Id,First_Name__c='Tom',Last_Name__c='Cruise',Email__c='abcde9@gmail.com');
           
            ApexPages.StandardController con=new ApexPages.StandardController(testVC);
            ApexPages.currentPage().getParameters().put('Id',testVC.Id);
          
        
            CreateNewVendorContactController   ext=new CreateNewVendorContactController(con);
        
            ApexPages.PageReference result1=ext.saveme();
            ext.RoleId=ur.id;
            String role=ext.getRoleId();
            ext.setRoleId(role);
            List<SelectOption> optionsRole=ext.getRole();
            result1=ext.saveme();

            Vendor_Contact__c testVendor1=new Vendor_Contact__c();
            try
            {
                ApexPages.StandardController con1=new ApexPages.StandardController(testVendor1);
                CreateNewVendorContactController   ext1=new CreateNewVendorContactController(con1);
                ApexPages.PageReference result2=ext1.saveme();
            }
            catch(System.DMLException e)
            {
                System.assertEquals('FIELD_CUSTOM_VALIDATION_EXCEPTION',e.getDmlStatusCode(0));
            }
            
            //Test coverage for editClientContact class.
            ApexPages.StandardController con1=new ApexPages.StandardController(testVC);
            ApexPages.currentPage().getParameters().put('Id',testVC.Id);
            EditVendorContactExtension ext1 = new EditVendorContactExtension(con1);
            
            ext1.saveme();
            ext1.RoleId=ur.id;
            String role1=ext1.getRoleId();
            ext1.setRoleId(role1);
            List<SelectOption> optionsRole1=ext1.getRole();
            ext1.saveme();
        }
    }    
    /* End of Positive Test Case*/    
}