objects/Job_Number_Settings__c/Job_Number_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Job Number Settings</label>
</CustomObject>

objects/Job_Number_Settings__c/fields/Auto__c.field-meta.xml
<CustomField>
    <fullName>Auto__c</fullName>
    <label>Auto</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

objects/Job_Number_Settings__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <label>Date</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

objects/NotesFiles__c/NotesFiles__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Notes and Files Tab</label>
</CustomObject>

objects/NotesFiles__c/fields/Profiles__c.field-meta.xml
<CustomField>
    <fullName>Profiles__c</fullName>
    <label>Profiles</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

classes/TestcustomSettingsInroPg.cls
//@istest
public class TestcustomSettingsInroPg{
/*static testmethod void testclass(){
  
        Job_Number_Settings__c var_JNoSetng = new Job_Number_Settings__c(Name='shashi1', Auto__c='Auto123',Type__c='Auto');
        insert var_JNoSetng;
        
        NotesFiles__c  NF = new NotesFiles__c (Name = 'Profiles',Profiles__c = 'System Administrator' );
        insert NF;
         
        customSettingsInroPg tct = new customSettingsInroPg();

        var_JNoSetng.Date__c = 'mm-dd-yy';
        var_JNoSetng.Type__c = 'Date';
        update var_JNoSetng;
        customSettingsInroPg tct2 = new customSettingsInroPg();

        var_JNoSetng.Code__c='Client';
        var_JNoSetng.Type__c='Code';
        update var_JNoSetng;
        customSettingsInroPg tct3 = new customSettingsInroPg();
        
        tct.savePage();

        delete var_JNoSetng;
        string str_DateForm = 'yy';
        string str_Code = 'Client';
        tct.savePage();
        tct.cancelPage();    
         
         
        }*/
  }