objects/GL_Code__c/GL_Code__c.object-meta.xml
<CustomObject>
    <description>GL Codes are used to build line items on our Job Cost Layouts.  The Job Cost Layouts are the Quote, Estimate, Purchase Order, and Vendor Invoice.   The line items on each of these follow similar logic.</description>
    <label>GL Code</label>
    <nameField>
        <label>Description</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GL Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/GL_Code__c/fields/GL_Department__c.field-meta.xml
<CustomField>
    <fullName>GL_Department__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GL Department</label>
    <referenceTo>GL_Department__c</referenceTo>
    <relationshipLabel>GL Codes</relationshipLabel>
    <relationshipName>GL_Codes</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/GL_Code__c/fields/GL_ID__c.field-meta.xml
<CustomField>
    <fullName>GL_ID__c</fullName>
    <description>This is GL ID field. These id&apos;s are auto generated.</description>
    <label>GL Code</label>
    <length>15</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

objects/GL_Code__c/fields/Unit_Cost__c.field-meta.xml
<CustomField>
    <fullName>Unit_Cost__c</fullName>
    <label>Unit Cost (In $)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

objects/GL_Code__c/fields/Unit_Type__c.field-meta.xml
<CustomField>
    <fullName>Unit_Type__c</fullName>
    <label>Unit Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Days</fullName>
                <default>true</default>
                <label>Days</label>
            </value>
            <value>
                <fullName>Each</fullName>
            </value>
            <value>
                <fullName>Hours</fullName>
            </value>
            <value>
                <fullName>Project</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/GL_Department__c/GL_Department__c.object-meta.xml
<CustomObject>
    <description>This Object is Master of GLCode Object in JobSuite Application.</description>
    <label>GL Department</label>
    <nameField>
        <label>GL Department</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GL Department</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <description>This is Invoice object.</description>
    <label>Invoice</label>
    <nameField>
        <label>Invoice Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Invoice__c/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <label>Job Name</label>
    <referenceTo>Job__c</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/Invoice__c/fields/Revised_Amount__c.field-meta.xml
<CustomField>
    <fullName>Revised_Amount__c</fullName>
    <label>Estimated Amount</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

objects/Invoice__c/fields/Vendor__c.field-meta.xml
<CustomField>
    <fullName>Vendor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vendor</label>
    <referenceTo>Vendor__c</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Invoice_Line_Item__c/Invoice_Line_Item__c.object-meta.xml
<CustomObject>
    <description>This is Invoice Line Item object. It is child object Invoice object.</description>
    <label>Invoice Line Item</label>
    <nameField>
        <displayFormat>ILI-{0000}</displayFormat>
        <label>ILI #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Invoice_Line_Item__c/fields/GL_Code__c.field-meta.xml
<CustomField>
    <fullName>GL_Code__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GL Description</label>
    <referenceTo>GL_Code__c</referenceTo>
    <relationshipLabel>Invoice Line Items</relationshipLabel>
    <relationshipName>Invoice_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Invoice_Line_Item__c/fields/GL_Department__c.field-meta.xml
<CustomField>
    <fullName>GL_Department__c</fullName>
    <formula>GL_Code__r.GL_Department__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>GL Department</label>
    <type>Text</type>
</CustomField>

objects/Invoice_Line_Item__c/fields/Unit_Type__c.field-meta.xml
<CustomField>
    <fullName>Unit_Type__c</fullName>
    <formula>Text( GL_Code__r.Unit_Type__c)</formula>
    <label>Unit Type</label>
    <type>Text</type>
</CustomField>

objects/Job__c/Job__c.object-meta.xml
<CustomObject>
    <description>This is Job object.</description>
    <label>Job</label>
    <nameField>
        <label>Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Job__c/fields/Media_Types__c.field-meta.xml
<CustomField>
    <fullName>Media_Types__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Media Type</label>
    <referenceTo>Media_Type__c</referenceTo>
    <relationshipName>Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Job__c/fields/Schedule_Template__c.field-meta.xml
<CustomField>
    <fullName>Schedule_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Schedule Template</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Schedule_Template__c.Media_Types__c</field>
            <operation>equals</operation>
            <valueField>$Source.Media_Types__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Schedule_Template__c</referenceTo>
    <relationshipName>Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Job__c/fields/Specification_Template__c.field-meta.xml
<CustomField>
    <fullName>Specification_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Creative Brief Template</label>
    <referenceTo>Specification_Template__c</referenceTo>
    <relationshipName>Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Job_Number_Setting__c/Job_Number_Setting__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This is Job Auto Number setting to set the Job Number format.</description>
    <label>Job Number</label>
</CustomObject>

objects/Media_Type__c/Media_Type__c.object-meta.xml
<CustomObject>
    <description>This is Media Type object.</description>
    <label>Media Type</label>
    <nameField>
        <label>Media Type</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Media Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Schedule_Template__c/Schedule_Template__c.object-meta.xml
<CustomObject>
    <description>This is Schedule Template object.</description>
    <label>Schedule Template</label>
    <nameField>
        <label>Schedule Template</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Schedule Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Schedule_Template__c/fields/Media_Types__c.field-meta.xml
<CustomField>
    <fullName>Media_Types__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Media Type</label>
    <referenceTo>Media_Type__c</referenceTo>
    <relationshipLabel>Schedule Templates</relationshipLabel>
    <relationshipName>Schedule_Templates</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Specification_Template__c/Specification_Template__c.object-meta.xml
<CustomObject>
    <description>This is Creative Brief Template object. Also known as Specification Template.</description>
    <label>Creative Brief Template</label>
    <nameField>
        <label>Creative Brief Template</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Creative Brief Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Vendor__c/Vendor__c.object-meta.xml
<CustomObject>
    <description>This is Vendor object. Vendors in JobSuite are assigned to the line items on Quotes, Estimates, Purchase Orders and Vendor Invoices.  A printer or photographer may be a vendor.</description>
    <label>Vendor</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vendors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Vendor__c/fields/Vendor__c.field-meta.xml
<CustomField>
    <fullName>Vendor__c</fullName>
    <label>Vendor #</label>
    <length>30</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

objects/Vendor_GL_Code__c/Vendor_GL_Code__c.object-meta.xml
<CustomObject>
    <description>This is Vendor GL Code object.</description>
    <label>Vendor GL Code</label>
    <nameField>
        <displayFormat>VGC - {0000}</displayFormat>
        <label>Vendor GL Code #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vendor GL Codes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Vendor_GL_Code__c/fields/GL_Code__c.field-meta.xml
<CustomField>
    <fullName>GL_Code__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GL Code</label>
    <referenceTo>GL_Code__c</referenceTo>
    <relationshipName>Vendor_GL_Codes</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Vendor_GL_Code__c/fields/Vendor__c.field-meta.xml
<CustomField>
    <fullName>Vendor__c</fullName>
    <label>Vendor</label>
    <referenceTo>Vendor__c</referenceTo>
    <relationshipName>Vendor_GL_Codes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

classes/AddInvoiceLineItemExtension.cls
// This class is used as a extension to add Invoice Line Items

public with sharing class AddInvoiceLineItemExtension 
{
    // Glbal variables
  /*  private final Invoice_Line_Item__c ILI;
    public String Invoiceid{get;set;}
    public String InvoiceName{get;set;}
    public String VendorId{get;set;}
    public String VendorName{get;set;}
    // End of Global variables
     // End of Global variables
      
    // Start constructor
    public AddInvoiceLineItemExtension(ApexPages.StandardController controller) 
    {
        this.ILI=(Invoice_Line_Item__c)controller.getRecord();
        Invoiceid=ApexPages.CurrentPage().getParameters().get('Invid');
        Invoice__c objIN=[Select id,name,Vendor__c,Vendor__r.Name from Invoice__c where id=:Invoiceid];
        InvoiceName=objIN.Name;
        VendorId = objIN.Vendor__c;
        VendorName = objIN.Vendor__r.Name;
        ILI.Invoice__c = InvoiceId;
    }
    // End of Constructor
    
    // Method to populate GL Code
    public List<selectOption> getGLCode()
    {
        List<selectOption> options = new List<selectOption>(); //new list for holding all of the picklist options
       
        options.add(new selectOption('', '- None -')); //add the first option of '- None -' in case the user doesn't want to select a value or in case no values are returned from query below
      
         for (AggregateResult ar:[SELECT GL_Code__c,GL_Code__r.Name FROM Vendor_GL_Code__c where Vendor__c=: VendorId Group By GL_Code__c,GL_Code__r.Name Order By GL_Code__r.Name])  
          { 
               String aID = (string)ar.get('GL_Code__c');  
               Vendor_GL_Code__c elis=[Select id,Name,Vendor__c,GL_Code__c,GL_Code__r.Name from Vendor_GL_Code__c where GL_Code__c =: aID and Vendor__c=: VendorId  Limit 1];
               options.add(new selectOption(String.Valueof(ar.get('GL_Code__c')),elis.GL_Code__r.Name)); //for all records found - add them to the picklist options
          }
        return options; //return the picklist options
    }
    // End of method getGLCode
    
   // Save Method
    public PageReference saveme() 
     { 
        try
        {
            insert ILI;
        }
        catch(DMLException e)
        {
            return null;
        }
      // After creating Invoice Line Item record navigate to Invoice Detail Page        
      PageReference pageRef = new PageReference('/apex/Invoicedetailpage?id='+Invoiceid);
      pageRef.setRedirect(true);
      return pageRef;
    }
  // End of Save Method

        // Cancel Method
        Public PageReference cancelme()
        {       
            PageReference p =  new Pagereference('/apex/Invoicedetailpage?id='+Invoiceid);
            p.setRedirect(true);
            return p;     
       }
        // End of Cancel Method 

     // Start Test Method
      static testMethod void CreateInvoice()
        {
            Job_Number_Setting__c customSetting1 = new  Job_Number_Setting__c(Name= 'yy');

            insert customSetting1;
            
           Media_Type__c testMedia=new Media_Type__c(Name='TM01March');
            try
             {
               insert testMedia;
             }
            catch(System.DMLException e)
             {
                  System.assertEquals('FIELD_CUSTOM_VALIDATION',e.getDmlStatusCode(0));
             }
           
           Schedule_Template__c testST=new Schedule_Template__c(Name='TST01March',Media_Types__c=testMedia.Id);
             
                 insert testST;
                 
           Specification_Template__c testSpec=new Specification_Template__c(Name='TST01March');
           
                 insert testSpec;
                
           Job__c testJob1=new Job__c(Name='TJ01March',Start_Date__c=System.Today(),Media_Types__c=testMedia.Id,Schedule_Template__c=testST.Id,Specification_Template__c=testSpec.Id);
               try
               {
                   insert testJob1;
               }
               catch(System.DMLException e)
               {
                    System.assertEquals('FIELD_CUSTOM_VALIDATION',e.getDmlStatusCode(0));
               }
            System.assertEquals('TJ01March',testJob1.Name);
               
            GL_Department__c testGLD = new GL_Department__c(Name='GLD01March');
            try
            {
                insert testGLD;
            }
            catch(System.DMLException e)
            {
                System.assertEquals('FIELD_CUSTOM_VALIDATION_EXCEPTION',e.getDmlStatusCode(0));
            }   
                    
            Vendor__c testVendor=new Vendor__c(Name='TV01March');
            insert testVendor;
             
            GL_Code__c testGL1=new GL_Code__c();
              testGL1.Name='TGLCode01March';
              testGL1.GL_Id__c='GLC01March';
              testGL1.GL_Department__c=testGLD.id;
              testGL1.Unit_Cost__c=2500;
              testGL1.Unit_Type__c='Days';
             
            try
            {
                 insert testGL1;
            }
            catch(System.DMLException e)
            {
                System.assert(e.getMessage().contains('Record already exist with same GLCode'));
            }
             Vendor_GL_Code__c testVGLCode = new Vendor_GL_Code__c(Vendor__c = testVendor.id,GL_Code__c = testGL1.id);
             insert testVGLCode;
             
             Invoice__c inv = new Invoice__c(Name = 'INV00987',Job__c=testJob1.id,Vendor__c = testVendor.id,Revised_Amount__c = 1000);
             insert inv;
             
             Invoice_Line_Item__c ILI = new Invoice_Line_Item__c(GL_Code__c = testGL1.id,Amount__c = 900);
                   
            // Invoke the primary method on the extension 
            ApexPages.currentPage().getParameters().put('Invid',inv.Id);
            ApexPages.StandardController con=new ApexPages.StandardController(ILI);
            
            // Instantiate the extention instance with the standard controller
            
            AddInvoiceLineItemExtension ext=new AddInvoiceLineItemExtension(con); 
            List<SelectOption> options1 = ext.getGLCode();       
        
            // Invoke the primary method on the extension
           
             ApexPages.PageReference result1=ext.saveme();
             ApexPages.PageReference result2=ext.cancelme();
       }*/
    // End Test Coverage
} // End of Class