objects/GL_Code__c/GL_Code__c.object-meta.xml
<CustomObject>
    <description>GL Codes are used to build line items on our Job Cost Layouts.  The Job Cost Layouts are the Quote, Estimate, Purchase Order, and Vendor Invoice.   The line items on each of these follow similar logic.</description>
    <label>GL Code</label>
    <nameField>
        <label>Description</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GL Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/GL_Code__c/fields/GL_Department__c.field-meta.xml
<CustomField>
    <fullName>GL_Department__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GL Department</label>
    <referenceTo>GL_Department__c</referenceTo>
    <relationshipLabel>GL Codes</relationshipLabel>
    <relationshipName>GL_Codes</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/GL_Code__c/fields/GL_ID__c.field-meta.xml
<CustomField>
    <fullName>GL_ID__c</fullName>
    <description>This is GL ID field. These id&apos;s are auto generated.</description>
    <label>GL Code</label>
    <length>15</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

objects/GL_Department__c/GL_Department__c.object-meta.xml
<CustomObject>
    <description>This Object is Master of GLCode Object in JobSuite Application.</description>
    <label>GL Department</label>
    <nameField>
        <label>GL Department</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GL Department</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Job__c/Job__c.object-meta.xml
<CustomObject>
    <description>This is Job object.</description>
    <label>Job</label>
    <nameField>
        <label>Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Job__c/fields/Job_Auto_Number__c.field-meta.xml
<CustomField>
    <fullName>Job_Auto_Number__c</fullName>
    <defaultValue>&quot;Auto Fill&quot;</defaultValue>
    <externalId>true</externalId>
    <label>Job #</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

objects/Material_Item__c/Material_Item__c.object-meta.xml
<CustomObject>
    <description>This is Material Item object.</description>
    <label>Material Item</label>
    <nameField>
        <label>Material Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Material Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Material_Item__c/fields/Calc_Unit__c.field-meta.xml
<CustomField>
    <fullName>Calc_Unit__c</fullName>
    <label>Calc Unit</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Sheet</fullName>
            </value>
            <value>
                <fullName>Size</fullName>
            </value>
            <value>
                <fullName>Each</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Material_Item__c/fields/GL_Code__c.field-meta.xml
<CustomField>
    <fullName>GL_Code__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GL Code</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The GL Department has been changed for this GL Code in Admin. Please re-select the GL Department and GL Code.</errorMessage>
        <filterItems>
            <field>GL_Code__c.GL_Department__c</field>
            <operation>equals</operation>
            <valueField>$Source.GL_Department__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>GL_Code__c</referenceTo>
    <relationshipLabel>Material Items</relationshipLabel>
    <relationshipName>Material_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Material_Item__c/fields/GL_Department__c.field-meta.xml
<CustomField>
    <fullName>GL_Department__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GL Department</label>
    <referenceTo>GL_Department__c</referenceTo>
    <relationshipLabel>Material Items</relationshipLabel>
    <relationshipName>Material_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Material_Item__c/fields/Vendor__c.field-meta.xml
<CustomField>
    <fullName>Vendor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vendor</label>
    <referenceTo>Vendor__c</referenceTo>
    <relationshipLabel>Material Items</relationshipLabel>
    <relationshipName>Material_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Material_Item__c/recordTypes/Each.recordType-meta.xml
<RecordType>
    <fullName>Each</fullName>
    <active>true</active>
    <label>Each</label>
</RecordType>

objects/Material_Item__c/recordTypes/Sheet.recordType-meta.xml
<RecordType>
    <fullName>Sheet</fullName>
    <active>true</active>
    <label>Sheet</label>
</RecordType>

objects/Production_Estimate__c/Production_Estimate__c.object-meta.xml
<CustomObject>
    <description>This is Production Estimate object.</description>
    <label>Production Estimate</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Production Estimates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Production_Estimate__c/fields/Calc_Unit__c.field-meta.xml
<CustomField>
    <fullName>Calc_Unit__c</fullName>
    <label>Calc Unit</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Each</fullName>
            </value>
            <value>
                <fullName>Sheet</fullName>
            </value>
            <value>
                <fullName>Size</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Production_Estimate__c/fields/Divide_Sheets_By_Two__c.field-meta.xml
<CustomField>
    <fullName>Divide_Sheets_By_Two__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Divide Sheets By Two</label>
    <type>Checkbox</type>
</CustomField>

objects/Production_Estimate__c/fields/GL_Code__c.field-meta.xml
<CustomField>
    <fullName>GL_Code__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GL Description</label>
    <referenceTo>GL_Code__c</referenceTo>
    <relationshipLabel>Production Estimates</relationshipLabel>
    <relationshipName>Production_Estimates</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Production_Estimate__c/fields/GL_Department__c.field-meta.xml
<CustomField>
    <fullName>GL_Department__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GL Department</label>
    <referenceTo>GL_Department__c</referenceTo>
    <relationshipLabel>Production Estimates</relationshipLabel>
    <relationshipName>Production_Estimates</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Production_Estimate__c/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <label>Job Name</label>
    <referenceTo>Job__c</referenceTo>
    <relationshipLabel>Production Estimates</relationshipLabel>
    <relationshipName>Production_Estimates</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/Production_Estimate__c/fields/Material_Item__c.field-meta.xml
<CustomField>
    <fullName>Material_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Material Item</label>
    <referenceTo>Material_Item__c</referenceTo>
    <relationshipLabel>Production Estimates</relationshipLabel>
    <relationshipName>Production_Estimates</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Production_Estimate__c/fields/of_Pages__c.field-meta.xml
<CustomField>
    <fullName>of_Pages__c</fullName>
    <label># of Pages</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

objects/Production_Estimate__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipLabel>Production Estimates</relationshipLabel>
    <relationshipName>Production_Estimates</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Production_Estimate__c/fields/SheetQtyUpforUsed__c.field-meta.xml
<CustomField>
    <fullName>SheetQtyUpforUsed__c</fullName>
    <label>SheetQtyUpforUsed</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

objects/Production_Estimate__c/fields/Sided__c.field-meta.xml
<CustomField>
    <fullName>Sided__c</fullName>
    <label>Sided</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Single</fullName>
            </value>
            <value>
                <fullName>Double</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Production_Estimate__c/fields/Vendor__c.field-meta.xml
<CustomField>
    <fullName>Vendor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vendor</label>
    <referenceTo>Vendor__c</referenceTo>
    <relationshipLabel>Production Estimates</relationshipLabel>
    <relationshipName>Production_Estimates</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Quote__c/Quote__c.object-meta.xml
<CustomObject>
    <description>This is Quote object.</description>
    <label>Quote</label>
    <nameField>
        <label>Quote Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Quote__c/fields/GL_Code__c.field-meta.xml
<CustomField>
    <fullName>GL_Code__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GL Code</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>$Source.GL_Department__c</field>
            <operation>equals</operation>
            <valueField>GL_Code__c.GL_Department__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>GL_Code__c</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Quote__c/fields/GL_Department__c.field-meta.xml
<CustomField>
    <fullName>GL_Department__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GL Department</label>
    <referenceTo>GL_Department__c</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Quote__c/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <label>Job Name</label>
    <referenceTo>Job__c</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/Quote__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <label>Quantity</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

objects/Vendor__c/Vendor__c.object-meta.xml
<CustomObject>
    <description>This is Vendor object. Vendors in JobSuite are assigned to the line items on Quotes, Estimates, Purchase Orders and Vendor Invoices.  A printer or photographer may be a vendor.</description>
    <label>Vendor</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vendors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Vendor__c/fields/Vendor__c.field-meta.xml
<CustomField>
    <fullName>Vendor__c</fullName>
    <label>Vendor #</label>
    <length>30</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

objects/Vendor_GL_Code__c/Vendor_GL_Code__c.object-meta.xml
<CustomObject>
    <description>This is Vendor GL Code object.</description>
    <label>Vendor GL Code</label>
    <nameField>
        <displayFormat>VGC - {0000}</displayFormat>
        <label>Vendor GL Code #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vendor GL Codes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Vendor_GL_Code__c/fields/GL_Code__c.field-meta.xml
<CustomField>
    <fullName>GL_Code__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GL Code</label>
    <referenceTo>GL_Code__c</referenceTo>
    <relationshipName>Vendor_GL_Codes</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Vendor_GL_Code__c/fields/Vendor__c.field-meta.xml
<CustomField>
    <fullName>Vendor__c</fullName>
    <label>Vendor</label>
    <referenceTo>Vendor__c</referenceTo>
    <relationshipName>Vendor_GL_Codes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

classes/CreateProductionEstimateExtension.cls
public with sharing class CreateProductionEstimateExtension {

  // Start Global variables
  
   /* public boolean isLtng{private set; get{
                                            String theme = UserInfo.getUITheme();
                                            return (theme=='Theme4d')?true:false;
                                          }
     }  
            
            
     public boolean isMob{private set; get{
                                            String theme = UserInfo.getUITheme();
                                            return (theme=='Theme4t')?true:false;
                                          }
    }  
    
  
  
    Public String MIName,GLDName,VName,GLCName;
    public String getMIName() { return MIName; }
    public void setMIName(String s) {  this.MIName = s; }
   
    
    public String getGLDName() { return GLDName; }
    public void setGLDName(String s) {  this.GLDName = s; }

    
    public String getGLCName() { return GLCName; }
    public void setGLCName(String s) {  this.GLCname = s; }
    
   
    public String getVName() { return VName; }
    public void setVName(String s) {  this.Vname = s; }

    
    
    public String selectedDepartment {get;set;}
    public  Quote__c user {get;set;}
    public String  UserSelectedControllingOption {get;set;}
    public String  UserSelectedDependentOption {get;set;}

    private final Production_Estimate__c pest;
    public  job__c abc;
    public String qid{get;set;}
    public String quoteid{get;set;}
    public String vqid{get;set;}
    public String orgId{get; set;}
    // End of Global variables
   
   // Start of Constructor
    public CreateProductionEstimateExtension(ApexPages.StandardController controller) 
     {
         
         
         this.pest=(Production_Estimate__c)controller.getRecord();
         qid=ApexPages.CurrentPage().getParameters().get('jobid');
         abc = [select id,name,Job_Auto_Number__c from Job__c where id =: qid];

         pest.Job__c=qid;
         
         
         orgId = UserInfo.getOrganizationId();
        system.debug('org id --------->'+orgId);
     }
   // End of Constructor 
   // This method is used to retrieve all MaterialItems into dropdown list
     public List<selectOption> getMaterialItems() 
     {    
          List<selectOption> optionList = new List<selectOption>();
          optionList.add(new selectOption('', '- None -'));  
          for (Material_Item__c MI : [SELECT Id, name FROM Material_Item__c where recordtype.name =:pest.Calc_Unit__c order by Name limit 999]) 
          {  
               optionList.add(new selectOption(MI.Id, MI.Name));  
          }
          return optionList;  
     }   
     
     
     public List<selectOption> getMaterialItems2() 
     {    
          List<selectOption> optionList = new List<selectOption>();
         // optionList.add(new selectOption('', '- None -'));  
          for (Material_Item__c MI : [SELECT Id, name FROM Material_Item__c where recordtype.name =:pest.Calc_Unit__c order by Name limit 999 offset 999]) 
          {  
               optionList.add(new selectOption(MI.Id, MI.Name));  
          }
          return optionList;  
     }  
     // End of method MaterialItems
   
   
   
   
   
   
    
    // This method is used to retrieve all GLDepartments into dropdown list
    public List<selectOption> getGLDepartments() 
     {    
          List<selectOption> optionList = new List<selectOption>();
          optionList.add(new selectOption('', '- None -'));  
          for (GL_Department__c gld : [SELECT Id, name FROM GL_Department__c order by Name limit 999]) 
          {  
               optionList.add(new selectOption(gld.Id, gld.Name));  
          }
          return optionList;  
     }   
     // End of method getGLDepartments
    
    // This method is used to retrieve all GLCodes into dropdown list
    public List<selectOption> getGLCodes() 
     {
          List<selectOption> optionList = new List<selectOption>();
          optionList.add(new selectOption('', '- None -'));  
          for (GL_Code__c users : [SELECT Id,GL_Id__c,Name FROM GL_Code__c where GL_Department__c =: GLDName ORDER BY Name limit 999]) 
          {  
               optionList.add(new selectOption(users.Id, users.GL_Id__c +' '+users.Name));  
          }
          return optionList;  
     }
     // End of method getGLCodes  
  
     // This method is used to retrieve all Vendors into dropdown list
    public List<selectOption> getVendors()
     {
          List<selectOption> options = new List<selectOption>(); //new list for holding all of the picklist options
          options.add(new selectOption('', '- None -')); //add the first option of '- None -' in case the user doesn't want to select a value or in case no values are returned from query below
          List<Vendor_GL_Code__c> ven = [SELECT Id,Name,Vendor__c,Vendor__r.Name,GL_Code__c FROM Vendor_GL_Code__c where GL_Code__c =: GLCName limit 999];
          for(Vendor_GL_Code__c am : ven)
          {
               System.Debug('a = '+am);
          }
     
          for (Vendor_GL_Code__c ar : ven)  
          { 
               options.add(new selectOption(ar.Vendor__c,ar.Vendor__r.Name)); //for all records found - add them to the picklist options
          }
            return options; //return the picklist options
     }
     // End of method getVendors
  
  
    
   // Save method
    public PageReference saveme() 
    { 
     string strPEstimateId;
     
     
     
      try
       { 
        if(GLDName == null)
         { 
             String stringGLD = Schema.Production_Estimate__c.fields.GL_Department__c.getDescribe().getLabel();
             ApexPages.Message msg1 = new ApexPages.Message(ApexPages.Severity.ERROR,stringGLD+' : You must select a '+stringGLD+'.');
             ApexPages.addMessage(msg1);
             return null;
         }
        
        if(GLCName == null)
         {
             String stringGLC = Schema.Production_Estimate__c.fields.GL_Code__c.getDescribe().getLabel();
             ApexPages.Message msg2 = new ApexPages.Message(ApexPages.Severity.ERROR,stringGLC+' : You must select a '+stringGLC+'.');
             ApexPages.addMessage(msg2);
             return null;
         }
             
        if(VName == null)
         {
             String stringV = Schema.Production_Estimate__c.fields.Vendor__c.getDescribe().getLabel();
             ApexPages.Message msg3 = new ApexPages.Message(ApexPages.Severity.ERROR,stringV+' : You must select a '+stringV+'.');
             ApexPages.addMessage(msg3);
             return null;
         }
             
        else
         {          
             if (Schema.sObjectType.Production_Estimate__c.fields.GL_Department__c.isCreateable()) {
                 pest.GL_Department__c = GLDName;}
              if (Schema.sObjectType.Production_Estimate__c.fields.GL_Code__c.isCreateable()) {
                  pest.GL_Code__c = GLCName;}
             if (Schema.sObjectType.Production_Estimate__c.fields.Vendor__c.isCreateable()) {
                 pest.Vendor__c = Vname;}
             if (Schema.sObjectType.Production_Estimate__c.fields.Material_Item__c.isCreateable()) {
                 pest.Material_Item__c=MIName;}
             
             if(Pest.Qty_Up__c ==null  && Pest.of_Pages__c ==null) {
                  if (Schema.sObjectType.Production_Estimate__c.fields.Qty_Up__c.isCreateable()) {
                      Pest.Qty_Up__c=1;}
             }
            
             
            if(pest.Quantity__c==null)
             {
                  if (Schema.sObjectType.Production_Estimate__c.fields.Quantity__c.isCreateable()) {
                      Pest.Quantity__c=1;}
              }
             
            
             
             if(pest.Calc_Unit__c=='Sheet' && Pest.Sided__c=='Double' && Pest.Qty_Up__c !=null && pest.Divide_Sheets_By_Two__c==true){
                 if (Schema.sObjectType.Production_Estimate__c.fields.SheetQtyUpforUsed__c.isCreateable()) {
                     pest.SheetQtyUpforUsed__c=(pest.Quantity__c/pest.Qty_Up__c)/2;}
                 }
                 
                 else if (pest.Calc_Unit__c=='Sheet' && Pest.Sided__c=='Double' && Pest.Qty_Up__c !=null && pest.Divide_Sheets_By_Two__c==false){
                  if (Schema.sObjectType.Production_Estimate__c.fields.SheetQtyUpforUsed__c.isCreateable()) {
                      pest.SheetQtyUpforUsed__c=(pest.Quantity__c/pest.Qty_Up__c);}
                 }
                 
                 
               else  if(pest.Calc_Unit__c=='Sheet' && Pest.Sided__c=='Single' && Pest.Qty_Up__c !=null){
                  if (Schema.sObjectType.Production_Estimate__c.fields.SheetQtyUpforUsed__c.isCreateable()) {
                      pest.SheetQtyUpforUsed__c=(pest.Quantity__c/pest.Qty_Up__c);}
                 
                 }
             
               else if(pest.Calc_Unit__c=='Each' && Pest.Qty_Up__c !=null){
                  if (Schema.sObjectType.Production_Estimate__c.fields.EachQtyUpforUsed__c.isCreateable()) {
                      pest.EachQtyUpforUsed__c=(pest.Quantity__c/pest.Qty_Up__c);}
                 
               }
             if(Schema.sObjectType.Production_Estimate__c.isCreateable()){
                 insert pest;}
             strPEstimateId = pest.id;
             
             
             
         }
       }   
      catch(System.DMLException e)
       {
          ApexPages.addMessages(e);
          
           return null;
       }
        
        
       PageReference p;
        if(isLtng)
        {
             p = new Pagereference('/apex/JobdetailpageLightening07?id='+qid+'&tab=Jobcost'+'&section=PE');
        }
        else
        {
              p = new Pagereference('/apex/JobListView?id='+qid+'&intFocus=14');
        }
      
      p.setRedirect(true);
      return p;   
        
    /*    
      PageReference pageref =  new Pagereference('/apex/JobListView?id='+qid+'&intFocus=14');
      pageRef.setRedirect(true);
      return pageRef;
   } 
  // End of Save Method 
    
     
 
           
    // Method to deal with cancel button 
     public PageReference cancelme()
      {
         PageReference p;
        if(isLtng)
        {
             p = new Pagereference('/apex/JobdetailpageLightening07?id='+qid+'&tab=Jobcost'+'&section=PE');
        }
        else
        {
              p = new Pagereference('/apex/JobListView?id='+qid+'&intFocus=14');
        }
      
      p.setRedirect(true);
      return p;   
      }*/
      // End of method cancelme
}