objects/GL_Code__c/GL_Code__c.object-meta.xml
<CustomObject>
    <description>GL Codes are used to build line items on our Job Cost Layouts.  The Job Cost Layouts are the Quote, Estimate, Purchase Order, and Vendor Invoice.   The line items on each of these follow similar logic.</description>
    <label>GL Code</label>
    <nameField>
        <label>Description</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GL Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/GL_Code__c/fields/GL_Department__c.field-meta.xml
<CustomField>
    <fullName>GL_Department__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GL Department</label>
    <referenceTo>GL_Department__c</referenceTo>
    <relationshipLabel>GL Codes</relationshipLabel>
    <relationshipName>GL_Codes</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/GL_Code__c/fields/GL_ID__c.field-meta.xml
<CustomField>
    <fullName>GL_ID__c</fullName>
    <description>This is GL ID field. These id&apos;s are auto generated.</description>
    <label>GL Code</label>
    <length>15</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

objects/GL_Department__c/GL_Department__c.object-meta.xml
<CustomObject>
    <description>This Object is Master of GLCode Object in JobSuite Application.</description>
    <label>GL Department</label>
    <nameField>
        <label>GL Department</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GL Department</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Holiday__c/Holiday__c.object-meta.xml
<CustomObject>
    <description>This is Holiday Object. 
Each Holiday Line Item has the following fields : Holiday Name, Holiday Date.</description>
    <label>Holiday</label>
    <nameField>
        <label>Holiday</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Holidays</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Holiday__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <description>This is Holiday Date field.</description>
    <label>Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

objects/Job__c/Job__c.object-meta.xml
<CustomObject>
    <description>This is Job object.</description>
    <label>Job</label>
    <nameField>
        <label>Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Job__c/fields/Media_Types__c.field-meta.xml
<CustomField>
    <fullName>Media_Types__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Media Type</label>
    <referenceTo>Media_Type__c</referenceTo>
    <relationshipName>Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Job__c/fields/Schedule_Calc__c.field-meta.xml
<CustomField>
    <fullName>Schedule_Calc__c</fullName>
    <label>Schedule  Calc</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Start Date</fullName>
                <default>true</default>
                <label>Start Date</label>
            </value>
            <value>
                <fullName>End Date</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Job__c/fields/Schedule_Template__c.field-meta.xml
<CustomField>
    <fullName>Schedule_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Schedule Template</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Schedule_Template__c.Media_Types__c</field>
            <operation>equals</operation>
            <valueField>$Source.Media_Types__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Schedule_Template__c</referenceTo>
    <relationshipName>Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Job__c/fields/Specification_Template__c.field-meta.xml
<CustomField>
    <fullName>Specification_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Creative Brief Template</label>
    <referenceTo>Specification_Template__c</referenceTo>
    <relationshipName>Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Job_Number_Setting__c/Job_Number_Setting__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This is Job Auto Number setting to set the Job Number format.</description>
    <label>Job Number</label>
</CustomObject>

objects/Job_Task__c/Job_Task__c.object-meta.xml
<CustomObject>
    <description>This is Job Task object. Also known as Schedule.</description>
    <label>Job Task</label>
    <nameField>
        <label>Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Job_Task__c/fields/Days__c.field-meta.xml
<CustomField>
    <fullName>Days__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Days</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

objects/Job_Task__c/fields/Due_Date__c.field-meta.xml
<CustomField>
    <fullName>Due_Date__c</fullName>
    <label>Auto Due Date</label>
    <type>Date</type>
</CustomField>

objects/Job_Task__c/fields/GL_Code__c.field-meta.xml
<CustomField>
    <fullName>GL_Code__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GL Code</label>
    <referenceTo>GL_Code__c</referenceTo>
    <relationshipName>Job_Task</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Job_Task__c/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <label>Job Name</label>
    <referenceTo>Job__c</referenceTo>
    <relationshipName>Job_Task</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/Job_Task__c/fields/Revised_Due_Date__c.field-meta.xml
<CustomField>
    <fullName>Revised_Due_Date__c</fullName>
    <label>Final Due Date</label>
    <type>Date</type>
</CustomField>

objects/Job_Task__c/fields/Schedule_Roles__c.field-meta.xml
<CustomField>
    <fullName>Schedule_Roles__c</fullName>
    <label>Schedule Roles</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Designer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Job_Team__c/Job_Team__c.object-meta.xml
<CustomObject>
    <description>This is Job Team object. It is used to store role and assigned staff to that role for a Job record.</description>
    <label>Job Team</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>JobTeam Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Team</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Job_Team__c/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <label>Job Name</label>
    <referenceTo>Job__c</referenceTo>
    <relationshipLabel>Job Team</relationshipLabel>
    <relationshipName>Job_Team</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/Media_Type__c/Media_Type__c.object-meta.xml
<CustomObject>
    <description>This is Media Type object.</description>
    <label>Media Type</label>
    <nameField>
        <label>Media Type</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Media Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Schedule_Template__c/Schedule_Template__c.object-meta.xml
<CustomObject>
    <description>This is Schedule Template object.</description>
    <label>Schedule Template</label>
    <nameField>
        <label>Schedule Template</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Schedule Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Schedule_Template__c/fields/Media_Types__c.field-meta.xml
<CustomField>
    <fullName>Media_Types__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Media Type</label>
    <referenceTo>Media_Type__c</referenceTo>
    <relationshipLabel>Schedule Templates</relationshipLabel>
    <relationshipName>Schedule_Templates</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Specification_Template__c/Specification_Template__c.object-meta.xml
<CustomObject>
    <description>This is Creative Brief Template object. Also known as Specification Template.</description>
    <label>Creative Brief Template</label>
    <nameField>
        <label>Creative Brief Template</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Creative Brief Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/Testextension_JobTask.cls
@isTest

Public Class Testextension_JobTask{
/*
 static testMethod void Test_extension_JobTask()
   {
          Holiday__c hc=new Holiday__c(Date__c=system.Today());
          insert hc;
          Job_Number_Setting__c customSetting999 = new  Job_Number_Setting__c(Name= 'yy');
          insert customSetting999;
         
          Media_Type__c testMedia=new Media_Type__c(Name='MT018');
          insert testMedia;
             
          Schedule_Template__c testST=new Schedule_Template__c(Name='ST018',Media_Types__c=testMedia.Id);
          insert testST;
                 
          Specification_Template__c testSpec=new Specification_Template__c(Name='SPT018');
          insert testSpec;
                
          Job__c testJob1=new Job__c(Name='J018',Start_Date__c=System.Today(),Media_Types__c=testMedia.Id,Schedule_Template__c=testST.Id,Specification_Template__c=testSpec.Id,Schedule_Calc__c='Start Date');
          insert testJob1;
          
            GL_Department__c testGLD = new GL_Department__c(Name='GLD018');
            try
            {
            insert testGLD;
            }
            catch(System.DMLException e)
            {
             System.assertEquals('FIELD_CUSTOM_VALIDATION_EXCEPTION',e.getDmlStatusCode(0));
            }
              
           GL_Code__c testGL=new GL_Code__c(Name='GLC018',GL_ID__c='GLC012',GL_Department__c = testGLD.id);
            try
             {
                 insert testGL;
             }
             catch(System.DMLException e)
             {
              System.assertEquals('FIELD_CUSTOM_VALIDATION_EXCEPTION',e.getDmlStatusCode(0));
             }
           Job_Team__c jt=new Job_Team__c(role__c='Test',Job__c=testJob1.id);
           insert jt;
           
                 
          Job_Task__c testJobTask=new Job_Task__c(Name='JT018',Job__c=testJob1.Id,Days__c=3,GL_Code__c=TestGL.id,Revised_Due_Date__c=System.Today(),Start_Date__c=System.Today());
          insert testJobTask;
         
          Job_Task__c testJobTask1=new Job_Task__c(Name='JT019',GL_Code__c=TestGL.id,Days__c=2,Schedule_Roles__c='Test');
          
          
           Job__c testJob2=new Job__c(Name='J019',Start_Date__c=System.Today(),Due_Date__c=System.Today(),Media_Types__c=testMedia.Id,Schedule_Template__c=testST.Id,Specification_Template__c=testSpec.Id,Schedule_Calc__c='End Date');
          insert testJob2;
           Job_Team__c jt1=new Job_Team__c(role__c='Test',Job__c=testJob2.id);
           insert jt1;
          
          
            Job_Task__c testJobTask2=new Job_Task__c(Name='JT019',Job__c=testJob2.Id,Days__c=3,GL_Code__c=TestGL.id,Revised_Due_Date__c=System.Today(),Start_Date__c=System.Today(),Due_Date__c=System.Today());
          insert testJobTask2;
          Job_Task__c testJobTask4=new Job_Task__c(Name='JT029',Job__c=testJob2.Id,Days__c=5,GL_Code__c=TestGL.id,Revised_Due_Date__c=System.Today(),Start_Date__c=System.Today(),Due_Date__c=System.Today());
          insert testJobTask4;
          Job_Task__c testJobTask5=new Job_Task__c(Name='JT021',Job__c=testJob2.Id,Days__c=1,GL_Code__c=TestGL.id,Revised_Due_Date__c=System.Today(),Start_Date__c=System.Today(),Due_Date__c=System.Today());
          insert testJobTask5;
         
          Job_Task__c testJobTask3=new Job_Task__c(Name='JT020',GL_Code__c=TestGL.id,Days__c=2,Schedule_Roles__c='Test');
        
          
        
       // Instantiate the standard controller with the Job 
        ApexPages.currentPage().getParameters().put('jobid1',testJob1.Id);
        ApexPages.StandardController con=new ApexPages.StandardController(testJobTask1);
        
       // Instantiate the extention instance with the standardcontroller 
          extension_JobTask ext=new extension_JobTask(con);
          ext.GLCName = testGL.id;
          String GLCName = ext.getGLCName();
          ext.setGLCName(GLCName);
          List<SelectOption> options = ext.getGLCodes();
           List<SelectOption> options2 = ext.getRoles();
         
           ext.RolesList='subway,Loves';
        
      // Invoke the primary method on the extension 
        ApexPages.PageReference result1=ext.save();    
        ApexPages.PageReference result2=ext.cancelme();
        
         ApexPages.currentPage().getParameters().put('jobid1',testJob2.Id);
         con=new ApexPages.StandardController(testJobTask3);
        
       // Instantiate the extention instance with the standardcontroller 
           ext=new extension_JobTask(con);
               ext.GLCName = testGL.id;
               ext.RolesList='subway,Loves';
          GLCName = ext.getGLCName();
          ext.setGLCName(GLCName);
          options = ext.getGLCodes() ;   
           result1=ext.save();    
           result2=ext.cancelme();
        
        Job_Task__c resultm=ext.objJobTask;
        
        delete testJobTask;
        result1=ext.save();   
          }
*/


}