objects/GL_Code__c/GL_Code__c.object-meta.xml
<CustomObject>
    <description>GL Codes are used to build line items on our Job Cost Layouts.  The Job Cost Layouts are the Quote, Estimate, Purchase Order, and Vendor Invoice.   The line items on each of these follow similar logic.</description>
    <label>GL Code</label>
    <nameField>
        <label>Description</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GL Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/GL_Code__c/fields/GL_Department__c.field-meta.xml
<CustomField>
    <fullName>GL_Department__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GL Department</label>
    <referenceTo>GL_Department__c</referenceTo>
    <relationshipLabel>GL Codes</relationshipLabel>
    <relationshipName>GL_Codes</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/GL_Code__c/fields/GL_ID__c.field-meta.xml
<CustomField>
    <fullName>GL_ID__c</fullName>
    <description>This is GL ID field. These id&apos;s are auto generated.</description>
    <label>GL Code</label>
    <length>15</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

objects/GL_Department__c/GL_Department__c.object-meta.xml
<CustomObject>
    <description>This Object is Master of GLCode Object in JobSuite Application.</description>
    <label>GL Department</label>
    <nameField>
        <label>GL Department</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GL Department</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Material_Item__c/Material_Item__c.object-meta.xml
<CustomObject>
    <description>This is Material Item object.</description>
    <label>Material Item</label>
    <nameField>
        <label>Material Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Material Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Material_Item__c/fields/GL_Code__c.field-meta.xml
<CustomField>
    <fullName>GL_Code__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GL Code</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The GL Department has been changed for this GL Code in Admin. Please re-select the GL Department and GL Code.</errorMessage>
        <filterItems>
            <field>GL_Code__c.GL_Department__c</field>
            <operation>equals</operation>
            <valueField>$Source.GL_Department__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>GL_Code__c</referenceTo>
    <relationshipLabel>Material Items</relationshipLabel>
    <relationshipName>Material_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Material_Item__c/fields/GL_Department__c.field-meta.xml
<CustomField>
    <fullName>GL_Department__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GL Department</label>
    <referenceTo>GL_Department__c</referenceTo>
    <relationshipLabel>Material Items</relationshipLabel>
    <relationshipName>Material_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Material_Item__c/fields/Production_Estimate_Template__c.field-meta.xml
<CustomField>
    <fullName>Production_Estimate_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Production Estimate Template</label>
    <referenceTo>Production_Estimate_Template__c</referenceTo>
    <relationshipLabel>Material Items</relationshipLabel>
    <relationshipName>Material_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Material_Item__c/fields/Vendor__c.field-meta.xml
<CustomField>
    <fullName>Vendor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vendor</label>
    <referenceTo>Vendor__c</referenceTo>
    <relationshipLabel>Material Items</relationshipLabel>
    <relationshipName>Material_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Production_Estimate_Temp_Line_Items__c/Production_Estimate_Temp_Line_Items__c.object-meta.xml
<CustomObject>
    <label>Production Estimate Temp Line Items</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Production Estimate Temp Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Production_Estimate_Temp_Line_Items__c/fields/GL_Code__c.field-meta.xml
<CustomField>
    <fullName>GL_Code__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GL Code</label>
    <referenceTo>GL_Code__c</referenceTo>
    <relationshipLabel>Production Estimate Temp Line Items</relationshipLabel>
    <relationshipName>Production_Estimate_Temp_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Production_Estimate_Temp_Line_Items__c/fields/GL_Department__c.field-meta.xml
<CustomField>
    <fullName>GL_Department__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GL Department</label>
    <referenceTo>GL_Department__c</referenceTo>
    <relationshipLabel>Production Estimate Temp Line Items</relationshipLabel>
    <relationshipName>Production_Estimate_Temp_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Production_Estimate_Temp_Line_Items__c/fields/Material_Item__c.field-meta.xml
<CustomField>
    <fullName>Material_Item__c</fullName>
    <label>Material Item</label>
    <referenceTo>Material_Item__c</referenceTo>
    <relationshipLabel>Production Estimate Temp Line Items</relationshipLabel>
    <relationshipName>Production_Estimate_Temp_Line_Items</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

objects/Production_Estimate_Temp_Line_Items__c/fields/Production_Estimate_Template__c.field-meta.xml
<CustomField>
    <fullName>Production_Estimate_Template__c</fullName>
    <label>Production Estimate Template</label>
    <referenceTo>Production_Estimate_Template__c</referenceTo>
    <relationshipLabel>Production Estimate Temp Line Items</relationshipLabel>
    <relationshipName>Production_Estimate_Temp_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/Production_Estimate_Temp_Line_Items__c/fields/Vendor__c.field-meta.xml
<CustomField>
    <fullName>Vendor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vendor</label>
    <referenceTo>Vendor__c</referenceTo>
    <relationshipLabel>Production Estimate Temp Line Items</relationshipLabel>
    <relationshipName>Production_Estimate_Temp_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Production_Estimate_Template__c/Production_Estimate_Template__c.object-meta.xml
<CustomObject>
    <label>Production Estimate Template</label>
    <nameField>
        <label>Production Estimate Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Production Estimate Template</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Vendor__c/Vendor__c.object-meta.xml
<CustomObject>
    <description>This is Vendor object. Vendors in JobSuite are assigned to the line items on Quotes, Estimates, Purchase Orders and Vendor Invoices.  A printer or photographer may be a vendor.</description>
    <label>Vendor</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vendors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Vendor__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>This is Vendor Email field.</description>
    <label>Email</label>
    <type>Email</type>
</CustomField>

objects/Vendor__c/fields/Vendor__c.field-meta.xml
<CustomField>
    <fullName>Vendor__c</fullName>
    <label>Vendor #</label>
    <length>30</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

objects/Vendor__c/fields/Zip__c.field-meta.xml
<CustomField>
    <fullName>Zip__c</fullName>
    <description>This is vendor zip code field.</description>
    <label>Zip</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

objects/Vendor_GL_Code__c/Vendor_GL_Code__c.object-meta.xml
<CustomObject>
    <description>This is Vendor GL Code object.</description>
    <label>Vendor GL Code</label>
    <nameField>
        <displayFormat>VGC - {0000}</displayFormat>
        <label>Vendor GL Code #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vendor GL Codes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Vendor_GL_Code__c/fields/GL_Code__c.field-meta.xml
<CustomField>
    <fullName>GL_Code__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GL Code</label>
    <referenceTo>GL_Code__c</referenceTo>
    <relationshipName>Vendor_GL_Codes</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Vendor_GL_Code__c/fields/Vendor__c.field-meta.xml
<CustomField>
    <fullName>Vendor__c</fullName>
    <label>Vendor</label>
    <referenceTo>Vendor__c</referenceTo>
    <relationshipName>Vendor_GL_Codes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

classes/TestCreatePETLINewpageExtension.cls
@isTest
Public class TestCreatePETLINewpageExtension 
{
    static testMethod void TestCreatePETLINewpageExtension ()
    {
      /*Material_Item__c MI=new Material_Item__c(name='Test');
          insert MI;
        
          Production_Estimate_Template__c TestIAT=new Production_Estimate_Template__c(Name='Test IAT');
            Insert TestIAT;
        
          GL_Department__c testGLD = new GL_Department__c(Name='GLD016');
            try
            {
            insert testGLD;
            }
            catch(System.DMLException e)
            {
            System.assertEquals('FIELD_CUSTOM_VALIDATION_EXCEPTION',e.getDmlStatusCode(0));
            }
              
            GL_Code__c testGL=new GL_Code__c(Name='GLC016',GL_ID__c='GLC016',GL_Department__c = testGLD.id);
            try
             {
                 insert testGL;
             }
             catch(System.DMLException e)
             {
             System.assertEquals('FIELD_CUSTOM_VALIDATION_EXCEPTION',e.getDmlStatusCode(0));
             }
             
           Vendor__c testVendor=new Vendor__c(Name='TV016',Email__c='abcd@gmail.com',Zip__c='12345');
             try
              {
                  insert testVendor;
              }
              catch(System.DMLException e)
              {
                 System.assertEquals('FIELD_CUSTOM_VALIDATION_EXCEPTION',e.getDmlStatusCode(0));
              }  
          
    
            Vendor_GL_Code__c vgc = new Vendor_GL_Code__c(GL_Code__c=testGL.id,Vendor__c=testVendor.id);
             try
              {
                  insert vgc;
              }
              catch(System.DMLException e)
              {
                 System.assertEquals('FIELD_CUSTOM_VALIDATION_EXCEPTION',e.getDmlStatusCode(0));
              }  
        
          
        
        
          
          Production_Estimate_Temp_Line_Items__c  testIATLI =new  Production_Estimate_Temp_Line_Items__c  (Production_Estimate_Template__c=TestIAT.id);
              
            
           ApexPages.currentPage().getParameters().put('Parentid',TestIAT.Id);
           ApexPages.StandardController con=new ApexPages.StandardController(testIATLI);
     
           // Instantiate the extention instance with the standard controller
           CreatePETLINewpageExtension ext =new CreatePETLINewpageExtension(con);
        
           // Invoke the primary method on the extension 
           ApexPages.PageReference result1=ext.saveme();
          
           
           ext.setGLDName(testGLD.id);
           ext.getGLDName();
        ApexPages.PageReference result111=ext.saveme();
           ext.setGLCName(testGL.id);
           ext.getGLCName();
        ApexPages.PageReference result222=ext.saveme();
           ext.setVName(testVendor.id);
           ext.getVName();
           ext.setMIName(MI.id);
           ext.getMIName();
           ext.getGLDepartments();
           ext.getMaterialItems();
           ext.getMaterialItems2();
           ext.getOptions2();
           ext.getVendors();
           ext.getGLCodes();
           ext.saveme();
          ext.cancelme();
          // ext.setMaterialItems('Test234'); 
           
         */

        }



}