objects/GL_Code__c/GL_Code__c.object-meta.xml
<CustomObject>
    <description>GL Codes are used to build line items on our Job Cost Layouts.  The Job Cost Layouts are the Quote, Estimate, Purchase Order, and Vendor Invoice.   The line items on each of these follow similar logic.</description>
    <label>GL Code</label>
    <nameField>
        <label>Description</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GL Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/GL_Code__c/fields/GL_Department__c.field-meta.xml
<CustomField>
    <fullName>GL_Department__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GL Department</label>
    <referenceTo>GL_Department__c</referenceTo>
    <relationshipLabel>GL Codes</relationshipLabel>
    <relationshipName>GL_Codes</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/GL_Code__c/fields/GL_ID__c.field-meta.xml
<CustomField>
    <fullName>GL_ID__c</fullName>
    <description>This is GL ID field. These id&apos;s are auto generated.</description>
    <label>GL Code</label>
    <length>15</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

objects/GL_Department__c/GL_Department__c.object-meta.xml
<CustomObject>
    <description>This Object is Master of GLCode Object in JobSuite Application.</description>
    <label>GL Department</label>
    <nameField>
        <label>GL Department</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GL Department</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Job__c/Job__c.object-meta.xml
<CustomObject>
    <description>This is Job object.</description>
    <label>Job</label>
    <nameField>
        <label>Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Job__c/fields/Media_Types__c.field-meta.xml
<CustomField>
    <fullName>Media_Types__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Media Type</label>
    <referenceTo>Media_Type__c</referenceTo>
    <relationshipName>Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Job__c/fields/Schedule_Template__c.field-meta.xml
<CustomField>
    <fullName>Schedule_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Schedule Template</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Schedule_Template__c.Media_Types__c</field>
            <operation>equals</operation>
            <valueField>$Source.Media_Types__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Schedule_Template__c</referenceTo>
    <relationshipName>Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Job__c/fields/Specification_Template__c.field-meta.xml
<CustomField>
    <fullName>Specification_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Creative Brief Template</label>
    <referenceTo>Specification_Template__c</referenceTo>
    <relationshipName>Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Job_Number_Setting__c/Job_Number_Setting__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This is Job Auto Number setting to set the Job Number format.</description>
    <label>Job Number</label>
</CustomObject>

objects/Media_Type__c/Media_Type__c.object-meta.xml
<CustomObject>
    <description>This is Media Type object.</description>
    <label>Media Type</label>
    <nameField>
        <label>Media Type</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Media Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Production_Spec_Item__c/Production_Spec_Item__c.object-meta.xml
<CustomObject>
    <description>This Object is used as child object of Production Spec Template in Master detail relationship.</description>
    <label>Production Spec Item</label>
    <nameField>
        <label>Spec Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Production Spec Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Production_Spec_Item__c/fields/Production_Spec_Template__c.field-meta.xml
<CustomField>
    <fullName>Production_Spec_Template__c</fullName>
    <label>Production Spec Template</label>
    <referenceTo>Production_Spec_Template__c</referenceTo>
    <relationshipLabel>Production Spec Items</relationshipLabel>
    <relationshipName>Production_Spec_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/Production_Spec_Template__c/Production_Spec_Template__c.object-meta.xml
<CustomObject>
    <description>This object is used to import spec for Quote object.</description>
    <label>Production Spec Template</label>
    <nameField>
        <label>Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Production Spec Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Quote__c/Quote__c.object-meta.xml
<CustomObject>
    <description>This is Quote object.</description>
    <label>Quote</label>
    <nameField>
        <label>Quote Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Quote__c/fields/Approved__c.field-meta.xml
<CustomField>
    <fullName>Approved__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Approved</label>
    <type>Checkbox</type>
</CustomField>

objects/Quote__c/fields/GL_Code__c.field-meta.xml
<CustomField>
    <fullName>GL_Code__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GL Code</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>$Source.GL_Department__c</field>
            <operation>equals</operation>
            <valueField>GL_Code__c.GL_Department__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>GL_Code__c</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Quote__c/fields/GL_Department__c.field-meta.xml
<CustomField>
    <fullName>GL_Department__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GL Department</label>
    <referenceTo>GL_Department__c</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Quote__c/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <label>Job Name</label>
    <referenceTo>Job__c</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/Quote__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <label>Quantity</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

objects/Quote_Spec_Item__c/Quote_Spec_Item__c.object-meta.xml
<CustomObject>
    <description>This is Quote Spec Item object. It is child object of Quote object.</description>
    <label>Quote Spec Items</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quote Spec Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Quote_Spec_Item__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <label>Quote</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipName>Quote_Spec_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/Quote_Spec_Item__c/fields/Specification_Template__c.field-meta.xml
<CustomField>
    <fullName>Specification_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Specification Template</label>
    <referenceTo>Specification_Template__c</referenceTo>
    <relationshipName>Quote_Spec_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Schedule_Template__c/Schedule_Template__c.object-meta.xml
<CustomObject>
    <description>This is Schedule Template object.</description>
    <label>Schedule Template</label>
    <nameField>
        <label>Schedule Template</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Schedule Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Schedule_Template__c/fields/Media_Types__c.field-meta.xml
<CustomField>
    <fullName>Media_Types__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Media Type</label>
    <referenceTo>Media_Type__c</referenceTo>
    <relationshipLabel>Schedule Templates</relationshipLabel>
    <relationshipName>Schedule_Templates</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Spec_Item__c/Spec_Item__c.object-meta.xml
<CustomObject>
    <description>This is Spec Item object. It is child object of Creative Brief Template/ Specification Template object.</description>
    <label>Creative Spec Items</label>
    <nameField>
        <label>Spec Item</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Spec Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Spec_Item__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <defaultValue>&quot;Enter Description here&quot;</defaultValue>
    <label>Description</label>
    <type>TextArea</type>
</CustomField>

objects/Spec_Item__c/fields/Specification_Template__c.field-meta.xml
<CustomField>
    <fullName>Specification_Template__c</fullName>
    <label>Specification Template</label>
    <referenceTo>Specification_Template__c</referenceTo>
    <relationshipName>Spec_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

objects/Specification_Template__c/Specification_Template__c.object-meta.xml
<CustomObject>
    <description>This is Creative Brief Template object. Also known as Specification Template.</description>
    <label>Creative Brief Template</label>
    <nameField>
        <label>Creative Brief Template</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Creative Brief Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/Import_Production_Spec_Item_Extension.cls
public with sharing class Import_Production_Spec_Item_Extension 
{
    // Global variables
    public boolean isLtng{private set;get{
    
                                   string theme=Userinfo.getUITheme();
                                   return (theme=='Theme4d')?true:false;  
    }}
    
    
    public Id QuoteId{get;set;}
    public String ProductionSpecTempName{get;set;}
    public List<Quote_Spec_Item__c> lstQuoteSpec{get;set;}

    public Import_Production_Spec_Item_Extension(ApexPages.StandardController controller) 
    {
    QuoteId = ApexPages.currentPage().getParameters().get('Qid');
    LoadSpecs();
    }
    
     private void LoadSpecs()
    {
         QuoteId = ApexPages.currentPage().getParameters().get('Qid');       
         lstQuoteSpec=[Select id,Name,Description__c from Quote_Spec_Item__c where Quote__c =: QuoteId Order By CreatedDate];  
    }



// This method is called on to populate all Production Spec Templates into drop down list
    public List<selectOption> getProductionSpecTemplates() 
    {        
        List<selectOption> optionList = new List<selectOption>();
        optionList.add(new SelectOption('','-None-'));
        for (Production_Spec_Template__c a : [SELECT Id, name FROM Production_Spec_Template__c ORDER BY Name Limit 5000]) 
        {  
            optionList.add(new selectOption(a.Id, a.Name));  
        }
        return optionList;  
    }
    // End of method getProductionSpecTemplates
    
     // This method is called on to handle Cancel button
     Public PageReference cancelme()
     {
     
     
        If(isLtng){        
         PageReference p = new Pagereference('/apex/QuoteDetailPageLightning?id='+QuoteId+'&section=estspecitems');
         p.setRedirect(true);
         return p;
         }
         
         else{
         
         PageReference p = new Pagereference('/apex/QuoteDetailPage?id='+QuoteId);
         p.setRedirect(true);
         return p;
         
         } 
    
       }
    // End of Cancel method
    
    
    // This method is called on to Import Specs
    public pagereference importSpecs()
    {
        List<Quote_Spec_Item__c> insertQuoteSpecs=new List<Quote_Spec_Item__c>();    
        
        if(ProductionSpecTempName==NULL || ProductionSpecTempName=='-None-')
        {
           ApexPages.Message msg1 = new ApexPages.Message(ApexPages.Severity.ERROR,'Production Spec Template : You must select a Template.');
           ApexPages.addMessage(msg1);
           return null;
        }
        else
        {
            try
            {
            List<Production_Spec_Item__c> lstSpecs=[Select id,Name,Description__c from Production_Spec_Item__c where Production_Spec_Template__c=:ProductionSpecTempName Order By CreatedDate];
            for(Production_Spec_Item__c PSI:lstSpecs)
            {
              Quote_Spec_Item__c qsi=new Quote_Spec_Item__c();
              qsi.Name=PSI.Name;
              qsi.Description__c=PSI.Description__c;
              qsi.Quote__c = QuoteId;
              insertQuoteSpecs.add(qsi);
            }
            insert insertQuoteSpecs;
            }
            catch(System.DMLException e)
            {
              return NULL;
            }
        }   
        LoadSpecs();
        
        
         If(isLtng){        
         PageReference p = new Pagereference('/apex/QuoteDetailPageLightning?id='+QuoteId+'&section=estspecitems');
         p.setRedirect(true);
         return p;
         }
         
         else{
         
         PageReference p = new Pagereference('/apex/QuoteDetailPage?id='+QuoteId);
         p.setRedirect(true);
         return p;
         
         } 
        
      
    }
    // End of method Import Specs
    
    // Start Test Coverage
    static testMethod void Test_Import_Production_Spec_Item()
    {
    
    Job_Number_Setting__c customSetting980 = new  Job_Number_Setting__c(Name= 'yy');
    insert customSetting980;
        
     Production_Spec_Template__c testPST1=new Production_Spec_Template__c(Name='PST01');
         try
         {
            insert testPST1;
         }
         catch(System.DMLException e)
         {
            System.assert(e.getMessage().contains('Error'));
         }
        
         system.assertEquals('PST01',testPST1.Name);
         
         Production_Spec_Item__c testPSI=new Production_Spec_Item__c(Name='TestPSI01',Production_Spec_Template__c=testPST1.Id);
         insert testPSI;
         
         Production_Spec_Item__c testPSI1=new Production_Spec_Item__c(Name='TestPSI02',Production_Spec_Template__c=testPST1.Id);
         insert testPSI1;
    
         Media_Type__c testMedia=new Media_Type__c(Name='TM999876');
         insert testMedia;
             
         Schedule_Template__c testST=new Schedule_Template__c(Name='TST999876',Media_Types__c=testMedia.Id);
         insert testST;
                 
         Specification_Template__c testSpec1=new Specification_Template__c(Name='TST999876');
         insert testSpec1;
                
         Spec_Item__c testSPI1=new Spec_Item__c(Name='Test SPI 1310',Description__c='Test Desc 1310',Specification_Template__c=testSpec1.id);
         insert testSPI1;     
             
         Specification_Template__c testSpec2=new Specification_Template__c(Name='Testing Spcification Template 1311');
         insert testSpec2;
                
         Job__c testJob1=new Job__c(Name='TJ999876',Start_Date__c=System.Today(),Media_Types__c=testMedia.Id,Schedule_Template__c=testST.Id,Specification_Template__c=testSpec1.Id);
         insert testJob1;
                 
         System.assertEquals('TJ999876',testJob1.Name); 
         
         GL_Department__c testGLD = new GL_Department__c(Name='TGLD999876');
         try
          {
           insert testGLD;
          }
         catch(System.DMLException e)
          {
           System.assertEquals('FIELD_CUSTOM_VALIDATION_EXCEPTION',e.getDmlStatusCode(0));
          }

         GL_Code__c testGL=new GL_Code__c(Name='TGLC999876',GL_ID__c='TGLD999876',GL_Department__c=testGLD.id);
         insert testGL;
               
         Quote__c testQ=new Quote__c(Name='Q999876',Job__c=testjob1.Id,GL_Department__c=testGLD.id,Approved__c=false,Quantity__c=5000.00,GL_Code__c=testGL.Id);
         insert testQ;
           
         ApexPages.currentPage().getParameters().put('Qid',testQ.Id);
         
         // Instantiate the standard controller with the Quote
         ApexPages.StandardController con=new ApexPages.StandardController(testQ);
       
         // Instantiate the extention instance with the standard controller 
         Import_Production_Spec_Item_Extension ext1=new Import_Production_Spec_Item_Extension(con);
        
         ApexPages.Pagereference result=ext1.importSpecs();
        
         ext1.ProductionSpecTempName=testPST1.Id;
         result=ext1.importSpecs();
         List<SelectOption> lst=ext1.getProductionSpecTemplates();
         result=ext1.cancelme();
    }
   // End Test Coverage
    
}
/* End of Class */