objects/GL_Code__c/GL_Code__c.object-meta.xml
<CustomObject>
    <description>GL Codes are used to build line items on our Job Cost Layouts.  The Job Cost Layouts are the Quote, Estimate, Purchase Order, and Vendor Invoice.   The line items on each of these follow similar logic.</description>
    <label>GL Code</label>
    <nameField>
        <label>Description</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GL Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/GL_Code__c/fields/GL_ID__c.field-meta.xml
<CustomField>
    <fullName>GL_ID__c</fullName>
    <description>This is GL ID field. These id&apos;s are auto generated.</description>
    <label>GL Code</label>
    <length>15</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

objects/Media_Type__c/Media_Type__c.object-meta.xml
<CustomObject>
    <description>This is Media Type object.</description>
    <label>Media Type</label>
    <nameField>
        <label>Media Type</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Media Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Schedule_Task__c/Schedule_Task__c.object-meta.xml
<CustomObject>
    <description>This is Schedule Task object. It is child object of Schedule Template object.</description>
    <label>Schedule Task</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Schedule Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Schedule_Task__c/fields/Days__c.field-meta.xml
<CustomField>
    <fullName>Days__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Days</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

objects/Schedule_Task__c/fields/GL_Code__c.field-meta.xml
<CustomField>
    <fullName>GL_Code__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GL Code</label>
    <referenceTo>GL_Code__c</referenceTo>
    <relationshipLabel>Schedule Tasks</relationshipLabel>
    <relationshipName>Schedule_Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Schedule_Task__c/fields/Schedule_Template__c.field-meta.xml
<CustomField>
    <fullName>Schedule_Template__c</fullName>
    <label>Schedule Template</label>
    <referenceTo>Schedule_Template__c</referenceTo>
    <relationshipLabel>Schedule Tasks</relationshipLabel>
    <relationshipName>Schedule_Tasks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/Schedule_Template__c/Schedule_Template__c.object-meta.xml
<CustomObject>
    <description>This is Schedule Template object.</description>
    <label>Schedule Template</label>
    <nameField>
        <label>Schedule Template</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Schedule Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Schedule_Template__c/fields/Media_Types__c.field-meta.xml
<CustomField>
    <fullName>Media_Types__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Media Type</label>
    <referenceTo>Media_Type__c</referenceTo>
    <relationshipLabel>Schedule Templates</relationshipLabel>
    <relationshipName>Schedule_Templates</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/ScheduleTaskRole__c/ScheduleTaskRole__c.object-meta.xml
<CustomObject>
    <description>This is Schedule Task Role object. It is used to store assign roles to Schedule Task.</description>
    <label>ScheduleTask Role</label>
    <nameField>
        <label>Role</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ScheduleTaskRole</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/ScheduleTaskRole__c/fields/Schedule_Task__c.field-meta.xml
<CustomField>
    <fullName>Schedule_Task__c</fullName>
    <label>Schedule Task</label>
    <referenceTo>Schedule_Task__c</referenceTo>
    <relationshipName>ScheduleTaskRole</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

classes/Test_SchedTaskRoleunderschedtempExt.cls
@isTest
public class Test_SchedTaskRoleunderschedtempExt{
      static testMethod void Test_SchedTaskRoleunderschedtempExt()
           {
         /*    Media_Type__c testMedia=new Media_Type__c(Name='Test Media 1');
                insert testMedia;
                
             Schedule_Template__c testST=new Schedule_Template__c(Name='Test Schedule Template 10',Media_Types__c=testMedia.Id);
                 
                  insert testST;
                  
              GL_Code__c testGL=new GL_Code__c(Name='Test GL Code',GL_ID__c='Test GL001');
                  insert testGL;
         
              Schedule_Task__c testSCT=new Schedule_Task__c(Name='Test Schedule Task 10',Schedule_Template__c=testST.Id,Days__c=5,GL_Code__c=testGL.Id);
                 insert testSCT;
                 
              System.assertEquals('Test Schedule Task 10',testSCT.Name);   
                 
               User u1 = [SELECT UserRole.Name from User where Profile.Name='System Administrator' limit 1];
               RoleWrapper w = New RoleWrapper();
                
               List<RoleWrapper> wlist = new List<RoleWrapper>(); 
      
               w.u = u1.UserRole;
               w.Checked= True;
               wlist.add(w); 
               
                // Instantiate the standard controller with the Spec Item
       
               ScheduleTaskRole__c st=new ScheduleTaskRole__c();
               //insert st;
               
               ApexPages.currentPage().getParameters().put('scheduleTaskId',testSCT.id);
               ApexPages.StandardController con = new ApexPages.StandardController(st);
        
                // Instantiate the extention instance with the standardcontroller 
                SchedTaskRoleunderschedtempExt ext=new SchedTaskRoleunderschedtempExt(con);
                 ApexPages.PageReference result=ext.Save();    
                 
                 ext.roleWraps[0].checked=True;
                
        
                // Invoke the primary method on the extension 
                
                 result=ext.Save();     
               
               User u2 = [SELECT UserRole.Name from User where Profile.Name='System Administrator' limit 1];
               RoleWrapper w1 = New RoleWrapper();
                
               List<RoleWrapper> wlist1 = new List<RoleWrapper>(); 
      
               w1.u = u2.UserRole;
               w1.Checked= True;
               wlist1.add(w); 
               
                // Instantiate the standard controller with the Spec Item 
       
                ScheduleTaskRole__c st1=new ScheduleTaskRole__c();
               //upsert st1;
               
                ApexPages.currentPage().getParameters().put('scheduleTaskId',testSCT.id);
               ApexPages.StandardController con1 = new ApexPages.StandardController(st1);
        
                // Instantiate the extention instance with the standardcontroller 
                SchedTaskRoleunderschedtempExt ext1=new SchedTaskRoleunderschedtempExt(con1);
        
                //  Invoke the primary method on the extension 
                 ApexPages.PageReference result1=ext1.Save();   
                 result1=ext1.cancel();
                 
                 
                     }
     // End Test Coverage 
     
      public class RoleWrapper
                 {
                     public UserRole u{get;set;}
                     public Boolean checked{get;set;}*/
                 }      

    
    }