objects/GL_Code__c/GL_Code__c.object-meta.xml
<CustomObject>
    <description>GL Codes are used to build line items on our Job Cost Layouts.  The Job Cost Layouts are the Quote, Estimate, Purchase Order, and Vendor Invoice.   The line items on each of these follow similar logic.</description>
    <label>GL Code</label>
    <nameField>
        <label>Description</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GL Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Job__c/Job__c.object-meta.xml
<CustomObject>
    <description>This is Job object.</description>
    <label>Job</label>
    <nameField>
        <label>Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Job__c/fields/Job_Auto_Number__c.field-meta.xml
<CustomField>
    <fullName>Job_Auto_Number__c</fullName>
    <defaultValue>&quot;Auto Fill&quot;</defaultValue>
    <externalId>true</externalId>
    <label>Job #</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

objects/Timesheet_Entries__c/Timesheet_Entries__c.object-meta.xml
<CustomObject>
    <label>Timesheet Entry</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Timesheet Entry No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Timesheet Entries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Timesheet_Entries__c/fields/GL_Code__c.field-meta.xml
<CustomField>
    <fullName>GL_Code__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GL Code</label>
    <referenceTo>GL_Code__c</referenceTo>
    <relationshipName>Timesheet_Entries</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Timesheet_Entries__c/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <label>Job</label>
    <referenceTo>Job__c</referenceTo>
    <relationshipName>Job_Timesheets</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

objects/Timesheet_Entries__c/fields/Task_Name__c.field-meta.xml
<CustomField>
    <fullName>Task_Name__c</fullName>
    <label>Task Name</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

classes/MyTimesheetlistviewController.cls
public with sharing class MyTimesheetlistviewController 
{

 

    public MyTimesheetlistviewController(ApexPages.StandardController controller) {
    String strGetUserName=UserInfo.getUserName();
         User u=[Select id,Name from User where Username=: strGetUserName];
         String strId=u.id;
         
        /*  lstTsEntry= [select id,name,Task_Name__c,CreatedById from Timesheet_Entries__c  where CreatedById=:strId order by name  LIMIT :blockSize OFFSET :index];*/
         totalRecs = [select count() from Timesheet_Entries__c  where CreatedById=:strId];
 

    }

    public integer totalRecs{get;set;}    
    private integer index = 0;
    private integer blockSize = 10;  
    public List<Timesheet_Entries__c> lstTsEntry{get;set;}

  public string HomePage;


    
     public List<Timesheet_Entries__c> getTsEnty() 
    {
    
         String strGetUserName=UserInfo.getUserName();
         User u=[Select id,Name from User where Username=: strGetUserName];
         String strId=u.id;
         lstTsEntry= [select id,name,Task_Name__c,GL_Code__c,Hours_Worked__c,Date__c ,Job__r.Job_Auto_Number__c,Job__r.Name,CreatedById from Timesheet_Entries__c  where CreatedById=:strId  order by name DESC LIMIT :blockSize OFFSET :index];
      
        return lstTsEntry;
    }  
    
    
    public PageReference NewMethod()
    {
        String th = userinfo.getUiTheme();
          PageReference p;
         if(th == 'Theme4d')
              p=new PageReference('/apex/TimesheetEntriesLightning?Page=HomePage');
         else
          p=new PageReference('/apex/TimesheetEntries?Page=HomePage');
          p.setRedirect(true); 
          return p;
    }
    
    
    public void beginning()
    {
        index = 0;
    }
    
    public void previous()
    {
        index = index - blockSize;
    }
    
    public void next()
    {
        index = index + blockSize;
    }

    public void end()
    {
        index = totalrecs - math.mod(totalRecs,blockSize);
    }        
    
    public boolean getprev()
    {
        if(index == 0)
        return true;
        else
        return false;
    }  
    
    public boolean getnxt()
    {
        if((index + blockSize) >= totalRecs)
        return true;
        else
        return false;
    }     
    




}