objects/GL_Code__c/GL_Code__c.object-meta.xml
<CustomObject>
    <description>GL Codes are used to build line items on our Job Cost Layouts.  The Job Cost Layouts are the Quote, Estimate, Purchase Order, and Vendor Invoice.   The line items on each of these follow similar logic.</description>
    <label>GL Code</label>
    <nameField>
        <label>Description</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GL Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/GL_Code__c/fields/GL_Department__c.field-meta.xml
<CustomField>
    <fullName>GL_Department__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GL Department</label>
    <referenceTo>GL_Department__c</referenceTo>
    <relationshipLabel>GL Codes</relationshipLabel>
    <relationshipName>GL_Codes</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/GL_Code__c/fields/GL_ID__c.field-meta.xml
<CustomField>
    <fullName>GL_ID__c</fullName>
    <description>This is GL ID field. These id&apos;s are auto generated.</description>
    <label>GL Code</label>
    <length>15</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

objects/GL_Code__c/fields/Unit_Cost__c.field-meta.xml
<CustomField>
    <fullName>Unit_Cost__c</fullName>
    <label>Unit Cost (In $)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

objects/GL_Code__c/fields/Unit_Type__c.field-meta.xml
<CustomField>
    <fullName>Unit_Type__c</fullName>
    <label>Unit Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Days</fullName>
                <default>true</default>
                <label>Days</label>
            </value>
            <value>
                <fullName>Each</fullName>
            </value>
            <value>
                <fullName>Hours</fullName>
            </value>
            <value>
                <fullName>Project</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/GL_Department__c/GL_Department__c.object-meta.xml
<CustomObject>
    <description>This Object is Master of GLCode Object in JobSuite Application.</description>
    <label>GL Department</label>
    <nameField>
        <label>GL Department</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GL Department</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Job__c/Job__c.object-meta.xml
<CustomObject>
    <description>This is Job object.</description>
    <label>Job</label>
    <nameField>
        <label>Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Job__c/fields/Media_Types__c.field-meta.xml
<CustomField>
    <fullName>Media_Types__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Media Type</label>
    <referenceTo>Media_Type__c</referenceTo>
    <relationshipName>Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Job__c/fields/Schedule_Template__c.field-meta.xml
<CustomField>
    <fullName>Schedule_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Schedule Template</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Schedule_Template__c.Media_Types__c</field>
            <operation>equals</operation>
            <valueField>$Source.Media_Types__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Schedule_Template__c</referenceTo>
    <relationshipName>Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Job__c/fields/Specification_Template__c.field-meta.xml
<CustomField>
    <fullName>Specification_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Creative Brief Template</label>
    <referenceTo>Specification_Template__c</referenceTo>
    <relationshipName>Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Media_Type__c/Media_Type__c.object-meta.xml
<CustomObject>
    <description>This is Media Type object.</description>
    <label>Media Type</label>
    <nameField>
        <label>Media Type</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Media Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Quote__c/Quote__c.object-meta.xml
<CustomObject>
    <description>This is Quote object.</description>
    <label>Quote</label>
    <nameField>
        <label>Quote Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Quote__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Quote Amount</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

objects/Quote__c/fields/GL_Code__c.field-meta.xml
<CustomField>
    <fullName>GL_Code__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GL Code</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>$Source.GL_Department__c</field>
            <operation>equals</operation>
            <valueField>GL_Code__c.GL_Department__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>GL_Code__c</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Quote__c/fields/GL_Department__c.field-meta.xml
<CustomField>
    <fullName>GL_Department__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GL Department</label>
    <referenceTo>GL_Department__c</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Quote__c/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <label>Job Name</label>
    <referenceTo>Job__c</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/Quote__c/fields/Unit_Type__c.field-meta.xml
<CustomField>
    <fullName>Unit_Type__c</fullName>
    <formula>Text(GL_Code__r.Unit_Type__c )</formula>
    <label>Unit Type</label>
    <type>Text</type>
</CustomField>

objects/Quote_Spec_Item__c/Quote_Spec_Item__c.object-meta.xml
<CustomObject>
    <description>This is Quote Spec Item object. It is child object of Quote object.</description>
    <label>Quote Spec Items</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quote Spec Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Quote_Spec_Item__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <label>Quote</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipName>Quote_Spec_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/Quote_Spec_Item__c/fields/Specification_Template__c.field-meta.xml
<CustomField>
    <fullName>Specification_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Specification Template</label>
    <referenceTo>Specification_Template__c</referenceTo>
    <relationshipName>Quote_Spec_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Schedule_Template__c/Schedule_Template__c.object-meta.xml
<CustomObject>
    <description>This is Schedule Template object.</description>
    <label>Schedule Template</label>
    <nameField>
        <label>Schedule Template</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Schedule Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Schedule_Template__c/fields/Media_Types__c.field-meta.xml
<CustomField>
    <fullName>Media_Types__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Media Type</label>
    <referenceTo>Media_Type__c</referenceTo>
    <relationshipLabel>Schedule Templates</relationshipLabel>
    <relationshipName>Schedule_Templates</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Specification_Template__c/Specification_Template__c.object-meta.xml
<CustomObject>
    <description>This is Creative Brief Template object. Also known as Specification Template.</description>
    <label>Creative Brief Template</label>
    <nameField>
        <label>Creative Brief Template</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Creative Brief Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Vendor__c/Vendor__c.object-meta.xml
<CustomObject>
    <description>This is Vendor object. Vendors in JobSuite are assigned to the line items on Quotes, Estimates, Purchase Orders and Vendor Invoices.  A printer or photographer may be a vendor.</description>
    <label>Vendor</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vendors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Vendor__c/fields/Vendor__c.field-meta.xml
<CustomField>
    <fullName>Vendor__c</fullName>
    <label>Vendor #</label>
    <length>30</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

objects/Vendor_GL_Code__c/Vendor_GL_Code__c.object-meta.xml
<CustomObject>
    <description>This is Vendor GL Code object.</description>
    <label>Vendor GL Code</label>
    <nameField>
        <displayFormat>VGC - {0000}</displayFormat>
        <label>Vendor GL Code #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vendor GL Codes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Vendor_GL_Code__c/fields/GL_Code__c.field-meta.xml
<CustomField>
    <fullName>GL_Code__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GL Code</label>
    <referenceTo>GL_Code__c</referenceTo>
    <relationshipName>Vendor_GL_Codes</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Vendor_GL_Code__c/fields/Vendor__c.field-meta.xml
<CustomField>
    <fullName>Vendor__c</fullName>
    <label>Vendor</label>
    <referenceTo>Vendor__c</referenceTo>
    <relationshipName>Vendor_GL_Codes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/Vendor_Quote__c/Vendor_Quote__c.object-meta.xml
<CustomObject>
    <description>This is Vendor Quote object. This object is used to assign Quote to the Vendor.</description>
    <label>Vendor Quote</label>
    <nameField>
        <displayFormat>VQ-{0000}</displayFormat>
        <label>VQ #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vendor Quotes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Vendor_Quote__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Quote Amount</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

objects/Vendor_Quote__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <label>Quote To Vendor</label>
    <type>Date</type>
</CustomField>

objects/Vendor_Quote__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <label>Quote</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipLabel>Vendors</relationshipLabel>
    <relationshipName>Vendor_Quotes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/Vendor_Quote__c/fields/Vendor__c.field-meta.xml
<CustomField>
    <fullName>Vendor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vendor</label>
    <referenceTo>Vendor__c</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Vendor_Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

classes/TestCreateNewVendorQuoteFinalExtension.cls
@isTest
public class TestCreateNewVendorQuoteFinalExtension {
/*	static testMethod void CreateNewVendorQuotePositiveTest()
         {
              Media_Type__c testMedia=new Media_Type__c(Name='Test Media 357');
             
                 insert testMedia;
             
              Schedule_Template__c testST=new Schedule_Template__c(Name='Test Schedule Template 357',Media_Types__c=testMedia.Id);
             
                 insert testST;
    
              Specification_Template__c testSpec=new Specification_Template__c(Name='Testing Spcification Template 357');
             
                 insert testSpec;
  
              Job__c testJob1=new Job__c(Name='Test Job 357',Start_Date__c=System.Today(),Media_Types__c=testMedia.Id,Schedule_Template__c=testST.Id,Specification_Template__c=testSpec.Id);
               try
               {
                   insert testJob1;
               }
               catch(System.DMLException e)
               {
                   System.assertEquals('FIELD_CUSTOM_VALIDATION_EXCEPTION',e.getDmlStatusCode(0));
               }
            
              GL_Department__c testGLD = new GL_Department__c(Name='TestGLD');
              try
              {
                insert testGLD;
              }
              catch(System.DMLException e)
              {
                System.assertEquals('FIELD_CUSTOM_VALIDATION_EXCEPTION',e.getDmlStatusCode(0));
              }
        
              Quote__c testQ=new Quote__c(Name='Quote 357',Job__c=testjob1.Id,GL_Department__c=testGLD.id);
              try
               {
                   insert testQ;
               }
               catch(System.DMLException e)
               {
                   System.assertEquals('REQUIRED_FIELD_MISSING',e.getDmlStatusCode(0));
               }
               catch(Exception f)
               {
                  System.assertEquals('FIELD_CUSTOM_VALIDATION_EXCEPTION',f.getDmlStatusCode(0));
               }
               
              System.assertEquals('Quote 357',testQ.Name);
               
              Quote_Spec_Item__c QSI=new Quote_Spec_Item__c(Name='Test QSI',Description__c='Des Test',Quote__c=testQ.Id);
               insert QSI;
              Quote_Spec_Item__c QSI1=new Quote_Spec_Item__c(Name='Test QSI1',Description__c='Des Test1',Quote__c=testQ.Id);
               insert QSI1;
               
              Vendor__c testVendor=new Vendor__c(Name='Vendor 357');
                insert testVendor;
             
              Vendor_Quote__c testVQ=new Vendor_Quote__c(Quote__c=testQ.Id,Vendor__c=testVendor.Id,Date__c=System.Today(),Amount__c=500);
              
             GL_Code__c glcode=new GL_Code__c(name='GL Code Test',GL_ID__c='111907',GL_Department__c=testGLD.id,Unit_Type__c='Days',Unit_Cost__c=100);
         	 insert glcode;  
             
             Vendor_GL_Code__c vendglcode=new Vendor_GL_Code__c(Vendor__c=testVendor.Id,GL_Code__c=glcode.id);
             insert vendglcode;
                 
                 
              ApexPages.currentPage().getParameters().put('qid',testQ.id);
              ApexPages.StandardController con=new ApexPages.StandardController(testVQ);
            
              // Instantiate the extention instance with the standard controller
            
              CreateNewVendorQuoteFinalExtension  ext=new CreateNewVendorQuoteFinalExtension (con);
          
             //Example of calling a public method in the controller apex class
             List<SelectOption> options = ext.getVendor();
           
            // Invoke the primary method on the extension
            ApexPages.PageReference result1=ext.saveme();
            ApexPages.PageReference result2=ext.cancelme();
            ext.getVendorName();
             ext.setVendorName('vendor');
            System.assertEquals(testQ.Id,testVQ.Quote__c);

           } */
}