objects/Material_Inventory_Item__c/Material_Inventory_Item__c.object-meta.xml
<CustomObject>
    <description>This  Material Inventory Item  object is child object of Material Item object</description>
    <label>Material Inventory Item</label>
    <nameField>
        <label>Inventory Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Material Inventory Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Material_Inventory_Item__c/fields/Material_Item__c.field-meta.xml
<CustomField>
    <fullName>Material_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Material Item</label>
    <referenceTo>Material_Item__c</referenceTo>
    <relationshipLabel>Material Inventory Items</relationshipLabel>
    <relationshipName>Material_Inventory_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Material_Item__c/Material_Item__c.object-meta.xml
<CustomObject>
    <description>This is Material Item object.</description>
    <label>Material Item</label>
    <nameField>
        <label>Material Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Material Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/TestCreateMaterialInventoryExtension.cls
//@isTest
Public class TestCreateMaterialInventoryExtension{
/*static testMethod void TestCreateMaterialInventoryExtension(){

    Material_Item__c  testI=new Material_Item__c (name='test 123');
    insert testI;
   
    Material_Inventory_Item__c mi= new Material_Inventory_Item__c(Material_Item__c=testI.id);
    
    
    ApexPages.currentPage().getParameters().put('materialid',testI.Id);
    ApexPages.StandardController con=new ApexPages.StandardController(mi);
     
           // Instantiate the extention instance with the standard controller
           CreateMaterialInventoryExtension ext =new CreateMaterialInventoryExtension(con);
    ApexPages.PageReference result1=ext.saveme();
    ApexPages.PageReference result2=ext.cancelme();
    

}*/

}