objects/Material_Inventory_Item__c/Material_Inventory_Item__c.object-meta.xml
<CustomObject>
    <description>This  Material Inventory Item  object is child object of Material Item object</description>
    <label>Material Inventory Item</label>
    <nameField>
        <label>Inventory Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Material Inventory Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Material_Inventory_Item__c/fields/Material_Item__c.field-meta.xml
<CustomField>
    <fullName>Material_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Material Item</label>
    <referenceTo>Material_Item__c</referenceTo>
    <relationshipLabel>Material Inventory Items</relationshipLabel>
    <relationshipName>Material_Inventory_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Material_Inventory_Item__c/fields/Qty_On_Hand__c.field-meta.xml
<CustomField>
    <fullName>Qty_On_Hand__c</fullName>
    <formula>Qty_On_Hand_temp__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Qty On Hand</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

objects/Material_Inventory_Item__c/fields/Qty_On_Shelf__c.field-meta.xml
<CustomField>
    <fullName>Qty_On_Shelf__c</fullName>
    <label>Qty On Shelf</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

objects/Material_Item__c/Material_Item__c.object-meta.xml
<CustomObject>
    <description>This is Material Item object.</description>
    <label>Material Item</label>
    <nameField>
        <label>Material Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Material Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Material_Item__c/fields/Case_Pack__c.field-meta.xml
<CustomField>
    <fullName>Case_Pack__c</fullName>
    <label>Case Pack</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

objects/Material_Item__c/fields/Qty_On_Hand__c.field-meta.xml
<CustomField>
    <fullName>Qty_On_Hand__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Qty On Hand</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

classes/TestDisplayMaterialInventoryController.cls
//@isTest
Public class TestDisplayMaterialInventoryController{

/*Static testMethod void TestDisplayMaterialInventoryController()
     {
            Material_Item__c  testI=new Material_Item__c (name='test 123',Qty_On_Hand__c=0, Case_Pack__c=10.00);
            insert testI;
   
            Material_Inventory_Item__c mi= new Material_Inventory_Item__c(Material_Item__c=testI.id,Qty_On_Shelf__c=10.00);
            insert mi;
                    
            ApexPages.currentPage().getParameters().put('id',testI.Id);
         // Instantiate the extention instance with the Custom Controller
           DisplayMaterialInventoryController ext1=new DisplayMaterialInventoryController();
          
            // Invoke the primary method on the extension
           ApexPages.PageReference result1=ext1.createMI();
           
           ext1.strMI = mi.Id;
           result1 = ext1.deleteMI();
      } 
     // End of test Method
*/



}