objects/Material_Inventory_Item__c/Material_Inventory_Item__c.object-meta.xml
<CustomObject>
    <description>This  Material Inventory Item  object is child object of Material Item object</description>
    <label>Material Inventory Item</label>
    <nameField>
        <label>Inventory Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Material Inventory Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Material_Inventory_Item__c/fields/Material_Item__c.field-meta.xml
<CustomField>
    <fullName>Material_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Material Item</label>
    <referenceTo>Material_Item__c</referenceTo>
    <relationshipLabel>Material Inventory Items</relationshipLabel>
    <relationshipName>Material_Inventory_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Material_Inventory_Item__c/fields/Qty_On_Hand__c.field-meta.xml
<CustomField>
    <fullName>Qty_On_Hand__c</fullName>
    <formula>Qty_On_Hand_temp__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Qty On Hand</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

objects/Material_Inventory_Item__c/fields/Qty_On_Shelf__c.field-meta.xml
<CustomField>
    <fullName>Qty_On_Shelf__c</fullName>
    <label>Qty On Shelf</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

objects/Material_Item__c/Material_Item__c.object-meta.xml
<CustomObject>
    <description>This is Material Item object.</description>
    <label>Material Item</label>
    <nameField>
        <label>Material Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Material Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Material_Item__c/fields/Calc_Unit__c.field-meta.xml
<CustomField>
    <fullName>Calc_Unit__c</fullName>
    <label>Calc Unit</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Sheet</fullName>
            </value>
            <value>
                <fullName>Size</fullName>
            </value>
            <value>
                <fullName>Each</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Material_Item__c/fields/Qty_On_Hand__c.field-meta.xml
<CustomField>
    <fullName>Qty_On_Hand__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Qty On Hand</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

objects/Material_Item__c/recordTypes/Each.recordType-meta.xml
<RecordType>
    <fullName>Each</fullName>
    <active>true</active>
    <label>Each</label>
</RecordType>

objects/Material_Item__c/recordTypes/Size.recordType-meta.xml
<RecordType>
    <fullName>Size</fullName>
    <active>true</active>
    <label>Size</label>
</RecordType>

objects/Material_Usage_line_item__c/Material_Usage_line_item__c.object-meta.xml
<CustomObject>
    <description>This  Material Usage line item  object is child object of Material Item object</description>
    <label>Material Usage line item</label>
    <nameField>
        <displayFormat>MULI-{00000}</displayFormat>
        <label>MULI#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Material Usage line items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Material_Usage_line_item__c/fields/Material_Item__c.field-meta.xml
<CustomField>
    <fullName>Material_Item__c</fullName>
    <label>Material Item</label>
    <referenceTo>Material_Item__c</referenceTo>
    <relationshipLabel>Material Usage line items</relationshipLabel>
    <relationshipName>Material_Usage_line_items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/Material_Usage_line_item__c/fields/Qty_On_Hand__c.field-meta.xml
<CustomField>
    <fullName>Qty_On_Hand__c</fullName>
    <label>Qty On Hand</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

classes/TestMaterial_Items_Controller.cls
@IsTest
public class TestMaterial_Items_Controller {
    public static testMethod void TestMaterial_Items_Controller(){  
       
        Recordtype rt=[SELECT ID,name FROM RecordType WHERE Name ='Each'];
        system.debug('***************'+rt);
        Material_Item__c  testI=new Material_Item__c (name='test 123',Calc_Unit__c ='Size');
        insert testI;
        
        Material_Inventory_Item__c mi= new Material_Inventory_Item__c(Material_Item__c=testI.id,Qty_On_Shelf__c=100);    
        insert mi;
        
        Material_Inventory_Item__c miInve= new Material_Inventory_Item__c(Material_Item__c=testI.id,Qty_On_Shelf__c=200);    
        insert miInve;
        
        Material_Usage_line_item__c  Tmuli= new Material_Usage_line_item__c (Material_Item__c=testI.id,Qty_On_Hand__c=100);
        insert Tmuli;
        
        Material_Usage_line_item__c  muli= new Material_Usage_line_item__c (Material_Item__c=testI.id);
        insert muli;
        
        test.startTest();
            Material_Items_Controller.getFieldsforObject('Material_Item__c');
            Material_Items_Controller.getMaterialUsageItems(testI.Id);
            Material_Items_Controller.updateMaterailItemQtyOnHandField(testI.Id);
            Material_Items_Controller.getMaterialInventory(testI.Id);
            Material_Items_Controller.deleteMInventoryItem(miInve.Id);
            Material_Items_Controller.deleteMIUsageItem(Tmuli.Id,testI.Id);
            Material_Items_Controller.fetchLatestFiles(testI.Id);
            Material_Items_Controller.gettodaydate();
        test.stopTest();

    }
}