objects/Job__c/Job__c.object-meta.xml
<CustomObject>
    <description>This is Job object.</description>
    <label>Job</label>
    <nameField>
        <label>Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Purchase_Order__c/Purchase_Order__c.object-meta.xml
<CustomObject>
    <description>This is Purchase Order object.</description>
    <label>Purchase Order</label>
    <nameField>
        <label>PO #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Purchase Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Purchase_Order__c/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <label>Job Name</label>
    <referenceTo>Job__c</referenceTo>
    <relationshipLabel>Purchase Orders</relationshipLabel>
    <relationshipName>Purchase_Orders</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

classes/TestEstimateViewFromPoSwitchExt.cls
@isTest
public class TestEstimateViewFromPoSwitchExt {
	static testmethod void TestEstimateViewFromPoSwitchExt (){
 		/*Job__c job=new Job__c(name='job');
        insert job;
        Purchase_Order__c po=new Purchase_Order__c(name='po',job__c=job.id);
        insert po;
     ApexPages.StandardController con = new ApexPages.StandardController(po);
     EstimateViewFromPoSwitchExt ext=new EstimateViewFromPoSwitchExt(con);
           ext.EstviewFromPO();
           
*/ 
 }
}