objects/Job__c/Job__c.object-meta.xml
<CustomObject>
    <description>This is Job object.</description>
    <label>Job</label>
    <nameField>
        <label>Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Shipment__c/Shipment__c.object-meta.xml
<CustomObject>
    <description>This is shipment object used for production estimate process</description>
    <label>Shipment</label>
    <nameField>
        <displayFormat>Ship-{000000}</displayFormat>
        <label>Shipment #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shipments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Shipment__c/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Job</label>
    <referenceTo>Job__c</referenceTo>
    <relationshipLabel>Shipments</relationshipLabel>
    <relationshipName>Shipments</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

classes/ShipmentListViewSwitchExt.cls
public with sharing class ShipmentListViewSwitchExt {

  /*  public boolean isLtng{get{
                                            String theme = UserInfo.getUITheme();
                                            return (theme=='Theme4d')?true:false;
                                          } set;
            }  
   
   
    public string shpid{get;set;}
    public Shipment__c Shipment{get;set;}
  
    public ShipmentListViewSwitchExt(ApexPages.StandardController controller) {
          shpid = controller.getRecord().id;
        
        Shipment=[select id,name,Job__c from Shipment__c where id=:shpid];
    }
    
    Public PageReference pagedir()
    {
         String jobid;
         jobid =  Shipment.Job__c;
        PageReference p;
         if(isLtng)
        {
             p=  new Pagereference('/apex/JobdetailpageLightening07?id='+jobId+'&tab=Jobcost'+'&section=shipment');
             
        }
        else
        {
           p = new Pagereference('/apex/jobListView?id='+jobId+'&intFocus=16');

        } 
        p.setRedirect(true);
        return p; 
    }*/


}