objects/Job__c/Job__c.object-meta.xml
<CustomObject>
    <description>This is Job object.</description>
    <label>Job</label>
    <nameField>
        <label>Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Job__c/fields/marked_Done__c.field-meta.xml
<CustomField>
    <fullName>marked_Done__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field is used to marked done all tasks when job status is completed</description>
    <label>marked Done</label>
    <type>Checkbox</type>
</CustomField>

objects/Job_Spec__c/Job_Spec__c.object-meta.xml
<CustomObject>
    <description>This is Creative Brief object. Also known as Job Spec.</description>
    <label>Creative Brief</label>
    <nameField>
        <label>Spec Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Creative Briefs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Job_Spec__c/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <label>Job Name</label>
    <referenceTo>Job__c</referenceTo>
    <relationshipLabel>Creative Briefs</relationshipLabel>
    <relationshipName>Job_Specs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/Job_Task__c/Job_Task__c.object-meta.xml
<CustomObject>
    <description>This is Job Task object. Also known as Schedule.</description>
    <label>Job Task</label>
    <nameField>
        <label>Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Job_Task__c/fields/Assigned_Users__c.field-meta.xml
<CustomField>
    <fullName>Assigned_Users__c</fullName>
    <label>Staff</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

objects/Job_Task__c/fields/Due_Date__c.field-meta.xml
<CustomField>
    <fullName>Due_Date__c</fullName>
    <label>Auto Due Date</label>
    <type>Date</type>
</CustomField>

objects/Job_Task__c/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <label>Job Name</label>
    <referenceTo>Job__c</referenceTo>
    <relationshipName>Job_Task</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/Job_Task__c/fields/Marked_Done__c.field-meta.xml
<CustomField>
    <fullName>Marked_Done__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Marked Done</label>
    <type>Checkbox</type>
</CustomField>

objects/Job_Task__c/fields/Revised_Due_Date__c.field-meta.xml
<CustomField>
    <fullName>Revised_Due_Date__c</fullName>
    <label>Final Due Date</label>
    <type>Date</type>
</CustomField>

objects/Job_Task__c/fields/Task_Order__c.field-meta.xml
<CustomField>
    <fullName>Task_Order__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Task Order</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

objects/Job_Team__c/Job_Team__c.object-meta.xml
<CustomObject>
    <description>This is Job Team object. It is used to store role and assigned staff to that role for a Job record.</description>
    <label>Job Team</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>JobTeam Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Team</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Job_Team__c/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <label>Job Name</label>
    <referenceTo>Job__c</referenceTo>
    <relationshipLabel>Job Team</relationshipLabel>
    <relationshipName>Job_Team</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/Job_Team__c/fields/Staff__c.field-meta.xml
<CustomField>
    <fullName>Staff__c</fullName>
    <label>Staff</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

objects/Staff__c/Staff__c.object-meta.xml
<CustomObject>
    <description>This is Staff object.</description>
    <label>Staff</label>
    <nameField>
        <label>Staff Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Staff</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ClientScheduleReportExtension.cls
public with sharing class ClientScheduleReportExtension {
    // Global variables  
    public DateTime today{get;set;}
    String jobid;
    //public List<Job_Team__c> JobTeam{get;set;} 
    public List<Job_Spec__c> JobSpec{get;set;} 
    public List<Job_Task__c> JobTask{get;set;} 
    public List<Document> lstDoc;
    public String imageBody{get;set;}
    public String imageURL{get;set;}
    public boolean imageNotFound{get;set;}
    // End Global variables

      // Start Cobstructor
    public ClientScheduleReportExtension(ApexPages.StandardController controller) 
    {
         // To display Subscriber Organization Logo
         
        imageURL = '/servlet/servlet.FileDownload?file='; 
        lstDoc = [Select Id, Name, Body from Document where Name =: 'JobSuite_OrganizationLogo' WITH SECURITY_ENFORCED LIMIT 1];
        if(!lstDoc.isEmpty())
        {
           String imageId =  lstDoc[0].Id;
           imageBody = imageURL+imageId;   imageNotFound = False;
        }    
        else
        {
           imageNotFound = True;
        }
           // End of code to display Subscriber Organization Logo
           
       jobid = ApexPages.currentpage().getParameters().get('id');
       //JobTeam = [select id,Name,Role__c,Staff__c from Job_Team__c where Job__c =: jobid];
       JobTask = [select id,Name,Due_Date__c,Start_Date__c,Revised_Due_Date__c,Task_Order__c,Marked_Done__c,Assigned_Users__c from Job_Task__c where Job__c =: jobid WITH SECURITY_ENFORCED Order By Task_Order__c];
       today=System.NOW();
    }
    // End Constructor 
}