objects/Job__c/Job__c.object-meta.xml
<CustomObject>
    <description>This is Job object.</description>
    <label>Job</label>
    <nameField>
        <label>Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Job__c/fields/Job_Auto_Number__c.field-meta.xml
<CustomField>
    <fullName>Job_Auto_Number__c</fullName>
    <defaultValue>&quot;Auto Fill&quot;</defaultValue>
    <externalId>true</externalId>
    <label>Job #</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

objects/Job_Team__c/Job_Team__c.object-meta.xml
<CustomObject>
    <description>This is Job Team object. It is used to store role and assigned staff to that role for a Job record.</description>
    <label>Job Team</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>JobTeam Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Team</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Job_Team__c/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <label>Job Name</label>
    <referenceTo>Job__c</referenceTo>
    <relationshipLabel>Job Team</relationshipLabel>
    <relationshipName>Job_Team</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/Job_Team__c/fields/Staff__c.field-meta.xml
<CustomField>
    <fullName>Staff__c</fullName>
    <label>Staff</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

objects/Staff__c/Staff__c.object-meta.xml
<CustomObject>
    <description>This is Staff object.</description>
    <label>Staff</label>
    <nameField>
        <label>Staff Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Staff</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Staff__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <label>Email</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

objects/Staff__c/fields/User_Type__c.field-meta.xml
<CustomField>
    <fullName>User_Type__c</fullName>
    <label>User Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Licensed User</fullName>
            </value>
            <value>
                <fullName>Unlicensed Staff</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Staff__c/fields/Username__c.field-meta.xml
<CustomField>
    <fullName>Username__c</fullName>
    <label>Username</label>
    <type>Email</type>
</CustomField>

classes/emailWorkorderTeam.cls
public with sharing class emailWorkorderTeam {

   /* public emailWorkorderTeam(ApexPages.StandardController controller) {
    
        jobid = ApexPages.currentpage().getParameters().get('id');
        isError=False;
    }

    public boolean isError{get;set;}  
    public string jobid{get;set;}
    public String addresses;
    Public Blob b;
    list<string> st1 = new list<string>(); 
    
    public emailWorkorderTeam()
    {
      jobid = ApexPages.currentpage().getParameters().get('id');
      isError=False;
    }
    public pagereference send()
    {
        isError=False;
        PageReference pdf = Page.WorkOrder;
        jobid = ApexPages.currentpage().getParameters().get('id');
        pdf.getParameters().put('id',jobid);
        pdf.setRedirect(true);
        job__C j =[select Name,Job_Auto_Number__c,  id from job__c where id =:jobid WITH SECURITY_ENFORCED];        
        list<Job_Team__c> lstTeam = [select id,Name,Staff__c,Email__c from Job_Team__c where job__c = : jobid WITH SECURITY_ENFORCED];
        system.debug('****'+ lstTeam.size());
        list<string> st = new list<string>();
        for(Job_Team__c jst:lstTeam)
        {
          st1.add(jst.Email__c );
        }
        
      /*  list<Staff__c> lststaff = [select name,Email__c from Staff__c where name in :st  ];
        
        
        for(Staff__c jst:lststaff)
        {
            st1.add(jst.Email__c);
        }
        system.debug('****'+ st1);*
            
        // Take the PDF content and Create the email attachment
       if (!Test.IsRunningTest())  b = pdf.getContent();
         Messaging.EmailFileAttachment efa = new Messaging.EmailFileAttachment();
        efa.setFileName('Workorder.pdf');
        efa.setBody(b);
        // email.setFileAttachments(new Messaging.EmailFileAttachment[] {efa});
       
        // Loop through the whole list of contacts and their emails
      
        
        if(st1.size() > 0)
         {
          addresses = st1[0];
            for (Integer i = 1; i < st1.size(); i++) {
                if (st1!= null)
                { 
                    addresses += ':' + st1[i];
                    system.debug('**********'+addresses);
                  }
            }
                String[] toAddresses = addresses.split(':', 0);
                system.debug('&&&&&&&&&&&&&&&'+toAddresses);
                //string email = 'shashi.cherukupally@yahoo.com';
                Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
                mail.setUseSignature(false);
                mail.setToAddresses(toAddresses);
                mail.setSubject('Work Order for Job Name:'+j.name+', Job # :'+j.Job_Auto_Number__c);
                mail.setHtmlBody('Attached is a Work Order for your review.');
                mail.setFileAttachments(new Messaging.EmailFileAttachment[] { efa }); 
                // Send the email
        
                try
                {
                Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });  
                //PageReference p =  new Pagereference('/apex/JobListView?id='+jobid+'&intFocus=1&checksucess=true');
                //p.setRedirect(true);
                //return p;
                 ApexPages.addMessage(new ApexPages.message(ApexPages.severity.Info,'Mail sent Sucessfully!'));
                 return null;
                }
                catch(Exception e)
                {
                //isError=true;
                ApexPages.addMessage(new ApexPages.message(ApexPages.severity.Error,'Messege Sending Failed'));
                return null;
                }
          }
          else
          {
            //isError=true;
            ApexPages.addMessage(new ApexPages.message(ApexPages.severity.Error,'No Team members avaliable'));
                return null;
          }
          
      
        
        
         
    }
    
    //test method 
  /*  static testMethod void Test_emailWorkorderTeam()
    {
    
        job__c testjob = New job__c(Name='testJob');
        insert testjob;
       
        staff__c staff = new Staff__c(Name='teststaff',Email__c='test@gmail.com',Role__c = 'Test Role',UserName__c='test@test.com');
        insert staff;
        staff__c staff1 = new Staff__c(Name='teststaff1',Email__c='test1@gmail.com', Role__c = 'Test Role1',UserName__c='test@test1.com');
        insert staff1;
        
        Staff__c testStaff=new Staff__c(Name='teststaff1',First_Name__c='Test Staff',Last_Name__c='001',Email__c='TestStaff001@SFDC.com',Username__c='TestStaff001@SFDC.com',User_Type__c='Staff');
        insert testStaff;
            

        
        Job_Team__c team = new Job_Team__c(Staff__c='teststaff',Job__c =testjob.id,Role__c='Test Role');
        insert team;
        Job_Team__c team1 = new Job_Team__c(Staff__c='teststaff1',Job__c =testjob.id,Role__c='Test Role1');
        insert team1;
        
        System.assertEquals('Test Staff',testStaff.First_Name__c);
        
        
         PageReference pref = Page.emailworkorder;
        pref.getParameters().put('id',testjob.id);
        Test.setCurrentPage(pref);
        
              
        emailWorkorderTeam con = new emailWorkorderTeam();
        Blob bodyBlob=Blob.valueOf('Unit Test Attachment Body');
        con.b=bodyBlob; 
            
            
            
                
     
        //Test.startTest();
     
         System.assertEquals('testJob',testjob.Name);
     
        // populate the field with values
        ApexPages.currentPage().getParameters().put('id',testjob.id);
        con.addresses = 'test@noemail.com : test2@noemail.com';
        //con.st1 = 'test@noemail.com';
        //con.b = b1;
        // submit the record
        pref = con.send();
     
        //Test.stopTest(); 
    
     
    } */

}