objects/Job__c/Job__c.object-meta.xml
<CustomObject>
    <description>This is Job object.</description>
    <label>Job</label>
    <nameField>
        <label>Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Purchase_Order__c/Purchase_Order__c.object-meta.xml
<CustomObject>
    <description>This is Purchase Order object.</description>
    <label>Purchase Order</label>
    <nameField>
        <label>PO #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Purchase Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Purchase_Order__c/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <label>Job Name</label>
    <referenceTo>Job__c</referenceTo>
    <relationshipLabel>Purchase Orders</relationshipLabel>
    <relationshipName>Purchase_Orders</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

classes/EstimateViewFromPoSwitchExt.cls
public with sharing class EstimateViewFromPoSwitchExt {


   public boolean isLtng {set;get{
   
   return (Userinfo.getUITheme()=='Theme4d')?true:false;
  
   }} 
    public string poid {set;get;}
    public Purchase_Order__c PO {get;set;}
   

    public EstimateViewFromPoSwitchExt(ApexPages.StandardController controller) {
    
    poid=controller.getRecord().id;
    PO=[select id,name,Job__c From Purchase_Order__c where id=:poid];

    }
    
    
    public pageReference EstviewFromPO(){
     String jobid;
         jobid =  PO.Job__c;
         
        if(isLtng)
        {
             PageReference p =  new Pagereference('/apex/JobdetailpageLightening07?id='+jobId+'&tab=Jobcost'+'&section=estimate');
             p.setRedirect(true);
             return p; 
        }
        else
        {
                PageReference p =  new Pagereference('/apex/jobListView?id='+jobId+'&intFocus=5');
                p.setRedirect(true);
                return p;
        }
    }

}