objects/Job__c/Job__c.object-meta.xml
<CustomObject>
    <description>This is Job object.</description>
    <label>Job</label>
    <nameField>
        <label>Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Quote__c/Quote__c.object-meta.xml
<CustomObject>
    <description>This is Quote object.</description>
    <label>Quote</label>
    <nameField>
        <label>Quote Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Quote__c/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <label>Job Name</label>
    <referenceTo>Job__c</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/Vendor__c/Vendor__c.object-meta.xml
<CustomObject>
    <description>This is Vendor object. Vendors in JobSuite are assigned to the line items on Quotes, Estimates, Purchase Orders and Vendor Invoices.  A printer or photographer may be a vendor.</description>
    <label>Vendor</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vendors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Vendor__c/fields/Vendor__c.field-meta.xml
<CustomField>
    <fullName>Vendor__c</fullName>
    <label>Vendor #</label>
    <length>30</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

objects/Vendor_Quote__c/Vendor_Quote__c.object-meta.xml
<CustomObject>
    <description>This is Vendor Quote object. This object is used to assign Quote to the Vendor.</description>
    <label>Vendor Quote</label>
    <nameField>
        <displayFormat>VQ-{0000}</displayFormat>
        <label>VQ #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vendor Quotes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Vendor_Quote__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <label>Quote</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipLabel>Vendors</relationshipLabel>
    <relationshipName>Vendor_Quotes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/Vendor_Quote__c/fields/Vendor__c.field-meta.xml
<CustomField>
    <fullName>Vendor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vendor</label>
    <referenceTo>Vendor__c</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Vendor_Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

classes/TestQuoteVendorViewSwitchExt.cls
@isTest
public class TestQuoteVendorViewSwitchExt {
	static TestMethod void TestQuoteVendorViewSwitchExt(){
      /*  job__c job=new job__c(Name='testjob');
        insert job;
        Vendor__c ven=new Vendor__c(name='vendor');
        insert ven;
        Quote__c testQ=new Quote__c(name='quote',job__c=job.id);
        insert testQ;
        Vendor_Quote__c testVQSpec=new Vendor_Quote__c(Vendor__c=ven.id,Quote__c=testQ.id);
        insert testVQSpec;
       
        QuoteVendorViewSwitchExt controller = new QuoteVendorViewSwitchExt(new ApexPages.StandardController(testVQSpec));
       // boolean x = controller.isMobile;
       controller.pagedir();*/
    }
}