objects/Job__c/Job__c.object-meta.xml
<CustomObject>
    <description>This is Job object.</description>
    <label>Job</label>
    <nameField>
        <label>Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Quote__c/Quote__c.object-meta.xml
<CustomObject>
    <description>This is Quote object.</description>
    <label>Quote</label>
    <nameField>
        <label>Quote Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Quote__c/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <label>Job Name</label>
    <referenceTo>Job__c</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

classes/TestQuoteViewSwitchExt.cls
@isTest
public class TestQuoteViewSwitchExt {
	 static TestMethod void TestQuoteViewSwitchExt(){
       /* Job__c testJob1=new Job__c(Name='Job858',Start_Date__c=System.Today());
        insert testJob1;
        Quote__c testQ=new Quote__c(Name='Camp',Job__c=testJob1.id);
        insert testQ;
        QuoteViewSwitchExt controller = new QuoteViewSwitchExt(new ApexPages.StandardController(testQ));
      //  boolean x = controller.isMobile;
        controller.isLtng=true;
        controller.pagedir();
         */
}
}