objects/Job__c/Job__c.object-meta.xml
<CustomObject>
    <description>This is Job object.</description>
    <label>Job</label>
    <nameField>
        <label>Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Job__c/fields/Job_Auto_Number__c.field-meta.xml
<CustomField>
    <fullName>Job_Auto_Number__c</fullName>
    <defaultValue>&quot;Auto Fill&quot;</defaultValue>
    <externalId>true</externalId>
    <label>Job #</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

objects/Job__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Requested</fullName>
                <default>true</default>
                <label>Requested</label>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Job_Task__c/Job_Task__c.object-meta.xml
<CustomObject>
    <description>This is Job Task object. Also known as Schedule.</description>
    <label>Job Task</label>
    <nameField>
        <label>Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Job_Task__c/fields/Assigned_Users__c.field-meta.xml
<CustomField>
    <fullName>Assigned_Users__c</fullName>
    <label>Staff</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

objects/Job_Task__c/fields/Due_Date__c.field-meta.xml
<CustomField>
    <fullName>Due_Date__c</fullName>
    <label>Auto Due Date</label>
    <type>Date</type>
</CustomField>

objects/Job_Task__c/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <label>Job Name</label>
    <referenceTo>Job__c</referenceTo>
    <relationshipName>Job_Task</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/Job_Task__c/fields/Revised_Due_Date__c.field-meta.xml
<CustomField>
    <fullName>Revised_Due_Date__c</fullName>
    <label>Final Due Date</label>
    <type>Date</type>
</CustomField>

objects/Job_Task__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Requested</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

classes/getAllTasksController1.cls
public with sharing class getAllTasksController1 {

    //Global variables 
  /*  TRANSIENT public List<Job_Task__c> results {get;set;}
    TRANSIENT public String filterId {get;set;}
    private String sortDirection = 'ASC';
    private String sortExp = 'Job__r.Name';
    //Variables ends here
    
    //Class constructor
    public getAllTasksController1(){
        results = new List<Job_Task__c>();
        filterId = 'Today';
        processRequests();
    }
    //class constructor ends here
    
    //Method to get data on selection of filter value 
    public PageReference processRequests()
    {
        if (filterId == 'Today') {
            results = new List<Job_Task__c>();
            results = [Select Id, Name, Revised_Due_Date__c, Due_Date__c, Assigned_Users__c, Job__r.Name, Job__r.Job_Auto_Number__c, Job__r.Status__c FROM Job_Task__c WHERE Revised_Due_Date__c =: System.Today() AND Job__r.Status__c =:'Active' AND Status__c =:'Active' ORDER BY Job__r.Name limit 1000]; //AND Assigned_Users__c != NULL
        }
        else if(filterId == 'Week'){
            results = new List<Job_Task__c>();
            results = [Select Id, Name, Revised_Due_Date__c, Due_Date__c, Assigned_Users__c, Job__r.Name, Job__r.Job_Auto_Number__c, Job__r.Status__c FROM Job_Task__c WHERE Revised_Due_Date__c >=: System.Today() AND Revised_Due_Date__c <=: System.Today().addDays(6) AND Job__r.Status__c =:'Active' AND Status__c =:'Active' ORDER BY Job__r.Name limit 1000]; //AND Assigned_Users__c != NULL 
        }
        else{
            results = new List<Job_Task__c>();
            results = [Select Id, Name, Revised_Due_Date__c, Due_Date__c, Assigned_Users__c, Job__r.Name, Job__r.Job_Auto_Number__c, Job__r.Status__c FROM Job_Task__c WHERE Revised_Due_Date__c <: System.Today() AND Job__r.Status__c =:'Active' AND Status__c =:'Active' ORDER BY Job__r.Name limit 1000]; //AND Assigned_Users__c != NULL 
        }
        return null;
    }
    //Method ends here

    //Method to add filter values to the page.
    public List<SelectOption> getItems() {
        List<SelectOption> options = new List<SelectOption>();
        options.add(new SelectOption('Today', 'Tasks Due Today'));
        options.add(new SelectOption('Week', 'Tasks Due This Week'));
        options.add(new SelectOption('Past', 'Tasks Past Due'));
        return options;
    }
    //Method ends here.
    
    public String sortExpression{
        get{
            return sortExp;
        }
        set{
            // if the columns is clicked on then switch between ascending and descending modes
            if( value == sortExp)
            {
                sortDirection = (sortDirection== 'ASC')?'DESC' : 'ASC';
            }
            else
            {
                sortDirection='ASC';
            } 
            sortExp=value;
        }
    }
    
    public string getSortDirection(){
        // if not columns is selected
        if(sortExpression==NULL || sortExpression=='')
        {
            return 'ASC';
        }
        else
        {
            return sortDirection;
        }
    }
    
    public void setSortDirection(String value){
        sortDirection=value;
    }
    
    //Method to get data based on column sorting.
    public PageReference ViewData(){
        System.debug('filterId --------> ' + filterId);
        string sortFullExp = sortExpression  + ' ' + sortDirection;
        String stat = 'Active';
        if (filterId == 'Today') {
            results = new List<Job_Task__c>();
            results = Database.query('Select Id, Name, Revised_Due_Date__c, Due_Date__c, Assigned_Users__c, Job__r.Name, Job__r.Job_Auto_Number__c, Job__r.Status__c FROM Job_Task__c WHERE Revised_Due_Date__c = ' + String.valueOf(System.Today()) + ' AND Job__r.Status__c =: stat AND Status__c =: stat Order by ' + sortFullExp + ' limit 1000'); //AND Assigned_Users__c != NULL  
        }
        else if(filterId == 'Week'){
            results = new List<Job_Task__c>();
            results = Database.query('Select Id, Name, Revised_Due_Date__c, Due_Date__c, Assigned_Users__c, Job__r.Name, Job__r.Job_Auto_Number__c, Job__r.Status__c FROM Job_Task__c WHERE Revised_Due_Date__c >= ' + String.valueOf(System.Today()) + ' AND Revised_Due_Date__c <= ' + String.valueOf(System.Today().addDays(6)) + ' AND Job__r.Status__c =: stat AND Status__c =: stat Order by ' + sortFullExp + ' limit 1000'); //AND Assigned_Users__c != NULL 
        }
        else{
            results = new List<Job_Task__c>();
            results = Database.query('Select Id, Name, Revised_Due_Date__c, Due_Date__c, Assigned_Users__c, Job__r.Name, Job__r.Job_Auto_Number__c, Job__r.Status__c FROM Job_Task__c WHERE Revised_Due_Date__c < ' + String.valueOf(System.Today()) + ' AND Job__r.Status__c =: stat AND Status__c =: stat Order by ' + sortFullExp + ' limit 1000'); //AND Assigned_Users__c != NULL 
        }
        return null;
    }
    //method ends here. */
}