objects/Job__c/Job__c.object-meta.xml
<CustomObject>
    <description>This is Job object.</description>
    <label>Job</label>
    <nameField>
        <label>Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Job__c/fields/Media_Types__c.field-meta.xml
<CustomField>
    <fullName>Media_Types__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Media Type</label>
    <referenceTo>Media_Type__c</referenceTo>
    <relationshipName>Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Job__c/fields/Schedule_Template__c.field-meta.xml
<CustomField>
    <fullName>Schedule_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Schedule Template</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Schedule_Template__c.Media_Types__c</field>
            <operation>equals</operation>
            <valueField>$Source.Media_Types__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Schedule_Template__c</referenceTo>
    <relationshipName>Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Job__c/fields/Specification_Template__c.field-meta.xml
<CustomField>
    <fullName>Specification_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Creative Brief Template</label>
    <referenceTo>Specification_Template__c</referenceTo>
    <relationshipName>Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Job_Number_Setting__c/Job_Number_Setting__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This is Job Auto Number setting to set the Job Number format.</description>
    <label>Job Number</label>
</CustomObject>

objects/Media_Type__c/Media_Type__c.object-meta.xml
<CustomObject>
    <description>This is Media Type object.</description>
    <label>Media Type</label>
    <nameField>
        <label>Media Type</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Media Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Quote__c/Quote__c.object-meta.xml
<CustomObject>
    <description>This is Quote object.</description>
    <label>Quote</label>
    <nameField>
        <label>Quote Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Quote__c/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <label>Job Name</label>
    <referenceTo>Job__c</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/Quote_Spec_Item__c/Quote_Spec_Item__c.object-meta.xml
<CustomObject>
    <description>This is Quote Spec Item object. It is child object of Quote object.</description>
    <label>Quote Spec Items</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quote Spec Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Quote_Spec_Item__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <label>Quote</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipName>Quote_Spec_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/Quote_Spec_Item__c/fields/Specification_Template__c.field-meta.xml
<CustomField>
    <fullName>Specification_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Specification Template</label>
    <referenceTo>Specification_Template__c</referenceTo>
    <relationshipName>Quote_Spec_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Schedule_Task__c/Schedule_Task__c.object-meta.xml
<CustomObject>
    <description>This is Schedule Task object. It is child object of Schedule Template object.</description>
    <label>Schedule Task</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Schedule Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Schedule_Task__c/fields/Days__c.field-meta.xml
<CustomField>
    <fullName>Days__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Days</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

objects/Schedule_Task__c/fields/Schedule_Template__c.field-meta.xml
<CustomField>
    <fullName>Schedule_Template__c</fullName>
    <label>Schedule Template</label>
    <referenceTo>Schedule_Template__c</referenceTo>
    <relationshipLabel>Schedule Tasks</relationshipLabel>
    <relationshipName>Schedule_Tasks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/Schedule_Template__c/Schedule_Template__c.object-meta.xml
<CustomObject>
    <description>This is Schedule Template object.</description>
    <label>Schedule Template</label>
    <nameField>
        <label>Schedule Template</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Schedule Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Schedule_Template__c/fields/Media_Types__c.field-meta.xml
<CustomField>
    <fullName>Media_Types__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Media Type</label>
    <referenceTo>Media_Type__c</referenceTo>
    <relationshipLabel>Schedule Templates</relationshipLabel>
    <relationshipName>Schedule_Templates</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/ScheduleTaskRole__c/ScheduleTaskRole__c.object-meta.xml
<CustomObject>
    <description>This is Schedule Task Role object. It is used to store assign roles to Schedule Task.</description>
    <label>ScheduleTask Role</label>
    <nameField>
        <label>Role</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ScheduleTaskRole</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/ScheduleTaskRole__c/fields/Schedule_Task__c.field-meta.xml
<CustomField>
    <fullName>Schedule_Task__c</fullName>
    <label>Schedule Task</label>
    <referenceTo>Schedule_Task__c</referenceTo>
    <relationshipName>ScheduleTaskRole</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/Specification_Template__c/Specification_Template__c.object-meta.xml
<CustomObject>
    <description>This is Creative Brief Template object. Also known as Specification Template.</description>
    <label>Creative Brief Template</label>
    <nameField>
        <label>Creative Brief Template</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Creative Brief Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Vendor_Quote__c/Vendor_Quote__c.object-meta.xml
<CustomObject>
    <description>This is Vendor Quote object. This object is used to assign Quote to the Vendor.</description>
    <label>Vendor Quote</label>
    <nameField>
        <displayFormat>VQ-{0000}</displayFormat>
        <label>VQ #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vendor Quotes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Vendor_Quote__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <label>Quote</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipLabel>Vendors</relationshipLabel>
    <relationshipName>Vendor_Quotes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

classes/DisplayVQLIwhenApprovedExtension.cls
// This class is used to Display Vendor Quote Line Item when Approved
public with sharing class DisplayVQLIwhenApprovedExtension 
{
    // Global variables
 /*   String theID;
    Id quoteId;
    public List<Quote_Spec_Item__c> vq{get;set;} 
    // End of Global variables
    
    // Start Constructor
    public DisplayVQLIwhenApprovedExtension(ApexPages.StandardController controller) 
    {
        theID = ApexPages.CurrentPage().getParameters().get('id');
        Vendor_Quote__c objVendorQ=[Select Id,Quote__c from Vendor_Quote__c where Id=: theId LIMIT 1];
        quoteId=objVendorQ.Quote__c;
        vq=[select id,Name,Description__c from Quote_Spec_Item__c where Quote__c =: quoteId Order By CreatedDate];
    }
    // End Constructor
 
    // Test Method
  static testMethod void DisplayVQLIwhenApproved()
    {
            Job_Number_Setting__c customSetting993 = new  Job_Number_Setting__c(Name= 'yy');
            insert customSetting993;
           
            Media_Type__c testMedia=new Media_Type__c(Name='Test Media 8797');
             
                insert testMedia;
             
            Schedule_Template__c testST=new Schedule_Template__c(Name='Test Schedule Template 8797',Media_Types__c=testMedia.Id);
             
                 insert testST;
                 
            Schedule_Task__c testSchedule1=new Schedule_Task__C(Name='Test Schedule Task 8797',Schedule_Template__c=testST.id,Days__c=3);
                insert testSchedule1;
                
         
                
            ScheduleTaskRole__c testSTR1=new ScheduleTaskRole__c(Name='Test Role 8797',Schedule_Task__c=testSchedule1.id);
                insert testSTR1;
                
             Specification_Template__c testSpec=new Specification_Template__c(Name='Testing Spcification Template 8797');
                insert testSpec;
                
             Job__c testJob1=new Job__c(Name='Test Job 8797',Start_Date__c=System.Today(),Media_Types__c=testMedia.Id,Schedule_Template__c=testST.Id,Specification_Template__c=testSpec.Id);
         
                 insert testJob1;
                 
            Quote__c testQ=new Quote__c(Name='Test Q 8797',Job__c=testJob1.id);
                insert testQ;
       
           Vendor_Quote__c testvq = new Vendor_Quote__c(Quote__c=testQ.Id);
               insert testVQ;

           ApexPages.currentPage().getParameters().put('id',testVQ.id);
           ApexPages.StandardController con=new ApexPages.StandardController(testVQ);
           DisplayVQLIwhenApprovedExtension ext=new DisplayVQLIwhenApprovedExtension(con);
           System.assertEquals('Test Job 8797',testJob1.Name);
    } */
     // End of test Method 
}
// End of Class