objects/Job__c/Job__c.object-meta.xml
<CustomObject>
    <description>This is Job object.</description>
    <label>Job</label>
    <nameField>
        <label>Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Job__c/fields/Flag__c.field-meta.xml
<CustomField>
    <fullName>Flag__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This is flag field to check import process.</description>
    <label>Flag</label>
    <type>Checkbox</type>
</CustomField>

objects/Job__c/fields/Job_Auto_Number__c.field-meta.xml
<CustomField>
    <fullName>Job_Auto_Number__c</fullName>
    <defaultValue>&quot;Auto Fill&quot;</defaultValue>
    <externalId>true</externalId>
    <label>Job #</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

objects/Job__c/fields/Media_Types__c.field-meta.xml
<CustomField>
    <fullName>Media_Types__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Media Type</label>
    <referenceTo>Media_Type__c</referenceTo>
    <relationshipName>Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Job__c/fields/Schedule_Template__c.field-meta.xml
<CustomField>
    <fullName>Schedule_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Schedule Template</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Schedule_Template__c.Media_Types__c</field>
            <operation>equals</operation>
            <valueField>$Source.Media_Types__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Schedule_Template__c</referenceTo>
    <relationshipName>Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Job__c/fields/Specification_Template__c.field-meta.xml
<CustomField>
    <fullName>Specification_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Creative Brief Template</label>
    <referenceTo>Specification_Template__c</referenceTo>
    <relationshipName>Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Job_Number_Setting__c/Job_Number_Setting__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This is Job Auto Number setting to set the Job Number format.</description>
    <label>Job Number</label>
</CustomObject>

objects/Media_Type__c/Media_Type__c.object-meta.xml
<CustomObject>
    <description>This is Media Type object.</description>
    <label>Media Type</label>
    <nameField>
        <label>Media Type</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Media Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Schedule_Template__c/Schedule_Template__c.object-meta.xml
<CustomObject>
    <description>This is Schedule Template object.</description>
    <label>Schedule Template</label>
    <nameField>
        <label>Schedule Template</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Schedule Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Schedule_Template__c/fields/Media_Types__c.field-meta.xml
<CustomField>
    <fullName>Media_Types__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Media Type</label>
    <referenceTo>Media_Type__c</referenceTo>
    <relationshipLabel>Schedule Templates</relationshipLabel>
    <relationshipName>Schedule_Templates</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Specification_Template__c/Specification_Template__c.object-meta.xml
<CustomObject>
    <description>This is Creative Brief Template object. Also known as Specification Template.</description>
    <label>Creative Brief Template</label>
    <nameField>
        <label>Creative Brief Template</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Creative Brief Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Tag__c/Tag__c.object-meta.xml
<CustomObject>
    <description>This is Tag object. It stores the tags of Job record.</description>
    <label>Job Tags</label>
    <nameField>
        <label>Tag</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Tags</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Tag__c/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <label>Job Name</label>
    <referenceTo>Job__c</referenceTo>
    <relationshipName>Tags</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

classes/EditTagExtensions.cls
// This method is used in Edit_Tag vf page 
public with sharing class EditTagExtensions
{
   // Global variables
  /* 
     public boolean isLtng{private set; get{
                                            String theme = UserInfo.getUITheme();
                                            return (theme=='Theme4d')?true:false;
                                          }
     } 
  
   
   
    private final Tag__c objTag;
    String strId1,strId2;
    public String jobId{get;set;}
    // End of Global variables
    
    // Constructor 
    public EditTagExtensions(ApexPages.StandardController con) 
    {
        this.objTag=(Tag__c)con.getrecord();
        
        Tag__c gdid = [select id,job__c from Tag__c where id =:objTag.id]; 
      
       jobId=gdid.Job__c; 
    }
    // End of Constructor 
    
    // method to Update
    Public PageReference saveme()
     {
      //  strId1 =  objTag.Job__c;
        try
        {
            update objTag;
        }
        catch(System.DMLException e)
        {
            return null;
        }
        
        PageReference p;
        if(isLtng)
        {
             p =  new Pagereference('/apex/JobdetailpageLightening07?id='+jobId+'&section=Tag');
        }
        else
        {
             p =  new Pagereference('/apex/JobListView?id='+Jobid+'&intFocus=9');
        }
       
        
                
        //PageReference p =  new Pagereference('/apex/JobListView?id='+jobId);
        p.setRedirect(true);
        return p; 
     }
   // End of Update Method
   
   // Cancel method
    Public PageReference cancelme()
    {
     //  strId2 =  objTag.Job__c;        
     //  PageReference p =  new Pagereference('/apex/JobListView?id='+jobId+'&intFocus=9');
    
         PageReference p;
        if(isLtng)
        {
             p =  new Pagereference('/apex/JobdetailpageLightening07?id='+jobId+'&section=Tag');
        }
        else
        {
             p =  new Pagereference('/apex/JobListView?id='+Jobid+'&intFocus=9');
        }
    
    //  PageReference p =  new Pagereference('/apex/JobListView?id='+jobId);
       p.setRedirect(true);
       return p;
    } 
   // End of Cancel method
    
    // Test Coverage
     
  /*   static testMethod void Test_EditTagExtensions()
     {
               Job_Number_Setting__c customSetting001 = new  Job_Number_Setting__c(Name='NO');

               insert customSetting001;
               
              Media_Type__c testMedia = new Media_Type__c(Name='Test Media 622');
              insert testMedia;
             
              Schedule_Template__c testST = new Schedule_Template__c(Name='Test Schedule Template 622',Media_Types__c=testMedia.Id);
              insert testST;
                 
              Specification_Template__c testSpec = new Specification_Template__c(Name='Testing Spcification Template 622');
              insert testSpec;
                
              Job__c testJob1 = new Job__c(Name='Test Job 622',Flag__c = True, Job_Auto_Number__c='Job 622', Start_Date__c=System.Today(),Media_Types__c=testMedia.Id,Schedule_Template__c=testST.Id,Specification_Template__c=testSpec.Id);
               try
                {
                   insert testJob1;
                }
               catch(System.DMLException e)
                {
                   System.assertEquals('FIELD_CUSTOM_VALIDATION_EXCEPTION' ,e.getDmlStatusCode(0));
                }
              System.assertEquals('Test Job 622',testJob1.Name); 
               
              Tag__c testTag = new Tag__c(Name='Test Tag 622',Job__c=testJob1.Id);
                  insert testTag;
              
        // Instantiate the standard controller with the Job 
           ApexPages.StandardController con=new ApexPages.StandardController(testTag);
        
        // Instantiate the extention instance with the standardcontroller
           EditTagExtensions ext=new EditTagExtensions(con);
        
        // Invoke the primary method on the extension 
           ApexPages.PageReference result=ext.saveme();
           ApexPages.PageReference result1=ext.cancelme();
         
           // To cover catch block  
           delete testTag;
           result=ext.saveme();
    }// End Test Coverage */
}
// End of class