objects/Job__c/Job__c.object-meta.xml
<CustomObject>
    <description>This is Job object.</description>
    <label>Job</label>
    <nameField>
        <label>Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Job__c/fields/Flag__c.field-meta.xml
<CustomField>
    <fullName>Flag__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This is flag field to check import process.</description>
    <label>Flag</label>
    <type>Checkbox</type>
</CustomField>

objects/Job__c/fields/Job_Auto_Number__c.field-meta.xml
<CustomField>
    <fullName>Job_Auto_Number__c</fullName>
    <defaultValue>&quot;Auto Fill&quot;</defaultValue>
    <externalId>true</externalId>
    <label>Job #</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

objects/Job__c/fields/Media_Types__c.field-meta.xml
<CustomField>
    <fullName>Media_Types__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Media Type</label>
    <referenceTo>Media_Type__c</referenceTo>
    <relationshipName>Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Job__c/fields/Schedule_Template__c.field-meta.xml
<CustomField>
    <fullName>Schedule_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Schedule Template</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Schedule_Template__c.Media_Types__c</field>
            <operation>equals</operation>
            <valueField>$Source.Media_Types__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Schedule_Template__c</referenceTo>
    <relationshipName>Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Job__c/fields/Specification_Template__c.field-meta.xml
<CustomField>
    <fullName>Specification_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Creative Brief Template</label>
    <referenceTo>Specification_Template__c</referenceTo>
    <relationshipName>Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Job_Number_Setting__c/Job_Number_Setting__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This is Job Auto Number setting to set the Job Number format.</description>
    <label>Job Number</label>
</CustomObject>

objects/Media_Type__c/Media_Type__c.object-meta.xml
<CustomObject>
    <description>This is Media Type object.</description>
    <label>Media Type</label>
    <nameField>
        <label>Media Type</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Media Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Schedule_Template__c/Schedule_Template__c.object-meta.xml
<CustomObject>
    <description>This is Schedule Template object.</description>
    <label>Schedule Template</label>
    <nameField>
        <label>Schedule Template</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Schedule Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Schedule_Template__c/fields/Media_Types__c.field-meta.xml
<CustomField>
    <fullName>Media_Types__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Media Type</label>
    <referenceTo>Media_Type__c</referenceTo>
    <relationshipLabel>Schedule Templates</relationshipLabel>
    <relationshipName>Schedule_Templates</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Specification_Template__c/Specification_Template__c.object-meta.xml
<CustomObject>
    <description>This is Creative Brief Template object. Also known as Specification Template.</description>
    <label>Creative Brief Template</label>
    <nameField>
        <label>Creative Brief Template</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Creative Brief Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Tag__c/Tag__c.object-meta.xml
<CustomObject>
    <description>This is Tag object. It stores the tags of Job record.</description>
    <label>Job Tags</label>
    <nameField>
        <label>Tag</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Tags</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Tag__c/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <label>Job Name</label>
    <referenceTo>Job__c</referenceTo>
    <relationshipName>Tags</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/Tag__c/fields/Tag_Air_Date__c.field-meta.xml
<CustomField>
    <fullName>Tag_Air_Date__c</fullName>
    <description>This is Tag Air Date field.</description>
    <label>Air Date</label>
    <type>Date</type>
</CustomField>

objects/Tag__c/fields/Tag_Air_Time__c.field-meta.xml
<CustomField>
    <fullName>Tag_Air_Time__c</fullName>
    <label>Air Time</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

objects/Tag__c/fields/Tag_Due_Date__c.field-meta.xml
<CustomField>
    <fullName>Tag_Due_Date__c</fullName>
    <label>Promo Due Date</label>
    <type>Date</type>
</CustomField>

objects/Tag__c/fields/Tag_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Tag_End_Date__c</fullName>
    <description>This is Tag End Date.</description>
    <label>Promo End Date</label>
    <type>Date</type>
</CustomField>

objects/Tag__c/fields/Tag_Lengths__c.field-meta.xml
<CustomField>
    <fullName>Tag_Lengths__c</fullName>
    <description>This is Tag Lengths field.</description>
    <label>Lengths</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

objects/Tag__c/fields/Tag_Program_Title__c.field-meta.xml
<CustomField>
    <fullName>Tag_Program_Title__c</fullName>
    <description>This is Program Title field.</description>
    <label>Tag Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

objects/Tag__c/fields/Tag_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Tag_Start_Date__c</fullName>
    <description>This is Tag Start Date.</description>
    <label>Show Air Date</label>
    <type>Date</type>
</CustomField>

classes/displayTagsUnderJobTab.cls
// This class is used to display Tags under Jobs Tab
public with sharing class displayTagsUnderJobTab
{
 /*   // Global variables
    public Id jobId{get;set;}  
    public List<Tag__c> lstTags{get;set;}
    public String strTagId{get;set;}
    // End of Global variables
    
    // This mthod is called on to handle Inline Edit save
    public Pagereference save()
    {
        try
        {
            update lstTags; 
         }
         catch(Exception e)
         {   
            return NULL; 
         }
         return NULL;
    }
    // End of method save
    
    // This method is called on to handle Cancel button
    public pagereference cancel()
    {
        return NULL;
    }
    // End of method Cancel
    
    // Start Constructor
    public displayTagsUnderJobTab()
    {
        displayTags();
    }
    // End of Constructor
    
    // This method is called on to displayTags
    public void displayTags()
    {
        jobId=ApexPages.CurrentPage().getParameters().get('id');
        //commented by yogini on 9/11/12 - added order by createddate 
        //lstTags=[Select Id,Job__c,Name,Tag_Program_Title__c, Tag_Start_Date__c, Tag_End_Date__c, Tag_Due_Date__c, Tag_Air_Date__c, Tag_Air_Time__c, Tag_Lengths__c from Tag__c where Job__c=:jobId ORDER BY Name];        
        lstTags=[Select Id,Job__c,Name,Tag_Program_Title__c, Tag_Start_Date__c, Tag_End_Date__c, Tag_Due_Date__c, Tag_Air_Date__c, Tag_Air_Time__c, Tag_Lengths__c from Tag__c where Job__c=:jobId ORDER BY CreatedDate ASC];        
    }
    // End of method displayTags
    
    // This method is called on to editTag
    public pagereference editTag()
    {
        Pagereference p=new Pagereference('/apex/editTag?id='+strTagId);
        p.setRedirect(true);
        return p;
    }
    // End of method editTag
    
    // This method is called on to handle deleteTag
    public pagereference deleteTag()
    {
      /*
        Tag__c delTag= new Tag__c(Id=strTagId);
        delete delTag;
        displayTags();
        return NULL;
       
         Pagereference p=new Pagereference('/apex/DeleteTag?id='+strTagId);
         p.setRedirect(true);
         return p;
    }
    // End of method deleteTag
    
    // This method is used to create New Tag
    public pagereference createNewTag()
    {
           PageReference p=Page.CreateNewTag;
           p.setRedirect(true);
           p.getParameters().put('jobId',jobId);
           return p;
    }
    // End of createNewTag method
    
    // Start Test Coverage
    static testMethod void Test_displayTagsUnderJobTab()
    {
         Job_Number_Setting__c customSetting1371 = new  Job_Number_Setting__c(Name='NO');

                insert customSetting1371;
                
         Media_Type__c testMedia=new Media_Type__c(Name='Test Media 1371');
             
                insert testMedia;
             
          Schedule_Template__c testST=new Schedule_Template__c(Name='Test Schedule Template 1371',Media_Types__c=testMedia.Id);
             
                 insert testST;
     
          Specification_Template__c testSpec=new Specification_Template__c(Name='Testing Spcification Template 1371');
                insert testSpec;
    
          Job__c testJob1=new Job__c(Flag__c=True,Job_Auto_Number__c='J 1371',Name='Test Job 1371',Start_Date__c=System.Today(),Media_Types__c=testMedia.Id,Schedule_Template__c=testST.Id,Specification_Template__c=testSpec.Id);
           
                   insert testJob1;
               
          Tag__c testTag1=new Tag__c(Name='Test Tag 1371',Job__c=testJob1.Id);
           
               insert testTag1;
               

          System.assertEquals('Test Tag 1371',testTag1.Name);
       
            // Instantiate the extention instance with the Custom Controller
          displayTagsUnderJobTab ext=new displayTagsUnderJobTab();
           
           // Invoke the primary method on the extension
          ext.displayTags();
          ext.strTagId=testTag1.Id;
          ApexPages.Pagereference result=ext.editTag();
          result=ext.deleteTag();
          result=ext.createNewTag();
          result=ext.save();
          result=ext.cancel();
           
          testTag1.Tag_Start_Date__c=System.Today();
          testTag1.Tag_Due_Date__c=System.Today()-1;
          result=ext.save();
           
          delete testJob1;
           
          result=ext.save();
    }  // End Test Coverage*/
}// End of Class