objects/Job__c/Job__c.object-meta.xml
<CustomObject>
    <description>This is Job object.</description>
    <label>Job</label>
    <nameField>
        <label>Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Job__c/fields/Flag__c.field-meta.xml
<CustomField>
    <fullName>Flag__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This is flag field to check import process.</description>
    <label>Flag</label>
    <type>Checkbox</type>
</CustomField>

objects/Job__c/fields/Job_Auto_Number__c.field-meta.xml
<CustomField>
    <fullName>Job_Auto_Number__c</fullName>
    <defaultValue>&quot;Auto Fill&quot;</defaultValue>
    <externalId>true</externalId>
    <label>Job #</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

objects/Job__c/fields/Media_Types__c.field-meta.xml
<CustomField>
    <fullName>Media_Types__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Media Type</label>
    <referenceTo>Media_Type__c</referenceTo>
    <relationshipName>Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Job__c/fields/Schedule_Template__c.field-meta.xml
<CustomField>
    <fullName>Schedule_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Schedule Template</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Schedule_Template__c.Media_Types__c</field>
            <operation>equals</operation>
            <valueField>$Source.Media_Types__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Schedule_Template__c</referenceTo>
    <relationshipName>Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Job__c/fields/Specification_Template__c.field-meta.xml
<CustomField>
    <fullName>Specification_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Creative Brief Template</label>
    <referenceTo>Specification_Template__c</referenceTo>
    <relationshipName>Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Job_Number_Setting__c/Job_Number_Setting__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This is Job Auto Number setting to set the Job Number format.</description>
    <label>Job Number</label>
</CustomObject>

objects/Media_Type__c/Media_Type__c.object-meta.xml
<CustomObject>
    <description>This is Media Type object.</description>
    <label>Media Type</label>
    <nameField>
        <label>Media Type</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Media Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Music_Usage__c/Music_Usage__c.object-meta.xml
<CustomObject>
    <description>This is Music Usage object.</description>
    <label>Music Usage</label>
    <nameField>
        <label>Music Usage Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Music Usages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Music_Usage__c/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <description>This is Job field. Each Music Usage record will contain its related Job.</description>
    <label>Job</label>
    <referenceTo>Job__c</referenceTo>
    <relationshipLabel>Music Usages</relationshipLabel>
    <relationshipName>Music_Usages</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/Music_Usage__c/fields/Music_Usage_Drop__c.field-meta.xml
<CustomField>
    <fullName>Music_Usage_Drop__c</fullName>
    <description>This is Music Usage Drop field.</description>
    <label>Music Usage Drop</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

objects/Music_Usage__c/fields/Music_Usage_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Music_Usage_End_Date__c</fullName>
    <description>This is Music Usage End Date field.</description>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

objects/Music_Usage__c/fields/Music_Usage_Promo_Length__c.field-meta.xml
<CustomField>
    <fullName>Music_Usage_Promo_Length__c</fullName>
    <label>Promo Length</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

objects/Music_Usage__c/fields/Music_Usage_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Music_Usage_Start_Date__c</fullName>
    <description>This is Music Usage Start Date field.</description>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

objects/Music_Usage__c/fields/Music_Usage_Track__c.field-meta.xml
<CustomField>
    <fullName>Music_Usage_Track__c</fullName>
    <description>This is Music Usage Track field.</description>
    <label>Track</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

objects/Music_Usage__c/fields/Music_Usage_Track_Info__c.field-meta.xml
<CustomField>
    <fullName>Music_Usage_Track_Info__c</fullName>
    <description>This is Music Usage Track Info field.</description>
    <label>Track Info</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

objects/Schedule_Template__c/Schedule_Template__c.object-meta.xml
<CustomObject>
    <description>This is Schedule Template object.</description>
    <label>Schedule Template</label>
    <nameField>
        <label>Schedule Template</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Schedule Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Schedule_Template__c/fields/Media_Types__c.field-meta.xml
<CustomField>
    <fullName>Media_Types__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Media Type</label>
    <referenceTo>Media_Type__c</referenceTo>
    <relationshipLabel>Schedule Templates</relationshipLabel>
    <relationshipName>Schedule_Templates</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Specification_Template__c/Specification_Template__c.object-meta.xml
<CustomObject>
    <description>This is Creative Brief Template object. Also known as Specification Template.</description>
    <label>Creative Brief Template</label>
    <nameField>
        <label>Creative Brief Template</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Creative Brief Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CreateNewMusicUsage.cls
// This class is used as extension for inseting Music Usage record
// This class is used as extension for page : CreateNewMusicUsage
public with sharing class CreateNewMusicUsage {
/*
    // Global variables
    
    public String jobId{get;set;}
    public String jobName{get;set;}
    private final Music_Usage__c objMU;

    // End of Global variables
    
    // Start constructor
    public CreateNewMusicUsage(ApexPages.StandardController controller) 
    {
        this.objMU = (Music_Usage__c)controller.getRecord(); 
        jobId=ApexPages.CurrentPage().getParameters().get('jobId');
        objMU.Job__c = jobId;
    }
    // End of constructor
    
    // This method is called on to handle Save button
    public pagereference save()
    {
        try
        {
            insert objMU; 
        }
        catch(Exception e)
        {
            return NULL;    
        } 
        Pagereference p=new Pagereference('/apex/JobListView?id='+jobId+'&intFocus=12');
        p.setRedirect(true);
        return(p);
    }
    // End of method Save
    
    // This method is called on to handle Cancel button
    public pagereference cancel()
    {
        Pagereference p=new Pagereference('/apex/JobListView?id='+jobId+'&intFocus=12');
        p.setRedirect(true);
        return p;
    }
    // End of method Cancel
    
    // Start Test method
    static testMethod void Test_CreateNewMusicUsage()
    {
        Job_Number_Setting__c customSetting351 = new  Job_Number_Setting__c(Name= 'yy');
                insert customSetting351;
            
        Media_Type__c testMedia1=new Media_Type__c(Name='Test Media 3519');
                insert testMedia1;
             
        Schedule_Template__c testST1=new Schedule_Template__c(Name='Test Schedule Template 3519',Media_Types__c=testMedia1.Id);
                insert testST1;
                 
        Specification_Template__c testSpec1=new Specification_Template__c(Name='Testing Spcification Template 3519');
                insert testSpec1;
                
        Job__c testJob1=new Job__c(Name='Test Job 3519',Flag__c=True, Job_Auto_Number__c='Job 3519',Start_Date__c=System.Today(),Media_Types__c=testMedia1.Id,Schedule_Template__c=testST1.Id,Specification_Template__c=testSpec1.Id);
                insert testJob1;
                 
        System.assertEquals('Test Job 3519',testJob1.Name);        
         
        Music_Usage__c testMU1=new Music_Usage__c(
                                    Name='Test MU 3519',
                                    Job__c = testJob1.Id,
                                    Music_Usage_Promo_Length__c = 'Test Promo Length', 
                                    Music_Usage_Track__c = 'Test Track', 
                                    Music_Usage_Track_Info__c = 'Test Track Info',
                                    Music_Usage_Drop__c = 'Test Drop',
                                    Music_Usage_Start_Date__c = System.Today(),
                                    Music_Usage_End_Date__c = System.Today() + 5 );   
                
        
        ApexPages.currentPage().getParameters().put('jobId',testJob1.id);
        
        // Instantiate the standard controller with Music Usage
        ApexPages.StandardController con= new ApexPages.StandardController(testMU1);
        
        // Instantiate the extension instance with the standard controller
       CreateNewMusicUsage ext= new CreateNewMusicUsage(con);
        
        // Invoke the primary methods on extension
        ApexPages.Pagereference result=ext.save();
        
        result = ext.cancel();    
        
        delete testMU1; // To cover catch block inside save method
        
        result = ext.save();
    }*/
    // End of Test method

}// End of class