objects/Job__c/Job__c.object-meta.xml
<CustomObject>
    <description>This is Job object.</description>
    <label>Job</label>
    <nameField>
        <label>Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Job_Spec__c/Job_Spec__c.object-meta.xml
<CustomObject>
    <description>This is Creative Brief object. Also known as Job Spec.</description>
    <label>Creative Brief</label>
    <nameField>
        <label>Spec Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Creative Briefs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Job_Spec__c/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <label>Job Name</label>
    <referenceTo>Job__c</referenceTo>
    <relationshipLabel>Creative Briefs</relationshipLabel>
    <relationshipName>Job_Specs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

classes/TestSpecViewSwitchExt.cls
@isTest
public class TestSpecViewSwitchExt {
	static TestMethod void TestSpecViewSwitchExt  (){
       /* job__c job=new job__c(Name='testjob');
        insert job;
        Job_Spec__c testSpec=new Job_Spec__c(Name='Camp',job__c=job.id);
        insert testSpec;
        SpecViewSwitchExt controller = new SpecViewSwitchExt (new ApexPages.StandardController(testSpec));
       // boolean x = controller.isMobile;
       controller.pagedir();*/
}
}