objects/Job__c/Job__c.object-meta.xml
<CustomObject>
    <description>This is Job object.</description>
    <label>Job</label>
    <nameField>
        <label>Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Job__c/fields/Media_Types__c.field-meta.xml
<CustomField>
    <fullName>Media_Types__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Media Type</label>
    <referenceTo>Media_Type__c</referenceTo>
    <relationshipName>Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Job__c/fields/Schedule_Template__c.field-meta.xml
<CustomField>
    <fullName>Schedule_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Schedule Template</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Schedule_Template__c.Media_Types__c</field>
            <operation>equals</operation>
            <valueField>$Source.Media_Types__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Schedule_Template__c</referenceTo>
    <relationshipName>Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Job__c/fields/Specification_Template__c.field-meta.xml
<CustomField>
    <fullName>Specification_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Creative Brief Template</label>
    <referenceTo>Specification_Template__c</referenceTo>
    <relationshipName>Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Job_Task__c/Job_Task__c.object-meta.xml
<CustomObject>
    <description>This is Job Task object. Also known as Schedule.</description>
    <label>Job Task</label>
    <nameField>
        <label>Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Job_Task__c/fields/Days__c.field-meta.xml
<CustomField>
    <fullName>Days__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Days</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

objects/Job_Task__c/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <label>Job Name</label>
    <referenceTo>Job__c</referenceTo>
    <relationshipName>Job_Task</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/Job_Task_Role__c/Job_Task_Role__c.object-meta.xml
<CustomObject>
    <description>Staff assigned to the Job Tasks.</description>
    <label>Task Staff Assigned</label>
    <nameField>
        <label>Role</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Task Staff Assigned</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Job_Task_Role__c/fields/Job_Task__c.field-meta.xml
<CustomField>
    <fullName>Job_Task__c</fullName>
    <label>Job Task</label>
    <referenceTo>Job_Task__c</referenceTo>
    <relationshipName>Job_Task_Roles</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/Job_Team__c/Job_Team__c.object-meta.xml
<CustomObject>
    <description>This is Job Team object. It is used to store role and assigned staff to that role for a Job record.</description>
    <label>Job Team</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>JobTeam Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Team</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Job_Team__c/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <label>Job Name</label>
    <referenceTo>Job__c</referenceTo>
    <relationshipLabel>Job Team</relationshipLabel>
    <relationshipName>Job_Team</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/Media_Type__c/Media_Type__c.object-meta.xml
<CustomObject>
    <description>This is Media Type object.</description>
    <label>Media Type</label>
    <nameField>
        <label>Media Type</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Media Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Schedule_Template__c/Schedule_Template__c.object-meta.xml
<CustomObject>
    <description>This is Schedule Template object.</description>
    <label>Schedule Template</label>
    <nameField>
        <label>Schedule Template</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Schedule Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Schedule_Template__c/fields/Media_Types__c.field-meta.xml
<CustomField>
    <fullName>Media_Types__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Media Type</label>
    <referenceTo>Media_Type__c</referenceTo>
    <relationshipLabel>Schedule Templates</relationshipLabel>
    <relationshipName>Schedule_Templates</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Specification_Template__c/Specification_Template__c.object-meta.xml
<CustomObject>
    <description>This is Creative Brief Template object. Also known as Specification Template.</description>
    <label>Creative Brief Template</label>
    <nameField>
        <label>Creative Brief Template</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Creative Brief Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/JobTaskRoleExtension.cls
// This class is used to add Role for Task 
public with sharing class JobTaskRoleExtension {

    // Global variables 
    /*public  boolean isError{get;set;}
    public List<RoleWrapper> rolewraps{get;set;}
    public Job_Task_Role__c stRole{get;set;}
    public List<Job_Task_Role__c> lst{get;set;}
    List<Job_Team__c> lstJobTeam{get;set;}
    public Job_Task_Role__c stc;
    String strSTId,strid;
    public String qid{get;set;}
    // End of Global variables 

    // Standard Controller 
    public JobTaskRoleExtension(ApexPages.StandardController controller) 
    {
       isError=false;
       this.stc=(Job_Task_Role__c)controller.getrecord();
       qid=ApexPages.CurrentPage().getParameters().get('qid');
       stc.Job_Task__c=qid;
       roleWraps=new List<RoleWrapper>();
    
       List<UserRole> uRole=[Select Name from UserRole ORDER By Name LIMIT 10000];
    
        for(UserRole u: uRole)
        {
            RoleWrapper rw=new RoleWrapper();
            rw.u=u;
            rw.checked=false;
            roleWraps.add(rw);        
        }
    }
    // End of Constructor

     // Start Wrapper class : THis class will bind Role and Checkbox on User interface
     public class RoleWrapper
     {
         public UserRole u{get;set;}
         public Boolean checked{get;set;}
     }
     // End of Wrapper Class
            
    // Method called on to Save selected Roles
    public pagereference Save()
    {
     try
      {
         for(RoleWrapper rw:roleWraps)
         {
            lst=new List<Job_Task_Role__c>();
            lstJobTeam=new List<Job_Team__c>(); 
            if(rw.checked==true)
             {
                 stRole=new Job_Task_Role__c();
                 strid = stc.Job_Task__c;
                  if (Schema.sObjectType.Job_Task_Role__c.fields.Name.isCreateable()) {   
                      stRole.Name=rw.u.Name;}
                 if (Schema.sObjectType.Job_Task_Role__c.fields.Job_Task__c.isCreateable()) {   
                     stRole.Job_Task__c=strid;}
                 lst.add(stRole);
             }
             if(Schema.sObjectType.Job_Task_Role__c.isCreateable()){ insert lst;}
         }
             // After Save operation navigate to JobTaskDetail page
             PageReference p =  new Pagereference('/apex/JobTaskDetailPage?id='+qid);
             p.setRedirect(true);
             return p;
         }
        catch(DMLException e)
        {
          isError = true;
          ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, string.valueOf(e))); 
          return null;
        }    
     }
     // End Of Save method
     
     // Method called on to handle Cancel button operation 
     public pagereference cancel()
     {
         // strid = stc.Job_Task__c;
          PageReference p =  new Pagereference('/apex/JobTaskDetailPage?id='+qid);
          p.setRedirect(true);
          return p;
     }
     // End of Cancel Button
     
     // Test Coverage 
         static testMethod void Test_JobTaskRoleExtension()
         {
           Media_Type__c testMedia=new Media_Type__c(Name='Test Media 303');
           
           try
           {
               insert testMedia;
           }
           catch(System.DMLException e)
           {
                  System.assertEquals('FIELD_CUSTOM_VALIDATION',e.getDmlStatusCode(0));
           }
                
          Schedule_Template__c testST=new Schedule_Template__c(Name='Test Schedule Template 303',Media_Types__c=testMedia.Id);
                 insert testST;
                 
          Schedule_Template__c testST1=new Schedule_Template__c(Name='Test Schedule Template 304',Media_Types__c=testMedia.Id);
                 insert testST1;
                 
          Specification_Template__c testSpec=new Specification_Template__c(Name='Testing Spcification Template 303');
                 insert testSpec;
                
          Specification_Template__c testSpec1=new Specification_Template__c(Name='Testing Spcification Template 304');
                 insert testSpec1;
           
          Job__c testJob1=new Job__c(Name='Test Job 303',Start_Date__c=System.Today(),Media_Types__c=testMedia.Id,Schedule_Template__c=testST.Id,Specification_Template__c=testSpec.Id);
               try
               {
                   insert testJob1;
               }
               catch(System.DMLException e)
               {
                    System.assertEquals('FIELD_CUSTOM_VALIDATION',e.getDmlStatusCode(0));
               }      
          System.assertEquals('Test Job 303',testJob1.Name);
               
          Job_Task__c testJT=new Job_Task__c(Name='Test Job Task 301',Job__c=testJob1.Id,Days__c=5,Start_Date__c=System.Today());
           try
            {
                 insert testJT;
            }       
           catch(System.DMLException e)
            {
                  System.assertEquals('FIELD_CUSTOM_VALIDATION',e.getDmlStatusCode(0));
            }
       
       // Instantiate the standard controller with the Job Task
       Job_Task_Role__c objJTR=new Job_Task_Role__c(Job_Task__c=testJT.Id);
       ApexPages.StandardController con = new ApexPages.StandardController(objJTR);
        
      // Instantiate the extention instance with the standard controller
      JobTaskRoleExtension ext=new JobTaskRoleExtension(con);
              
      
      // Invoke the Save method on the extension
      ApexPages.PageReference result=ext.Save();
      ext.roleWraps[0].checked=true;
      result=ext.save();
      ApexPages.PageReference result1=ext.cancel();
    }
// End of Test Coverage */
}
// End of Class