objects/Job__c/Job__c.object-meta.xml
<CustomObject>
    <description>This is Job object.</description>
    <label>Job</label>
    <nameField>
        <label>Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Purchase_Order__c/Purchase_Order__c.object-meta.xml
<CustomObject>
    <description>This is Purchase Order object.</description>
    <label>Purchase Order</label>
    <nameField>
        <label>PO #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Purchase Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Purchase_Order__c/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <label>Job Name</label>
    <referenceTo>Job__c</referenceTo>
    <relationshipLabel>Purchase Orders</relationshipLabel>
    <relationshipName>Purchase_Orders</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

classes/POViewSwitchExt.cls
public with sharing class POViewSwitchExt {

    public boolean isLtng{private set; get{
                                            String theme = UserInfo.getUITheme();
                                            return (theme=='Theme4d')?true:false;
                                          }
            }  
            
    
    
    public string POId{get;set;}
    public Purchase_Order__c PO{get;set;}
    
    public POViewSwitchExt (ApexPages.StandardController controller) 
    {
        POId = controller.getRecord().id;
        
        PO=[select id,name,Job__c from Purchase_Order__c where id=:POId];
        
    }
    
    Public PageReference pagedir()
    {
         String jobid;
         jobid =  PO.Job__c;
         
        if(isLtng)
        {
             PageReference p =  new Pagereference('/apex/JobdetailpageLightening07?id='+jobId+'&tab=Jobcost'+'&section=purchaseorders');
             p.setRedirect(true);
             return p; 
        }
        else
        {
                PageReference p =  new Pagereference('/apex/jobListView?id='+jobId+'&intFocus=6');
                p.setRedirect(true);
                return p;
        }
         
    }
  
}