objects/Job__c/Job__c.object-meta.xml
<CustomObject>
    <description>This is Job object.</description>
    <label>Job</label>
    <nameField>
        <label>Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Job__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Requested</fullName>
                <default>true</default>
                <label>Requested</label>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

classes/TestActiveJobsByUserDashboardExt.cls
@istest
public class TestActiveJobsByUserDashboardExt {
    @istest static void TestActiveJobsByUserDashBoard(){
        
      /*   job__c job=new job__c(Name='testjob',Status__c='Active');
        insert job;
        ActiveJobsByUserDashboardExt ext=new ActiveJobsByUserDashboardExt(new Apexpages.StandardController(job));
         ext.beginning();
         ext.end();
        ext.getnxt();
        ext.getprev();
        ext.getJobs();
        ext.next();
        ext.previous();
        */
        
    }
    

}