objects/Job__c/Job__c.object-meta.xml
<CustomObject>
    <description>This is Job object.</description>
    <label>Job</label>
    <nameField>
        <label>Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Job__c/fields/Flag__c.field-meta.xml
<CustomField>
    <fullName>Flag__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This is flag field to check import process.</description>
    <label>Flag</label>
    <type>Checkbox</type>
</CustomField>

objects/Job__c/fields/Job_Auto_Number__c.field-meta.xml
<CustomField>
    <fullName>Job_Auto_Number__c</fullName>
    <defaultValue>&quot;Auto Fill&quot;</defaultValue>
    <externalId>true</externalId>
    <label>Job #</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

objects/Job__c/fields/Media_Types__c.field-meta.xml
<CustomField>
    <fullName>Media_Types__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Media Type</label>
    <referenceTo>Media_Type__c</referenceTo>
    <relationshipName>Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Job__c/fields/Schedule_Template__c.field-meta.xml
<CustomField>
    <fullName>Schedule_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Schedule Template</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Schedule_Template__c.Media_Types__c</field>
            <operation>equals</operation>
            <valueField>$Source.Media_Types__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Schedule_Template__c</referenceTo>
    <relationshipName>Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Job__c/fields/Specification_Template__c.field-meta.xml
<CustomField>
    <fullName>Specification_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Creative Brief Template</label>
    <referenceTo>Specification_Template__c</referenceTo>
    <relationshipName>Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Job_Spec__c/Job_Spec__c.object-meta.xml
<CustomObject>
    <description>This is Creative Brief object. Also known as Job Spec.</description>
    <label>Creative Brief</label>
    <nameField>
        <label>Spec Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Creative Briefs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Job_Spec__c/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <label>Job Name</label>
    <referenceTo>Job__c</referenceTo>
    <relationshipLabel>Creative Briefs</relationshipLabel>
    <relationshipName>Job_Specs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/Media_Type__c/Media_Type__c.object-meta.xml
<CustomObject>
    <description>This is Media Type object.</description>
    <label>Media Type</label>
    <nameField>
        <label>Media Type</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Media Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Schedule_Template__c/Schedule_Template__c.object-meta.xml
<CustomObject>
    <description>This is Schedule Template object.</description>
    <label>Schedule Template</label>
    <nameField>
        <label>Schedule Template</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Schedule Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Schedule_Template__c/fields/Media_Types__c.field-meta.xml
<CustomField>
    <fullName>Media_Types__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Media Type</label>
    <referenceTo>Media_Type__c</referenceTo>
    <relationshipLabel>Schedule Templates</relationshipLabel>
    <relationshipName>Schedule_Templates</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Specification_Template__c/Specification_Template__c.object-meta.xml
<CustomObject>
    <description>This is Creative Brief Template object. Also known as Specification Template.</description>
    <label>Creative Brief Template</label>
    <nameField>
        <label>Creative Brief Template</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Creative Brief Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/TestdeleteJobSpec.cls
@isTest
public class TestdeleteJobSpec
{
/*
          // Test Coverage Code
     static testMethod void TestdeleteJobSpec()
      {
             
           Media_Type__c testMedia=new Media_Type__c(Name='Test Media 329');
               insert testMedia;
             
           Schedule_Template__c testST=new Schedule_Template__c(Name='Test Schedule Template 329',Media_Types__c=testMedia.Id);
               insert testST;
                 
           Specification_Template__c testSpec=new Specification_Template__c(Name='Testing Spcification Template 329');
               insert testSpec;
                
           Job__c testJob1=new Job__c(Job_Auto_Number__c='329',Flag__c=True,Name='Test Job 329',Start_Date__c=System.Today(),Media_Types__c=testMedia.Id,Schedule_Template__c=testST.Id,Specification_Template__c=testSpec.Id);
               insert testJob1;
       
           System.assertEquals('Test Job 329',testjob1.Name);
                 
           Job_Spec__c testJobSpec=new Job_Spec__c(Name='Job Spec 329',Job__c=testJob1.Id);
               insert testJobSpec;
                 
           // Test Duplicate JobSpec for any Job
           Job_Spec__c testJobSpec1=new Job_Spec__c(Name='Job Spec 329',Job__c=testJob1.Id);
            try
             {
                 insert testJobSpec1;
             }
             catch(System.DMLException e)
             {
                 System.assertEquals('FIELD_CUSTOM_VALIDATION_EXCEPTION'  ,  e.getDmlStatusCode(0));
             }
        
           Job_Spec__c testJobSpec2=new Job_Spec__c(Name='Job Spec 629',Job__c=testJob1.Id);
               insert testJobSpec2; 
               testJobSpec2.Name='Job Spec 329'; 
                try
                {
                     update testJobSpec2;
                }
                catch(System.DMLException e)
                {
                     System.assertEquals('FIELD_CUSTOM_VALIDATION_EXCEPTION'  ,  e.getDmlStatusCode(0));
                } 
               // End Duplicate Job Spec
                 
           // Instantiate the standard controller with the Job 
        ApexPages.currentPage().getParameters().put('Id',testJobSpec.Id);
        ApexPages.StandardController con=new ApexPages.StandardController(testJobSpec);
        
        // Instantiate the extention instance with the standardcontroller 
        DeleteJobSpecExtension ext=new DeleteJobSpecExtension(con);
        
        // Invoke the primary method on the extension 
        ApexPages.PageReference result=ext.checkDelete();
        
        // Below code covers the Catch statement 
        result=ext.checkDelete();       
      }
    // ENd of Test Method
*/
}