objects/Job__c/Job__c.object-meta.xml
<CustomObject>
    <description>This is Job object.</description>
    <label>Job</label>
    <nameField>
        <label>Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Job__c/fields/Media_Types__c.field-meta.xml
<CustomField>
    <fullName>Media_Types__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Media Type</label>
    <referenceTo>Media_Type__c</referenceTo>
    <relationshipName>Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Job__c/fields/Schedule_Template__c.field-meta.xml
<CustomField>
    <fullName>Schedule_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Schedule Template</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Schedule_Template__c.Media_Types__c</field>
            <operation>equals</operation>
            <valueField>$Source.Media_Types__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Schedule_Template__c</referenceTo>
    <relationshipName>Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Job__c/fields/Specification_Template__c.field-meta.xml
<CustomField>
    <fullName>Specification_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Creative Brief Template</label>
    <referenceTo>Specification_Template__c</referenceTo>
    <relationshipName>Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Job_Number_Setting__c/Job_Number_Setting__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This is Job Auto Number setting to set the Job Number format.</description>
    <label>Job Number</label>
</CustomObject>

objects/Job_Spec__c/Job_Spec__c.object-meta.xml
<CustomObject>
    <description>This is Creative Brief object. Also known as Job Spec.</description>
    <label>Creative Brief</label>
    <nameField>
        <label>Spec Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Creative Briefs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Job_Spec__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <defaultValue>&quot;Enter Description here&quot;</defaultValue>
    <label>Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

objects/Job_Spec__c/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <label>Job Name</label>
    <referenceTo>Job__c</referenceTo>
    <relationshipLabel>Creative Briefs</relationshipLabel>
    <relationshipName>Job_Specs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/Media_Type__c/Media_Type__c.object-meta.xml
<CustomObject>
    <description>This is Media Type object.</description>
    <label>Media Type</label>
    <nameField>
        <label>Media Type</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Media Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Schedule_Template__c/Schedule_Template__c.object-meta.xml
<CustomObject>
    <description>This is Schedule Template object.</description>
    <label>Schedule Template</label>
    <nameField>
        <label>Schedule Template</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Schedule Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Schedule_Template__c/fields/Media_Types__c.field-meta.xml
<CustomField>
    <fullName>Media_Types__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Media Type</label>
    <referenceTo>Media_Type__c</referenceTo>
    <relationshipLabel>Schedule Templates</relationshipLabel>
    <relationshipName>Schedule_Templates</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Spec_Item__c/Spec_Item__c.object-meta.xml
<CustomObject>
    <description>This is Spec Item object. It is child object of Creative Brief Template/ Specification Template object.</description>
    <label>Creative Spec Items</label>
    <nameField>
        <label>Spec Item</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Spec Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Spec_Item__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <defaultValue>&quot;Enter Description here&quot;</defaultValue>
    <label>Description</label>
    <type>TextArea</type>
</CustomField>

objects/Spec_Item__c/fields/Specification_Template__c.field-meta.xml
<CustomField>
    <fullName>Specification_Template__c</fullName>
    <label>Specification Template</label>
    <referenceTo>Specification_Template__c</referenceTo>
    <relationshipName>Spec_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

objects/Specification_Template__c/Specification_Template__c.object-meta.xml
<CustomObject>
    <description>This is Creative Brief Template object. Also known as Specification Template.</description>
    <label>Creative Brief Template</label>
    <nameField>
        <label>Creative Brief Template</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Creative Brief Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Tag__c/Tag__c.object-meta.xml
<CustomObject>
    <description>This is Tag object. It stores the tags of Job record.</description>
    <label>Job Tags</label>
    <nameField>
        <label>Tag</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Tags</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Tag__c/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <label>Job Name</label>
    <referenceTo>Job__c</referenceTo>
    <relationshipName>Tags</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/Tag_Template__c/Tag_Template__c.object-meta.xml
<CustomObject>
    <description>This object holds the template for tag object.</description>
    <label>Tag Template</label>
    <nameField>
        <label>Tag Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tag Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Tag_Template_Item__c/Tag_Template_Item__c.object-meta.xml
<CustomObject>
    <description>This object holds the tag template items.</description>
    <label>Tags Admin</label>
    <nameField>
        <label>Tag Line Item</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tags_Admin</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Tag_Template_Item__c/fields/Air_Date__c.field-meta.xml
<CustomField>
    <fullName>Air_Date__c</fullName>
    <label>Air Date</label>
    <type>Date</type>
</CustomField>

objects/Tag_Template_Item__c/fields/Air_Time__c.field-meta.xml
<CustomField>
    <fullName>Air_Time__c</fullName>
    <label>Air Time</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

objects/Tag_Template_Item__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Tag Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

objects/Tag_Template_Item__c/fields/Lengths__c.field-meta.xml
<CustomField>
    <fullName>Lengths__c</fullName>
    <label>Lengths</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

objects/Tag_Template_Item__c/fields/Promo_Due_Date__c.field-meta.xml
<CustomField>
    <fullName>Promo_Due_Date__c</fullName>
    <label>Promo Due Date</label>
    <type>Date</type>
</CustomField>

objects/Tag_Template_Item__c/fields/Promo_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Promo_End_Date__c</fullName>
    <label>Promo End Date</label>
    <type>Date</type>
</CustomField>

objects/Tag_Template_Item__c/fields/Show_Air_Date__c.field-meta.xml
<CustomField>
    <fullName>Show_Air_Date__c</fullName>
    <label>Show Air Date</label>
    <type>Date</type>
</CustomField>

objects/Tag_Template_Item__c/fields/TagTemplate__c.field-meta.xml
<CustomField>
    <fullName>TagTemplate__c</fullName>
    <description>This is master for tag line item</description>
    <label>Tag Template</label>
    <referenceTo>Tag_Template__c</referenceTo>
    <relationshipName>Tag_Template_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

classes/displayTagsUnderJobTab_New_Test.cls
//@IsTest
public class displayTagsUnderJobTab_New_Test{
    /*static testMethod void Test_RetrieveJobTags()
    {
        Job_Number_Setting__c customSetting1310 = new  Job_Number_Setting__c(Name='NO');

            insert customSetting1310;
            
        Media_Type__c testMedia=new Media_Type__c(Name='Test Media 1310');
             
                insert testMedia;
             
        Schedule_Template__c testST=new Schedule_Template__c(Name='Test Schedule Template 1310',Media_Types__c=testMedia.Id);
             
                 insert testST;
                 
        Specification_Template__c testSpec1=new Specification_Template__c(Name='Testing Spcification Template 1310');
                insert testSpec1;
                
        Spec_Item__c testSPI1=new Spec_Item__c(Name='Test SPI 1310',Description__c='Test Desc 1310',Specification_Template__c=testSpec1.id);
             insert testSPI1;     
             
         Specification_Template__c testSpec2=new Specification_Template__c(Name='Testing Spcification Template 1311');
                insert testSpec2;
                
        Spec_Item__c testSPI2=new Spec_Item__c(Name='Test SPI 1311',Description__c='Test Desc 1310',Specification_Template__c=testSpec2.id);
             insert testSPI2;            
        
        Tag_Template__c testTagTemp = new Tag_Template__c(Name='Test tag temp 5Apr13');
            insert testTagTemp;
            
        Tag_Template_Item__c testTagTempItem = new Tag_Template_Item__c(Name='Test temp Item 5Apr13',TagTemplate__c=testTagTemp.id,Air_Time__c='150', Show_Air_Date__c=date.today(), Promo_End_Date__c=date.today(), Promo_Due_Date__c=date.today(), Air_Date__c=date.today(),Lengths__c='200');
            insert testTagTempItem;
            
        Job__c testJob1=new Job__c(Name='Test Job 1310',Start_Date__c=System.Today(),Media_Types__c=testMedia.Id,Schedule_Template__c=testST.Id,Specification_Template__c=testSpec1.Id);
         
                 insert testJob1;
                 
        System.assertEquals('Test Job 1310',testJob1.Name);        
                 
        Job_Spec__c testJobSpec=new Job_Spec__c(Name='Job Spec 1310',Job__c=testJob1.id);        
             
                 insert testJobSpec;
        
        Tag__c testJobTag = new Tag__c(Name='Test temp Item 5Apr13', Job__c=testJob1.id);
                 insert testJobTag;
                 
        ApexPages.currentPage().getParameters().put('id',testJob1.Id); 
       
       // Instantiate the standard controller with the Job
        ApexPages.StandardController con=new ApexPages.StandardController(testJob1);
       
        // Instantiate the extention instance with the standard controller 
        
        displayTagsUnderJobTab_New ext1=new displayTagsUnderJobTab_New(con);
         ext1.queryStringcopy='tag';     
        // Invoke the primary method on the extension
        ext1.tagId = testJobTag.id;
        ApexPages.currentPage().getParameters().put('id',testJob1.Id);
        ApexPages.currentPage().getParameters().put('tagId',testJobTag.Id);
        ext1.DuplicateTag(); 
        
        ApexPages.Pagereference result=ext1.editJobTag();
       
        result=ext1.save();
        ext1.importTags();
        
        ext1.TagTempName=testTagTemp.Id;
        ext1.importTags();
        result=ext1.addNewJobTag();
        
        List<SelectOption> lst=ext1.getTagTemplates();
       
        result=ext1.cancelme();
       
        ext1.deleteJobTag();
        
        List<Job_Spec__c> lstJobTag=[Select id from Job_Spec__c where Job__r.Name=:'Test Job 1310'];
        delete lstJobTag;
        result=ext1.save();
        
        Job__c obj=[Select Id from Job__c where Name=:'Test Job 1310'];
        delete obj;
        
        Specification_Template__c specTemp1=[Select id from Specification_Template__c where Name=:'Testing Spcification Template 1310'];
        delete specTemp1;
        
        Specification_Template__c specTemp2=[Select id from Specification_Template__c where Name=:'Testing Spcification Template 1311'];
        delete specTemp2;
        
        ext1.importTags();
        
        //added by yogini on 18-Sep-13  
              
    }*/
}