objects/Job__c/Job__c.object-meta.xml
<CustomObject>
    <description>This is Job object.</description>
    <label>Job</label>
    <nameField>
        <label>Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Job_Team__c/Job_Team__c.object-meta.xml
<CustomObject>
    <description>This is Job Team object. It is used to store role and assigned staff to that role for a Job record.</description>
    <label>Job Team</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>JobTeam Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Team</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Job_Team__c/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <label>Job Name</label>
    <referenceTo>Job__c</referenceTo>
    <relationshipLabel>Job Team</relationshipLabel>
    <relationshipName>Job_Team</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/Job_Team__c/fields/Staff__c.field-meta.xml
<CustomField>
    <fullName>Staff__c</fullName>
    <label>Staff</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

objects/Staff__c/Staff__c.object-meta.xml
<CustomObject>
    <description>This is Staff object.</description>
    <label>Staff</label>
    <nameField>
        <label>Staff Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Staff</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/JobTeamStaffSectionExtension.cls
// This class is used to display Roles under Job Detail layout 
public with sharing class JobTeamStaffSectionExtension {
     
     // Global Variables 
     
      public List<Job_Team__c> lstJobTeam{get;set;}
      public String jobId;
      
     // End of Global variables 
      
     // Start Constructor
     public JobTeamStaffSectionExtension(ApexPages.StandardController controller)
      {
         jobId=System.currentPagereference().getParameters().get('id');
         lstJobTeam=[Select Id, Role__c,Staff__c, Job__r.Name from Job_Team__c where Job__c =: jobId order by CreatedDate];
      }
      // End of Constructor
      
      
      //start Method to go to the JobTeamAddEditStaff page
      public Pagereference AddStaffs()
       {
           String theId=ApexPages.CurrentPage().getParameters().get('id');
           PageReference p = Page.JobTeamAddEditStaff;
           p.setredirect(true);
           p.getParameters().put('id',theID); 
           return p;
       }
      //End Method to go to the JobTeamAddEditStaff page
      
      
      
 }