objects/Job__c/Job__c.object-meta.xml
<CustomObject>
    <description>This is Job object.</description>
    <label>Job</label>
    <nameField>
        <label>Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Job__c/fields/marked_Done__c.field-meta.xml
<CustomField>
    <fullName>marked_Done__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field is used to marked done all tasks when job status is completed</description>
    <label>marked Done</label>
    <type>Checkbox</type>
</CustomField>

objects/Job__c/fields/Media_Types__c.field-meta.xml
<CustomField>
    <fullName>Media_Types__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Media Type</label>
    <referenceTo>Media_Type__c</referenceTo>
    <relationshipName>Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Job__c/fields/Schedule_Calc__c.field-meta.xml
<CustomField>
    <fullName>Schedule_Calc__c</fullName>
    <label>Schedule  Calc</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Start Date</fullName>
                <default>true</default>
                <label>Start Date</label>
            </value>
            <value>
                <fullName>End Date</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Job__c/fields/Schedule_Template__c.field-meta.xml
<CustomField>
    <fullName>Schedule_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Schedule Template</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Schedule_Template__c.Media_Types__c</field>
            <operation>equals</operation>
            <valueField>$Source.Media_Types__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Schedule_Template__c</referenceTo>
    <relationshipName>Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Job__c/fields/Specification_Template__c.field-meta.xml
<CustomField>
    <fullName>Specification_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Creative Brief Template</label>
    <referenceTo>Specification_Template__c</referenceTo>
    <relationshipName>Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Job__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Requested</fullName>
                <default>true</default>
                <label>Requested</label>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Job_Number_Setting__c/Job_Number_Setting__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This is Job Auto Number setting to set the Job Number format.</description>
    <label>Job Number</label>
</CustomObject>

objects/Job_Spec__c/Job_Spec__c.object-meta.xml
<CustomObject>
    <description>This is Creative Brief object. Also known as Job Spec.</description>
    <label>Creative Brief</label>
    <nameField>
        <label>Spec Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Creative Briefs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Job_Spec__c/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <label>Job Name</label>
    <referenceTo>Job__c</referenceTo>
    <relationshipLabel>Creative Briefs</relationshipLabel>
    <relationshipName>Job_Specs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/Job_Task__c/Job_Task__c.object-meta.xml
<CustomObject>
    <description>This is Job Task object. Also known as Schedule.</description>
    <label>Job Task</label>
    <nameField>
        <label>Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Job_Task__c/fields/Days__c.field-meta.xml
<CustomField>
    <fullName>Days__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Days</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

objects/Job_Task__c/fields/Due_Date__c.field-meta.xml
<CustomField>
    <fullName>Due_Date__c</fullName>
    <label>Auto Due Date</label>
    <type>Date</type>
</CustomField>

objects/Job_Task__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <label>Staff Email</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

objects/Job_Task__c/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <label>Job Name</label>
    <referenceTo>Job__c</referenceTo>
    <relationshipName>Job_Task</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/Job_Task__c/fields/Marked_Done__c.field-meta.xml
<CustomField>
    <fullName>Marked_Done__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Marked Done</label>
    <type>Checkbox</type>
</CustomField>

objects/Job_Task__c/fields/Revised_Due_Date__c.field-meta.xml
<CustomField>
    <fullName>Revised_Due_Date__c</fullName>
    <label>Final Due Date</label>
    <type>Date</type>
</CustomField>

objects/Job_Task__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Requested</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Job_Task__c/fields/Task_Order__c.field-meta.xml
<CustomField>
    <fullName>Task_Order__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Task Order</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

objects/Job_Task_Role__c/Job_Task_Role__c.object-meta.xml
<CustomObject>
    <description>Staff assigned to the Job Tasks.</description>
    <label>Task Staff Assigned</label>
    <nameField>
        <label>Role</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Task Staff Assigned</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Job_Task_Role__c/fields/Job_Task__c.field-meta.xml
<CustomField>
    <fullName>Job_Task__c</fullName>
    <label>Job Task</label>
    <referenceTo>Job_Task__c</referenceTo>
    <relationshipName>Job_Task_Roles</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/Job_Team__c/Job_Team__c.object-meta.xml
<CustomObject>
    <description>This is Job Team object. It is used to store role and assigned staff to that role for a Job record.</description>
    <label>Job Team</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>JobTeam Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Team</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Job_Team__c/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <label>Job Name</label>
    <referenceTo>Job__c</referenceTo>
    <relationshipLabel>Job Team</relationshipLabel>
    <relationshipName>Job_Team</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/Job_Team__c/fields/Staff__c.field-meta.xml
<CustomField>
    <fullName>Staff__c</fullName>
    <label>Staff</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

objects/Media_Type__c/Media_Type__c.object-meta.xml
<CustomObject>
    <description>This is Media Type object.</description>
    <label>Media Type</label>
    <nameField>
        <label>Media Type</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Media Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Schedule_Task__c/Schedule_Task__c.object-meta.xml
<CustomObject>
    <description>This is Schedule Task object. It is child object of Schedule Template object.</description>
    <label>Schedule Task</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Schedule Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Schedule_Task__c/fields/Days__c.field-meta.xml
<CustomField>
    <fullName>Days__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Days</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

objects/Schedule_Task__c/fields/Schedule_Template__c.field-meta.xml
<CustomField>
    <fullName>Schedule_Template__c</fullName>
    <label>Schedule Template</label>
    <referenceTo>Schedule_Template__c</referenceTo>
    <relationshipLabel>Schedule Tasks</relationshipLabel>
    <relationshipName>Schedule_Tasks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/Schedule_Template__c/Schedule_Template__c.object-meta.xml
<CustomObject>
    <description>This is Schedule Template object.</description>
    <label>Schedule Template</label>
    <nameField>
        <label>Schedule Template</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Schedule Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Schedule_Template__c/fields/Media_Types__c.field-meta.xml
<CustomField>
    <fullName>Media_Types__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Media Type</label>
    <referenceTo>Media_Type__c</referenceTo>
    <relationshipLabel>Schedule Templates</relationshipLabel>
    <relationshipName>Schedule_Templates</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/ScheduleTaskRole__c/ScheduleTaskRole__c.object-meta.xml
<CustomObject>
    <description>This is Schedule Task Role object. It is used to store assign roles to Schedule Task.</description>
    <label>ScheduleTask Role</label>
    <nameField>
        <label>Role</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ScheduleTaskRole</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/ScheduleTaskRole__c/fields/Schedule_Task__c.field-meta.xml
<CustomField>
    <fullName>Schedule_Task__c</fullName>
    <label>Schedule Task</label>
    <referenceTo>Schedule_Task__c</referenceTo>
    <relationshipName>ScheduleTaskRole</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/Specification_Template__c/Specification_Template__c.object-meta.xml
<CustomObject>
    <description>This is Creative Brief Template object. Also known as Specification Template.</description>
    <label>Creative Brief Template</label>
    <nameField>
        <label>Creative Brief Template</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Creative Brief Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Staff__c/Staff__c.object-meta.xml
<CustomObject>
    <description>This is Staff object.</description>
    <label>Staff</label>
    <nameField>
        <label>Staff Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Staff</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Staff__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <label>Email</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

classes/Test_RetrieveTaskNewTesting.cls
@isTest
public class Test_RetrieveTaskNewTesting{ 
    static testMethod void Test_RetrieveTaskNewTesting()
        {
           /*   test.starttest();
           Job_Number_Setting__c customSetting1 = new  Job_Number_Setting__c(Name= 'yy');

            insert customSetting1;
         
            Media_Type__c testMedia=new Media_Type__c(Name='Test Media 614');
             
                insert testMedia;
             
            Schedule_Template__c testST=new Schedule_Template__c(Name='Test Schedule Template 614',Media_Types__c=testMedia.Id);
             
                 insert testST;
                 
            Schedule_Task__c testSchedule1=new Schedule_Task__C(Name='Test Schedule Task 914',Schedule_Template__c=testST.id,Days__c=3);
                insert testSchedule1;
                
            Schedule_Task__c testSchedule2=new Schedule_Task__C(Name='Test Schedule Task 915',Schedule_Template__c=testST.id,Days__c=3);
                insert testSchedule2;
                
            ScheduleTaskRole__c testSTR1=new ScheduleTaskRole__c(Name='Test Role 001',Schedule_Task__c=testSchedule1.id);
                insert testSTR1;
                
             Specification_Template__c testSpec=new Specification_Template__c(Name='Testing Spcification Template 614');
                insert testSpec;
                
            Job__c testJob1=new Job__c(Name='Test Job 614',Start_Date__c=System.Today(),Media_Types__c=testMedia.Id,Schedule_Template__c=testST.Id,Specification_Template__c=testSpec.Id,Schedule_Calc__c='Start Date');
         
                 insert testJob1;
                 
             System.assertEquals('Test Job 614',testJob1.Name);
                 
            Job_Task__c testJobTask1=new Job_Task__c(Name='Job Task 615',Job__c=testJob1.Id,Marked_Done__c=True,Days__c=2,Task_Order__c = 1,Revised_Due_Date__c=System.Today()+15,Email__C='mani@gmail.com,sugu@gmail.com');
        
                insert testJobTask1;
             list<Job_Task__c> Jobtasklist=new list<Job_Task__c>();
        
             Job_Task__c testJobTask2=new Job_Task__c(Name='Job Task 616',Job__c=testJob1.Id,Marked_Done__c=False,Days__c=3,Task_Order__c = 2,Revised_Due_Date__c=System.Today()+15,Email__C='mani@gmail.com,sugu@gmail.com');
        
               Jobtasklist.add(testJobTask2);
        
            Job_Task__c testJobTask3=new Job_Task__c(Name='Job Task 617',Job__c=testJob1.Id,Marked_Done__c=False,Days__c=3,Task_Order__c = 3,Revised_Due_Date__c=System.Today()+15,Email__C='mani@gmail.com,sugu@gmail.com');
        
                
                Jobtasklist.add(testJobTask3);
            insert Jobtasklist;    
                
            Job_Task_Role__c testJTR1=new Job_Task_Role__c(Name='Job Task Role 615',Job_Task__c=testJobTask1.Id);
        
                insert testJTR1;
                
                
                
                 List<selectOption> optionList = new List<selectOption>();
        Schema.DescribeFieldResult field = Job__c.Schedule_Calc__c.getDescribe();
        for (Schema.PicklistEntry a : field.getPicklistValues()) 
        {  
            optionList.add(new selectOption(a.getLabel(), a.getLabel()));  
        }
      
           Job__c testJob2=new Job__c(Name='Test Job 615',Due_Date__c=System.Today(),Start_Date__c=System.Today(),Media_Types__c=testMedia.Id,Schedule_Template__c=testST.Id,Specification_Template__c=testSpec.Id,Schedule_Calc__c='End Date');
         
                 insert testJob2;
                 
             System.assertEquals('Test Job 615',testJob2.Name);
                 
            Job_Task__c testJobTask4=new Job_Task__c(Name='Job Task 617',Job__c=testJob2.Id,Marked_Done__c=True,Days__c=2,Task_Order__c = 4,Revised_Due_Date__c=System.Today()+15,Email__C='mani@gmail.com,sugu@gmail.com');
        
                insert testJobTask4;
        
            
            Job_Task__c testJobTask8=new Job_Task__c(Name='Job Task 6188',Job__c=testJob2.Id,Start_Date__c=System.Today(),Marked_Done__c=False,Days__c=3,Task_Order__c = 4,Revised_Due_Date__c=System.Today()+15,Email__C='mani@gmail.com,sugu@gmail.com');
        
                insert testJobTask8;
                
            Job_Task__c testJobTask5=new Job_Task__c(Name='Job Task 619',Job__c=testJob2.Id,Start_Date__c=System.Today(),Marked_Done__c=False, Task_Order__c = 5,Days__c=3,Revised_Due_Date__c=System.Today()+15,Email__C='mani@gmail.com,sugu@gmail.com');
        
                insert testJobTask5;
                
             Job_Task__c testJobTask6=new Job_Task__c(Name='Job Task 618',Job__c=testJob2.Id,Start_Date__c=System.Today(), Task_Order__c = 6,Days__c=3,Marked_Done__c=false,Revised_Due_Date__c=System.Today(),Email__C='mani@gmail.com,sugu@gmail.com' );
        
                insert testJobTask6;
                
            Job_Task__c testJobTask7=new Job_Task__c(Name='Job Task 6191',Job__c=testJob2.Id,Start_Date__c=System.Today(),Marked_Done__c=False,Task_Order__c = 7,Days__c=3,Revised_Due_Date__c=System.Today()+1,Email__C='mani@gmail.com,sugu@gmail.com');
        
                insert testJobTask7;
           
           
           
                
                
            Job_Task_Role__c testJTR2=new Job_Task_Role__c(Name='test',Job_Task__c=testJobTask6.Id,Email__c='mani@gmail.com');
        
                insert testJTR2;
              Job_Team__c jteam = new Job_Team__c(staff__c='test', role__c='test', email__c='test@test.com', job__c=testJob2.id);  
              insert jteam;
             ApexPages.currentPage().getParameters().put('id',testJob1.Id); 
       
            // Instantiate the standard controller with the Job
            
            ApexPages.StandardController con12=new ApexPages.StandardController(testJob1);
            RetrieveTaskNewTesting ext123=new RetrieveTaskNewTesting(con12);
            
            ApexPages.currentPage().getParameters().put('afJobId',testJob2.Id);
            ApexPages.currentPage().getParameters().put('afTaskId',testJobTask6.Id);
            ApexPages.currentPage().getParameters().put('afTeamateName','test');
            
            ApexPages.currentPage().getParameters().put('afTaskId1',testJobTask6.Id);
            ApexPages.currentPage().getParameters().put('afTeamateName1','test');
            
            ext123.addTeams();
            ext123.removeTeam();
            
            test.stoptest();
            
            ApexPages.currentPage().getParameters().put('id',testJob1.Id); 
       
            // Instantiate the standard controller with the Job
            
            ApexPages.StandardController con=new ApexPages.StandardController(testJob1);
       
            // Instantiate the extention instance with the standard controller 

            RetrieveTaskNewTesting ext1=new RetrieveTaskNewTesting(con);
            
            ext1.strJTID=testJobTask1.Id;
           
  //          ext1.strJTID=testJobTask2.Id;
         
            // Invoke the primary method on the extension
            
            ApexPages.Pagereference result=ext1.save();
            
            Job_Task__c objTaskNew = [select id, name,Email__c, Days__c,Start_date__c,Revised_Due_Date__c from Job_Task__c where id=: testJobTask5.id];          
       
       
       DateTime dtnbew = System.Today().AddDays(2);
       Date  dtnbew1 = System.Today();
       Date d4 = Date.newInstance(dtnbew .Year(), dtnbew .Month(), dtnbew .Day());
       objTaskNew.Start_date__c = dtnbew1;
       update objTaskNew;
        //ext1.dt= d4 ;
       ext1.taskId1 = objTaskNew.id; 
            ext1.taskId = testJobTask5.id;
            ext1.dt = System.Today().AddDays(2);
            ext1.updateRestScheduleRevDt = 'true';
       result=ext1.updateRestSchedule();
        
           result=ext1.displayTasksInCalendar();
       
           result=ext1.createSchedule();
       
           result=ext1.addNewTask();
       
           result=ext1.insertNewTask();
       
           result=ext1.EditJobTask();
         
         ext1.insertNewTaskLight();
            ext1.addNewTaskLight();
            ApexPages.currentPage().getParameters().put('index','1'); 
            ext1.updateScheduleHours();
            //ext1.RetrieveTaskNewTesting();
            ext1.RetrieveTaskNewTesting123();
            ext1.taskId123  = objTaskNew.id;
            ext1.dt123 = System.Today().AddDays(2);
            ext1.saveOrder();
            ext1.TaskId3 = objTaskNew.id;
            ext1.moveUpandDown();
            ext1.refreshTasks();
            ext1.Complete();
            ext1.Active();
            ext1.toggleviewCalender();
            ext1.toggleviewList();
             ApexPages.currentPage().getParameters().put('CalTaskId',objTaskNew.id); 
            ext1.calenderTaskEdit();
            ext1.CaleEditSave();
            ext1.CalEditCancel();
             ApexPages.currentPage().getParameters().put('DTaskId',objTaskNew.id);
            ext1.statusChangeUpdate();
             ApexPages.currentPage().getParameters().put('DCalTaskId',objTaskNew.id);
            ApexPages.currentPage().getParameters().put('DcalDueDate','2018-09-09');
            ext1.TaskDueDateUpdate();
            
            ext1.deltask();
         
            Job_Task__c objTaskNew1 = [select id, name,Email__c, Days__c,Start_date__c from Job_Task__c where id=: testJobTask5.id];
       objTaskNew1.Days__c = 2;
       update objTaskNew1;
       ext1.days1= '5';
       ext1.taskId1 = objTaskNew1.id;
       ext1.updateRestScheduleDays= 'true';
        result=ext1.updateScheduleOnDays();
       
      
       
       result=ext1.deleteJobTask();
         result=ext1.cancelme();
       
           result=ext1.createSchedule();
            
      
  /*    
         ApexPages.currentPage().getParameters().put('id',testJob2.Id); 
       
            // Instantiate the standard controller with the Job
            
             con=new ApexPages.StandardController(testJob2);
       
            // Instantiate the extention instance with the standard controller 

            RetrieveTaskNewTesting ext2=new RetrieveTaskNewTesting(con);

           // ext1.strJTID=testJobTask5.Id;
           
            ext1.strJTID=testJobTask6.Id;
         
            // Invoke the primary method on the extension
            
            result=ext1.save();
       
          
            ext1.strJTID=testJobTask6.Id;
            
            
             // testJobTask5=new Job_Task__c(Name='Job Task 6177',Job__c=testJob1.Id,Start_Date__c=System.Today(),Marked_Done__c=False,Days__c=3);
        
              //  insert testJobTask5;
                
            //Job_Task__c objTaskNew2 = [select id, name, Days__c,Start_date__c,Revised_Due_Date__c from Job_Task__c where id=: testJobTask3.id]  ;
      // testJobTask5.Revised_Due_Date__c = ;
       //update testJobTask5;
      
       
        result=ext2.displayTasksInCalendar();
       
         //  result=ext2.createSchedule();
       
         //  result=ext2.addNewTask();
       
         //  result=ext2.insertNewTask();
       
          // result=ext2.EditJobTask();
         
           result=ext2.cancelme();
       
          //result=ext2.createSchedule();
       
           result=ext2.deleteJobTask();
       
       
       
         // Job__c testJob3=new Job__c(Name='Test Job 615',Start_Date__c=System.Today(),Media_Types__c=testMedia.Id,Schedule_Template__c=testST.Id,Specification_Template__c=testSpec.Id,Schedule_Calc__c='Start Date');
         
          //       insert testJob3;
                 
          // ApexPages.currentPage().getParameters().put('id',testJob3.Id); 
         
          // ApexPages.StandardController con2=new ApexPages.StandardController(testJob3);
        
          //  RetrieveTaskNewTesting ext3=new RetrieveTaskNewTesting(con2);
        
         //   result=ext3.createSchedule();
            
           // Delete Job Tasks
             List<Job_Task__c> lstTask=[select id from Job_Task__c where Job__c=:testJob2.Id];
             delete lstTask;
         
             // Delete Job Specs
         
             List<Job_Spec__c> lstSpecs=[select id from Job_Spec__c where Job__c=:testJob2.Id ];
             delete lstSpecs;
         
             Job__c obj1=[Select id,Status__c from Job__c where Name=: 'Test Job 615'];
             obj1.Status__c='Cancelled';
             //update obj1;
         
         // To cover catch block
         // Job__c obj2=[Select id from Job__c where Name=: 'Test Job 615'];
         //delete obj2;
 
     //   delete testJob1;
        result=ext1.save();
            
      
        
    // End of Test Coverage
    */
   
   }
    }