objects/GL_Department__c/GL_Department__c.object-meta.xml
<CustomObject>
    <description>This Object is Master of GLCode Object in JobSuite Application.</description>
    <label>GL Department</label>
    <nameField>
        <label>GL Department</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GL Department</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Job__c/Job__c.object-meta.xml
<CustomObject>
    <description>This is Job object.</description>
    <label>Job</label>
    <nameField>
        <label>Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Job__c/fields/Media_Types__c.field-meta.xml
<CustomField>
    <fullName>Media_Types__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Media Type</label>
    <referenceTo>Media_Type__c</referenceTo>
    <relationshipName>Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Job__c/fields/Schedule_Template__c.field-meta.xml
<CustomField>
    <fullName>Schedule_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Schedule Template</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Schedule_Template__c.Media_Types__c</field>
            <operation>equals</operation>
            <valueField>$Source.Media_Types__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Schedule_Template__c</referenceTo>
    <relationshipName>Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Job__c/fields/Specification_Template__c.field-meta.xml
<CustomField>
    <fullName>Specification_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Creative Brief Template</label>
    <referenceTo>Specification_Template__c</referenceTo>
    <relationshipName>Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Job_Number_Setting__c/Job_Number_Setting__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This is Job Auto Number setting to set the Job Number format.</description>
    <label>Job Number</label>
</CustomObject>

objects/Media_Type__c/Media_Type__c.object-meta.xml
<CustomObject>
    <description>This is Media Type object.</description>
    <label>Media Type</label>
    <nameField>
        <label>Media Type</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Media Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Quote__c/Quote__c.object-meta.xml
<CustomObject>
    <description>This is Quote object.</description>
    <label>Quote</label>
    <nameField>
        <label>Quote Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Quote__c/fields/GL_Department__c.field-meta.xml
<CustomField>
    <fullName>GL_Department__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GL Department</label>
    <referenceTo>GL_Department__c</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Quote__c/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <label>Job Name</label>
    <referenceTo>Job__c</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/Quote_Spec_Item__c/Quote_Spec_Item__c.object-meta.xml
<CustomObject>
    <description>This is Quote Spec Item object. It is child object of Quote object.</description>
    <label>Quote Spec Items</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quote Spec Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Quote_Spec_Item__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <label>Quote</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipName>Quote_Spec_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/Quote_Spec_Item__c/fields/Specification_Template__c.field-meta.xml
<CustomField>
    <fullName>Specification_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Specification Template</label>
    <referenceTo>Specification_Template__c</referenceTo>
    <relationshipName>Quote_Spec_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Schedule_Template__c/Schedule_Template__c.object-meta.xml
<CustomObject>
    <description>This is Schedule Template object.</description>
    <label>Schedule Template</label>
    <nameField>
        <label>Schedule Template</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Schedule Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Schedule_Template__c/fields/Media_Types__c.field-meta.xml
<CustomField>
    <fullName>Media_Types__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Media Type</label>
    <referenceTo>Media_Type__c</referenceTo>
    <relationshipLabel>Schedule Templates</relationshipLabel>
    <relationshipName>Schedule_Templates</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Specification_Template__c/Specification_Template__c.object-meta.xml
<CustomObject>
    <description>This is Creative Brief Template object. Also known as Specification Template.</description>
    <label>Creative Brief Template</label>
    <nameField>
        <label>Creative Brief Template</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Creative Brief Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CreateNewQuoteSpecItemExtension.cls
/* This Class is used to create ne quote spec item functionality */
public with sharing class CreateNewQuoteSpecItemExtension 
{
    
     public boolean isLtng{private set; get{
                                            String theme = UserInfo.getUITheme();
                                            return (theme=='Theme4d')?true:false;
                                          }
            }  
    
    private final Quote_Spec_Item__c objQSI;
    public Id QId{get;set;}
    public String strQuote{get;set;}

   /* start of Constructor */
    public CreateNewQuoteSpecItemExtension(ApexPages.StandardController controller) 
     {
     QId=ApexPages.currentPage().getParameters().get('Qid');
     Quote__c objQuote=[Select id,Name from Quote__c where id=:QId];
     strQuote=objQuote.Name;
     this.objQSI = (Quote_Spec_Item__c)controller.getRecord(); 
     }
   /* End of Constructor */  
    
    /* Save Method */
    Public PageReference saveme()
     {
     
       Quote_Spec_Item__c obj=new Quote_Spec_Item__c(Quote__c=QId,Name=objQSI.Name,Description__c=objQSI.Description__c);
           try
            {
                insert obj;
            }
            catch(System.DMLException e)
            {
                return NULL;
            }    
           /* once item is inserted user should navigate to its Quote's detail page */   
           
           
           
           if(isLtng)
            {
                 PageReference p =  new Pagereference('/apex/QuoteDetailPageLightning?id='+QId+'&section=estspecitems');
                 p.setRedirect(true);                 return p; 
            }
            else
            {
                    PageReference p =  new Pagereference('/apex/QuoteDetailPage?id='+QId);
                    p.setRedirect(true);
                    return p;
            }
           
          
     }
    /*End of Save method */ 
    
   // This method is called on to handle Cancel button
   Public PageReference cancelme()
    {     
           if(isLtng)
            {
                 PageReference p =  new Pagereference('/apex/QuoteDetailPageLightning?id='+QId+'&section=estspecitems');
                 p.setRedirect(true);
                 return p; 
            }
            else
            {
                    PageReference p =  new Pagereference('/apex/QuoteDetailPage?id='+QId);
                    p.setRedirect(true);
                    return p;
            }
    }
    // ENd Cancel method 
    
  
    /* Test Coverage */
   /* static testMethod void CreateQuoteSIPositiveTest()
     {
        Job_Number_Setting__c customSetting995 = new  Job_Number_Setting__c(Name= 'yy');
        insert customSetting995;
 
        Media_Type__c testMedia=new Media_Type__c(Name='Test Media 320');
        insert testMedia;
             
        Schedule_Template__c testST=new Schedule_Template__c(Name='Test Schedule Template 320',Media_Types__c=testMedia.Id);
        insert testST;
                 
        Schedule_Template__c testST1=new Schedule_Template__c(Name='Test Schedule Template 320',Media_Types__c=testMedia.Id);
         try
          {
          insert testST1;
          }
         catch(System.DMLException e)
          {
          System.assertEquals('FIELD_CUSTOM_VALIDATION_EXCEPTION',e.getDmlStatusCode(0));
          }
              
        Specification_Template__c testSpec=new Specification_Template__c(Name='Testing Spcification Template 320');
        insert testSpec;
                
        Specification_Template__c testSpec1=new Specification_Template__c(Name='Testing Spcification Template 320');
         try
          {
          insert testSpec1;
          }
         catch(System.DMLException e)
          {
          System.assertEquals('FIELD_CUSTOM_VALIDATION_EXCEPTION',e.getDmlStatusCode(0));
          }
           
        Job__c testJob1=new Job__c(Name='Test Job 320',Start_Date__c=System.Today(),Media_Types__c=testMedia.Id,Schedule_Template__c=testST.Id,Specification_Template__c=testSpec.Id);
         try
          {
          insert testJob1;
          }
         catch(System.DMLException e)
          {
          System.assert(e.getMessage().contains('Job with same name Exists'));
          }
         System.assertEquals('Test Job 320',testJob1.Name);      
       
         GL_Department__c testGLD = new GL_Department__c(Name='TestGLD11');
          try
           {
           insert testGLD;
           }
          catch(System.DMLException e)
           {
           System.assertEquals('FIELD_CUSTOM_VALIDATION_EXCEPTION',e.getDmlStatusCode(0));
           }
            
         Quote__c testQ=new Quote__c(Name='Quote 320',Job__c=testjob1.Id,GL_Department__c=testGLD.id);
          try
           {
           insert testQ;
           }
          catch(System.DMLException e)
           {
           System.assert(e.getMessage().contains('Job with same name Exists'));
           }
               
         Quote_Spec_Item__c testQSI = new Quote_Spec_Item__c(Name='Spec Item 320',Quote__c=testQ.Id);
             
         /* Instantiate the extention instance with the standard controller 
                  ApexPages.currentPage().getParameters().put('QId',testQ.id); 
         ApexPages.StandardController con=new ApexPages.StandardController(testQSI);
         CreateNewQuoteSpecItemExtension  ext=new CreateNewQuoteSpecItemExtension(con);
        
         /* Invoke the saveme method on the extension
         ApexPages.PageReference result1=ext.saveme();
            
         /* Insert record with required fields missing 
         Quote_Spec_Item__c testQSI1 = new Quote_Spec_Item__c();
            
         /* Instantiate the extention instance with the standard controller 
          ApexPages.currentPage().getParameters().put('QId',testQ.id); 
         ApexPages.StandardController con1=new ApexPages.StandardController(testQSI1);
         CreateNewQuoteSpecItemExtension  ext1=new CreateNewQuoteSpecItemExtension(con1);
        
         /* Invoke the saveme method on the extension 
         ApexPages.PageReference result2=ext1.saveme();
         result2 = ext.cancelme();
     }*/
    /* End of Test Coverage */
}
/* End of Apex class */