objects/GL_Department__c/GL_Department__c.object-meta.xml
<CustomObject>
    <description>This Object is Master of GLCode Object in JobSuite Application.</description>
    <label>GL Department</label>
    <nameField>
        <label>GL Department</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GL Department</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Job__c/Job__c.object-meta.xml
<CustomObject>
    <description>This is Job object.</description>
    <label>Job</label>
    <nameField>
        <label>Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Job__c/fields/Media_Types__c.field-meta.xml
<CustomField>
    <fullName>Media_Types__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Media Type</label>
    <referenceTo>Media_Type__c</referenceTo>
    <relationshipName>Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Job__c/fields/Schedule_Template__c.field-meta.xml
<CustomField>
    <fullName>Schedule_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Schedule Template</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Schedule_Template__c.Media_Types__c</field>
            <operation>equals</operation>
            <valueField>$Source.Media_Types__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Schedule_Template__c</referenceTo>
    <relationshipName>Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Job__c/fields/Specification_Template__c.field-meta.xml
<CustomField>
    <fullName>Specification_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Creative Brief Template</label>
    <referenceTo>Specification_Template__c</referenceTo>
    <relationshipName>Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Media_Type__c/Media_Type__c.object-meta.xml
<CustomObject>
    <description>This is Media Type object.</description>
    <label>Media Type</label>
    <nameField>
        <label>Media Type</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Media Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ProductionEstimate__c/ProductionEstimate__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>This is to use Production Estimate in place of Standard Estimate &amp; New Copy Schedule Button.</description>
    <label>Job Suite Controls</label>
</CustomObject>

objects/ProductionEstimate__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This One Is for to Activate Production Estimate in place of Standard Estimate</description>
    <inlineHelpText>This One Is for to Activate Production Estimate in place of Standard Estimate</inlineHelpText>
    <label>Production Estimate Active</label>
    <type>Checkbox</type>
</CustomField>

objects/Quote__c/Quote__c.object-meta.xml
<CustomObject>
    <description>This is Quote object.</description>
    <label>Quote</label>
    <nameField>
        <label>Quote Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Quote__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Quote Amount</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

objects/Quote__c/fields/GL_Department__c.field-meta.xml
<CustomField>
    <fullName>GL_Department__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GL Department</label>
    <referenceTo>GL_Department__c</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Quote__c/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <label>Job Name</label>
    <referenceTo>Job__c</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/Quote_Spec_Item__c/Quote_Spec_Item__c.object-meta.xml
<CustomObject>
    <description>This is Quote Spec Item object. It is child object of Quote object.</description>
    <label>Quote Spec Items</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quote Spec Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Quote_Spec_Item__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <label>Quote</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipName>Quote_Spec_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/Quote_Spec_Item__c/fields/Specification_Template__c.field-meta.xml
<CustomField>
    <fullName>Specification_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Specification Template</label>
    <referenceTo>Specification_Template__c</referenceTo>
    <relationshipName>Quote_Spec_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Schedule_Template__c/Schedule_Template__c.object-meta.xml
<CustomObject>
    <description>This is Schedule Template object.</description>
    <label>Schedule Template</label>
    <nameField>
        <label>Schedule Template</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Schedule Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Schedule_Template__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

objects/Schedule_Template__c/fields/Media_Types__c.field-meta.xml
<CustomField>
    <fullName>Media_Types__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Media Type</label>
    <referenceTo>Media_Type__c</referenceTo>
    <relationshipLabel>Schedule Templates</relationshipLabel>
    <relationshipName>Schedule_Templates</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Specification_Template__c/Specification_Template__c.object-meta.xml
<CustomObject>
    <description>This is Creative Brief Template object. Also known as Specification Template.</description>
    <label>Creative Brief Template</label>
    <nameField>
        <label>Creative Brief Template</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Creative Brief Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Specification_Template__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Display only Active CB Templates in the Job layout.

Added this field as per dev item #3445</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

objects/Vendor__c/Vendor__c.object-meta.xml
<CustomObject>
    <description>This is Vendor object. Vendors in JobSuite are assigned to the line items on Quotes, Estimates, Purchase Orders and Vendor Invoices.  A printer or photographer may be a vendor.</description>
    <label>Vendor</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vendors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Vendor__c/fields/Vendor__c.field-meta.xml
<CustomField>
    <fullName>Vendor__c</fullName>
    <label>Vendor #</label>
    <length>30</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

objects/Vendor_Quote__c/Vendor_Quote__c.object-meta.xml
<CustomObject>
    <description>This is Vendor Quote object. This object is used to assign Quote to the Vendor.</description>
    <label>Vendor Quote</label>
    <nameField>
        <displayFormat>VQ-{0000}</displayFormat>
        <label>VQ #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vendor Quotes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Vendor_Quote__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Quote Amount</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

objects/Vendor_Quote__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <label>Quote To Vendor</label>
    <type>Date</type>
</CustomField>

objects/Vendor_Quote__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <label>Quote</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipLabel>Vendors</relationshipLabel>
    <relationshipName>Vendor_Quotes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/Vendor_Quote__c/fields/Vendor__c.field-meta.xml
<CustomField>
    <fullName>Vendor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vendor</label>
    <referenceTo>Vendor__c</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Vendor_Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Vendor_Quote_Line_Item__c/Vendor_Quote_Line_Item__c.object-meta.xml
<CustomObject>
    <description>This is Vendor Quote Line Item object. It is child object of Vendor Quote object.</description>
    <label>Vendor Quote Line Item</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vendor Quote Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Vendor_Quote_Line_Item__c/fields/Vendor_Quote__c.field-meta.xml
<CustomField>
    <fullName>Vendor_Quote__c</fullName>
    <label>Vendor Quote</label>
    <referenceTo>Vendor_Quote__c</referenceTo>
    <relationshipLabel>Line Items</relationshipLabel>
    <relationshipName>Vendor_Quote_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

classes/TestVendorQuoteController.cls
@isTest
Public class TestVendorQuoteController{

  /* static testMethod void TestVendorQuoteController()
    {
         ProductionEstimate__c customSetting1 = new  ProductionEstimate__c(Active__c=true);

            insert customSetting1;
            
        Media_Type__c testMedia=new Media_Type__c(Name='Test Media 328');
            insert testMedia;
             
        Schedule_Template__c testST=new Schedule_Template__c(Name='Test Schedule Template 328',Media_Types__c=testMedia.Id);
            insert testST;
        
        Specification_Template__c testSpec=new Specification_Template__c(Name='Testing Spcification Template 328');
            insert testSpec;
      
        Job__c testJob1=new Job__c(Name='Test Job 328',Start_Date__c=System.Today(),Media_Types__c=testMedia.Id,Schedule_Template__c=testST.Id,Specification_Template__c=testSpec.Id);
         try
          {
              insert testJob1;
          }
         catch(System.DMLException e)
          {
              System.assertEquals('FIELD_CUSTOM_VALIDATION_EXCEPTION',e.getDmlStatusCode(0));
          }
         System.assertEquals('Test Job 328',testJob1.Name);
               
         GL_Department__c testGLD = new GL_Department__c(Name='TestGLD12');
          try
           {
               insert testGLD;
           }
          catch(System.DMLException e)
          {
              System.assertEquals('FIELD_CUSTOM_VALIDATION_EXCEPTION',e.getDmlStatusCode(0));
          }
   
       Quote__c testQ=new Quote__c(Name='Quote 328',Job__c=testjob1.Id,GL_Department__c=testGLD.id);
       try
        {
            insert testQ;
        }
       catch(System.DMLException e)
        {
        System.assertEquals('REQUIRED_FIELD_MISSING',e.getDmlStatusCode(0));
        }
       catch(Exception f)
        {
         System.assertEquals('FIELD_CUSTOM_VALIDATION_EXCEPTION',f.getDmlStatusCode(0));
        }
        
        Quote_Spec_Item__c qsinew = new Quote_Spec_Item__c(Name='testQSI',Description__c='Desc1',Quote__c=testQ.id);
        insert qsinew;
        
        Quote_Spec_Item__c qsinew1 = new Quote_Spec_Item__c(Name='testQSI1',Description__c='Desc1',Quote__c=testQ.id);
        insert qsinew1;
              
     Vendor__c testVendor=new Vendor__c(Name='Vendor 328');
     insert testVendor;
             
     Vendor_Quote__c testVQ=new Vendor_Quote__c(Quote__c=testQ.Id,Vendor__c=testVendor.Id,Date__c=System.Today(),Amount__c=500);
     insert testVQ;
              
     Vendor_Quote_Line_Item__c testVQLI=new Vendor_Quote_Line_Item__c(Name='test333',Description__c='Des333',Vendor_Quote__c=testVQ.Id); 
     insert testVQLI;
             
     ApexPages.StandardController con=new ApexPages.StandardController(testVQ);
     ApexPages.currentPage().getParameters().put('Id',testVQ.Id);
          
    // Instantiate the extention instance with the standard controller
     VendorQuoteController ext=new VendorQuoteController(con);
        
    // Invoke the primary method on the extension 
     ApexPages.PageReference result1=ext.autoRun();
     delete testVQ;
     result1=ext.autoRun();
    }  
   static testMethod void TestVendorQuoteController1()
    {
         
            
        Media_Type__c testMedia=new Media_Type__c(Name='Test Media 328');
            insert testMedia;
             
        Schedule_Template__c testST=new Schedule_Template__c(Name='Test Schedule Template 328',Media_Types__c=testMedia.Id);
            insert testST;
        
        Specification_Template__c testSpec=new Specification_Template__c(Name='Testing Spcification Template 328');
            insert testSpec;
      
        Job__c testJob1=new Job__c(Name='Test Job 328',Start_Date__c=System.Today(),Media_Types__c=testMedia.Id,Schedule_Template__c=testST.Id,Specification_Template__c=testSpec.Id);
         try
          {
              insert testJob1;
          }
         catch(System.DMLException e)
          {
              System.assertEquals('FIELD_CUSTOM_VALIDATION_EXCEPTION',e.getDmlStatusCode(0));
          }
         System.assertEquals('Test Job 328',testJob1.Name);
               
         GL_Department__c testGLD = new GL_Department__c(Name='TestGLD12');
          try
           {
               insert testGLD;
           }
          catch(System.DMLException e)
          {
              System.assertEquals('FIELD_CUSTOM_VALIDATION_EXCEPTION',e.getDmlStatusCode(0));
          }
   
       Quote__c testQ=new Quote__c(Name='Quote 328',Job__c=testjob1.Id,GL_Department__c=testGLD.id);
       try
        {
            insert testQ;
        }
       catch(System.DMLException e)
        {
        System.assertEquals('REQUIRED_FIELD_MISSING',e.getDmlStatusCode(0));
        }
       catch(Exception f)
        {
         System.assertEquals('FIELD_CUSTOM_VALIDATION_EXCEPTION',f.getDmlStatusCode(0));
        }
        
        Quote_Spec_Item__c qsinew = new Quote_Spec_Item__c(Name='testQSI',Description__c='Desc1',Quote__c=testQ.id);
        insert qsinew;
        
        Quote_Spec_Item__c qsinew1 = new Quote_Spec_Item__c(Name='testQSI1',Description__c='Desc1',Quote__c=testQ.id);
        insert qsinew1;
              
     Vendor__c testVendor=new Vendor__c(Name='Vendor 328');
     insert testVendor;
             
     Vendor_Quote__c testVQ=new Vendor_Quote__c(Quote__c=testQ.Id,Vendor__c=testVendor.Id,Date__c=System.Today(),Amount__c=500);
     insert testVQ;
              
     Vendor_Quote_Line_Item__c testVQLI=new Vendor_Quote_Line_Item__c(Name='test333',Description__c='Des333',Vendor_Quote__c=testVQ.Id); 
     insert testVQLI;
             
     ApexPages.StandardController con=new ApexPages.StandardController(testVQ);
     ApexPages.currentPage().getParameters().put('Id',testVQ.Id);
          
    // Instantiate the extention instance with the standard controller
     VendorQuoteController ext=new VendorQuoteController(con);
        
    // Invoke the primary method on the extension 
     ApexPages.PageReference result1=ext.autoRun();
     delete testVQ;
     result1=ext.autoRun();
    } */

}