objects/Spec_Item__c/Spec_Item__c.object-meta.xml
<CustomObject>
    <description>This is Spec Item object. It is child object of Creative Brief Template/ Specification Template object.</description>
    <label>Creative Spec Items</label>
    <nameField>
        <label>Spec Item</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Spec Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Spec_Item__c/fields/Specification_Template__c.field-meta.xml
<CustomField>
    <fullName>Specification_Template__c</fullName>
    <label>Specification Template</label>
    <referenceTo>Specification_Template__c</referenceTo>
    <relationshipName>Spec_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

objects/Specification_Template__c/Specification_Template__c.object-meta.xml
<CustomObject>
    <description>This is Creative Brief Template object. Also known as Specification Template.</description>
    <label>Creative Brief Template</label>
    <nameField>
        <label>Creative Brief Template</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Creative Brief Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/TestEditSpecItemSwitchExt.cls
@isTest
public class TestEditSpecItemSwitchExt {
  /*  
    testmethod static void editSpecItem(){
        
          Specification_Template__c testST1=new Specification_Template__c(Name='Testing Specification Template');
         insert testST1;
            Spec_Item__c testSPI1=new Spec_Item__c(Name='Test Spec Item 1',Specification_Template__c=testST1.Id);
         insert testSPI1;
        
        EditSpecItemSwitchExt eSpecon=new EditSpecItemSwitchExt(new Apexpages.standardController (testSPI1));
        
        
    }*/
    

}