objects/Spec_Item__c/Spec_Item__c.object-meta.xml
<CustomObject>
    <description>This is Spec Item object. It is child object of Creative Brief Template/ Specification Template object.</description>
    <label>Creative Spec Items</label>
    <nameField>
        <label>Spec Item</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Spec Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Spec_Item__c/fields/Specification_Template__c.field-meta.xml
<CustomField>
    <fullName>Specification_Template__c</fullName>
    <label>Specification Template</label>
    <referenceTo>Specification_Template__c</referenceTo>
    <relationshipName>Spec_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

objects/Specification_Template__c/Specification_Template__c.object-meta.xml
<CustomObject>
    <description>This is Creative Brief Template object. Also known as Specification Template.</description>
    <label>Creative Brief Template</label>
    <nameField>
        <label>Creative Brief Template</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Creative Brief Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/SpecTemplateDetailSwitchExt.cls
public with sharing class SpecTemplateDetailSwitchExt {
/*
  public boolean isLtng{private set; get{
                                            String theme = UserInfo.getUITheme();
                                            return (theme=='Theme4d')?true:false;
                                        }
            }  
    public string SpecItemId{get;set;}
    public Spec_Item__c  speItem{get;set;}


    public SpecTemplateDetailSwitchExt(ApexPages.StandardController controller) {
    
        SpecItemId=controller.getRecord().id;
        
        speItem=[select id,name,Specification_Template__c from Spec_Item__c where id=:SpecItemId];

    }
    
   
   

public pageReference spedatailview(){
  
  String specTempId=speItem.Specification_Template__c;
    PageReference p;
     if(isLtng)
        p =  new Pagereference('/apex/SpecificationTemplateTabOverrideLti?id='+specTempId);
     else
        p =  new Pagereference('/apex/SpecificationTemplateTabOverride?id='+specTempId);
        p.setRedirect(true);
       return p;
}

 */   

}