objects/Graphics_Deliverables__c/Graphics_Deliverables__c.object-meta.xml
<CustomObject>
    <description>This is Graphics Deliverables object.</description>
    <label>Graphic Deliverable</label>
    <nameField>
        <label>Deliverable Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Graphic Deliverables</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Graphics_Deliverables__c/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <label>Job</label>
    <referenceTo>Job__c</referenceTo>
    <relationshipLabel>Graphics Deliverables</relationshipLabel>
    <relationshipName>Graphics_Deliverables</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/Job__c/Job__c.object-meta.xml
<CustomObject>
    <description>This is Job object.</description>
    <label>Job</label>
    <nameField>
        <label>Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/GDListViewSwitchExt.cls
public with sharing class GDListViewSwitchExt{
    
 /*   public boolean isLtng{get{
                                            String theme = UserInfo.getUITheme();
                                            return (theme=='Theme4d')?true:false;
                                          } set;
            }  
   
   
    public string GDId{get;set;}
    public Graphics_Deliverables__c GD{get;set;}
    
    public GDListViewSwitchExt(ApexPages.StandardController controller) 
    {
        GDId= controller.getRecord().id;
        
        GD=[select id,name,Job__c from Graphics_Deliverables__c where id=:GDId];
        
    }
    
    Public PageReference pagedir()
    {
         String jobid;
         jobid =  GD.Job__c;
         if(isLtng)
        {
             PageReference p =  new Pagereference('/apex/JobdetailpageLightening07?id='+jobId+'&section=GD');
             p.setRedirect(true);
             return p; 
        }
        else
        {
                PageReference p =  new Pagereference('/apex/jobListView?id='+jobId+'&intFocus=11');
                p.setRedirect(true);
                return p;
        } 
    }*/
    

}