objects/Development_Item__c/Development_Item__c.object-meta.xml
<CustomObject>
    <label>Development Item</label>
    <nameField>
        <label>Development Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Development Items</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Development_Item__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>2000</length>
    <type>Html</type>
</CustomField>

objects/Development_Item__c/fields/Duration__c.field-meta.xml
<CustomField>
    <fullName>Duration__c</fullName>
    <label>Developer Hours</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

objects/Development_Item__c/fields/Estimate_Number__c.field-meta.xml
<CustomField>
    <fullName>Estimate_Number__c</fullName>
    <label>Estimate Number</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

objects/Development_Item__c/fields/Hours__c.field-meta.xml
<CustomField>
    <fullName>Hours__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Hours Required</description>
    <label>Calculated Actual Hours</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

objects/Development_Item__c/fields/Platform__c.field-meta.xml
<CustomField>
    <fullName>Platform__c</fullName>
    <label>Platform</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Saleforce</fullName>
                <default>true</default>
                <label>Saleforce</label>
            </value>
            <value>
                <fullName>FileMaker</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Development_Item__c/fields/Priority__c.field-meta.xml
<CustomField>
    <fullName>Priority__c</fullName>
    <label>Priority</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>13</fullName>
            </value>
            <value>
                <fullName>14</fullName>
            </value>
            <value>
                <fullName>15</fullName>
            </value>
            <value>
                <fullName>16</fullName>
            </value>
            <value>
                <fullName>17</fullName>
            </value>
            <value>
                <fullName>18</fullName>
            </value>
            <value>
                <fullName>19</fullName>
            </value>
            <value>
                <fullName>20</fullName>
            </value>
            <value>
                <fullName>21</fullName>
            </value>
            <value>
                <fullName>22</fullName>
            </value>
            <value>
                <fullName>23</fullName>
            </value>
            <value>
                <fullName>24</fullName>
            </value>
            <value>
                <fullName>25</fullName>
            </value>
            <value>
                <fullName>26</fullName>
            </value>
            <value>
                <fullName>27</fullName>
            </value>
            <value>
                <fullName>28</fullName>
            </value>
            <value>
                <fullName>29</fullName>
            </value>
            <value>
                <fullName>30</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Development_Item__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Production Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Estimate Needed</fullName>
            </value>
            <value>
                <fullName>Estimate Ready</fullName>
            </value>
            <value>
                <fullName>Ready for Review</fullName>
            </value>
            <value>
                <fullName>Ready for Package</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
                <default>true</default>
                <label>In Progress</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Time_Sheet__c/Time_Sheet__c.object-meta.xml
<CustomObject>
    <label>Dev Time Sheet</label>
    <nameField>
        <label>TS Description</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dev Time Sheets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Time_Sheet__c/fields/Dev_Item__c.field-meta.xml
<CustomField>
    <fullName>Dev_Item__c</fullName>
    <label>Dev Item</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Development_Item__c.Status__c</field>
            <operation>equals</operation>
            <value>Open</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Development_Item__c</referenceTo>
    <relationshipName>Time_Sheets</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

objects/Time_Sheet__c/fields/Developer__c.field-meta.xml
<CustomField>
    <fullName>Developer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Name of Developer</description>
    <label>Developer</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Time_Sheets</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Time_Sheet__c/fields/Duration__c.field-meta.xml
<CustomField>
    <fullName>Duration__c</fullName>
    <description>This is total duration of time spent on the Dev Item.</description>
    <label>Actual Hours</label>
    <precision>7</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

objects/Time_Sheet__c/fields/Hours__c.field-meta.xml
<CustomField>
    <fullName>Hours__c</fullName>
    <label>Billable Hours</label>
    <precision>4</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

objects/Time_Sheet__c/fields/TS_Date__c.field-meta.xml
<CustomField>
    <fullName>TS_Date__c</fullName>
    <description>Date the time was executed.</description>
    <label>TS Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

objects/Time_Sheet__c/fields/TS_Long_Description__c.field-meta.xml
<CustomField>
    <fullName>TS_Long_Description__c</fullName>
    <label>TS Long Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

classes/updateActHrsTest.cls
@IsTest
Public class updateActHrsTest{
    public static testMethod void updateActHrsTest(){    
        Development_Item__c objDev = new Development_Item__c();
        
        objDev.Name = 'TestDev01';
        objDev.Platform__c = 'Saleforce';        
        objDev.Priority__c = '1';
        objDev.Status__c = 'Open';
        objDev.Estimate_Number__c = 'test001';
        objDev.Description__c = 'This is test development item';
        insert objDev;
        
        Time_Sheet__c objTs = new Time_Sheet__c();
        objTs.Name = objDev.Name;
        objTs.Dev_Item__c = objDev.Id;
        objTs.TS_Long_Description__c = 'Worked on testdev01';
        objTs.TS_Date__c = date.today();
        objTs.Developer__c = UserInfo.getUserId();
        objTs.Hours__c = 5.5;
        objTs.Duration__c = 6.0; 
        insert objTs;   
        
        objTs.TS_Long_Description__c = 'Worked extra';
        objTs.Hours__c = 1.5;
        objTs.Duration__c = 3.5;        
        update objTs;
        
        delete objTs;
    }    
}