objects/Job_Task__c/Job_Task__c.object-meta.xml
<CustomObject>
    <description>This is Job Task object. Also known as Schedule.</description>
    <label>Job Task</label>
    <nameField>
        <label>Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Job_Task_Role__c/Job_Task_Role__c.object-meta.xml
<CustomObject>
    <description>Staff assigned to the Job Tasks.</description>
    <label>Task Staff Assigned</label>
    <nameField>
        <label>Role</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Task Staff Assigned</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Job_Task_Role__c/fields/Job_Task__c.field-meta.xml
<CustomField>
    <fullName>Job_Task__c</fullName>
    <label>Job Task</label>
    <referenceTo>Job_Task__c</referenceTo>
    <relationshipName>Job_Task_Roles</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

classes/TaskRoleStaffSectionExtension.cls
public with sharing class TaskRoleStaffSectionExtension {

    // Global Variables 
    
    
    public boolean isLtng{private set; get{
                                    String theme = UserInfo.getUITheme();
                                    return (theme=='Theme4d')?true:false;
                                  }
    }  
    
    
    
    
     
      public List<Job_Task_Role__c> lstTR{get;set;}
      public String Taskid;
      
     // End of Global variables 
      
     // Start Constructor
     public TaskRoleStaffSectionExtension (ApexPages.StandardController controller)
      {
         Taskid=System.currentPagereference().getParameters().get('id');
         lstTR=[Select Id,Name,User__c from Job_Task_Role__c where Job_Task__c =: Taskid order by CreatedDate];
      }
      // End of Constructor
      
      
      //start Method to go to the JobTeamAddEditStaff page
      public Pagereference AddStaffs()
       {
           String theId=ApexPages.CurrentPage().getParameters().get('id');
           
           if(isLtng)
                 {
                   PageReference p = Page.TaskRoleAddEditStaffLightning;
                   p.setredirect(true);
                   p.getParameters().put('id',theID); 
                   return p;
                 }
          else
                 {
                  PageReference p = Page.TaskRoleAddEditStaff;
                   p.setredirect(true);
                   p.getParameters().put('id',theID); 
                   return p;
          
                  }
       }
      //End Method to go to the JobTeamAddEditStaff page
}