objects/Staff__c/Staff__c.object-meta.xml
<CustomObject>
    <description>This is Staff object.</description>
    <label>Staff</label>
    <nameField>
        <label>Staff Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Staff</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Staff__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <label>Email</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

objects/Staff__c/fields/Username__c.field-meta.xml
<CustomField>
    <fullName>Username__c</fullName>
    <label>Username</label>
    <type>Email</type>
</CustomField>

classes/DisplayStaff.cls
public with sharing class DisplayStaff
{
/*
    public DisplayStaff(ApexPages.StandardController controller) 
    {

    }

    public List <Staff__c> lstStaff{get;set;}

    public DisplayStaff() 
    {
    lstStaff=[SELECT First_Name__c,Last_Name__c,Email__c,Username__c from Staff__c LIMIT 10000];
    }


    
  static testMethod void DisplayStaff()
    {
      
         DisplayStaff ext=new DisplayStaff();
          Staff__c Staff = new Staff__c();
          ApexPages.StandardController con=new ApexPages.StandardController(Staff);
          DisplayStaff ext1=new DisplayStaff(con);
          System.assertEquals(null,ext1.lstStaff);
       
    } 
   
*/
}