objects/Estimate_Spec_Item__c/Estimate_Spec_Item__c.object-meta.xml
<CustomObject>
    <description>This is Estimate Spec Item object. It act as line items of Estimate Line Item Object.</description>
    <label>Spec  Item</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Estimate Spec Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Estimate_Spec_Item__c/fields/Estimates__c.field-meta.xml
<CustomField>
    <fullName>Estimates__c</fullName>
    <label>Estimates</label>
    <referenceTo>Estimate_Line_Items__c</referenceTo>
    <relationshipName>Estimate_Line_Item</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

classes/EditestimatelineitemunderJob.cls
public with sharing class EditestimatelineitemunderJob {

    public boolean isLtng{private set; get{
                                            String theme = UserInfo.getUITheme();
                                            return (theme=='Theme4d')?true:false;
                                          }
            }  
            
    
    
    // Global variables
    private final Estimate_Spec_Item__c objESI;
    public Id EstLIId{get;set;}
    // End of Global variables

    // Start Constructor
    public EditestimatelineitemunderJob (ApexPages.StandardController controller) 
    {
        this.objESI = (Estimate_Spec_Item__c)controller.getRecord(); 
      
    }
    // End of Constructor
    
    // Method to update Estimate Line Item 
    Public PageReference saveme()
     {
        String strid;
        strid = objESI.Estimates__c;
         PageReference p;
        try
        {
            update objESI;
        }
        catch(System.DMLException e)
        {
            return null;
        } 
        
        
        if(isLtng)
        {
              p = new Pagereference('/apex/EstimatedetailpageLightning?id='+strid+'&section=estimatespecitems');
        }
        else
        {
              p =  new Pagereference('/apex/estimatedetailpage?id='+strid);
              
        }
         p.setRedirect(true);                return p;
       
     }
    // End of saveme method
     
     
     Public PageReference cancelme()
     {
     
        String strid;
        strid = objESI.Estimates__c;
        PageReference p; 
        if(isLtng)
        {
              p = new Pagereference('/apex/EstimatedetailpageLightning?id='+strid+'&section=estimatespecitems');
             
        }
        else
        {
             p =  new Pagereference('/apex/estimatedetailpage?id='+strid);
               
        }
        p.setRedirect(true);     return p; 
     }
     
}