objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <description>This is Invoice object.</description>
    <label>Invoice</label>
    <nameField>
        <label>Invoice Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Invoice__c/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <label>Job Name</label>
    <referenceTo>Job__c</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/Job__c/Job__c.object-meta.xml
<CustomObject>
    <description>This is Job object.</description>
    <label>Job</label>
    <nameField>
        <label>Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/TestInvoiceSwitchExt.cls
@isTest
public class TestInvoiceSwitchExt {
	 static TestMethod void TestInvoiceSwitchExt(){
      /*  Job__c testJob1=new Job__c(Name='Job858',Start_Date__c=System.Today());
        insert testJob1;
        Invoice__c testInv=new Invoice__c(Name='Camp',Job__c=testJob1.id);
        insert testInv;
        InvoiceSwitchExt controller = new InvoiceSwitchExt(new ApexPages.StandardController(testInv));
      //  boolean x = controller.isMobile;*/
}
}