objects/Media_Type__c/Media_Type__c.object-meta.xml
<CustomObject>
    <description>This is Media Type object.</description>
    <label>Media Type</label>
    <nameField>
        <label>Media Type</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Media Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Schedule_Task__c/Schedule_Task__c.object-meta.xml
<CustomObject>
    <description>This is Schedule Task object. It is child object of Schedule Template object.</description>
    <label>Schedule Task</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Schedule Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Schedule_Task__c/fields/Schedule_Template__c.field-meta.xml
<CustomField>
    <fullName>Schedule_Template__c</fullName>
    <label>Schedule Template</label>
    <referenceTo>Schedule_Template__c</referenceTo>
    <relationshipLabel>Schedule Tasks</relationshipLabel>
    <relationshipName>Schedule_Tasks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/Schedule_Template__c/Schedule_Template__c.object-meta.xml
<CustomObject>
    <description>This is Schedule Template object.</description>
    <label>Schedule Template</label>
    <nameField>
        <label>Schedule Template</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Schedule Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Schedule_Template__c/fields/Media_Types__c.field-meta.xml
<CustomField>
    <fullName>Media_Types__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Media Type</label>
    <referenceTo>Media_Type__c</referenceTo>
    <relationshipLabel>Schedule Templates</relationshipLabel>
    <relationshipName>Schedule_Templates</relationshipName>
    <type>Lookup</type>
</CustomField>

classes/TestScheduleTemplateDetailSwitchExt.cls
@isTest
public class TestScheduleTemplateDetailSwitchExt {
	static testmethod void TestScheduleTemplateDetailSwitchExt(){
        /* Media_Type__c testMedia=new Media_Type__c(Name='MT012');
          insert testMedia;
          Schedule_Template__c testST=new Schedule_Template__c(Name='ST012',Media_Types__c=testMedia.Id);
          insert testST;
        Schedule_Task__c testSTask=new Schedule_Task__c(Name='ST012',Schedule_Template__c=testST.Id);
          insert testSTask;
       ScheduleTemplateDetailSwitchExt scheTemp=new ScheduleTemplateDetailSwitchExt(new Apexpages.StandardController(testSTask));
         //scheTemp.theme='Theme4d';
         scheTemp.stlistview();
        Apexpages.pageReference result;
        //result=scheTemp.stlistview();
         system.assertEquals(false,scheTemp.isLtng);*/
    }
}