objects/Media_Type__c/Media_Type__c.object-meta.xml
<CustomObject>
    <description>This is Media Type object.</description>
    <label>Media Type</label>
    <nameField>
        <label>Media Type</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Media Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Schedule_Task__c/Schedule_Task__c.object-meta.xml
<CustomObject>
    <description>This is Schedule Task object. It is child object of Schedule Template object.</description>
    <label>Schedule Task</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Schedule Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Schedule_Task__c/fields/Days__c.field-meta.xml
<CustomField>
    <fullName>Days__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Days</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

objects/Schedule_Task__c/fields/Schedule_Template__c.field-meta.xml
<CustomField>
    <fullName>Schedule_Template__c</fullName>
    <label>Schedule Template</label>
    <referenceTo>Schedule_Template__c</referenceTo>
    <relationshipLabel>Schedule Tasks</relationshipLabel>
    <relationshipName>Schedule_Tasks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/Schedule_Template__c/Schedule_Template__c.object-meta.xml
<CustomObject>
    <description>This is Schedule Template object.</description>
    <label>Schedule Template</label>
    <nameField>
        <label>Schedule Template</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Schedule Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Schedule_Template__c/fields/Media_Types__c.field-meta.xml
<CustomField>
    <fullName>Media_Types__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Media Type</label>
    <referenceTo>Media_Type__c</referenceTo>
    <relationshipLabel>Schedule Templates</relationshipLabel>
    <relationshipName>Schedule_Templates</relationshipName>
    <type>Lookup</type>
</CustomField>

classes/TestdisplayScheduleTaskUnderScheduleTemp.cls
@isTest
public class TestdisplayScheduleTaskUnderScheduleTemp{
/*
static testMethod void TestdisplayScheduleTaskUnderScheduleTemp()
    {         
          Media_Type__c testMedia=new Media_Type__c(Name='Test Media 1007');
             
                insert testMedia;
             
          Schedule_Template__c testST=new Schedule_Template__c(Name='Test Schedule Template 1007',Media_Types__c=testMedia.Id);
             
                 insert testST;
                 
          Schedule_Task__c testSchedule=new Schedule_Task__c(Name='Test Schedule Task 1007',Days__c=2,Schedule_Template__c=testST.id);
                insert testSchedule;
                
          System.assertEquals('Test Schedule Task 1007',testSchedule.Name);   

          
          // Instantiate the extention instance with the Custom Controller
          
          displayScheduleTaskUnderScheduleTemp ext=new displayScheduleTaskUnderScheduleTemp();
          
          ext.LoadData();
          
      // Invoke the primary methods on the extension        
          ApexPages.pagereference result=ext.save();
            result=ext.Cancel();
            result=ext.editTask();
            result=ext.insertTask();
            result=ext.insertTaskBelow();
            ext.selectedTaskId=testSchedule.id;
            ext.DeleteTask();
            ext.selectedTaskId=NULL;
            ext.DeleteTask();
            Schedule_Task__c st=[Select id from Schedule_Task__c where id=:testSchedule.id limit 1];
            delete st;
            ext.save();
            ext.LoadData();
    }// End of Test Coverage Code 

*/


}