objects/Media_Type__c/Media_Type__c.object-meta.xml
<CustomObject>
    <description>This is Media Type object.</description>
    <label>Media Type</label>
    <nameField>
        <label>Media Type</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Media Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Schedule_Template__c/Schedule_Template__c.object-meta.xml
<CustomObject>
    <description>This is Schedule Template object.</description>
    <label>Schedule Template</label>
    <nameField>
        <label>Schedule Template</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Schedule Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Schedule_Template__c/fields/Media_Types__c.field-meta.xml
<CustomField>
    <fullName>Media_Types__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Media Type</label>
    <referenceTo>Media_Type__c</referenceTo>
    <relationshipLabel>Schedule Templates</relationshipLabel>
    <relationshipName>Schedule_Templates</relationshipName>
    <type>Lookup</type>
</CustomField>

classes/TestScheduleTemplateListViewSwitchExt.cls
@isTest
public class TestScheduleTemplateListViewSwitchExt {
    
     static testmethod void testMethodScheTemp(){
     /*    Media_Type__c testMedia=new Media_Type__c(Name='MT012');
          insert testMedia;
          Schedule_Template__c testST=new Schedule_Template__c(Name='ST012',Media_Types__c=testMedia.Id);
          insert testST;
       ScheduleTemplateListViewSwitchExt scheTemp=new ScheduleTemplateListViewSwitchExt(new Apexpages.StandardController(testST));
         //scheTemp.theme='Theme4d';
        Apexpages.pageReference result;
        result=scheTemp.sclistview();
         system.assertEquals(false,scheTemp.isLtng);*/
    }

}