objects/Billboard_Invoice__c/Billboard_Invoice__c.object-meta.xml
<CustomObject>
    <description>This is Billboard invoice object. It is child object of Billboard.</description>
    <label>Billboard Invoice</label>
    <nameField>
        <label>BB Invoice #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billboard Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Billboard_Invoice_Line_Item__c/Billboard_Invoice_Line_Item__c.object-meta.xml
<CustomObject>
    <description>This is Billboard  Invoice Line Item object. It is child object of Billboard  Invoice.</description>
    <label>Billboard Invoice Line Item</label>
    <nameField>
        <displayFormat>BBILI{00000}</displayFormat>
        <label>BBILI</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Billboard Invoice Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Billboard_Invoice_Line_Item__c/fields/Billboard_Invoice__c.field-meta.xml
<CustomField>
    <fullName>Billboard_Invoice__c</fullName>
    <label>Billboard Invoice</label>
    <referenceTo>Billboard_Invoice__c</referenceTo>
    <relationshipLabel>Billboard Invoice Line Items</relationshipLabel>
    <relationshipName>Billboard_Invoice_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

objects/Billboard_Invoice_Line_Item__c/fields/GL_Code__c.field-meta.xml
<CustomField>
    <fullName>GL_Code__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GL Description</label>
    <referenceTo>GL_Code__c</referenceTo>
    <relationshipLabel>Billboard Invoice Line Items</relationshipLabel>
    <relationshipName>Billboard_Invoice_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Billboard_Invoice_Line_Item__c/fields/GL_Department__c.field-meta.xml
<CustomField>
    <fullName>GL_Department__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GL Department</label>
    <referenceTo>GL_Department__c</referenceTo>
    <relationshipLabel>Billboard Invoice Line Items</relationshipLabel>
    <relationshipName>Billboard_Invoice_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/GL_Code__c/GL_Code__c.object-meta.xml
<CustomObject>
    <description>GL Codes are used to build line items on our Job Cost Layouts.  The Job Cost Layouts are the Quote, Estimate, Purchase Order, and Vendor Invoice.   The line items on each of these follow similar logic.</description>
    <label>GL Code</label>
    <nameField>
        <label>Description</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GL Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/GL_Code__c/fields/GL_Department__c.field-meta.xml
<CustomField>
    <fullName>GL_Department__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GL Department</label>
    <referenceTo>GL_Department__c</referenceTo>
    <relationshipLabel>GL Codes</relationshipLabel>
    <relationshipName>GL_Codes</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/GL_Code__c/fields/GL_ID__c.field-meta.xml
<CustomField>
    <fullName>GL_ID__c</fullName>
    <description>This is GL ID field. These id&apos;s are auto generated.</description>
    <label>GL Code</label>
    <length>15</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

objects/GL_Department__c/GL_Department__c.object-meta.xml
<CustomObject>
    <description>This Object is Master of GLCode Object in JobSuite Application.</description>
    <label>GL Department</label>
    <nameField>
        <label>GL Department</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GL Department</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CreateBillboardInvoiceLIExtension.cls
public with sharing class CreateBillboardInvoiceLIExtension {

 /*   public boolean isLtng{private set; get{
                                            String theme = UserInfo.getUITheme();
                                            return (theme=='Theme4d')?true:false;
                                          }
    }  
   
   
    private final Billboard_Invoice_Line_Item__c bbili;
    public String bbiid{get;set;}
    public String BillboardInvoicename{get;set;}
   
    String GLDName;
    public String getGLDName() { return GLDName; }
    public void setGLDName(String s) {  this.GLDName = s; }

    String GLCName;
    public String getGLCName() { return GLCName; }
    public void setGLCName(String s) {  this.GLCname = s; }
    
    
    
    // Start Constructor
    public CreateBillboardInvoiceLIExtension(ApexPages.StandardController controller) {
    
     this.bbili=(Billboard_Invoice_Line_Item__c )controller.getRecord();
        bbiid=ApexPages.CurrentPage().getParameters().get('bbiid');
        Billboard_Invoice__c objBBI=[Select id,name from Billboard_Invoice__c where id=:bbiid];
        BillboardInvoicename=objBBI.Name;
        bbili.Billboard_Invoice__c = bbiid;
        
    }
    
    // This method is used to retrieve all GLDepartments into dropdown list
    public List<selectOption> getGLDepartments() 
     {    
          List<selectOption> optionList = new List<selectOption>();
          optionList.add(new selectOption('', '- None -'));  
          for (GL_Department__c gld : [SELECT Id, name FROM GL_Department__c order by Name]) 
          {  
               optionList.add(new selectOption(gld.Id, gld.Name));  
          }
          return optionList;  
     }   
     // End of method getGLDepartments
    
    // This method is used to retrieve all GLCodes into dropdown list
    public List<selectOption> getGLCodes() 
     {
          List<selectOption> optionList = new List<selectOption>();
          optionList.add(new selectOption('', '- None -'));  
          for (GL_Code__c users : [SELECT Id,GL_Id__c,Name FROM GL_Code__c where GL_Department__c =: GLDName ORDER BY Name]) 
          {  
               optionList.add(new selectOption(users.Id, users.GL_Id__c +' '+users.Name));  
          }
          return optionList;  
     }
     // End of method getGLCodes
    
            
      // Save Method
        public PageReference saveme() 
        {      
                try
                {
                    if(schema.SobjectType.Billboard_Invoice_Line_Item__c .Fields.GL_Department__c .isCreateable()){ 
                        bbili.GL_Department__c = GLDName;
                    }
                    if(schema.SobjectType.Billboard_Invoice_Line_Item__c .Fields.GL_Code__c .isCreateable()){ 
                        bbili.GL_Code__c = GLCName;
                    }
                    if(Schema.sObjectType.Billboard_Invoice_Line_Item__c .isCreateable()){
                        insert bbili;
                    }
                    
                }
                catch(DMLException e)
                {
                    return null;
                }
                
            
                 PageReference p;   
                 if(isLtng)
                 {
                    p = new PageReference('/apex/BillboardInvoiceDetailpageLightning?id='+bbiid+'&section=BBLI');
                 }
                
                else
                 {
                   p = new PageReference('/apex/BillboardInvoiceDetailpage?id='+bbiid);
                 }
                
            
            // PageReference pageRef = new PageReference('/apex/BillboardInvoiceDetailpage?id='+bbiid);
              p.setRedirect(true);
              return p;
                  
                  
        }
        // End of Save Method

        // Cancel Method
        Public PageReference cancelme()
        {       
           
           PageReference p;   
             if(isLtng)
             {
                p = new PageReference('/apex/BillboardInvoiceDetailpageLightning?id='+bbiid+'&section=BBLI');
             }
            
            else
             {
               p = new PageReference('/apex/BillboardInvoiceDetailpage?id='+bbiid);
             }
           
           
          //  PageReference p = new PageReference('/apex/BillboardInvoiceDetailpage?id='+bbiid);
            p.setRedirect(true);
            return p;   
            
       }
        // Cancel Method        
        
*/
}